// 版权所有2017-2018 Espressif Systems（上海）私人有限公司
//
// 根据Apache许可证2.0版（“许可证”）获得许可；
// 除非符合许可证，否则不得使用此文件。
// 您可以在以下地址获取许可证副本：
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// 除非适用法律要求或书面同意，软件
// 根据许可证分发的内容是按“原样”分发的，
// 无任何明示或暗示的保证或条件。
// 有关管理权限和
// 许可证下的限制。
#ifndef _SOC_APB_SARADC_REG_H_
#define _SOC_APB_SARADC_REG_H_


#ifdef __cplusplus
extern "C" {
#endif
#include "soc.h"
#define APB_SARADC_CTRL_REG          (DR_REG_APB_SARADC_BASE + 0x000)
/* APB_SARADC_WAIT_ARB_CYCLE:R/W；比特位置：[31:30]；默认值：2'd1；*/
/*描述：在sar_done之后等待仲裁信号稳定*/
#define APB_SARADC_WAIT_ARB_CYCLE  0x00000003
#define APB_SARADC_WAIT_ARB_CYCLE_M  ((APB_SARADC_WAIT_ARB_CYCLE_V)<<(APB_SARADC_WAIT_ARB_CYCLE_S))
#define APB_SARADC_WAIT_ARB_CYCLE_V  0x3
#define APB_SARADC_WAIT_ARB_CYCLE_S  30
/* APB_SARADC_XPD_SAR_FORCE:R/W；位位置：[28:27]；默认值：2'd0；*/
/*description:xpd-sar块的强制选项*/
#define APB_SARADC_XPD_SAR_FORCE  0x00000003
#define APB_SARADC_XPD_SAR_FORCE_M  ((APB_SARADC_XPD_SAR_FORCE_V)<<(APB_SARADC_XPD_SAR_FORCE_S))
#define APB_SARADC_XPD_SAR_FORCE_V  0x3
#define APB_SARADC_XPD_SAR_FORCE_S  27
/* APB_SARADC_DATA_TO_I2S:R/W；位位置：[26]；默认值：1’b0；*/
/*描述：1:I2S输入数据来自SAR ADC（用于DMA）0:I2S输入信号来自GPIO矩阵*/
#define APB_SARADC_DATA_TO_I2S  (BIT(26))
#define APB_SARADC_DATA_TO_I2S_M  (BIT(26))
#define APB_SARADC_DATA_TO_I2S_V  0x1
#define APB_SARADC_DATA_TO_I2S_S  26
/* APB_SARADC_DATA_SAR_SEL:R/W；位位置：[25]；默认值：1’b0；*/
/*描述：1:sar_sel将由16位输出数据的MSB编码，在这种情况下，分辨率不应大于11位。*/
#define APB_SARADC_DATA_SAR_SEL  (BIT(25))
#define APB_SARADC_DATA_SAR_SEL_M  (BIT(25))
#define APB_SARADC_DATA_SAR_SEL_V  0x1
#define APB_SARADC_DATA_SAR_SEL_S  25
/* APB_SARADC_SAR2_PATT_P_CLEAR:R/W；位位置：[24]；默认值：1'd0；*/
/*描述：清除DIG ADC2 CTRL的模式表指针*/
#define APB_SARADC_SAR2_PATT_P_CLEAR  (BIT(24))
#define APB_SARADC_SAR2_PATT_P_CLEAR_M  (BIT(24))
#define APB_SARADC_SAR2_PATT_P_CLEAR_V  0x1
#define APB_SARADC_SAR2_PATT_P_CLEAR_S  24
/* APB_SARADC_SAR1_PATT_P_CLEAR:R/W；位位置：[23]；默认值：1'd0；*/
/*描述：清除DIG ADC1 CTRL的模式表指针*/
#define APB_SARADC_SAR1_PATT_P_CLEAR  (BIT(23))
#define APB_SARADC_SAR1_PATT_P_CLEAR_M  (BIT(23))
#define APB_SARADC_SAR1_PATT_P_CLEAR_V  0x1
#define APB_SARADC_SAR1_PATT_P_CLEAR_S  23
/* APB_SARADC_SAR2_PATT_LEN:R/W；比特位置：[22:19]；默认值：4'd15；*/
/*说明：0~15表示长度1~16*/
#define APB_SARADC_SAR2_PATT_LEN  0x0000000F
#define APB_SARADC_SAR2_PATT_LEN_M  ((APB_SARADC_SAR2_PATT_LEN_V)<<(APB_SARADC_SAR2_PATT_LEN_S))
#define APB_SARADC_SAR2_PATT_LEN_V  0xF
#define APB_SARADC_SAR2_PATT_LEN_S  19
/* APB_SARADC_SAR1_PATT_LEN:R/W；比特位置：[18:15]；默认值：4'd15；*/
/*说明：0~15表示长度1~16*/
#define APB_SARADC_SAR1_PATT_LEN  0x0000000F
#define APB_SARADC_SAR1_PATT_LEN_M  ((APB_SARADC_SAR1_PATT_LEN_V)<<(APB_SARADC_SAR1_PATT_LEN_S))
#define APB_SARADC_SAR1_PATT_LEN_V  0xF
#define APB_SARADC_SAR1_PATT_LEN_S  15
/* APB_sarac_SAR_CLK_DIV:R/W；比特位置：[14:7]；默认值：8'd4；*/
/*描述：SAR时钟分频器*/
#define APB_SARADC_SAR_CLK_DIV  0x000000FF
#define APB_SARADC_SAR_CLK_DIV_M  ((APB_SARADC_SAR_CLK_DIV_V)<<(APB_SARADC_SAR_CLK_DIV_S))
#define APB_SARADC_SAR_CLK_DIV_V  0xFF
#define APB_SARADC_SAR_CLK_DIV_S  7
/* APB_sarac_SAR_CLK_GATED:R/W；位位置：[6]；默认值：1’b1；*/
/*说明：*/
#define APB_SARADC_SAR_CLK_GATED  (BIT(6))
#define APB_SARADC_SAR_CLK_GATED_M  (BIT(6))
#define APB_SARADC_SAR_CLK_GATED_V  0x1
#define APB_SARADC_SAR_CLK_GATED_S  6
/* APB_SARADC_SAR_SEL:R/W；位位置：[5]；默认值：1'd0；*/
/*description:0:SAR1 1:SAR2仅适用于单SAR模式*/
#define APB_SARADC_SAR_SEL  (BIT(5))
#define APB_SARADC_SAR_SEL_M  (BIT(5))
#define APB_SARADC_SAR_SEL_V  0x1
#define APB_SARADC_SAR_SEL_S  5
/* APB_SARADC_WORK_MODE：R/W；位位置：[4:3]；默认值：2'd0；*/
/*描述：0：单模式1：双模式2：交替模式*/
#define APB_SARADC_WORK_MODE  0x00000003
#define APB_SARADC_WORK_MODE_M  ((APB_SARADC_WORK_MODE_V)<<(APB_SARADC_WORK_MODE_S))
#define APB_SARADC_WORK_MODE_V  0x3
#define APB_SARADC_WORK_MODE_S  3
/* APB_SARADC_START：R/W；位位置：[1]；默认值：1'd0；*/
/*说明：*/
#define APB_SARADC_START  (BIT(1))
#define APB_SARADC_START_M  (BIT(1))
#define APB_SARADC_START_V  0x1
#define APB_SARADC_START_S  1
/* APB_SARADC_START_FORCE:R/W；位位置：[0]；默认值：1'd0；*/
/*说明：*/
#define APB_SARADC_START_FORCE  (BIT(0))
#define APB_SARADC_START_FORCE_M  (BIT(0))
#define APB_SARADC_START_FORCE_V  0x1
#define APB_SARADC_START_FORCE_S  0

#define APB_SARADC_CTRL2_REG          (DR_REG_APB_SARADC_BASE + 0x004)
/* APB_SARADC_TIMER_EN:R/W；位位置：[24]；默认值：1'd0；*/
/*描述：启用saradc计时器触发器*/
#define APB_SARADC_TIMER_EN  (BIT(24))
#define APB_SARADC_TIMER_EN_M  (BIT(24))
#define APB_SARADC_TIMER_EN_V  0x1
#define APB_SARADC_TIMER_EN_S  24
/* APB_SARADC_TIMER_TARGET:R/W；比特位置：[23:12]；默认值：12'd10；*/
/*description:设置saradc计时器目标*/
#define APB_SARADC_TIMER_TARGET  0x00000FFF
#define APB_SARADC_TIMER_TARGET_M  ((APB_SARADC_TIMER_TARGET_V)<<(APB_SARADC_TIMER_TARGET_S))
#define APB_SARADC_TIMER_TARGET_V  0xFFF
#define APB_SARADC_TIMER_TARGET_S  12
/* APB_SARADC_TIMER_SEL:R/W；位位置：[11]；默认值：1'd0；*/
/*描述：1:选择saradc计时器0:i2s_ws触发器*/
#define APB_SARADC_TIMER_SEL  (BIT(11))
#define APB_SARADC_TIMER_SEL_M  (BIT(11))
#define APB_SARADC_TIMER_SEL_V  0x1
#define APB_SARADC_TIMER_SEL_S  11
/* APB_SARADC_SAR2_INV:R/W；位位置：[10]；默认值：1'd0；*/
/*描述：1：DIG ADC2 CTRL的数据反转，否则不反转*/
#define APB_SARADC_SAR2_INV  (BIT(10))
#define APB_SARADC_SAR2_INV_M  (BIT(10))
#define APB_SARADC_SAR2_INV_V  0x1
#define APB_SARADC_SAR2_INV_S  10
/* APB_SARADC_SAR1_INV:R/W；位位置：[9]；默认值：1'd0；*/
/*描述：1：DIG ADC1 CTRL的数据反转，否则不反转*/
#define APB_SARADC_SAR1_INV  (BIT(9))
#define APB_SARADC_SAR1_INV_M  (BIT(9))
#define APB_SARADC_SAR1_INV_V  0x1
#define APB_SARADC_SAR1_INV_S  9
/* APB_SARADC_MAX_MEAS_NUM:R/W；位位置：[8:1]；默认值：8'd255；*/
/*description:最大转换数*/
#define APB_SARADC_MAX_MEAS_NUM  0x000000FF
#define APB_SARADC_MAX_MEAS_NUM_M  ((APB_SARADC_MAX_MEAS_NUM_V)<<(APB_SARADC_MAX_MEAS_NUM_S))
#define APB_SARADC_MAX_MEAS_NUM_V  0xFF
#define APB_SARADC_MAX_MEAS_NUM_S  1
/* APB_SARADC_MEAS_NUM_LIMIT:R/W；位位置：[0]；默认值：1'd0；*/
/*说明：*/
#define APB_SARADC_MEAS_NUM_LIMIT  (BIT(0))
#define APB_SARADC_MEAS_NUM_LIMIT_M  (BIT(0))
#define APB_SARADC_MEAS_NUM_LIMIT_V  0x1
#define APB_SARADC_MEAS_NUM_LIMIT_S  0

#define APB_SARADC_FSM_REG          (DR_REG_APB_SARADC_BASE + 0x008)
/* APB_SARADC_SAMPLE_CYCLE:R/W；位位置：[31:24]；默认值：8'd2；*/
/*描述：采样周期*/
#define APB_SARADC_SAMPLE_CYCLE  0x000000FF
#define APB_SARADC_SAMPLE_CYCLE_M  ((APB_SARADC_SAMPLE_CYCLE_V)<<(APB_SARADC_SAMPLE_CYCLE_S))
#define APB_SARADC_SAMPLE_CYCLE_V  0xFF
#define APB_SARADC_SAMPLE_CYCLE_S  24
/* APB_SARADC_SAMPLE_NUM:R/W；比特位置：[23:16]；默认值：8'd0；*/
/*description:样本编号*/
#define APB_SARADC_SAMPLE_NUM  0x000000FF
#define APB_SARADC_SAMPLE_NUM_M  ((APB_SARADC_SAMPLE_NUM_V)<<(APB_SARADC_SAMPLE_NUM_S))
#define APB_SARADC_SAMPLE_NUM_V  0xFF
#define APB_SARADC_SAMPLE_NUM_S  16

#define APB_SARADC_FSM_WAIT_REG          (DR_REG_APB_SARADC_BASE + 0x00C)
/* APB_SARADC_STANDBY_WAIT:R/W；比特位置：[23:16]；默认值：8'd255；*/
/*说明：*/
#define APB_SARADC_STANDBY_WAIT  0x000000FF
#define APB_SARADC_STANDBY_WAIT_M  ((APB_SARADC_STANDBY_WAIT_V)<<(APB_SARADC_STANDBY_WAIT_S))
#define APB_SARADC_STANDBY_WAIT_V  0xFF
#define APB_SARADC_STANDBY_WAIT_S  16
/* APB_SARADC_RSTB_WAIT:R/W；比特位置：[15:8]；默认值：8'd8；*/
/*说明：*/
#define APB_SARADC_RSTB_WAIT  0x000000FF
#define APB_SARADC_RSTB_WAIT_M  ((APB_SARADC_RSTB_WAIT_V)<<(APB_SARADC_RSTB_WAIT_S))
#define APB_SARADC_RSTB_WAIT_V  0xFF
#define APB_SARADC_RSTB_WAIT_S  8
/* APB_SARADC_XPD_WAIT:R/W；位位置：[7:0]；默认值：8'd8；*/
/*说明：*/
#define APB_SARADC_XPD_WAIT  0x000000FF
#define APB_SARADC_XPD_WAIT_M  ((APB_SARADC_XPD_WAIT_V)<<(APB_SARADC_XPD_WAIT_S))
#define APB_SARADC_XPD_WAIT_V  0xFF
#define APB_SARADC_XPD_WAIT_S  0

#define APB_SARADC_SAR1_STATUS_REG          (DR_REG_APB_SARADC_BASE + 0x010)
/* APB_SARADC_SAR1_STATUS：RO；位位置：[31:0]；默认值：32'd0；*/
/*说明：*/
#define APB_SARADC_SAR1_STATUS  0xFFFFFFFF
#define APB_SARADC_SAR1_STATUS_M  ((APB_SARADC_SAR1_STATUS_V)<<(APB_SARADC_SAR1_STATUS_S))
#define APB_SARADC_SAR1_STATUS_V  0xFFFFFFFF
#define APB_SARADC_SAR1_STATUS_S  0

#define APB_SARADC_SAR2_STATUS_REG          (DR_REG_APB_SARADC_BASE + 0x014)
/* APB_SARADC_SAR2_STATUS：RO；位位置：[31:0]；默认值：32'd0；*/
/*说明：*/
#define APB_SARADC_SAR2_STATUS  0xFFFFFFFF
#define APB_SARADC_SAR2_STATUS_M  ((APB_SARADC_SAR2_STATUS_V)<<(APB_SARADC_SAR2_STATUS_S))
#define APB_SARADC_SAR2_STATUS_V  0xFFFFFFFF
#define APB_SARADC_SAR2_STATUS_S  0

#define APB_SARADC_SAR1_PATT_TAB1_REG          (DR_REG_APB_SARADC_BASE + 0x018)
/* APB_SARADC_SAR1_PATT_TAB1:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表1的项目0~3（每个项目一个字节）*/
#define APB_SARADC_SAR1_PATT_TAB1  0xFFFFFFFF
#define APB_SARADC_SAR1_PATT_TAB1_M  ((APB_SARADC_SAR1_PATT_TAB1_V)<<(APB_SARADC_SAR1_PATT_TAB1_S))
#define APB_SARADC_SAR1_PATT_TAB1_V  0xFFFFFFFF
#define APB_SARADC_SAR1_PATT_TAB1_S  0

#define APB_SARADC_SAR1_PATT_TAB2_REG          (DR_REG_APB_SARADC_BASE + 0x01C)
/* APB_SARADC_SAR1_PATT_TAB2:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表1的项目4~7（每个项目一个字节）*/
#define APB_SARADC_SAR1_PATT_TAB2  0xFFFFFFFF
#define APB_SARADC_SAR1_PATT_TAB2_M  ((APB_SARADC_SAR1_PATT_TAB2_V)<<(APB_SARADC_SAR1_PATT_TAB2_S))
#define APB_SARADC_SAR1_PATT_TAB2_V  0xFFFFFFFF
#define APB_SARADC_SAR1_PATT_TAB2_S  0

#define APB_SARADC_SAR1_PATT_TAB3_REG          (DR_REG_APB_SARADC_BASE + 0x020)
/* APB_SARADC_SAR1_PATT_TAB3:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表1的项目8~11（每个项目一个字节）*/
#define APB_SARADC_SAR1_PATT_TAB3  0xFFFFFFFF
#define APB_SARADC_SAR1_PATT_TAB3_M  ((APB_SARADC_SAR1_PATT_TAB3_V)<<(APB_SARADC_SAR1_PATT_TAB3_S))
#define APB_SARADC_SAR1_PATT_TAB3_V  0xFFFFFFFF
#define APB_SARADC_SAR1_PATT_TAB3_S  0

#define APB_SARADC_SAR1_PATT_TAB4_REG          (DR_REG_APB_SARADC_BASE + 0x024)
/* APB_SARADC_SAR1_PATT_TAB4:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表1的项目12~15（每个项目一个字节）*/
#define APB_SARADC_SAR1_PATT_TAB4  0xFFFFFFFF
#define APB_SARADC_SAR1_PATT_TAB4_M  ((APB_SARADC_SAR1_PATT_TAB4_V)<<(APB_SARADC_SAR1_PATT_TAB4_S))
#define APB_SARADC_SAR1_PATT_TAB4_V  0xFFFFFFFF
#define APB_SARADC_SAR1_PATT_TAB4_S  0

#define APB_SARADC_SAR2_PATT_TAB1_REG          (DR_REG_APB_SARADC_BASE + 0x028)
/* APB_SARADC_SAR2_PATT_TAB1:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表2的项目0~3（每个项目一个字节）*/
#define APB_SARADC_SAR2_PATT_TAB1  0xFFFFFFFF
#define APB_SARADC_SAR2_PATT_TAB1_M  ((APB_SARADC_SAR2_PATT_TAB1_V)<<(APB_SARADC_SAR2_PATT_TAB1_S))
#define APB_SARADC_SAR2_PATT_TAB1_V  0xFFFFFFFF
#define APB_SARADC_SAR2_PATT_TAB1_S  0

#define APB_SARADC_SAR2_PATT_TAB2_REG          (DR_REG_APB_SARADC_BASE + 0x02C)
/* APB_SARADC_SAR2_PATT_TAB2:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表2的项目4~7（每个项目一个字节）*/
#define APB_SARADC_SAR2_PATT_TAB2  0xFFFFFFFF
#define APB_SARADC_SAR2_PATT_TAB2_M  ((APB_SARADC_SAR2_PATT_TAB2_V)<<(APB_SARADC_SAR2_PATT_TAB2_S))
#define APB_SARADC_SAR2_PATT_TAB2_V  0xFFFFFFFF
#define APB_SARADC_SAR2_PATT_TAB2_S  0

#define APB_SARADC_SAR2_PATT_TAB3_REG          (DR_REG_APB_SARADC_BASE + 0x030)
/* APB_SARADC_SAR2_PATT_TAB3:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表2的项目8~11（每个项目一个字节）*/
#define APB_SARADC_SAR2_PATT_TAB3  0xFFFFFFFF
#define APB_SARADC_SAR2_PATT_TAB3_M  ((APB_SARADC_SAR2_PATT_TAB3_V)<<(APB_SARADC_SAR2_PATT_TAB3_S))
#define APB_SARADC_SAR2_PATT_TAB3_V  0xFFFFFFFF
#define APB_SARADC_SAR2_PATT_TAB3_S  0

#define APB_SARADC_SAR2_PATT_TAB4_REG          (DR_REG_APB_SARADC_BASE + 0x034)
/* APB_SARADC_SAR2_PATT_TAB4:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表2的项目12~15（每个项目一个字节）*/
#define APB_SARADC_SAR2_PATT_TAB4  0xFFFFFFFF
#define APB_SARADC_SAR2_PATT_TAB4_M  ((APB_SARADC_SAR2_PATT_TAB4_V)<<(APB_SARADC_SAR2_PATT_TAB4_S))
#define APB_SARADC_SAR2_PATT_TAB4_V  0xFFFFFFFF
#define APB_SARADC_SAR2_PATT_TAB4_S  0

#define APB_SARADC_APB_ADC_ARB_CTRL_REG          (DR_REG_APB_SARADC_BASE + 0x038)
/* APB_sarac_ADC_ARB_FIX_PRIORITY:R/W；位位置：[12]；默认值：1’b0；*/
/*描述：adc2仲裁器使用固定优先级*/
#define APB_SARADC_ADC_ARB_FIX_PRIORITY  (BIT(12))
#define APB_SARADC_ADC_ARB_FIX_PRIORITY_M  (BIT(12))
#define APB_SARADC_ADC_ARB_FIX_PRIORITY_V  0x1
#define APB_SARADC_ADC_ARB_FIX_PRIORITY_S  12
/* APB_sarac_ADC_ARB_WIFI_PRIORITY:R/W；比特位置：[11:10]；默认值：2'd2；*/
/*description:设置adc2仲裁器wifi优先级*/
#define APB_SARADC_ADC_ARB_WIFI_PRIORITY  0x00000003
#define APB_SARADC_ADC_ARB_WIFI_PRIORITY_M  ((APB_SARADC_ADC_ARB_WIFI_PRIORITY_V)<<(APB_SARADC_ADC_ARB_WIFI_PRIORITY_S))
#define APB_SARADC_ADC_ARB_WIFI_PRIORITY_V  0x3
#define APB_SARADC_ADC_ARB_WIFI_PRIORITY_S  10
/* APB_SARADC_addc_ARB_RTC_PRIORITY:R/W；比特位置：[9:8]；默认值：2'd1；*/
/*description:设置adc2仲裁器rtc优先级*/
#define APB_SARADC_ADC_ARB_RTC_PRIORITY  0x00000003
#define APB_SARADC_ADC_ARB_RTC_PRIORITY_M  ((APB_SARADC_ADC_ARB_RTC_PRIORITY_V)<<(APB_SARADC_ADC_ARB_RTC_PRIORITY_S))
#define APB_SARADC_ADC_ARB_RTC_PRIORITY_V  0x3
#define APB_SARADC_ADC_ARB_RTC_PRIORITY_S  8
/* APB_SARADC_add_ARB_APB_优先级：R/W；位位置：[7:6]；默认值：2'd0；*/
/*description:设置adc2仲裁器优先级*/
#define APB_SARADC_ADC_ARB_APB_PRIORITY  0x00000003
#define APB_SARADC_ADC_ARB_APB_PRIORITY_M  ((APB_SARADC_ADC_ARB_APB_PRIORITY_V)<<(APB_SARADC_ADC_ARB_APB_PRIORITY_S))
#define APB_SARADC_ADC_ARB_APB_PRIORITY_V  0x3
#define APB_SARADC_ADC_ARB_APB_PRIORITY_S  6
/* APB_sarac_ADC_ARB_GRANT_FORCE:R/W；位位置：[5]；默认值：1’b0；*/
/*描述：adc2仲裁器强制授权*/
#define APB_SARADC_ADC_ARB_GRANT_FORCE  (BIT(5))
#define APB_SARADC_ADC_ARB_GRANT_FORCE_M  (BIT(5))
#define APB_SARADC_ADC_ARB_GRANT_FORCE_V  0x1
#define APB_SARADC_ADC_ARB_GRANT_FORCE_S  5
/* APB_sarac_ADC_ARB_WIFI_FORCE:R/W；位位置：[4]；默认值：1’b0；*/
/*描述：adc2仲裁器强制启用wifi控制器*/
#define APB_SARADC_ADC_ARB_WIFI_FORCE  (BIT(4))
#define APB_SARADC_ADC_ARB_WIFI_FORCE_M  (BIT(4))
#define APB_SARADC_ADC_ARB_WIFI_FORCE_V  0x1
#define APB_SARADC_ADC_ARB_WIFI_FORCE_S  4
/* APB_sarac_ADC_ARB_RTC_FORCE:R/W；位位置：[3]；默认值：1’b0；*/
/*描述：adc2仲裁器强制启用rtc控制器*/
#define APB_SARADC_ADC_ARB_RTC_FORCE  (BIT(3))
#define APB_SARADC_ADC_ARB_RTC_FORCE_M  (BIT(3))
#define APB_SARADC_ADC_ARB_RTC_FORCE_V  0x1
#define APB_SARADC_ADC_ARB_RTC_FORCE_S  3
/* APB_SARADC_add_ARB_APB_FORCE:R/W；位位置：[2]；默认值：1’b0；*/
/*描述：adc2仲裁器强制启用apb控制器*/
#define APB_SARADC_ADC_ARB_APB_FORCE  (BIT(2))
#define APB_SARADC_ADC_ARB_APB_FORCE_M  (BIT(2))
#define APB_SARADC_ADC_ARB_APB_FORCE_V  0x1
#define APB_SARADC_ADC_ARB_APB_FORCE_S  2

#define APB_SARADC_FILTER_CTRL_REG          (DR_REG_APB_SARADC_BASE + 0x03C)
/* APB_SARADC_addc_FILTER_EN:R/W；位位置：[31]；默认值：1’b0；*/
/*描述：启用apb_adc1_filter*/
#define APB_SARADC_ADC1_FILTER_EN  (BIT(31))
#define APB_SARADC_ADC1_FILTER_EN_M  (BIT(31))
#define APB_SARADC_ADC1_FILTER_EN_V  0x1
#define APB_SARADC_ADC1_FILTER_EN_S  31
/* APB_SARADC_addc_FILTER_EN:R/W；位位置：[30]；默认值：1’b0；*/
/*描述：启用apb_adc2_filter*/
#define APB_SARADC_ADC2_FILTER_EN  (BIT(30))
#define APB_SARADC_ADC2_FILTER_EN_M  (BIT(30))
#define APB_SARADC_ADC2_FILTER_EN_V  0x1
#define APB_SARADC_ADC2_FILTER_EN_S  30
/* APB_SARADC_addc_FILTER_actor:R/W；位位置：[29:23]；默认值：7'd64；*/
/*描述：apb_adc1_filter_actor*/
#define APB_SARADC_ADC1_FILTER_FACTOR  0x0000007F
#define APB_SARADC_ADC1_FILTER_FACTOR_M  ((APB_SARADC_ADC1_FILTER_FACTOR_V)<<(APB_SARADC_ADC1_FILTER_FACTOR_S))
#define APB_SARADC_ADC1_FILTER_FACTOR_V  0x7F
#define APB_SARADC_ADC1_FILTER_FACTOR_S  23
/* APB_SARADC_addc_FILTER_actor:R/W；比特位置：[22:16]；默认值：7'd64；*/
/*描述：apb_adc2_filter_actor*/
#define APB_SARADC_ADC2_FILTER_FACTOR  0x0000007F
#define APB_SARADC_ADC2_FILTER_FACTOR_M  ((APB_SARADC_ADC2_FILTER_FACTOR_V)<<(APB_SARADC_ADC2_FILTER_FACTOR_S))
#define APB_SARADC_ADC2_FILTER_FACTOR_V  0x7F
#define APB_SARADC_ADC2_FILTER_FACTOR_S  16
/* APB_SARADC_addc_FILTER_RESET:R/W；位位置：[1]；默认值：1’b0；*/
/*描述：reset_adc1_filter*/
#define APB_SARADC_ADC1_FILTER_RESET  (BIT(1))
#define APB_SARADC_ADC1_FILTER_RESET_M  (BIT(1))
#define APB_SARADC_ADC1_FILTER_RESET_V  0x1
#define APB_SARADC_ADC1_FILTER_RESET_S  1
/* APB_SARADC_addc_FILTER_RESET:R/W；位位置：[0]；默认值：1’b0；*/
/*描述：reset_adc2_filter*/
#define APB_SARADC_ADC2_FILTER_RESET  (BIT(0))
#define APB_SARADC_ADC2_FILTER_RESET_M  (BIT(0))
#define APB_SARADC_ADC2_FILTER_RESET_V  0x1
#define APB_SARADC_ADC2_FILTER_RESET_S  0

#define APB_SARADC_FILTER_STATUS_REG          (DR_REG_APB_SARADC_BASE + 0x040)
/* APB_SARADC_addc_FILTER数据：RO；比特位置：[31:16]；默认值：16'd0；*/
/*说明：*/
#define APB_SARADC_ADC1_FILTER_DATA  0x0000FFFF
#define APB_SARADC_ADC1_FILTER_DATA_M  ((APB_SARADC_ADC1_FILTER_DATA_V)<<(APB_SARADC_ADC1_FILTER_DATA_S))
#define APB_SARADC_ADC1_FILTER_DATA_V  0xFFFF
#define APB_SARADC_ADC1_FILTER_DATA_S  16
/* APB_SARADC_addc_FILTER数据：RO；比特位置：[15:0]；默认值：16'd0；*/
/*说明：*/
#define APB_SARADC_ADC2_FILTER_DATA  0x0000FFFF
#define APB_SARADC_ADC2_FILTER_DATA_M  ((APB_SARADC_ADC2_FILTER_DATA_V)<<(APB_SARADC_ADC2_FILTER_DATA_S))
#define APB_SARADC_ADC2_FILTER_DATA_V  0xFFFF
#define APB_SARADC_ADC2_FILTER_DATA_S  0

#define APB_SARADC_THRES_CTRL_REG          (DR_REG_APB_SARADC_BASE + 0x044)
/* APB_SARADC_addc_threes_EN:R/W；位位置：[31]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC1_THRES_EN  (BIT(31))
#define APB_SARADC_ADC1_THRES_EN_M  (BIT(31))
#define APB_SARADC_ADC1_THRES_EN_V  0x1
#define APB_SARADC_ADC1_THRES_EN_S  31
/* APB_SARADC_addc_threes_EN:R/W；位位置：[30]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC2_THRES_EN  (BIT(30))
#define APB_SARADC_ADC2_THRES_EN_M  (BIT(30))
#define APB_SARADC_ADC2_THRES_EN_V  0x1
#define APB_SARADC_ADC2_THRES_EN_S  30
/* APB_sarac_ADC1_threes:R/W；比特位置：[29:17]；默认值：13'd0；*/
/*说明：*/
#define APB_SARADC_ADC1_THRES  0x00001FFF
#define APB_SARADC_ADC1_THRES_M  ((APB_SARADC_ADC1_THRES_V)<<(APB_SARADC_ADC1_THRES_S))
#define APB_SARADC_ADC1_THRES_V  0x1FFF
#define APB_SARADC_ADC1_THRES_S  17
/* APB_SARADC_addc_threes:R/W；比特位置：[16:4]；默认值：13'd0；*/
/*说明：*/
#define APB_SARADC_ADC2_THRES  0x00001FFF
#define APB_SARADC_ADC2_THRES_M  ((APB_SARADC_ADC2_THRES_V)<<(APB_SARADC_ADC2_THRES_S))
#define APB_SARADC_ADC2_THRES_V  0x1FFF
#define APB_SARADC_ADC2_THRES_S  4
/* APB_SARADC__ADC1_threes_MODE:R/W；位位置：[3]；默认值：1'0；*/
/*说明：*/
#define APB_SARADC_ADC1_THRES_MODE  (BIT(3))
#define APB_SARADC_ADC1_THRES_MODE_M  (BIT(3))
#define APB_SARADC_ADC1_THRES_MODE_V  0x1
#define APB_SARADC_ADC1_THRES_MODE_S  3
/* APB_SARADC_addc_threes_MODE:R/W；位位置：[2]；默认值：1'0；*/
/*说明：*/
#define APB_SARADC_ADC2_THRES_MODE  (BIT(2))
#define APB_SARADC_ADC2_THRES_MODE_M  (BIT(2))
#define APB_SARADC_ADC2_THRES_MODE_V  0x1
#define APB_SARADC_ADC2_THRES_MODE_S  2
/* APB_SARADC_CLK_EN:R/W；位位置：[0]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_CLK_EN  (BIT(0))
#define APB_SARADC_CLK_EN_M  (BIT(0))
#define APB_SARADC_CLK_EN_V  0x1
#define APB_SARADC_CLK_EN_S  0

#define APB_SARADC_INT_ENA_REG          (DR_REG_APB_SARADC_BASE + 0x048)
/* APB_SARADC_addc_DONE_INT_ENA:R/W；位位置：[31]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC1_DONE_INT_ENA  (BIT(31))
#define APB_SARADC_ADC1_DONE_INT_ENA_M  (BIT(31))
#define APB_SARADC_ADC1_DONE_INT_ENA_V  0x1
#define APB_SARADC_ADC1_DONE_INT_ENA_S  31
/* APB_SARADC_addc_DONE_INT_ENA:R/W；位位置：[30]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC2_DONE_INT_ENA  (BIT(30))
#define APB_SARADC_ADC2_DONE_INT_ENA_M  (BIT(30))
#define APB_SARADC_ADC2_DONE_INT_ENA_V  0x1
#define APB_SARADC_ADC2_DONE_INT_ENA_S  30
/* APB_SARADC_addc_threshold_INT_ENA:R/W；位位置：[29]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC1_THRES_INT_ENA  (BIT(29))
#define APB_SARADC_ADC1_THRES_INT_ENA_M  (BIT(29))
#define APB_SARADC_ADC1_THRES_INT_ENA_V  0x1
#define APB_SARADC_ADC1_THRES_INT_ENA_S  29
/* APB_SARADC_addc_threshold_INT_ENA:R/W；位位置：[28]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC2_THRES_INT_ENA  (BIT(28))
#define APB_SARADC_ADC2_THRES_INT_ENA_M  (BIT(28))
#define APB_SARADC_ADC2_THRES_INT_ENA_V  0x1
#define APB_SARADC_ADC2_THRES_INT_ENA_S  28

#define APB_SARADC_INT_RAW_REG          (DR_REG_APB_SARADC_BASE + 0x04C)
/* APB_SARADC_addc_DONE_INT_RAW:RO；位位置：[31]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC1_DONE_INT_RAW  (BIT(31))
#define APB_SARADC_ADC1_DONE_INT_RAW_M  (BIT(31))
#define APB_SARADC_ADC1_DONE_INT_RAW_V  0x1
#define APB_SARADC_ADC1_DONE_INT_RAW_S  31
/* APB_SARADC_ADC2_DONE_INT_RAW:RO；位位置：[30]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC2_DONE_INT_RAW  (BIT(30))
#define APB_SARADC_ADC2_DONE_INT_RAW_M  (BIT(30))
#define APB_SARADC_ADC2_DONE_INT_RAW_V  0x1
#define APB_SARADC_ADC2_DONE_INT_RAW_S  30
/* APB_SARADC_addc_threes_INT_RAW:RO；位位置：[29]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC1_THRES_INT_RAW  (BIT(29))
#define APB_SARADC_ADC1_THRES_INT_RAW_M  (BIT(29))
#define APB_SARADC_ADC1_THRES_INT_RAW_V  0x1
#define APB_SARADC_ADC1_THRES_INT_RAW_S  29
/* APB_SARADC_addc_threshold_INT_RAW:RO；位位置：[28]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC2_THRES_INT_RAW  (BIT(28))
#define APB_SARADC_ADC2_THRES_INT_RAW_M  (BIT(28))
#define APB_SARADC_ADC2_THRES_INT_RAW_V  0x1
#define APB_SARADC_ADC2_THRES_INT_RAW_S  28

#define APB_SARADC_INT_ST_REG          (DR_REG_APB_SARADC_BASE + 0x050)
/* APB_SARADC_addc_DONE_INT_ST:RO；位位置：[31]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC1_DONE_INT_ST  (BIT(31))
#define APB_SARADC_ADC1_DONE_INT_ST_M  (BIT(31))
#define APB_SARADC_ADC1_DONE_INT_ST_V  0x1
#define APB_SARADC_ADC1_DONE_INT_ST_S  31
/* APB_SARADC_ADC2_DONE_INT_ST:RO；位位置：[30]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC2_DONE_INT_ST  (BIT(30))
#define APB_SARADC_ADC2_DONE_INT_ST_M  (BIT(30))
#define APB_SARADC_ADC2_DONE_INT_ST_V  0x1
#define APB_SARADC_ADC2_DONE_INT_ST_S  30
/* APB_sarac_ADC1_threes_INT_ST:RO；位位置：[29]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC1_THRES_INT_ST  (BIT(29))
#define APB_SARADC_ADC1_THRES_INT_ST_M  (BIT(29))
#define APB_SARADC_ADC1_THRES_INT_ST_V  0x1
#define APB_SARADC_ADC1_THRES_INT_ST_S  29
/* APB_SARADC_addc_threshold_INT_ST:RO；位位置：[28]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC2_THRES_INT_ST  (BIT(28))
#define APB_SARADC_ADC2_THRES_INT_ST_M  (BIT(28))
#define APB_SARADC_ADC2_THRES_INT_ST_V  0x1
#define APB_SARADC_ADC2_THRES_INT_ST_S  28

#define APB_SARADC_INT_CLR_REG          (DR_REG_APB_SARADC_BASE + 0x054)
/* APB_SARADC_addc_DONE_INT_CLR:WO；位位置：[31]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC1_DONE_INT_CLR  (BIT(31))
#define APB_SARADC_ADC1_DONE_INT_CLR_M  (BIT(31))
#define APB_SARADC_ADC1_DONE_INT_CLR_V  0x1
#define APB_SARADC_ADC1_DONE_INT_CLR_S  31
/* APB_SARADC_ADC2_DONE_INT_CLR:WO；位位置：[30]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC2_DONE_INT_CLR  (BIT(30))
#define APB_SARADC_ADC2_DONE_INT_CLR_M  (BIT(30))
#define APB_SARADC_ADC2_DONE_INT_CLR_V  0x1
#define APB_SARADC_ADC2_DONE_INT_CLR_S  30
/* APB_sarac_ADC1_threes_INT_CLR:WO；位位置：[29]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC1_THRES_INT_CLR  (BIT(29))
#define APB_SARADC_ADC1_THRES_INT_CLR_M  (BIT(29))
#define APB_SARADC_ADC1_THRES_INT_CLR_V  0x1
#define APB_SARADC_ADC1_THRES_INT_CLR_S  29
/* APB_SARADC_addc_threshold_INT_CLR:WO；位位置：[28]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_ADC2_THRES_INT_CLR  (BIT(28))
#define APB_SARADC_ADC2_THRES_INT_CLR_M  (BIT(28))
#define APB_SARADC_ADC2_THRES_INT_CLR_V  0x1
#define APB_SARADC_ADC2_THRES_INT_CLR_S  28

#define APB_SARADC_DMA_CONF_REG          (DR_REG_APB_SARADC_BASE + 0x058)
/* APB_sarac_APB_ADC_TRANS:R/W；位位置：[31]；默认值：1'd0；*/
/*描述：启用apb_adc使用spi_dma*/
#define APB_SARADC_APB_ADC_TRANS  (BIT(31))
#define APB_SARADC_APB_ADC_TRANS_M  (BIT(31))
#define APB_SARADC_APB_ADC_TRANS_V  0x1
#define APB_SARADC_APB_ADC_TRANS_S  31
/* APB_sarac_APB_ADC_RESET_FSM:R/W；位位置：[30]；默认值：1’b0；*/
/*描述：reset_apb_adc_state*/
#define APB_SARADC_APB_ADC_RESET_FSM  (BIT(30))
#define APB_SARADC_APB_ADC_RESET_FSM_M  (BIT(30))
#define APB_SARADC_APB_ADC_RESET_FSM_V  0x1
#define APB_SARADC_APB_ADC_RESET_FSM_S  30
/* APB_sarac_APB_ADC_of_NUM:R/W；比特位置：[15:0]；默认值：16'd255；*/
/*描述：样本cnt=spi_eof_num时的dma_in_suc_eof gen*/
#define APB_SARADC_APB_ADC_EOF_NUM  0x0000FFFF
#define APB_SARADC_APB_ADC_EOF_NUM_M  ((APB_SARADC_APB_ADC_EOF_NUM_V)<<(APB_SARADC_APB_ADC_EOF_NUM_S))
#define APB_SARADC_APB_ADC_EOF_NUM_V  0xFFFF
#define APB_SARADC_APB_ADC_EOF_NUM_S  0

#define APB_SARADC_APB_ADC_CLKM_CONF_REG          (DR_REG_APB_SARADC_BASE + 0x05c)
/* APB_SARADC_CLK_SEL:R/W；比特位置：[22:21]；默认值：2’b0；*/
/*description:设置此位以启用clk_apl*/
#define APB_SARADC_CLK_SEL  0x00000003
#define APB_SARADC_CLK_SEL_M  ((APB_SARADC_CLK_SEL_V)<<(APB_SARADC_CLK_SEL_S))
#define APB_SARADC_CLK_SEL_V  0x3
#define APB_SARADC_CLK_SEL_S  21
/* APB_SARADC_CLKM_DIV_A:R/W；比特位置：[19:14]；默认值：6'0；*/
/*description:分数分频器分母值*/
#define APB_SARADC_CLKM_DIV_A  0x0000003F
#define APB_SARADC_CLKM_DIV_A_M  ((APB_SARADC_CLKM_DIV_A_V)<<(APB_SARADC_CLKM_DIV_A_S))
#define APB_SARADC_CLKM_DIV_A_V  0x3F
#define APB_SARADC_CLKM_DIV_A_S  14
/* APB_SARADC_CLKM_DIV_B:R/W；比特位置：[13:8]；默认值：6'0；*/
/*description:分数分频器分子值*/
#define APB_SARADC_CLKM_DIV_B  0x0000003F
#define APB_SARADC_CLKM_DIV_B_M  ((APB_SARADC_CLKM_DIV_B_V)<<(APB_SARADC_CLKM_DIV_B_S))
#define APB_SARADC_CLKM_DIV_B_V  0x3F
#define APB_SARADC_CLKM_DIV_B_S  8
/* APB_SARADC_CLKM_DIV_NUM:R/W；位位置：[7:0]；默认值：8'd4；*/
/*description:积分I2S时钟分频器值*/
#define APB_SARADC_CLKM_DIV_NUM  0x000000FF
#define APB_SARADC_CLKM_DIV_NUM_M  ((APB_SARADC_CLKM_DIV_NUM_V)<<(APB_SARADC_CLKM_DIV_NUM_S))
#define APB_SARADC_CLKM_DIV_NUM_V  0xFF
#define APB_SARADC_CLKM_DIV_NUM_S  0

#define APB_SARADC_APB_DAC_CTRL_REG          (DR_REG_APB_SARADC_BASE + 0x060)
/* APB_sarac_APB_DAC_RST:R/W；位位置：[16]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_APB_DAC_RST  (BIT(16))
#define APB_SARADC_APB_DAC_RST_M  (BIT(16))
#define APB_SARADC_APB_DAC_RST_V  0x1
#define APB_SARADC_APB_DAC_RST_S  16
/* APB_SARADC_DAC_RESET_FIFO:R/W；位位置：[15]；默认值：1’b0；*/
/*说明：*/
#define APB_SARADC_DAC_RESET_FIFO  (BIT(15))
#define APB_SARADC_DAC_RESET_FIFO_M  (BIT(15))
#define APB_SARADC_DAC_RESET_FIFO_V  0x1
#define APB_SARADC_DAC_RESET_FIFO_S  15
/* APB_SARADC_APB_DAC_TRANS:R/W；位位置：[14]；默认值：1’b0；*/
/*描述：启用dma_dac*/
#define APB_SARADC_APB_DAC_TRANS  (BIT(14))
#define APB_SARADC_APB_DAC_TRANS_M  (BIT(14))
#define APB_SARADC_APB_DAC_TRANS_V  0x1
#define APB_SARADC_APB_DAC_TRANS_S  14
/* APB_sarac_APB_DAC_ALTER_MODE：R/W；位位置：[13]；默认值：1’b1；*/
/*描述：启用dac alter模式*/
#define APB_SARADC_APB_DAC_ALTER_MODE  (BIT(13))
#define APB_SARADC_APB_DAC_ALTER_MODE_M  (BIT(13))
#define APB_SARADC_APB_DAC_ALTER_MODE_V  0x1
#define APB_SARADC_APB_DAC_ALTER_MODE_S  13
/* APB_SARADC_DAC_TIMER_EN:R/W；位位置：[12]；默认值：1’b0；*/
/*description:启用读取dac数据*/
#define APB_SARADC_DAC_TIMER_EN  (BIT(12))
#define APB_SARADC_DAC_TIMER_EN_M  (BIT(12))
#define APB_SARADC_DAC_TIMER_EN_V  0x1
#define APB_SARADC_DAC_TIMER_EN_S  12
/* APB_SARADC_DAC_TIMER_TARGET:R/W；位位置：[11:0]；默认值：12'd100；*/
/*description:dac_timer目标*/
#define APB_SARADC_DAC_TIMER_TARGET  0x00000FFF
#define APB_SARADC_DAC_TIMER_TARGET_M  ((APB_SARADC_DAC_TIMER_TARGET_V)<<(APB_SARADC_DAC_TIMER_TARGET_S))
#define APB_SARADC_DAC_TIMER_TARGET_V  0xFFF
#define APB_SARADC_DAC_TIMER_TARGET_S  0

#define APB_SARADC_APB_CTRL_DATE_REG          (DR_REG_APB_SARADC_BASE + 0x3FC)
/* APB_sarac_APB_CTRL_DATE:R/W；位位置：[31:0]；默认值：32'H0190762；*/
/*说明：*/
#define APB_SARADC_APB_CTRL_DATE  0xFFFFFFFF
#define APB_SARADC_APB_CTRL_DATE_M  ((APB_SARADC_APB_CTRL_DATE_V)<<(APB_SARADC_APB_CTRL_DATE_S))
#define APB_SARADC_APB_CTRL_DATE_V  0xFFFFFFFF
#define APB_SARADC_APB_CTRL_DATE_S  0

#ifdef __cplusplus
}
#endif



#endif /*_SOC_APB_SARADC_REG_H_ */

