// 版权所有2017-2018 Espressif Systems（上海）私人有限公司
//
// 根据Apache许可证2.0版（“许可证”）获得许可；
// 除非符合许可证，否则不得使用此文件。
// 您可以在以下地址获取许可证副本：
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// 除非适用法律要求或书面同意，软件
// 根据许可证分发的内容是按“原样”分发的，
// 无任何明示或暗示的保证或条件。
// 有关管理权限和
// 许可证下的限制。
#ifndef _SOC_EXTMEM_REG_H_
#define _SOC_EXTMEM_REG_H_


#ifdef __cplusplus
extern "C" {
#endif
#include "soc.h"
#define EXTMEM_PRO_DCACHE_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x000)
/* EXTMEM_PRO_DCACHE_LOCK_DONE:RO；位位置：[25]；默认值：1’b0；*/
/*description:该位用于指示锁定操作完成。*/
#define EXTMEM_PRO_DCACHE_LOCK_DONE  (BIT(25))
#define EXTMEM_PRO_DCACHE_LOCK_DONE_M  (BIT(25))
#define EXTMEM_PRO_DCACHE_LOCK_DONE_V  0x1
#define EXTMEM_PRO_DCACHE_LOCK_DONE_S  25
/* EXTMEM_PRO_DCACHE_LOCK_ENA:R/W；位位置：[24]；默认值：1’b0；*/
/*description:该位用于启用锁定操作。锁定操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_DCACHE_LOCK_ENA  (BIT(24))
#define EXTMEM_PRO_DCACHE_LOCK_ENA_M  (BIT(24))
#define EXTMEM_PRO_DCACHE_LOCK_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_LOCK_ENA_S  24
/* EXTMEM_PRO_DCACHE_UNLOCK_DONE:RO；位位置：[23]；默认值：1’b0；*/
/*description:该位用于指示解锁操作完成。*/
#define EXTMEM_PRO_DCACHE_UNLOCK_DONE  (BIT(23))
#define EXTMEM_PRO_DCACHE_UNLOCK_DONE_M  (BIT(23))
#define EXTMEM_PRO_DCACHE_UNLOCK_DONE_V  0x1
#define EXTMEM_PRO_DCACHE_UNLOCK_DONE_S  23
/* EXTMEM_PRO_DCACHE_UNLOCK_ENA:R/W；位位置：[22]；默认值：1’b0；*/
/*description:该位用于启用解锁操作。解锁操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_DCACHE_UNLOCK_ENA  (BIT(22))
#define EXTMEM_PRO_DCACHE_UNLOCK_ENA_M  (BIT(22))
#define EXTMEM_PRO_DCACHE_UNLOCK_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_UNLOCK_ENA_S  22
/* EXTMEM_PRO_DCACHE_proad_DONE:RO；位位置：[21]；默认值：1’b0；*/
/*description:该位用于指示预加载操作完成。*/
#define EXTMEM_PRO_DCACHE_PRELOAD_DONE  (BIT(21))
#define EXTMEM_PRO_DCACHE_PRELOAD_DONE_M  (BIT(21))
#define EXTMEM_PRO_DCACHE_PRELOAD_DONE_V  0x1
#define EXTMEM_PRO_DCACHE_PRELOAD_DONE_S  21
/* EXTMEM_PRO_DCACHE_proad_ENA:R/W；位位置：[20]；默认值：1’b0；*/
/*description:该位用于启用预加载操作。预加载操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_DCACHE_PRELOAD_ENA  (BIT(20))
#define EXTMEM_PRO_DCACHE_PRELOAD_ENA_M  (BIT(20))
#define EXTMEM_PRO_DCACHE_PRELOAD_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_PRELOAD_ENA_S  20
/* EXTMEM_PRO_DCACHE_AUTOLOAD_DONE:RO；位位置：[19]；默认值：1’b0；*/
/*description:该位用于指示条件预加载操作完成。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_DONE  (BIT(19))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_DONE_M  (BIT(19))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_DONE_V  0x1
#define EXTMEM_PRO_DCACHE_AUTOLOAD_DONE_S  19
/* EXTMEM_PRO_DCACHE_AUTOLOAD_ENA:R/W；位位置：[18]；默认值：1’b0；*/
/*description:该位用于启用和禁用条件预加载操作。它与pre_dcache_autoload_done结合使用。1： 启用0：禁用。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ENA  (BIT(18))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ENA_M  (BIT(18))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ENA_S  18
/* EXTMEM_PRO_DCACHE_LOCK1_EN:R/W；位位置：[15]；默认值：1’b0；*/
/*description:该位用于启用与PRO_DCACHE_LOCK1_ADDR_REG和PRO_DCACHE _LOCK1_SIZE_REG组合的预锁定操作。*/
#define EXTMEM_PRO_DCACHE_LOCK1_EN  (BIT(15))
#define EXTMEM_PRO_DCACHE_LOCK1_EN_M  (BIT(15))
#define EXTMEM_PRO_DCACHE_LOCK1_EN_V  0x1
#define EXTMEM_PRO_DCACHE_LOCK1_EN_S  15
/* EXTMEM_PRO_DCACHE_LOCK0_EN:R/W；位位置：[14]；默认值：1’b0；*/
/*description:该位用于启用与PRO_DCACHE_LOCK0_ADDR_REG和PRO_DCACHE _LOCK0_SIZE_REG组合的预锁定操作。*/
#define EXTMEM_PRO_DCACHE_LOCK0_EN  (BIT(14))
#define EXTMEM_PRO_DCACHE_LOCK0_EN_M  (BIT(14))
#define EXTMEM_PRO_DCACHE_LOCK0_EN_V  0x1
#define EXTMEM_PRO_DCACHE_LOCK0_EN_S  14
/* EXTMEM_PRO_DCACHE_CLEAN_DONE:RO；位位置：[13]；默认值：1’b0；*/
/*description:该位用于指示清洁操作完成。*/
#define EXTMEM_PRO_DCACHE_CLEAN_DONE  (BIT(13))
#define EXTMEM_PRO_DCACHE_CLEAN_DONE_M  (BIT(13))
#define EXTMEM_PRO_DCACHE_CLEAN_DONE_V  0x1
#define EXTMEM_PRO_DCACHE_CLEAN_DONE_S  13
/* EXTMEM_PRO_DCACHE_CLEAN_ENA:R/W；位位置：[12]；默认值：1’b0；*/
/*description:该位用于启用清洁操作。清洁操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_DCACHE_CLEAN_ENA  (BIT(12))
#define EXTMEM_PRO_DCACHE_CLEAN_ENA_M  (BIT(12))
#define EXTMEM_PRO_DCACHE_CLEAN_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_CLEAN_ENA_S  12
/* EXTMEM_PRO_DCACHE_FLUSH_DONE:RO；位位置：[11]；默认值：1’b0；*/
/*description:该位用于指示冲洗操作已完成。*/
#define EXTMEM_PRO_DCACHE_FLUSH_DONE  (BIT(11))
#define EXTMEM_PRO_DCACHE_FLUSH_DONE_M  (BIT(11))
#define EXTMEM_PRO_DCACHE_FLUSH_DONE_V  0x1
#define EXTMEM_PRO_DCACHE_FLUSH_DONE_S  11
/* EXTMEM_PRO_DCACHE_FLUSH_ENA:R/W；位位置：[10]；默认值：1’b0；*/
/*description:该位用于启用刷新操作。冲洗操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_DCACHE_FLUSH_ENA  (BIT(10))
#define EXTMEM_PRO_DCACHE_FLUSH_ENA_M  (BIT(10))
#define EXTMEM_PRO_DCACHE_FLUSH_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_FLUSH_ENA_S  10
/* EXTMEM_PRO_DCACHE_invalidatedone:RO；位位置：[9]；默认值：1’b0；*/
/*description:该位用于指示无效操作已完成。*/
#define EXTMEM_PRO_DCACHE_INVALIDATE_DONE  (BIT(9))
#define EXTMEM_PRO_DCACHE_INVALIDATE_DONE_M  (BIT(9))
#define EXTMEM_PRO_DCACHE_INVALIDATE_DONE_V  0x1
#define EXTMEM_PRO_DCACHE_INVALIDATE_DONE_S  9
/* EXTMEM_PRO_DCACHE_INVALIDATE_ENA:R/W；位位置：[8]；默认值：1’b1；*/
/*description:该位用于启用无效操作。无效操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_DCACHE_INVALIDATE_ENA  (BIT(8))
#define EXTMEM_PRO_DCACHE_INVALIDATE_ENA_M  (BIT(8))
#define EXTMEM_PRO_DCACHE_INVALIDATE_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_INVALIDATE_ENA_S  8
/* EXTMEM_PRO_DCACHE_BLOCKSIZE_MODE：R/W；位位置：[3]；默认值：1’b0；*/
/*description:该位用于配置缓存块大小。0:16字节1:32字节*/
#define EXTMEM_PRO_DCACHE_BLOCKSIZE_MODE  (BIT(3))
#define EXTMEM_PRO_DCACHE_BLOCKSIZE_MODE_M  (BIT(3))
#define EXTMEM_PRO_DCACHE_BLOCKSIZE_MODE_V  0x1
#define EXTMEM_PRO_DCACHE_BLOCKSIZE_MODE_S  3
/* EXTMEM_PRO_DCACHE_SETSIZE_MODE：R/W；位位置：[2]；默认值：1’b0；*/
/*description:该位用于配置缓存内存大小。0:8KB 1:16KB*/
#define EXTMEM_PRO_DCACHE_SETSIZE_MODE  (BIT(2))
#define EXTMEM_PRO_DCACHE_SETSIZE_MODE_M  (BIT(2))
#define EXTMEM_PRO_DCACHE_SETSIZE_MODE_V  0x1
#define EXTMEM_PRO_DCACHE_SETSIZE_MODE_S  2
/* EXTMEM_PRO_DCACHE_ENABLE:R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于激活数据缓存。0：禁用1：启用*/
#define EXTMEM_PRO_DCACHE_ENABLE  (BIT(0))
#define EXTMEM_PRO_DCACHE_ENABLE_M  (BIT(0))
#define EXTMEM_PRO_DCACHE_ENABLE_V  0x1
#define EXTMEM_PRO_DCACHE_ENABLE_S  0

#define EXTMEM_PRO_DCACHE_CTRL1_REG          (DR_REG_EXTMEM_BASE + 0x004)
/* EXTMEM_PRO_DCACHE_MASK_BUS2:R/W；位位置：[2]；默认值：1’b1；*/
/*description:该位用于禁用dbus2 0:启用1:禁用*/
#define EXTMEM_PRO_DCACHE_MASK_BUS2  (BIT(2))
#define EXTMEM_PRO_DCACHE_MASK_BUS2_M  (BIT(2))
#define EXTMEM_PRO_DCACHE_MASK_BUS2_V  0x1
#define EXTMEM_PRO_DCACHE_MASK_BUS2_S  2
/* EXTMEM_PRO_DCACHE_MASK_BUS1:R/W；位位置：[1]；默认值：1’b1；*/
/*description:该位用于禁用dbus1 0:启用1:禁用*/
#define EXTMEM_PRO_DCACHE_MASK_BUS1  (BIT(1))
#define EXTMEM_PRO_DCACHE_MASK_BUS1_M  (BIT(1))
#define EXTMEM_PRO_DCACHE_MASK_BUS1_V  0x1
#define EXTMEM_PRO_DCACHE_MASK_BUS1_S  1
/* EXTMEM_PRO_DCACHE_MASK_BUS0:R/W；位位置：[0]；默认值：1’b1；*/
/*description:该位用于禁用dbus0 0:enable 1:disable*/
#define EXTMEM_PRO_DCACHE_MASK_BUS0  (BIT(0))
#define EXTMEM_PRO_DCACHE_MASK_BUS0_M  (BIT(0))
#define EXTMEM_PRO_DCACHE_MASK_BUS0_V  0x1
#define EXTMEM_PRO_DCACHE_MASK_BUS0_S  0
#define EXTMEM_PRO_DCACHE_MASK_DRAM0 EXTMEM_PRO_DCACHE_MASK_BUS0
#define EXTMEM_PRO_DCACHE_MASK_DRAM1 EXTMEM_PRO_DCACHE_MASK_BUS1
#define EXTMEM_PRO_DCACHE_MASK_DPORT EXTMEM_PRO_DCACHE_MASK_BUS2

#define EXTMEM_PRO_DCACHE_TAG_POWER_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x008)
/* EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PU:R/W；位位置：[2]；默认值：1’b1；*/
/*description:该位用于关闭dcache标记内存0:遵循rtc_lslp_pd 1:通电*/
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PU  (BIT(2))
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PU_M  (BIT(2))
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PU_V  0x1
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PU_S  2
/* EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PD:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于关闭dcache标记内存0：遵循rtc_lslp_pd 1：关闭电源*/
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PD  (BIT(1))
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PD_M  (BIT(1))
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PD_V  0x1
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_PD_S  1
/* EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_ON:R/W；位位置：[0]；默认值：1’b1；*/
/*description:该位用于关闭dcache标记内存的时钟门控。1： 关闭门控0：打开时钟门控。*/
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_ON  (BIT(0))
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_ON_M  (BIT(0))
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_ON_V  0x1
#define EXTMEM_PRO_DCACHE_TAG_MEM_FORCE_ON_S  0

#define EXTMEM_PRO_DCACHE_LOCK0_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x00C)
/* EXTMEM_PRO_DCACHE_LOCK0_ADDR:R/W；位位置：[31:0]；默认值：10'0；*/
/*描述：这些位用于配置与PRO_DCACHE_LOCK0_SIZE_REG组合的数据锁定的第一个起始虚拟地址*/
#define EXTMEM_PRO_DCACHE_LOCK0_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_LOCK0_ADDR_M  ((EXTMEM_PRO_DCACHE_LOCK0_ADDR_V)<<(EXTMEM_PRO_DCACHE_LOCK0_ADDR_S))
#define EXTMEM_PRO_DCACHE_LOCK0_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_LOCK0_ADDR_S  0

#define EXTMEM_PRO_DCACHE_LOCK0_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x010)
/* EXTMEM_PRO_DCACHE_LOCK0_SIZE:R/W；比特位置：[15:0]；默认值：16'0；*/
/*描述：这些位用于配置与PRO_DCACHE_LOCK0_ADDR_REG组合的数据锁定的第一个长度*/
#define EXTMEM_PRO_DCACHE_LOCK0_SIZE  0x0000FFFF
#define EXTMEM_PRO_DCACHE_LOCK0_SIZE_M  ((EXTMEM_PRO_DCACHE_LOCK0_SIZE_V)<<(EXTMEM_PRO_DCACHE_LOCK0_SIZE_S))
#define EXTMEM_PRO_DCACHE_LOCK0_SIZE_V  0xFFFF
#define EXTMEM_PRO_DCACHE_LOCK0_SIZE_S  0

#define EXTMEM_PRO_DCACHE_LOCK1_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x014)
/* EXTMEM_PRO_DCACHE_LOCK1_ADDR:R/W；位位置：[31:0]；默认值：10'0；*/
/*描述：这些位用于配置与PRO_DCACHE_LOCK1_SIZE_REG组合的数据锁定的第二个起始虚拟地址*/
#define EXTMEM_PRO_DCACHE_LOCK1_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_LOCK1_ADDR_M  ((EXTMEM_PRO_DCACHE_LOCK1_ADDR_V)<<(EXTMEM_PRO_DCACHE_LOCK1_ADDR_S))
#define EXTMEM_PRO_DCACHE_LOCK1_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_LOCK1_ADDR_S  0

#define EXTMEM_PRO_DCACHE_LOCK1_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x018)
/* EXTMEM_PRO_DCACHE_LOCK1_SIZE:R/W；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于配置与PRO_DCACHE_LOCK1_ADDR_REG组合的第二长度数据锁定*/
#define EXTMEM_PRO_DCACHE_LOCK1_SIZE  0x0000FFFF
#define EXTMEM_PRO_DCACHE_LOCK1_SIZE_M  ((EXTMEM_PRO_DCACHE_LOCK1_SIZE_V)<<(EXTMEM_PRO_DCACHE_LOCK1_SIZE_S))
#define EXTMEM_PRO_DCACHE_LOCK1_SIZE_V  0xFFFF
#define EXTMEM_PRO_DCACHE_LOCK1_SIZE_S  0

#define EXTMEM_PRO_DCACHE_MEM_SYNC0_REG          (DR_REG_EXTMEM_BASE + 0x01C)
/* EXTMEM_PRO_DCACHE_MEMSYNC_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置无效刷新清除锁定和解锁操作的起始虚拟地址。如果地址有效，将发出手动操作。如果地址无效，将发出自动操作。它应与PRO_DCACHE_MEM_SYNC1结合使用。*/
#define EXTMEM_PRO_DCACHE_MEMSYNC_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_MEMSYNC_ADDR_M  ((EXTMEM_PRO_DCACHE_MEMSYNC_ADDR_V)<<(EXTMEM_PRO_DCACHE_MEMSYNC_ADDR_S))
#define EXTMEM_PRO_DCACHE_MEMSYNC_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_MEMSYNC_ADDR_S  0

#define EXTMEM_PRO_DCACHE_MEM_SYNC1_REG          (DR_REG_EXTMEM_BASE + 0x020)
/* EXTMEM_PRO_DCACHE_MEMSYNC_SIZE:R/W；比特位置：[18:0]；默认值：19'0；*/
/*description:这些位用于配置无效清除锁定和解锁操作的长度。如果验证，将发布手动操作。如果无效，将发出自动操作。应与PRO_DCACHE_MEM_SYNC0组合使用。*/
#define EXTMEM_PRO_DCACHE_MEMSYNC_SIZE  0x0007FFFF
#define EXTMEM_PRO_DCACHE_MEMSYNC_SIZE_M  ((EXTMEM_PRO_DCACHE_MEMSYNC_SIZE_V)<<(EXTMEM_PRO_DCACHE_MEMSYNC_SIZE_S))
#define EXTMEM_PRO_DCACHE_MEMSYNC_SIZE_V  0x7FFFF
#define EXTMEM_PRO_DCACHE_MEMSYNC_SIZE_S  0

#define EXTMEM_PRO_DCACHE_PRELOAD_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x024)
/* EXTMEM_PRO_DCACHE_proad_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置手动预加载操作的起始虚拟地址。它应与PRO_DCACHE_PRELOAD_SIZE_REG组合使用。*/
#define EXTMEM_PRO_DCACHE_PRELOAD_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_PRELOAD_ADDR_M  ((EXTMEM_PRO_DCACHE_PRELOAD_ADDR_V)<<(EXTMEM_PRO_DCACHE_PRELOAD_ADDR_S))
#define EXTMEM_PRO_DCACHE_PRELOAD_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_PRELOAD_ADDR_S  0

#define EXTMEM_PRO_DCACHE_PRELOAD_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x028)
/* EXTMEM_PRO_DCACHE_proad_ORDER:R/W；位位置：[10]；默认值：1’b0；*/
/*description:这些位用于配置手动预加载操作的方向。1： 降序0：升序。*/
#define EXTMEM_PRO_DCACHE_PRELOAD_ORDER  (BIT(10))
#define EXTMEM_PRO_DCACHE_PRELOAD_ORDER_M  (BIT(10))
#define EXTMEM_PRO_DCACHE_PRELOAD_ORDER_V  0x1
#define EXTMEM_PRO_DCACHE_PRELOAD_ORDER_S  10
/* EXTMEM_PRO_DCACHE_proad_SIZE:R/W；位位置：[9:0]；默认值：10'h200；*/
/*description:这些位用于配置手动预加载操作的长度。它应与PRO_DCACHE_PRELOAD_ADDR_REG组合使用。。*/
#define EXTMEM_PRO_DCACHE_PRELOAD_SIZE  0x000003FF
#define EXTMEM_PRO_DCACHE_PRELOAD_SIZE_M  ((EXTMEM_PRO_DCACHE_PRELOAD_SIZE_V)<<(EXTMEM_PRO_DCACHE_PRELOAD_SIZE_S))
#define EXTMEM_PRO_DCACHE_PRELOAD_SIZE_V  0x3FF
#define EXTMEM_PRO_DCACHE_PRELOAD_SIZE_S  0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_CFG_REG          (DR_REG_EXTMEM_BASE + 0x02C)
/* EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ENA:R/W；位位置：[9]；默认值：1’b0；*/
/*description:这些位用于启用第一部分的条件预加载操作。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ENA  (BIT(9))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ENA_M  (BIT(9))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ENA_S  9
/* EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ENA:R/W；位位置：[8]；默认值：1’b0；*/
/*description:位用于启用第二部分进行条件预加载操作。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ENA  (BIT(8))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ENA_M  (BIT(8))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ENA_S  8
/* EXTMEM_PRO_DCACHE_AUTOLOAD_SIZE:R/W；位位置：[7:6]；默认值：2'h0；*/
/*description:这些位用于为发出条件预加载操作配置缓存块的编号。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SIZE  0x00000003
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SIZE_M  ((EXTMEM_PRO_DCACHE_AUTOLOAD_SIZE_V)<<(EXTMEM_PRO_DCACHE_AUTOLOAD_SIZE_S))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SIZE_V  0x3
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SIZE_S  6
/* EXTMEM_PRO_DCACHE_AUTOLOAD_RQST:R/W；比特位置：[5:4]；默认值：1’b0；*/
/*description:这些位用于配置条件预加载的触发条件。0/3:缓存未命中1:缓存命中2:缓存未命中和命中。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_RQST  0x00000003
#define EXTMEM_PRO_DCACHE_AUTOLOAD_RQST_M  ((EXTMEM_PRO_DCACHE_AUTOLOAD_RQST_V)<<(EXTMEM_PRO_DCACHE_AUTOLOAD_RQST_S))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_RQST_V  0x3
#define EXTMEM_PRO_DCACHE_AUTOLOAD_RQST_S  4
/* EXTMEM_PRO_DCACHE_AUTOLOAD_ORDER:R/W；位位置：[3]；默认值：1’b0；*/
/*description:这些位用于配置条件预加载操作的方向。1： 降序0：升序。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ORDER  (BIT(3))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ORDER_M  (BIT(3))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ORDER_V  0x1
#define EXTMEM_PRO_DCACHE_AUTOLOAD_ORDER_S  3
/* EXTMEM_PRO_DCACHE_AUTOLOAD_STEP：R/W；位位置：[2:1]；默认值：2’b0；*/
/*description:保留。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_STEP  0x00000003
#define EXTMEM_PRO_DCACHE_AUTOLOAD_STEP_M  ((EXTMEM_PRO_DCACHE_AUTOLOAD_STEP_V)<<(EXTMEM_PRO_DCACHE_AUTOLOAD_STEP_S))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_STEP_V  0x3
#define EXTMEM_PRO_DCACHE_AUTOLOAD_STEP_S  1
/* EXTMEM_PRO_DCACHE_AUTOLOAD_MODE：R/W；位位置：[0]；默认值：1'd0；*/
/*description:保留。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_MODE  (BIT(0))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_MODE_M  (BIT(0))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_MODE_V  0x1
#define EXTMEM_PRO_DCACHE_AUTOLOAD_MODE_S  0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_SECTION0_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x030)
/* EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置条件预加载操作的第一部分的起始虚拟地址。它应该与pro_dcache_autoload_sct0_ena结合使用。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ADDR_M  ((EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ADDR_V)<<(EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ADDR_S))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_ADDR_S  0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_SECTION0_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x034)
/* EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_SIZE:R/W；比特位置：[23:0]；默认值：24'h8000；*/
/*description:这些位用于配置条件预加载操作的第一部分的长度。它应该与pro_dcache_autoload_sct0_ena结合使用。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_SIZE  0x00FFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_SIZE_M  ((EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_SIZE_V)<<(EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_SIZE_S))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_SIZE_V  0xFFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT0_SIZE_S  0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_SECTION1_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x038)
/* EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置第二部分的开始虚拟地址，用于条件预加载操作。它应该与pro_dcache_autoload_sct1_ena结合使用。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ADDR_M  ((EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ADDR_V)<<(EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ADDR_S))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_ADDR_S  0

#define EXTMEM_PRO_DCACHE_AUTOLOAD_SECTION1_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x03C)
/* EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_SIZE:R/W；比特位置：[23:0]；默认值：24'h8000；*/
/*description:这些位用于配置条件预加载操作的第二部分的长度。它应该与pro_dcache_autoload_sct1_ena结合使用。*/
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_SIZE  0x00FFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_SIZE_M  ((EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_SIZE_V)<<(EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_SIZE_S))
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_SIZE_V  0xFFFFFF
#define EXTMEM_PRO_DCACHE_AUTOLOAD_SCT1_SIZE_S  0

#define EXTMEM_PRO_ICACHE_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x040)
/* EXTMEM_PRO_cache_LOCK_DONE:RO；位位置：[25]；默认值：1’b0；*/
/*description:该位用于指示锁定操作完成。*/
#define EXTMEM_PRO_ICACHE_LOCK_DONE  (BIT(25))
#define EXTMEM_PRO_ICACHE_LOCK_DONE_M  (BIT(25))
#define EXTMEM_PRO_ICACHE_LOCK_DONE_V  0x1
#define EXTMEM_PRO_ICACHE_LOCK_DONE_S  25
/* EXTMEM_PRO_cache_LOCK_ENA:R/W；位位置：[24]；默认值：1’b0；*/
/*description:该位用于启用锁定操作。锁定操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_ICACHE_LOCK_ENA  (BIT(24))
#define EXTMEM_PRO_ICACHE_LOCK_ENA_M  (BIT(24))
#define EXTMEM_PRO_ICACHE_LOCK_ENA_V  0x1
#define EXTMEM_PRO_ICACHE_LOCK_ENA_S  24
/* EXTMEM_PRO_cache_UNLOCK_DONE:RO；位位置：[23]；默认值：1’b0；*/
/*description:该位用于指示解锁操作完成。*/
#define EXTMEM_PRO_ICACHE_UNLOCK_DONE  (BIT(23))
#define EXTMEM_PRO_ICACHE_UNLOCK_DONE_M  (BIT(23))
#define EXTMEM_PRO_ICACHE_UNLOCK_DONE_V  0x1
#define EXTMEM_PRO_ICACHE_UNLOCK_DONE_S  23
/* EXTMEM_PRO_cache_UNLOCK_ENA:R/W；位位置：[22]；默认值：1’b0；*/
/*description:该位用于启用解锁操作。解锁操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_ICACHE_UNLOCK_ENA  (BIT(22))
#define EXTMEM_PRO_ICACHE_UNLOCK_ENA_M  (BIT(22))
#define EXTMEM_PRO_ICACHE_UNLOCK_ENA_V  0x1
#define EXTMEM_PRO_ICACHE_UNLOCK_ENA_S  22
/* EXTMEM_PRO_cache_proad_DONE:RO；位位置：[21]；默认值：1’b0；*/
/*description:该位用于指示预加载操作完成。*/
#define EXTMEM_PRO_ICACHE_PRELOAD_DONE  (BIT(21))
#define EXTMEM_PRO_ICACHE_PRELOAD_DONE_M  (BIT(21))
#define EXTMEM_PRO_ICACHE_PRELOAD_DONE_V  0x1
#define EXTMEM_PRO_ICACHE_PRELOAD_DONE_S  21
/* EXTMEM_PRO_cache_proad_ENA:R/W；位位置：[20]；默认值：1’b0；*/
/*description:该位用于启用预加载操作。预加载操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_ICACHE_PRELOAD_ENA  (BIT(20))
#define EXTMEM_PRO_ICACHE_PRELOAD_ENA_M  (BIT(20))
#define EXTMEM_PRO_ICACHE_PRELOAD_ENA_V  0x1
#define EXTMEM_PRO_ICACHE_PRELOAD_ENA_S  20
/* EXTMEM_PRO_cache_AUTOLOAD_DONE:RO；位位置：[19]；默认值：1’b0；*/
/*description:该位用于指示条件预加载操作完成。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_DONE  (BIT(19))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_DONE_M  (BIT(19))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_DONE_V  0x1
#define EXTMEM_PRO_ICACHE_AUTOLOAD_DONE_S  19
/* EXTMEM_PRO_cache_AUTOLOAD_ENA:R/W；位位置：[18]；默认值：1’b0；*/
/*description:该位用于启用和禁用条件预加载操作。它与pre_dcache_autoload_done结合使用。1： 启用0：禁用。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ENA  (BIT(18))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ENA_M  (BIT(18))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ENA_V  0x1
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ENA_S  18
/* EXTMEM_PRO_cache_LOCK1_EN:R/W；位位置：[15]；默认值：1’b0；*/
/*description:该位用于启用与PRO_ICACHE_LOCK1_ADDR_REG和PRO_ICACHE _LOCK1_SIZE_REG组合的预锁定操作。*/
#define EXTMEM_PRO_ICACHE_LOCK1_EN  (BIT(15))
#define EXTMEM_PRO_ICACHE_LOCK1_EN_M  (BIT(15))
#define EXTMEM_PRO_ICACHE_LOCK1_EN_V  0x1
#define EXTMEM_PRO_ICACHE_LOCK1_EN_S  15
/* EXTMEM_PRO_cache_LOCK0_EN:R/W；位位置：[14]；默认值：1’b0；*/
/*description:该位用于启用与PRO_ICACHE_LOCK0_ADDR_REG和PRO_ICACHE _LOCK0_SIZE_REG组合的预锁定操作。*/
#define EXTMEM_PRO_ICACHE_LOCK0_EN  (BIT(14))
#define EXTMEM_PRO_ICACHE_LOCK0_EN_M  (BIT(14))
#define EXTMEM_PRO_ICACHE_LOCK0_EN_V  0x1
#define EXTMEM_PRO_ICACHE_LOCK0_EN_S  14
/* EXTMEM_PRO_cache_invalidatedone:RO；位位置：[9]；默认值：1’b0；*/
/*description:该位用于指示无效操作已完成。*/
#define EXTMEM_PRO_ICACHE_INVALIDATE_DONE  (BIT(9))
#define EXTMEM_PRO_ICACHE_INVALIDATE_DONE_M  (BIT(9))
#define EXTMEM_PRO_ICACHE_INVALIDATE_DONE_V  0x1
#define EXTMEM_PRO_ICACHE_INVALIDATE_DONE_S  9
/* EXTMEM_PRO_cache_INVALIDATE_ENA:R/W；位位置：[8]；默认值：1’b1；*/
/*description:该位用于启用无效操作。无效操作完成后，将由硬件清除。*/
#define EXTMEM_PRO_ICACHE_INVALIDATE_ENA  (BIT(8))
#define EXTMEM_PRO_ICACHE_INVALIDATE_ENA_M  (BIT(8))
#define EXTMEM_PRO_ICACHE_INVALIDATE_ENA_V  0x1
#define EXTMEM_PRO_ICACHE_INVALIDATE_ENA_S  8
/* EXTMEM_PRO_cache_BLOCKSIZE_MODE：R/W；位位置：[3]；默认值：1’b0；*/
/*description:该位用于配置缓存块大小。0:16字节1:32字节*/
#define EXTMEM_PRO_ICACHE_BLOCKSIZE_MODE  (BIT(3))
#define EXTMEM_PRO_ICACHE_BLOCKSIZE_MODE_M  (BIT(3))
#define EXTMEM_PRO_ICACHE_BLOCKSIZE_MODE_V  0x1
#define EXTMEM_PRO_ICACHE_BLOCKSIZE_MODE_S  3
/* EXTMEM_PRO_cache_SETSIZE_MODE：R/W；位位置：[2]；默认值：1’b0；*/
/*description:该位用于配置缓存内存大小。0:8KB 1:16KB*/
#define EXTMEM_PRO_ICACHE_SETSIZE_MODE  (BIT(2))
#define EXTMEM_PRO_ICACHE_SETSIZE_MODE_M  (BIT(2))
#define EXTMEM_PRO_ICACHE_SETSIZE_MODE_V  0x1
#define EXTMEM_PRO_ICACHE_SETSIZE_MODE_S  2
/* EXTMEM_PRO_cache_ENABLE:R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于激活数据缓存。0：禁用1：启用*/
#define EXTMEM_PRO_ICACHE_ENABLE  (BIT(0))
#define EXTMEM_PRO_ICACHE_ENABLE_M  (BIT(0))
#define EXTMEM_PRO_ICACHE_ENABLE_V  0x1
#define EXTMEM_PRO_ICACHE_ENABLE_S  0

#define EXTMEM_PRO_ICACHE_CTRL1_REG          (DR_REG_EXTMEM_BASE + 0x044)
/* EXTMEM_PRO_cache_MASK_BUS2:R/W；位位置：[2]；默认值：1’b1；*/
/*description:该位用于禁用ibus2 0:启用1:禁用*/
#define EXTMEM_PRO_ICACHE_MASK_BUS2  (BIT(2))
#define EXTMEM_PRO_ICACHE_MASK_BUS2_M  (BIT(2))
#define EXTMEM_PRO_ICACHE_MASK_BUS2_V  0x1
#define EXTMEM_PRO_ICACHE_MASK_BUS2_S  2
/* EXTMEM_PRO_cache_MASK_BUS1:R/W；位位置：[1]；默认值：1’b1；*/
/*description:该位用于禁用ibus1 0:启用1:禁用*/
#define EXTMEM_PRO_ICACHE_MASK_BUS1  (BIT(1))
#define EXTMEM_PRO_ICACHE_MASK_BUS1_M  (BIT(1))
#define EXTMEM_PRO_ICACHE_MASK_BUS1_V  0x1
#define EXTMEM_PRO_ICACHE_MASK_BUS1_S  1
/* EXTMEM_PRO_cache_MASK_BUS0:R/W；位位置：[0]；默认值：1’b1；*/
/*description:该位用于禁用ibus0 0:启用1:禁用*/
#define EXTMEM_PRO_ICACHE_MASK_BUS0  (BIT(0))
#define EXTMEM_PRO_ICACHE_MASK_BUS0_M  (BIT(0))
#define EXTMEM_PRO_ICACHE_MASK_BUS0_V  0x1
#define EXTMEM_PRO_ICACHE_MASK_BUS0_S  0
#define EXTMEM_PRO_ICACHE_MASK_IRAM0 EXTMEM_PRO_ICACHE_MASK_BUS0
#define EXTMEM_PRO_ICACHE_MASK_IRAM1 EXTMEM_PRO_ICACHE_MASK_BUS1
#define EXTMEM_PRO_ICACHE_MASK_DROM0 EXTMEM_PRO_ICACHE_MASK_BUS2

#define EXTMEM_PRO_ICACHE_TAG_POWER_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x048)
/* EXTMEM_PRO_cache_TAG_MEM_FORCE_PU:R/W；位位置：[2]；默认值：1’b1；*/
/*description:该位用于关闭icache标记内存0：遵循rtc_lslp 1：通电*/
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_PU  (BIT(2))
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_PU_M  (BIT(2))
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_PU_V  0x1
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_PU_S  2
/* EXTMEM_PRO_cache_TAG_MEM_FORCE_PD:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于关闭icache标记内存0：遵循rtc_lslp 1：关闭电源*/
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_PD  (BIT(1))
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_PD_M  (BIT(1))
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_PD_V  0x1
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_PD_S  1
/* EXTMEM_PRO_cache_TAG_MEM_FORCE_ON:R/W；位位置：[0]；默认值：1’b1；*/
/*描述：该位用于关闭icache标签存储器的时钟门控。1： 关闭门控0：打开时钟门控。*/
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_ON  (BIT(0))
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_ON_M  (BIT(0))
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_ON_V  0x1
#define EXTMEM_PRO_ICACHE_TAG_MEM_FORCE_ON_S  0

#define EXTMEM_PRO_ICACHE_LOCK0_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x04C)
/* EXTMEM_PRO_cache_LOCK0_ADDR:R/W；位位置：[31:0]；默认值：10'0；*/
/*描述：这些位用于配置与PRO_ICACHE_LOCK0_SIZE_REG组合的数据锁定的第一个起始虚拟地址*/
#define EXTMEM_PRO_ICACHE_LOCK0_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_LOCK0_ADDR_M  ((EXTMEM_PRO_ICACHE_LOCK0_ADDR_V)<<(EXTMEM_PRO_ICACHE_LOCK0_ADDR_S))
#define EXTMEM_PRO_ICACHE_LOCK0_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_LOCK0_ADDR_S  0

#define EXTMEM_PRO_ICACHE_LOCK0_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x050)
/* EXTMEM_PRO_cache_LOCK0_SIZE:R/W；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于配置与PRO_ICACHE_LOCK0_ADDR_REG组合的数据锁定的第一个长度*/
#define EXTMEM_PRO_ICACHE_LOCK0_SIZE  0x0000FFFF
#define EXTMEM_PRO_ICACHE_LOCK0_SIZE_M  ((EXTMEM_PRO_ICACHE_LOCK0_SIZE_V)<<(EXTMEM_PRO_ICACHE_LOCK0_SIZE_S))
#define EXTMEM_PRO_ICACHE_LOCK0_SIZE_V  0xFFFF
#define EXTMEM_PRO_ICACHE_LOCK0_SIZE_S  0

#define EXTMEM_PRO_ICACHE_LOCK1_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x054)
/* EXTMEM_PRO_cache_LOCK1_ADDR:R/W；位位置：[31:0]；默认值：10'0；*/
/*描述：这些位用于配置与PRO_ICACHE_LOCK1_SIZE_REG组合的数据锁定的第二个起始虚拟地址*/
#define EXTMEM_PRO_ICACHE_LOCK1_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_LOCK1_ADDR_M  ((EXTMEM_PRO_ICACHE_LOCK1_ADDR_V)<<(EXTMEM_PRO_ICACHE_LOCK1_ADDR_S))
#define EXTMEM_PRO_ICACHE_LOCK1_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_LOCK1_ADDR_S  0

#define EXTMEM_PRO_ICACHE_LOCK1_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x058)
/* EXTMEM_PRO_cache_LOCK1_SIZE:R/W；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于配置与PRO_ICACHE_LOCK1_ADDR_REG组合的数据锁定的第二长度*/
#define EXTMEM_PRO_ICACHE_LOCK1_SIZE  0x0000FFFF
#define EXTMEM_PRO_ICACHE_LOCK1_SIZE_M  ((EXTMEM_PRO_ICACHE_LOCK1_SIZE_V)<<(EXTMEM_PRO_ICACHE_LOCK1_SIZE_S))
#define EXTMEM_PRO_ICACHE_LOCK1_SIZE_V  0xFFFF
#define EXTMEM_PRO_ICACHE_LOCK1_SIZE_S  0

#define EXTMEM_PRO_ICACHE_MEM_SYNC0_REG          (DR_REG_EXTMEM_BASE + 0x05C)
/* EXTMEM_PRO_cache_MEMSYNC_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置无效刷新清除锁定和解锁操作的起始虚拟地址。如果地址有效，将发出手动操作。如果地址无效，将发出自动操作。它应与PRO_ICACHE_MEM_SYNC1结合使用。*/
#define EXTMEM_PRO_ICACHE_MEMSYNC_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_MEMSYNC_ADDR_M  ((EXTMEM_PRO_ICACHE_MEMSYNC_ADDR_V)<<(EXTMEM_PRO_ICACHE_MEMSYNC_ADDR_S))
#define EXTMEM_PRO_ICACHE_MEMSYNC_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_MEMSYNC_ADDR_S  0

#define EXTMEM_PRO_ICACHE_MEM_SYNC1_REG          (DR_REG_EXTMEM_BASE + 0x060)
/* EXTMEM_PRO_cache_MEMSYNC_SIZE:R/W；比特位置：[18:0]；默认值：19'0；*/
/*description:这些位用于配置无效清除锁定和解锁操作的长度。如果验证，将发布手动操作。如果无效，将发出自动操作。它应与PRO_ICACHE_MEM_SYNC0结合使用。*/
#define EXTMEM_PRO_ICACHE_MEMSYNC_SIZE  0x0007FFFF
#define EXTMEM_PRO_ICACHE_MEMSYNC_SIZE_M  ((EXTMEM_PRO_ICACHE_MEMSYNC_SIZE_V)<<(EXTMEM_PRO_ICACHE_MEMSYNC_SIZE_S))
#define EXTMEM_PRO_ICACHE_MEMSYNC_SIZE_V  0x7FFFF
#define EXTMEM_PRO_ICACHE_MEMSYNC_SIZE_S  0

#define EXTMEM_PRO_ICACHE_PRELOAD_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x064)
/* EXTMEM_PRO_cache_proad_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置手动预加载操作的起始虚拟地址。它应与PRO_ICACHE_PRELOAD_SIZE_REG组合使用。*/
#define EXTMEM_PRO_ICACHE_PRELOAD_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_PRELOAD_ADDR_M  ((EXTMEM_PRO_ICACHE_PRELOAD_ADDR_V)<<(EXTMEM_PRO_ICACHE_PRELOAD_ADDR_S))
#define EXTMEM_PRO_ICACHE_PRELOAD_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_PRELOAD_ADDR_S  0

#define EXTMEM_PRO_ICACHE_PRELOAD_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x068)
/* EXTMEM_PRO_cache_proad_ORDER:R/W；位位置：[10]；默认值：1’b0；*/
/*description:这些位用于配置手动预加载操作的方向。1： 降序0：升序。*/
#define EXTMEM_PRO_ICACHE_PRELOAD_ORDER  (BIT(10))
#define EXTMEM_PRO_ICACHE_PRELOAD_ORDER_M  (BIT(10))
#define EXTMEM_PRO_ICACHE_PRELOAD_ORDER_V  0x1
#define EXTMEM_PRO_ICACHE_PRELOAD_ORDER_S  10
/* EXTMEM_PRO_cache_proad_SIZE:R/W；位位置：[9:0]；默认值：10'h200；*/
/*description:这些位用于配置手动预加载操作的长度。它应与PRO_ICACHE_PRELOAD_ADDR_REG组合使用。。*/
#define EXTMEM_PRO_ICACHE_PRELOAD_SIZE  0x000003FF
#define EXTMEM_PRO_ICACHE_PRELOAD_SIZE_M  ((EXTMEM_PRO_ICACHE_PRELOAD_SIZE_V)<<(EXTMEM_PRO_ICACHE_PRELOAD_SIZE_S))
#define EXTMEM_PRO_ICACHE_PRELOAD_SIZE_V  0x3FF
#define EXTMEM_PRO_ICACHE_PRELOAD_SIZE_S  0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_CFG_REG          (DR_REG_EXTMEM_BASE + 0x06C)
/* EXTMEM_PRO_cache_AUTOLOAD_SCT1_ENA:R/W；位位置：[9]；默认值：1’b0；*/
/*description:这些位用于启用第一部分的条件预加载操作。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ENA  (BIT(9))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ENA_M  (BIT(9))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ENA_V  0x1
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ENA_S  9
/* EXTMEM_PRO_cache_AUTOLOAD_SCT0_ENA:R/W；位位置：[8]；默认值：1’b0；*/
/*description:位用于启用第二部分进行条件预加载操作。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ENA  (BIT(8))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ENA_M  (BIT(8))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ENA_V  0x1
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ENA_S  8
/* EXTMEM_PRO_cache_AUTOLOAD_SIZE:R/W；位位置：[7:6]；默认值：2'h0；*/
/*description:这些位用于为发出条件预加载操作配置缓存块的编号。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SIZE  0x00000003
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SIZE_M  ((EXTMEM_PRO_ICACHE_AUTOLOAD_SIZE_V)<<(EXTMEM_PRO_ICACHE_AUTOLOAD_SIZE_S))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SIZE_V  0x3
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SIZE_S  6
/* EXTMEM_PRO_cache_AUTOLOAD_RQST:R/W；比特位置：[5:4]；默认值：1’b0；*/
/*description:这些位用于配置条件预加载的触发条件。0/3:缓存未命中1:缓存命中2:缓存未命中和命中。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_RQST  0x00000003
#define EXTMEM_PRO_ICACHE_AUTOLOAD_RQST_M  ((EXTMEM_PRO_ICACHE_AUTOLOAD_RQST_V)<<(EXTMEM_PRO_ICACHE_AUTOLOAD_RQST_S))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_RQST_V  0x3
#define EXTMEM_PRO_ICACHE_AUTOLOAD_RQST_S  4
/* EXTMEM_PRO_cache_AUTOLOAD_ORDER:R/W；位位置：[3]；默认值：1’b0；*/
/*description:这些位用于配置条件预加载操作的方向。1： 降序0：升序。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ORDER  (BIT(3))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ORDER_M  (BIT(3))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ORDER_V  0x1
#define EXTMEM_PRO_ICACHE_AUTOLOAD_ORDER_S  3
/* EXTMEM_PRO_cache_AUTOLOAD_STEP：R/W；位位置：[2:1]；默认值：2’b0；*/
/*description:保留。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_STEP  0x00000003
#define EXTMEM_PRO_ICACHE_AUTOLOAD_STEP_M  ((EXTMEM_PRO_ICACHE_AUTOLOAD_STEP_V)<<(EXTMEM_PRO_ICACHE_AUTOLOAD_STEP_S))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_STEP_V  0x3
#define EXTMEM_PRO_ICACHE_AUTOLOAD_STEP_S  1
/* EXTMEM_PRO_cache_AUTOLOAD_MODE：R/W；位位置：[0]；默认值：1'd0；*/
/*description:保留。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_MODE  (BIT(0))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_MODE_M  (BIT(0))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_MODE_V  0x1
#define EXTMEM_PRO_ICACHE_AUTOLOAD_MODE_S  0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_SECTION0_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x070)
/* EXTMEM_PRO_cache_AUTOLOAD_SCT0_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置条件预加载操作的第一部分的起始虚拟地址。它应该与pro_icache_autoload_sct0_ena结合使用。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ADDR_M  ((EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ADDR_V)<<(EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ADDR_S))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_ADDR_S  0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_SECTION0_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x074)
/* EXTMEM_PRO_cache_AUTOLOAD_SCT0_SIZE:R/W；比特位置：[23:0]；默认值：24'h8000；*/
/*description:这些位用于配置条件预加载操作的第一部分的长度。它应该与pro_icache_autoload_sct0_ena结合使用。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_SIZE  0x00FFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_SIZE_M  ((EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_SIZE_V)<<(EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_SIZE_S))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_SIZE_V  0xFFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT0_SIZE_S  0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_SECTION1_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x078)
/* EXTMEM_PRO_cache_AUTOLOAD_SCT1_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置第二部分的开始虚拟地址，用于条件预加载操作。它应该与pro_icache_autoload_sct1_ena结合使用。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ADDR  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ADDR_M  ((EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ADDR_V)<<(EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ADDR_S))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_ADDR_S  0

#define EXTMEM_PRO_ICACHE_AUTOLOAD_SECTION1_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x07C)
/* EXTMEM_PRO_cache_AUTOLOAD_SCT1_SIZE:R/W；比特位置：[23:0]；默认值：24'h8000；*/
/*description:这些位用于配置条件预加载操作的第二部分的长度。它应该与pro_icache_autoload_sct1_ena结合使用。*/
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_SIZE  0x00FFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_SIZE_M  ((EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_SIZE_V)<<(EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_SIZE_S))
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_SIZE_V  0xFFFFFF
#define EXTMEM_PRO_ICACHE_AUTOLOAD_SCT1_SIZE_S  0

#define EXTMEM_IC_PRELOAD_CNT_REG          (DR_REG_EXTMEM_BASE + 0x080)
/* EXTMEM_IC_PRELOAD_CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算发出的预加载的数量，包括手动预加载和条件预加载。*/
#define EXTMEM_IC_PRELOAD_CNT  0x0000FFFF
#define EXTMEM_IC_PRELOAD_CNT_M  ((EXTMEM_IC_PRELOAD_CNT_V)<<(EXTMEM_IC_PRELOAD_CNT_S))
#define EXTMEM_IC_PRELOAD_CNT_V  0xFFFF
#define EXTMEM_IC_PRELOAD_CNT_S  0

#define EXTMEM_IC_PRELOAD_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x084)
/* EXTMEM_IC_PRELOAD_MISS_CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算错过的预加载的数量，包括手动预加载和条件预加载。*/
#define EXTMEM_IC_PRELOAD_MISS_CNT  0x0000FFFF
#define EXTMEM_IC_PRELOAD_MISS_CNT_M  ((EXTMEM_IC_PRELOAD_MISS_CNT_V)<<(EXTMEM_IC_PRELOAD_MISS_CNT_S))
#define EXTMEM_IC_PRELOAD_MISS_CNT_V  0xFFFF
#define EXTMEM_IC_PRELOAD_MISS_CNT_S  0

#define EXTMEM_IBUS2_ABANDON_CNT_REG          (DR_REG_EXTMEM_BASE + 0x088)
/* EXTMEM_IBUS2_about_CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算放弃的ibus2访问的数量。*/
#define EXTMEM_IBUS2_ABANDON_CNT  0x0000FFFF
#define EXTMEM_IBUS2_ABANDON_CNT_M  ((EXTMEM_IBUS2_ABANDON_CNT_V)<<(EXTMEM_IBUS2_ABANDON_CNT_S))
#define EXTMEM_IBUS2_ABANDON_CNT_V  0xFFFF
#define EXTMEM_IBUS2_ABANDON_CNT_S  0

#define EXTMEM_IBUS1_ABANDON_CNT_REG          (DR_REG_EXTMEM_BASE + 0x08C)
/* EXTMEM_IBUS1_放弃_CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算放弃的ibus1访问的数量。*/
#define EXTMEM_IBUS1_ABANDON_CNT  0x0000FFFF
#define EXTMEM_IBUS1_ABANDON_CNT_M  ((EXTMEM_IBUS1_ABANDON_CNT_V)<<(EXTMEM_IBUS1_ABANDON_CNT_S))
#define EXTMEM_IBUS1_ABANDON_CNT_V  0xFFFF
#define EXTMEM_IBUS1_ABANDON_CNT_S  0

#define EXTMEM_IBUS0_ABANDON_CNT_REG          (DR_REG_EXTMEM_BASE + 0x090)
/* EXTMEM_IBUS0_advent_CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算放弃的ibus0访问的数量。*/
#define EXTMEM_IBUS0_ABANDON_CNT  0x0000FFFF
#define EXTMEM_IBUS0_ABANDON_CNT_M  ((EXTMEM_IBUS0_ABANDON_CNT_V)<<(EXTMEM_IBUS0_ABANDON_CNT_S))
#define EXTMEM_IBUS0_ABANDON_CNT_V  0xFFFF
#define EXTMEM_IBUS0_ABANDON_CNT_S  0

#define EXTMEM_IBUS2_ACS_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x094)
/* EXTMEM_IBUS2_ACS_MISS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算由ibus2访问导致的缓存未命中数。*/
#define EXTMEM_IBUS2_ACS_MISS_CNT  0xFFFFFFFF
#define EXTMEM_IBUS2_ACS_MISS_CNT_M  ((EXTMEM_IBUS2_ACS_MISS_CNT_V)<<(EXTMEM_IBUS2_ACS_MISS_CNT_S))
#define EXTMEM_IBUS2_ACS_MISS_CNT_V  0xFFFFFFFF
#define EXTMEM_IBUS2_ACS_MISS_CNT_S  0

#define EXTMEM_IBUS1_ACS_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x098)
/* EXTMEM_IBUS1_ACS_MISS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算由ibus1访问导致的缓存未命中数。*/
#define EXTMEM_IBUS1_ACS_MISS_CNT  0xFFFFFFFF
#define EXTMEM_IBUS1_ACS_MISS_CNT_M  ((EXTMEM_IBUS1_ACS_MISS_CNT_V)<<(EXTMEM_IBUS1_ACS_MISS_CNT_S))
#define EXTMEM_IBUS1_ACS_MISS_CNT_V  0xFFFFFFFF
#define EXTMEM_IBUS1_ACS_MISS_CNT_S  0

#define EXTMEM_IBUS0_ACS_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x09C)
/* EXTMEM_IBUS0_ACS_MISS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*描述：这些位用于计算由ibus0访问导致的缓存未命中数。*/
#define EXTMEM_IBUS0_ACS_MISS_CNT  0xFFFFFFFF
#define EXTMEM_IBUS0_ACS_MISS_CNT_M  ((EXTMEM_IBUS0_ACS_MISS_CNT_V)<<(EXTMEM_IBUS0_ACS_MISS_CNT_S))
#define EXTMEM_IBUS0_ACS_MISS_CNT_V  0xFFFFFFFF
#define EXTMEM_IBUS0_ACS_MISS_CNT_S  0

#define EXTMEM_IBUS2_ACS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0A0)
/* EXTMEM_IBUS2_ACS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算ibus2访问icache的数量。*/
#define EXTMEM_IBUS2_ACS_CNT  0xFFFFFFFF
#define EXTMEM_IBUS2_ACS_CNT_M  ((EXTMEM_IBUS2_ACS_CNT_V)<<(EXTMEM_IBUS2_ACS_CNT_S))
#define EXTMEM_IBUS2_ACS_CNT_V  0xFFFFFFFF
#define EXTMEM_IBUS2_ACS_CNT_S  0

#define EXTMEM_IBUS1_ACS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0A4)
/* EXTMEM_IBUS1_ACS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算ibus1访问icache的数量。*/
#define EXTMEM_IBUS1_ACS_CNT  0xFFFFFFFF
#define EXTMEM_IBUS1_ACS_CNT_M  ((EXTMEM_IBUS1_ACS_CNT_V)<<(EXTMEM_IBUS1_ACS_CNT_S))
#define EXTMEM_IBUS1_ACS_CNT_V  0xFFFFFFFF
#define EXTMEM_IBUS1_ACS_CNT_S  0

#define EXTMEM_IBUS0_ACS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0A8)
/* EXTMEM_IBUS0_ACS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*描述：这些位用于计算ibus0访问icache的数量。*/
#define EXTMEM_IBUS0_ACS_CNT  0xFFFFFFFF
#define EXTMEM_IBUS0_ACS_CNT_M  ((EXTMEM_IBUS0_ACS_CNT_V)<<(EXTMEM_IBUS0_ACS_CNT_S))
#define EXTMEM_IBUS0_ACS_CNT_V  0xFFFFFFFF
#define EXTMEM_IBUS0_ACS_CNT_S  0

#define EXTMEM_DC_PRELOAD_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0AC)
/* EXTMEM_DC_PRELOAD_CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算发出的预加载的数量，包括手动预加载和条件预加载。*/
#define EXTMEM_DC_PRELOAD_CNT  0x0000FFFF
#define EXTMEM_DC_PRELOAD_CNT_M  ((EXTMEM_DC_PRELOAD_CNT_V)<<(EXTMEM_DC_PRELOAD_CNT_S))
#define EXTMEM_DC_PRELOAD_CNT_V  0xFFFF
#define EXTMEM_DC_PRELOAD_CNT_S  0

#define EXTMEM_DC_PRELOAD_EVICT_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0B0)
/* EXTMEM_DC_PRELOAD_EVICT_CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:位用于按预加载（包括手动预加载和条件预加载）计算缓存逐出的数量。*/
#define EXTMEM_DC_PRELOAD_EVICT_CNT  0x0000FFFF
#define EXTMEM_DC_PRELOAD_EVICT_CNT_M  ((EXTMEM_DC_PRELOAD_EVICT_CNT_V)<<(EXTMEM_DC_PRELOAD_EVICT_CNT_S))
#define EXTMEM_DC_PRELOAD_EVICT_CNT_V  0xFFFF
#define EXTMEM_DC_PRELOAD_EVICT_CNT_S  0

#define EXTMEM_DC_PRELOAD_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0B4)
/* EXTMEM_DC_PRELOAD_MISS_CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算错过的预加载的数量，包括手动预加载和条件预加载。*/
#define EXTMEM_DC_PRELOAD_MISS_CNT  0x0000FFFF
#define EXTMEM_DC_PRELOAD_MISS_CNT_M  ((EXTMEM_DC_PRELOAD_MISS_CNT_V)<<(EXTMEM_DC_PRELOAD_MISS_CNT_S))
#define EXTMEM_DC_PRELOAD_MISS_CNT_V  0xFFFF
#define EXTMEM_DC_PRELOAD_MISS_CNT_S  0

#define EXTMEM_DBUS2_ABANDON_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0B8)
/* EXTMEM_DBUS2_放弃CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算放弃的dbus2访问的数量。*/
#define EXTMEM_DBUS2_ABANDON_CNT  0x0000FFFF
#define EXTMEM_DBUS2_ABANDON_CNT_M  ((EXTMEM_DBUS2_ABANDON_CNT_V)<<(EXTMEM_DBUS2_ABANDON_CNT_S))
#define EXTMEM_DBUS2_ABANDON_CNT_V  0xFFFF
#define EXTMEM_DBUS2_ABANDON_CNT_S  0

#define EXTMEM_DBUS1_ABANDON_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0BC)
/* EXTMEM_DBUS1_放弃CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算放弃的dbus1访问的数量。*/
#define EXTMEM_DBUS1_ABANDON_CNT  0x0000FFFF
#define EXTMEM_DBUS1_ABANDON_CNT_M  ((EXTMEM_DBUS1_ABANDON_CNT_V)<<(EXTMEM_DBUS1_ABANDON_CNT_S))
#define EXTMEM_DBUS1_ABANDON_CNT_V  0xFFFF
#define EXTMEM_DBUS1_ABANDON_CNT_S  0

#define EXTMEM_DBUS0_ABANDON_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0C0)
/* EXTMEM_DBUS0_advent_CNT:RO；比特位置：[15:0]；默认值：16'0；*/
/*description:这些位用于计算放弃的dbus0访问的数量。*/
#define EXTMEM_DBUS0_ABANDON_CNT  0x0000FFFF
#define EXTMEM_DBUS0_ABANDON_CNT_M  ((EXTMEM_DBUS0_ABANDON_CNT_V)<<(EXTMEM_DBUS0_ABANDON_CNT_S))
#define EXTMEM_DBUS0_ABANDON_CNT_V  0xFFFF
#define EXTMEM_DBUS0_ABANDON_CNT_S  0

#define EXTMEM_DBUS2_ACS_WB_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0C4)
/* EXTMEM_DBUS2_ACS_WB_CNT:RO；比特位置：[19:0]；默认值：20'00；*/
/*description:这些位用于计算dbus2访问缓存的缓存逐出次数。*/
#define EXTMEM_DBUS2_ACS_WB_CNT  0x000FFFFF
#define EXTMEM_DBUS2_ACS_WB_CNT_M  ((EXTMEM_DBUS2_ACS_WB_CNT_V)<<(EXTMEM_DBUS2_ACS_WB_CNT_S))
#define EXTMEM_DBUS2_ACS_WB_CNT_V  0xFFFFF
#define EXTMEM_DBUS2_ACS_WB_CNT_S  0

#define EXTMEM_DBUS1_ACS_WB_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0C8)
/* EXTMEM_DBUS1_ACS_WB_CNT:RO；比特位置：[19:0]；默认值：20'00；*/
/*description:这些位用于计算dbus1访问缓存的缓存逐出次数。*/
#define EXTMEM_DBUS1_ACS_WB_CNT  0x000FFFFF
#define EXTMEM_DBUS1_ACS_WB_CNT_M  ((EXTMEM_DBUS1_ACS_WB_CNT_V)<<(EXTMEM_DBUS1_ACS_WB_CNT_S))
#define EXTMEM_DBUS1_ACS_WB_CNT_V  0xFFFFF
#define EXTMEM_DBUS1_ACS_WB_CNT_S  0

#define EXTMEM_DBUS0_ACS_WB_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0CC)
/* EXTMEM_DBUS0_ACS_WB_CNT:RO；比特位置：[19:0]；默认值：20'00；*/
/*description:这些位用于计算dbus0访问缓存的缓存逐出次数。*/
#define EXTMEM_DBUS0_ACS_WB_CNT  0x000FFFFF
#define EXTMEM_DBUS0_ACS_WB_CNT_M  ((EXTMEM_DBUS0_ACS_WB_CNT_V)<<(EXTMEM_DBUS0_ACS_WB_CNT_S))
#define EXTMEM_DBUS0_ACS_WB_CNT_V  0xFFFFF
#define EXTMEM_DBUS0_ACS_WB_CNT_S  0

#define EXTMEM_DBUS2_ACS_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0D0)
/* EXTMEM_DBUS2_ACS_MISS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算dbus2访问导致的缓存未命中数。*/
#define EXTMEM_DBUS2_ACS_MISS_CNT  0xFFFFFFFF
#define EXTMEM_DBUS2_ACS_MISS_CNT_M  ((EXTMEM_DBUS2_ACS_MISS_CNT_V)<<(EXTMEM_DBUS2_ACS_MISS_CNT_S))
#define EXTMEM_DBUS2_ACS_MISS_CNT_V  0xFFFFFFFF
#define EXTMEM_DBUS2_ACS_MISS_CNT_S  0

#define EXTMEM_DBUS1_ACS_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0D4)
/* EXTMEM_DBUS1_ACS_MISS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算dbus1访问导致的缓存未命中数。*/
#define EXTMEM_DBUS1_ACS_MISS_CNT  0xFFFFFFFF
#define EXTMEM_DBUS1_ACS_MISS_CNT_M  ((EXTMEM_DBUS1_ACS_MISS_CNT_V)<<(EXTMEM_DBUS1_ACS_MISS_CNT_S))
#define EXTMEM_DBUS1_ACS_MISS_CNT_V  0xFFFFFFFF
#define EXTMEM_DBUS1_ACS_MISS_CNT_S  0

#define EXTMEM_DBUS0_ACS_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0D8)
/* EXTMEM_DBUS0_ACS_MISS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算dbus0访问导致的缓存未命中数。*/
#define EXTMEM_DBUS0_ACS_MISS_CNT  0xFFFFFFFF
#define EXTMEM_DBUS0_ACS_MISS_CNT_M  ((EXTMEM_DBUS0_ACS_MISS_CNT_V)<<(EXTMEM_DBUS0_ACS_MISS_CNT_S))
#define EXTMEM_DBUS0_ACS_MISS_CNT_V  0xFFFFFFFF
#define EXTMEM_DBUS0_ACS_MISS_CNT_S  0

#define EXTMEM_DBUS2_ACS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0DC)
/* EXTMEM_DBUS2_ACS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算dbus2访问dcache的数量。*/
#define EXTMEM_DBUS2_ACS_CNT  0xFFFFFFFF
#define EXTMEM_DBUS2_ACS_CNT_M  ((EXTMEM_DBUS2_ACS_CNT_V)<<(EXTMEM_DBUS2_ACS_CNT_S))
#define EXTMEM_DBUS2_ACS_CNT_V  0xFFFFFFFF
#define EXTMEM_DBUS2_ACS_CNT_S  0

#define EXTMEM_DBUS1_ACS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0E0)
/* EXTMEM_DBUS1_ACS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算dbus1访问dcache的数量。*/
#define EXTMEM_DBUS1_ACS_CNT  0xFFFFFFFF
#define EXTMEM_DBUS1_ACS_CNT_M  ((EXTMEM_DBUS1_ACS_CNT_V)<<(EXTMEM_DBUS1_ACS_CNT_S))
#define EXTMEM_DBUS1_ACS_CNT_V  0xFFFFFFFF
#define EXTMEM_DBUS1_ACS_CNT_S  0

#define EXTMEM_DBUS0_ACS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x0E4)
/* EXTMEM_DBUS0_ACS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于计算dbus0访问dcache的数量。*/
#define EXTMEM_DBUS0_ACS_CNT  0xFFFFFFFF
#define EXTMEM_DBUS0_ACS_CNT_M  ((EXTMEM_DBUS0_ACS_CNT_V)<<(EXTMEM_DBUS0_ACS_CNT_S))
#define EXTMEM_DBUS0_ACS_CNT_V  0xFFFFFFFF
#define EXTMEM_DBUS0_ACS_CNT_S  0

#define EXTMEM_CACHE_DBG_INT_ENA_REG          (DR_REG_EXTMEM_BASE + 0x0E8)
/* EXTMEM_MMU_ENTRY_FAULT_INT_ENA:R/W；位位置：[19]；默认值：1’b0；*/
/*description:该位用于通过mmu条目故障启用中断。*/
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA  (BIT(19))
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA_M  (BIT(19))
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA_V  0x1
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA_S  19
/* EXTMEM_DCACHE_SET_LOCK_ILG_INT_ENA:R/W；位位置：[18]；默认值：1’b0；*/
/*描述：当dcache忙于发出锁同步或预加载操作时，该位用于通过非法写入dcache的锁寄存器来启用中断。*/
#define EXTMEM_DCACHE_SET_LOCK_ILG_INT_ENA  (BIT(18))
#define EXTMEM_DCACHE_SET_LOCK_ILG_INT_ENA_M  (BIT(18))
#define EXTMEM_DCACHE_SET_LOCK_ILG_INT_ENA_V  0x1
#define EXTMEM_DCACHE_SET_LOCK_ILG_INT_ENA_S  18
/* EXTMEM_DCACHE_SET_SYNC_ILG_INT_ENA:R/W；位位置：[17]；默认值：1’b0；*/
/*描述：该位用于在dcache忙着发出锁定同步和预加载操作时，通过非法写入dcache的同步寄存器来启用中断。*/
#define EXTMEM_DCACHE_SET_SYNC_ILG_INT_ENA  (BIT(17))
#define EXTMEM_DCACHE_SET_SYNC_ILG_INT_ENA_M  (BIT(17))
#define EXTMEM_DCACHE_SET_SYNC_ILG_INT_ENA_V  0x1
#define EXTMEM_DCACHE_SET_SYNC_ILG_INT_ENA_S  17
/* EXTMEM_DCACHE_SET_PRELOAD_ILG_INT_ENA:R/W；位位置：[16]；默认值：1’b0；*/
/*描述：当dcache忙于发出锁同步和预加载操作时，该位用于通过非法写入dcache的预加载寄存器来启用中断。*/
#define EXTMEM_DCACHE_SET_PRELOAD_ILG_INT_ENA  (BIT(16))
#define EXTMEM_DCACHE_SET_PRELOAD_ILG_INT_ENA_M  (BIT(16))
#define EXTMEM_DCACHE_SET_PRELOAD_ILG_INT_ENA_V  0x1
#define EXTMEM_DCACHE_SET_PRELOAD_ILG_INT_ENA_S  16
/* EXTMEM_DCACHE_REJECT_INT_ENA:R/W；位位置：[15]；默认值：1’b0；*/
/*description:该位用于启用身份验证失败时的中断。*/
#define EXTMEM_DCACHE_REJECT_INT_ENA  (BIT(15))
#define EXTMEM_DCACHE_REJECT_INT_ENA_M  (BIT(15))
#define EXTMEM_DCACHE_REJECT_INT_ENA_V  0x1
#define EXTMEM_DCACHE_REJECT_INT_ENA_S  15
/* EXTMEM_DCACHE_WRITE_FLASH_INT_ENA:R/W；位位置：[14]；默认值：1’b0；*/
/*description:该位用于通过dcache尝试写入闪存来启用中断。*/
#define EXTMEM_DCACHE_WRITE_FLASH_INT_ENA  (BIT(14))
#define EXTMEM_DCACHE_WRITE_FLASH_INT_ENA_M  (BIT(14))
#define EXTMEM_DCACHE_WRITE_FLASH_INT_ENA_V  0x1
#define EXTMEM_DCACHE_WRITE_FLASH_INT_ENA_S  14
/* EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_ENA:R/W；位位置：[13]；默认值：1’b0；*/
/*description:该位用于通过手动预加载配置故障启用中断。*/
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_ENA  (BIT(13))
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_ENA_M  (BIT(13))
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_ENA_V  0x1
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_ENA_S  13
/* EXTMEM_DC_SYNC_SIZE_FAULT_INT_ENA:R/W；位位置：[12]；默认值：1’b0；*/
/*description:该位用于通过手动同步配置故障启用中断。*/
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_ENA  (BIT(12))
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_ENA_M  (BIT(12))
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_ENA_V  0x1
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_ENA_S  12
/* EXTMEM_DBUS_CNT_OVF_INT_ENA:R/W；位位置：[11]；默认值：1’b0；*/
/*description:该位用于通过dbus计数器溢出启用中断。*/
#define EXTMEM_DBUS_CNT_OVF_INT_ENA  (BIT(11))
#define EXTMEM_DBUS_CNT_OVF_INT_ENA_M  (BIT(11))
#define EXTMEM_DBUS_CNT_OVF_INT_ENA_V  0x1
#define EXTMEM_DBUS_CNT_OVF_INT_ENA_S  11
/* EXTMEM_DBUS_ACS_MSK_DC_INT_ENA:R/W；位位置：[10]；默认值：1’b0；*/
/*描述：该位用于启用中断通过cpu访问dcache，而禁用相应的dbus（包括推测访问）。*/
#define EXTMEM_DBUS_ACS_MSK_DC_INT_ENA  (BIT(10))
#define EXTMEM_DBUS_ACS_MSK_DC_INT_ENA_M  (BIT(10))
#define EXTMEM_DBUS_ACS_MSK_DC_INT_ENA_V  0x1
#define EXTMEM_DBUS_ACS_MSK_DC_INT_ENA_S  10
/* EXTMEM_ICACHE_SET_LOCK_ILG_INT_ENA:R/W；位位置：[9]；默认值：1’b0；*/
/*描述：该位用于在icache忙于发布锁同步或预加载操作时，通过非法写入icache的锁寄存器来启用中断。*/
#define EXTMEM_ICACHE_SET_LOCK_ILG_INT_ENA  (BIT(9))
#define EXTMEM_ICACHE_SET_LOCK_ILG_INT_ENA_M  (BIT(9))
#define EXTMEM_ICACHE_SET_LOCK_ILG_INT_ENA_V  0x1
#define EXTMEM_ICACHE_SET_LOCK_ILG_INT_ENA_S  9
/* EXTMEM_ICACHE_SET_SYNC_ILG_INT_ENA:R/W；位位置：[8]；默认值：1’b0；*/
/*描述：该位用于在icache忙于发布锁同步和预加载操作时，通过非法写入icache的同步寄存器来启用中断。*/
#define EXTMEM_ICACHE_SET_SYNC_ILG_INT_ENA  (BIT(8))
#define EXTMEM_ICACHE_SET_SYNC_ILG_INT_ENA_M  (BIT(8))
#define EXTMEM_ICACHE_SET_SYNC_ILG_INT_ENA_V  0x1
#define EXTMEM_ICACHE_SET_SYNC_ILG_INT_ENA_S  8
/* EXTMEM_ICACHE_SET_PRELOAD_ILG_INT_ENA:R/W；位位置：[7]；默认值：1’b0；*/
/*描述：当icache忙于发布锁同步和预加载操作时，该位用于通过非法写入icache的预加载寄存器来启用中断。*/
#define EXTMEM_ICACHE_SET_PRELOAD_ILG_INT_ENA  (BIT(7))
#define EXTMEM_ICACHE_SET_PRELOAD_ILG_INT_ENA_M  (BIT(7))
#define EXTMEM_ICACHE_SET_PRELOAD_ILG_INT_ENA_V  0x1
#define EXTMEM_ICACHE_SET_PRELOAD_ILG_INT_ENA_S  7
/* EXTMEM_ICACHE_REJECT_INT_ENA：R/W；位位置：[6]；默认值：1’b0；*/
/*description:该位用于启用身份验证失败时的中断。*/
#define EXTMEM_ICACHE_REJECT_INT_ENA  (BIT(6))
#define EXTMEM_ICACHE_REJECT_INT_ENA_M  (BIT(6))
#define EXTMEM_ICACHE_REJECT_INT_ENA_V  0x1
#define EXTMEM_ICACHE_REJECT_INT_ENA_S  6
/* EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_ENA:R/W；位位置：[5]；默认值：1’b0；*/
/*description:该位用于通过手动预加载配置故障启用中断。*/
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_ENA  (BIT(5))
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_ENA_M  (BIT(5))
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_ENA_V  0x1
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_ENA_S  5
/* EXTMEM_IC_SYNC_SIZE_FAULT_INT_ENA:R/W；位位置：[4]；默认值：1’b0；*/
/*description:该位用于通过手动同步配置故障启用中断。*/
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_ENA  (BIT(4))
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_ENA_M  (BIT(4))
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_ENA_V  0x1
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_ENA_S  4
/* EXTMEM_IBUS_CNT_OVF_INT_ENA:R/W；位位置：[3]；默认值：1’b0；*/
/*description:该位用于通过ibus计数器溢出启用中断。*/
#define EXTMEM_IBUS_CNT_OVF_INT_ENA  (BIT(3))
#define EXTMEM_IBUS_CNT_OVF_INT_ENA_M  (BIT(3))
#define EXTMEM_IBUS_CNT_OVF_INT_ENA_V  0x1
#define EXTMEM_IBUS_CNT_OVF_INT_ENA_S  3
/* EXTMEM_IBUS_ACS_MSK_IC_INT_ENA:R/W；位位置：[2]；默认值：1’b0；*/
/*描述：该位用于启用中断通过cpu访问icache，而禁用相应的ibu（包括推测访问）。*/
#define EXTMEM_IBUS_ACS_MSK_IC_INT_ENA  (BIT(2))
#define EXTMEM_IBUS_ACS_MSK_IC_INT_ENA_M  (BIT(2))
#define EXTMEM_IBUS_ACS_MSK_IC_INT_ENA_V  0x1
#define EXTMEM_IBUS_ACS_MSK_IC_INT_ENA_S  2
/* EXTMEM_CACHE_DBG_EN:R/W；位位置：[0]；默认值：1’b1；*/
/*description:该位用于激活缓存跟踪功能。1： 启用0：禁用。*/
#define EXTMEM_CACHE_DBG_EN  (BIT(0))
#define EXTMEM_CACHE_DBG_EN_M  (BIT(0))
#define EXTMEM_CACHE_DBG_EN_V  0x1
#define EXTMEM_CACHE_DBG_EN_S  0

#define EXTMEM_CACHE_DBG_INT_CLR_REG          (DR_REG_EXTMEM_BASE + 0x0EC)
/* EXTMEM_MMU_ENTRY_FAULT_INT_CLR:WOD；位位置：[13]；默认值：1’b0；*/
/*description:该位用于清除mmu条目故障导致的中断。*/
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR  (BIT(13))
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR_M  (BIT(13))
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR_V  0x1
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR_S  13
/* EXTMEM_DCACHE_SET_ILG_INT_CLR:WOD；位位置：[12]；默认值：1’b0；*/
/*描述：当dcache忙于发出锁同步或预加载操作时，该位用于通过非法写入dcache的锁寄存器来清除中断。*/
#define EXTMEM_DCACHE_SET_ILG_INT_CLR  (BIT(12))
#define EXTMEM_DCACHE_SET_ILG_INT_CLR_M  (BIT(12))
#define EXTMEM_DCACHE_SET_ILG_INT_CLR_V  0x1
#define EXTMEM_DCACHE_SET_ILG_INT_CLR_S  12
/* EXTMEM_DCACHE_REJECT_INT_CLR:WOD；位位置：[11]；默认值：1’b0；*/
/*description:该位用于清除身份验证失败时的中断。*/
#define EXTMEM_DCACHE_REJECT_INT_CLR  (BIT(11))
#define EXTMEM_DCACHE_REJECT_INT_CLR_M  (BIT(11))
#define EXTMEM_DCACHE_REJECT_INT_CLR_V  0x1
#define EXTMEM_DCACHE_REJECT_INT_CLR_S  11
/* EXTMEM_DCACHE_WRITE_FLASH_INT_CLR:WOD；位位置：[10]；默认值：1’b0；*/
/*描述：该位用于通过dcache尝试写入闪存来清除中断。*/
#define EXTMEM_DCACHE_WRITE_FLASH_INT_CLR  (BIT(10))
#define EXTMEM_DCACHE_WRITE_FLASH_INT_CLR_M  (BIT(10))
#define EXTMEM_DCACHE_WRITE_FLASH_INT_CLR_V  0x1
#define EXTMEM_DCACHE_WRITE_FLASH_INT_CLR_S  10
/* EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_CLR:WOD；位位置：[9]；默认值：1’b0；*/
/*description:该位用于清除手动预加载配置故障造成的中断。*/
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_CLR  (BIT(9))
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_CLR_M  (BIT(9))
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_CLR_V  0x1
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_INT_CLR_S  9
/* EXTMEM_DC_SYNC_SIZE_FAULT_INT_CLR:WOD；位位置：[8]；默认值：1’b0；*/
/*描述：该位用于清除手动同步配置故障造成的中断。*/
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_CLR  (BIT(8))
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_CLR_M  (BIT(8))
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_CLR_V  0x1
#define EXTMEM_DC_SYNC_SIZE_FAULT_INT_CLR_S  8
/* EXTMEM_DBUS_CNT_OVF_INT_CLR:WOD；位位置：[7]；默认值：1’b0；*/
/*description:该位用于清除dbus计数器溢出造成的中断。*/
#define EXTMEM_DBUS_CNT_OVF_INT_CLR  (BIT(7))
#define EXTMEM_DBUS_CNT_OVF_INT_CLR_M  (BIT(7))
#define EXTMEM_DBUS_CNT_OVF_INT_CLR_V  0x1
#define EXTMEM_DBUS_CNT_OVF_INT_CLR_S  7
/* EXTMEM_DBUS_ACS_MSK_DC_INT_CLR:WOD；位位置：[6]；默认值：1’b0；*/
/*描述：当禁用相应的dbus或禁用dcache（包括推测访问）时，该位用于清除cpu访问dcache的中断。*/
#define EXTMEM_DBUS_ACS_MSK_DC_INT_CLR  (BIT(6))
#define EXTMEM_DBUS_ACS_MSK_DC_INT_CLR_M  (BIT(6))
#define EXTMEM_DBUS_ACS_MSK_DC_INT_CLR_V  0x1
#define EXTMEM_DBUS_ACS_MSK_DC_INT_CLR_S  6
/* EXTMEM_ICACHE_SET_ILG_INT_CLR:WOD；位位置：[5]；默认值：1’b0；*/
/*描述：当icache忙于发出锁同步或预加载操作时，该位用于通过非法写入icache的锁寄存器来清除中断。*/
#define EXTMEM_ICACHE_SET_ILG_INT_CLR  (BIT(5))
#define EXTMEM_ICACHE_SET_ILG_INT_CLR_M  (BIT(5))
#define EXTMEM_ICACHE_SET_ILG_INT_CLR_V  0x1
#define EXTMEM_ICACHE_SET_ILG_INT_CLR_S  5
/* EXTMEM_ICACHE_REJECT_INT_CLR:WOD；位位置：[4]；默认值：1’b0；*/
/*description:该位用于清除身份验证失败时的中断。*/
#define EXTMEM_ICACHE_REJECT_INT_CLR  (BIT(4))
#define EXTMEM_ICACHE_REJECT_INT_CLR_M  (BIT(4))
#define EXTMEM_ICACHE_REJECT_INT_CLR_V  0x1
#define EXTMEM_ICACHE_REJECT_INT_CLR_S  4
/* EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_CLR:WOD；位位置：[3]；默认值：1’b0；*/
/*description:该位用于清除手动预加载配置故障造成的中断。*/
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_CLR  (BIT(3))
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_CLR_M  (BIT(3))
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_CLR_V  0x1
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_INT_CLR_S  3
/* EXTMEM_IC_SYNC_SIZE_FAULT_INT_CLR:WOD；位位置：[2]；默认值：1’b0；*/
/*描述：该位用于清除手动同步配置故障造成的中断。*/
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_CLR  (BIT(2))
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_CLR_M  (BIT(2))
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_CLR_V  0x1
#define EXTMEM_IC_SYNC_SIZE_FAULT_INT_CLR_S  2
/* EXTMEM_IBUS_CNT_OVF_INT_CLR:WOD；位位置：[1]；默认值：1’b0；*/
/*description:该位用于清除ibus计数器溢出造成的中断。*/
#define EXTMEM_IBUS_CNT_OVF_INT_CLR  (BIT(1))
#define EXTMEM_IBUS_CNT_OVF_INT_CLR_M  (BIT(1))
#define EXTMEM_IBUS_CNT_OVF_INT_CLR_V  0x1
#define EXTMEM_IBUS_CNT_OVF_INT_CLR_S  1
/* EXTMEM_IBUS_ACS_MSK_IC_INT_CLR:WOD；位位置：[0]；默认值：1’b0；*/
/*描述：当禁用相应的ibu或禁用icache（包括推测访问）时，该位用于清除cpu访问icache的中断。*/
#define EXTMEM_IBUS_ACS_MSK_IC_INT_CLR  (BIT(0))
#define EXTMEM_IBUS_ACS_MSK_IC_INT_CLR_M  (BIT(0))
#define EXTMEM_IBUS_ACS_MSK_IC_INT_CLR_V  0x1
#define EXTMEM_IBUS_ACS_MSK_IC_INT_CLR_S  0

#define EXTMEM_CACHE_DBG_STATUS0_REG          (DR_REG_EXTMEM_BASE + 0x0F0)
/* EXTMEM_ICACHE_SET_LOCK_ILG_ST:RO；位位置：[24]；默认值：1’b0；*/
/*描述：当icache忙着发布锁同步或预加载操作时，该位用于指示非法写入icache锁寄存器的中断。*/
#define EXTMEM_ICACHE_SET_LOCK_ILG_ST  (BIT(24))
#define EXTMEM_ICACHE_SET_LOCK_ILG_ST_M  (BIT(24))
#define EXTMEM_ICACHE_SET_LOCK_ILG_ST_V  0x1
#define EXTMEM_ICACHE_SET_LOCK_ILG_ST_S  24
/* EXTMEM_ICACHE_SET_SYNC_ILG_ST:RO；位位置：[23]；默认值：1’b0；*/
/*描述：当icache忙于发布锁同步和预加载操作时，该位用于指示非法写入icache同步寄存器的中断。*/
#define EXTMEM_ICACHE_SET_SYNC_ILG_ST  (BIT(23))
#define EXTMEM_ICACHE_SET_SYNC_ILG_ST_M  (BIT(23))
#define EXTMEM_ICACHE_SET_SYNC_ILG_ST_V  0x1
#define EXTMEM_ICACHE_SET_SYNC_ILG_ST_S  23
/* EXTMEM_ICACHE_SET_PRELOAD_ILG_ST:RO；位位置：[22]；默认值：1’b0；*/
/*描述：当icache忙于发布锁同步和预加载操作时，该位用于指示非法写入icache预加载寄存器的中断。*/
#define EXTMEM_ICACHE_SET_PRELOAD_ILG_ST  (BIT(22))
#define EXTMEM_ICACHE_SET_PRELOAD_ILG_ST_M  (BIT(22))
#define EXTMEM_ICACHE_SET_PRELOAD_ILG_ST_V  0x1
#define EXTMEM_ICACHE_SET_PRELOAD_ILG_ST_S  22
/* EXTMEM_ICACHE_REJECT_ST:RO；位位置：[21]；默认值：1’b0；*/
/*description:该位用于指示认证失败导致的中断。*/
#define EXTMEM_ICACHE_REJECT_ST  (BIT(21))
#define EXTMEM_ICACHE_REJECT_ST_M  (BIT(21))
#define EXTMEM_ICACHE_REJECT_ST_V  0x1
#define EXTMEM_ICACHE_REJECT_ST_S  21
/* EXTMEM_IC_PRELOAD_SIZE_FAULT_ST:RO；位位置：[20]；默认值：1’b0；*/
/*description:该位用于指示手动预加载配置故障导致的中断。*/
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_ST  (BIT(20))
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_ST_M  (BIT(20))
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_ST_V  0x1
#define EXTMEM_IC_PRELOAD_SIZE_FAULT_ST_S  20
/* EXTMEM_IC_SYNC_SIZE_FAULT_ST:RO；位位置：[19]；默认值：1’b0；*/
/*description:该位用于指示手动同步配置故障导致的中断。*/
#define EXTMEM_IC_SYNC_SIZE_FAULT_ST  (BIT(19))
#define EXTMEM_IC_SYNC_SIZE_FAULT_ST_M  (BIT(19))
#define EXTMEM_IC_SYNC_SIZE_FAULT_ST_V  0x1
#define EXTMEM_IC_SYNC_SIZE_FAULT_ST_S  19
/* EXTMEM_IC_PRELOAD_CNT_OVF_ST:RO；位位置：[18]；默认值：1’b0；*/
/*description:该位用于指示预加载计数器溢出导致的中断。*/
#define EXTMEM_IC_PRELOAD_CNT_OVF_ST  (BIT(18))
#define EXTMEM_IC_PRELOAD_CNT_OVF_ST_M  (BIT(18))
#define EXTMEM_IC_PRELOAD_CNT_OVF_ST_V  0x1
#define EXTMEM_IC_PRELOAD_CNT_OVF_ST_S  18
/* EXTMEM_IC_PRELOAD_MISS_CNT_OVF_ST:RO；位位置：[16]；默认值：1’b0；*/
/*description:该位用于指示预加载未命中计数器溢出导致的中断。*/
#define EXTMEM_IC_PRELOAD_MISS_CNT_OVF_ST  (BIT(16))
#define EXTMEM_IC_PRELOAD_MISS_CNT_OVF_ST_M  (BIT(16))
#define EXTMEM_IC_PRELOAD_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_IC_PRELOAD_MISS_CNT_OVF_ST_S  16
/* EXTMEM_IBUS2_放弃_CNT_OVF_ST:RO；位位置：[14]；默认值：1’b0；*/
/*description:该位用于指示ibus2放弃计数器溢出导致的中断。*/
#define EXTMEM_IBUS2_ABANDON_CNT_OVF_ST  (BIT(14))
#define EXTMEM_IBUS2_ABANDON_CNT_OVF_ST_M  (BIT(14))
#define EXTMEM_IBUS2_ABANDON_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS2_ABANDON_CNT_OVF_ST_S  14
/* EXTMEM_IBUS1_放弃_CNT_OVF_ST:RO；位位置：[13]；默认值：1’b0；*/
/*description:该位用于指示ibus1放弃计数器溢出导致的中断。*/
#define EXTMEM_IBUS1_ABANDON_CNT_OVF_ST  (BIT(13))
#define EXTMEM_IBUS1_ABANDON_CNT_OVF_ST_M  (BIT(13))
#define EXTMEM_IBUS1_ABANDON_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS1_ABANDON_CNT_OVF_ST_S  13
/* EXTMEM_IBUS0_放弃_CNT_OVF_ST:RO；位位置：[12]；默认值：1’b0；*/
/*description:该位用于指示ibus0放弃计数器溢出导致的中断。*/
#define EXTMEM_IBUS0_ABANDON_CNT_OVF_ST  (BIT(12))
#define EXTMEM_IBUS0_ABANDON_CNT_OVF_ST_M  (BIT(12))
#define EXTMEM_IBUS0_ABANDON_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS0_ABANDON_CNT_OVF_ST_S  12
/* EXTMEM_IBUS2_ACS_MISS_CNT_vf_ST:RO；位位置：[10]；默认值：1’b0；*/
/*description:该位用于指示ibus2未命中计数器溢出导致的中断。*/
#define EXTMEM_IBUS2_ACS_MISS_CNT_OVF_ST  (BIT(10))
#define EXTMEM_IBUS2_ACS_MISS_CNT_OVF_ST_M  (BIT(10))
#define EXTMEM_IBUS2_ACS_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS2_ACS_MISS_CNT_OVF_ST_S  10
/* EXTMEM_IBUS1_ACS_MISS_CNT_vf_ST:RO；位位置：[9]；默认值：1’b0；*/
/*description:该位用于指示ibus1未命中计数器溢出导致的中断。*/
#define EXTMEM_IBUS1_ACS_MISS_CNT_OVF_ST  (BIT(9))
#define EXTMEM_IBUS1_ACS_MISS_CNT_OVF_ST_M  (BIT(9))
#define EXTMEM_IBUS1_ACS_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS1_ACS_MISS_CNT_OVF_ST_S  9
/* EXTMEM_IBUS0_ACS_MISS_CNT_OVF_ST:RO；位位置：[8]；默认值：1’b0；*/
/*description:该位用于指示ibus0未命中计数器溢出导致的中断。*/
#define EXTMEM_IBUS0_ACS_MISS_CNT_OVF_ST  (BIT(8))
#define EXTMEM_IBUS0_ACS_MISS_CNT_OVF_ST_M  (BIT(8))
#define EXTMEM_IBUS0_ACS_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS0_ACS_MISS_CNT_OVF_ST_S  8
/* EXTMEM_IBUS2_ACS_CNT_ov_ST:RO；位位置：[6]；默认值：1’b0；*/
/*description:该位用于指示ibus2计数器溢出导致的中断。*/
#define EXTMEM_IBUS2_ACS_CNT_OVF_ST  (BIT(6))
#define EXTMEM_IBUS2_ACS_CNT_OVF_ST_M  (BIT(6))
#define EXTMEM_IBUS2_ACS_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS2_ACS_CNT_OVF_ST_S  6
/* EXTMEM_IBUS1_ACS_CNT_ov_ST:RO；位位置：[5]；默认值：1’b0；*/
/*description:该位用于指示ibus1计数器溢出导致的中断。*/
#define EXTMEM_IBUS1_ACS_CNT_OVF_ST  (BIT(5))
#define EXTMEM_IBUS1_ACS_CNT_OVF_ST_M  (BIT(5))
#define EXTMEM_IBUS1_ACS_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS1_ACS_CNT_OVF_ST_S  5
/* EXTMEM_IBUS0_ACS_CNT_OVF_ST:RO；位位置：[4]；默认值：1’b0；*/
/*description:该位用于指示ibus0计数器溢出导致的中断。*/
#define EXTMEM_IBUS0_ACS_CNT_OVF_ST  (BIT(4))
#define EXTMEM_IBUS0_ACS_CNT_OVF_ST_M  (BIT(4))
#define EXTMEM_IBUS0_ACS_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS0_ACS_CNT_OVF_ST_S  4
/* EXTMEM_IBUS2_ACS_MSK_cache_ST:RO；位位置：[2]；默认值：1’b0；*/
/*描述：当禁用ibus2或禁用icache（包括推测访问）时，该位用于指示cpu访问icache的中断。*/
#define EXTMEM_IBUS2_ACS_MSK_ICACHE_ST  (BIT(2))
#define EXTMEM_IBUS2_ACS_MSK_ICACHE_ST_M  (BIT(2))
#define EXTMEM_IBUS2_ACS_MSK_ICACHE_ST_V  0x1
#define EXTMEM_IBUS2_ACS_MSK_ICACHE_ST_S  2
/* EXTMEM_IBUS1_ACS_MSK_cache_ST:RO；位位置：[1]；默认值：1’b0；*/
/*描述：当禁用ibus1或禁用icache（包括推测访问）时，该位用于指示cpu访问icache的中断。*/
#define EXTMEM_IBUS1_ACS_MSK_ICACHE_ST  (BIT(1))
#define EXTMEM_IBUS1_ACS_MSK_ICACHE_ST_M  (BIT(1))
#define EXTMEM_IBUS1_ACS_MSK_ICACHE_ST_V  0x1
#define EXTMEM_IBUS1_ACS_MSK_ICACHE_ST_S  1
/* EXTMEM_IBUS0_ACS_MSK_cache_ST:RO；位位置：[0]；默认值：1’b0；*/
/*描述：当禁用ibus0或禁用icache（包括推测访问）时，该位用于指示cpu访问icache的中断。*/
#define EXTMEM_IBUS0_ACS_MSK_ICACHE_ST  (BIT(0))
#define EXTMEM_IBUS0_ACS_MSK_ICACHE_ST_M  (BIT(0))
#define EXTMEM_IBUS0_ACS_MSK_ICACHE_ST_V  0x1
#define EXTMEM_IBUS0_ACS_MSK_ICACHE_ST_S  0

#define EXTMEM_CACHE_DBG_STATUS1_REG          (DR_REG_EXTMEM_BASE + 0x0F4)
/* EXTMEM_MMU_ENTRY_FAULT_ST:RO；位位置：[30]；默认值：1’b0；*/
/*description:该位用于指示mmu条目故障导致的中断。*/
#define EXTMEM_MMU_ENTRY_FAULT_ST  (BIT(30))
#define EXTMEM_MMU_ENTRY_FAULT_ST_M  (BIT(30))
#define EXTMEM_MMU_ENTRY_FAULT_ST_V  0x1
#define EXTMEM_MMU_ENTRY_FAULT_ST_S  30
/* EXTMEM_DCACHE_SET_LOCK_ILG_ST:RO；位位置：[29]；默认值：1’b0；*/
/*描述：当icache忙着发布锁同步或预加载操作时，该位用于指示非法写入icache锁寄存器的中断。*/
#define EXTMEM_DCACHE_SET_LOCK_ILG_ST  (BIT(29))
#define EXTMEM_DCACHE_SET_LOCK_ILG_ST_M  (BIT(29))
#define EXTMEM_DCACHE_SET_LOCK_ILG_ST_V  0x1
#define EXTMEM_DCACHE_SET_LOCK_ILG_ST_S  29
/* EXTMEM_DCACHE_SET_SYNC_ILG_ST:RO；位位置：[28]；默认值：1’b0；*/
/*描述：当icache忙于发布锁同步和预加载操作时，该位用于指示非法写入icache同步寄存器的中断。*/
#define EXTMEM_DCACHE_SET_SYNC_ILG_ST  (BIT(28))
#define EXTMEM_DCACHE_SET_SYNC_ILG_ST_M  (BIT(28))
#define EXTMEM_DCACHE_SET_SYNC_ILG_ST_V  0x1
#define EXTMEM_DCACHE_SET_SYNC_ILG_ST_S  28
/* EXTMEM_DCACHE_SET_PRELOAD_ILG_ST:RO；位位置：[27]；默认值：1’b0；*/
/*描述：当icache忙于发布锁同步和预加载操作时，该位用于指示非法写入icache预加载寄存器的中断。*/
#define EXTMEM_DCACHE_SET_PRELOAD_ILG_ST  (BIT(27))
#define EXTMEM_DCACHE_SET_PRELOAD_ILG_ST_M  (BIT(27))
#define EXTMEM_DCACHE_SET_PRELOAD_ILG_ST_V  0x1
#define EXTMEM_DCACHE_SET_PRELOAD_ILG_ST_S  27
/* EXTMEM_DCACHE_REJECT_ST:RO；位位置：[26]；默认值：1’b0；*/
/*description:该位用于指示认证失败导致的中断。*/
#define EXTMEM_DCACHE_REJECT_ST  (BIT(26))
#define EXTMEM_DCACHE_REJECT_ST_M  (BIT(26))
#define EXTMEM_DCACHE_REJECT_ST_V  0x1
#define EXTMEM_DCACHE_REJECT_ST_S  26
/* EXTMEM_DCACHE_WRITE_FLASH_ST:RO；位位置：[25]；默认值：1’b0；*/
/*description:该位用于指示dcache尝试写入闪存时的中断。*/
#define EXTMEM_DCACHE_WRITE_FLASH_ST  (BIT(25))
#define EXTMEM_DCACHE_WRITE_FLASH_ST_M  (BIT(25))
#define EXTMEM_DCACHE_WRITE_FLASH_ST_V  0x1
#define EXTMEM_DCACHE_WRITE_FLASH_ST_S  25
/* EXTMEM_DC_PRELOAD_SIZE_FAULT_ST:RO；位位置：[24]；默认值：1’b0；*/
/*description:该位用于指示手动预加载配置故障导致的中断。*/
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_ST  (BIT(24))
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_ST_M  (BIT(24))
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_ST_V  0x1
#define EXTMEM_DC_PRELOAD_SIZE_FAULT_ST_S  24
/* EXTMEM_DC_SYNC_SIZE_FAULT_ST:RO；位位置：[23]；默认值：1’b0；*/
/*description:该位用于指示手动同步配置故障导致的中断。*/
#define EXTMEM_DC_SYNC_SIZE_FAULT_ST  (BIT(23))
#define EXTMEM_DC_SYNC_SIZE_FAULT_ST_M  (BIT(23))
#define EXTMEM_DC_SYNC_SIZE_FAULT_ST_V  0x1
#define EXTMEM_DC_SYNC_SIZE_FAULT_ST_S  23
/* EXTMEM_DC_PRELOAD_CNT_OVF_ST:RO；位位置：[22]；默认值：1’b0；*/
/*description:该位用于指示预加载计数器溢出导致的中断。*/
#define EXTMEM_DC_PRELOAD_CNT_OVF_ST  (BIT(22))
#define EXTMEM_DC_PRELOAD_CNT_OVF_ST_M  (BIT(22))
#define EXTMEM_DC_PRELOAD_CNT_OVF_ST_V  0x1
#define EXTMEM_DC_PRELOAD_CNT_OVF_ST_S  22
/* EXTMEM_DC_PRELOAD_EVICT_CNT_vf_ST:RO；位位置：[21]；默认值：1’b0；*/
/*description:该位用于通过预加载逐出计数器溢出指示中断。*/
#define EXTMEM_DC_PRELOAD_EVICT_CNT_OVF_ST  (BIT(21))
#define EXTMEM_DC_PRELOAD_EVICT_CNT_OVF_ST_M  (BIT(21))
#define EXTMEM_DC_PRELOAD_EVICT_CNT_OVF_ST_V  0x1
#define EXTMEM_DC_PRELOAD_EVICT_CNT_OVF_ST_S  21
/* EXTMEM_DC_PRELOAD_MISS_CNT_OVF_ST:RO；位位置：[20]；默认值：1’b0；*/
/*description:该位用于指示预加载未命中计数器溢出导致的中断。*/
#define EXTMEM_DC_PRELOAD_MISS_CNT_OVF_ST  (BIT(20))
#define EXTMEM_DC_PRELOAD_MISS_CNT_OVF_ST_M  (BIT(20))
#define EXTMEM_DC_PRELOAD_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_DC_PRELOAD_MISS_CNT_OVF_ST_S  20
/* EXTMEM_DBUS2_放弃_CNT_OVF_ST:RO；位位置：[18]；默认值：1’b0；*/
/*description:该位用于指示dbus2放弃计数器溢出导致的中断。*/
#define EXTMEM_DBUS2_ABANDON_CNT_OVF_ST  (BIT(18))
#define EXTMEM_DBUS2_ABANDON_CNT_OVF_ST_M  (BIT(18))
#define EXTMEM_DBUS2_ABANDON_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS2_ABANDON_CNT_OVF_ST_S  18
/* EXTMEM_DBUS1_放弃_CNT_OVF_ST:RO；位位置：[17]；默认值：1’b0；*/
/*description:该位用于指示dbus1放弃计数器溢出导致的中断。*/
#define EXTMEM_DBUS1_ABANDON_CNT_OVF_ST  (BIT(17))
#define EXTMEM_DBUS1_ABANDON_CNT_OVF_ST_M  (BIT(17))
#define EXTMEM_DBUS1_ABANDON_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS1_ABANDON_CNT_OVF_ST_S  17
/* EXTMEM_DBUS0_advard_CNT_OVF_ST:RO；位位置：[16]；默认值：1’b0；*/
/*description:该位用于指示dbus0放弃计数器溢出导致的中断。*/
#define EXTMEM_DBUS0_ABANDON_CNT_OVF_ST  (BIT(16))
#define EXTMEM_DBUS0_ABANDON_CNT_OVF_ST_M  (BIT(16))
#define EXTMEM_DBUS0_ABANDON_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS0_ABANDON_CNT_OVF_ST_S  16
/* EXTMEM_DBUS2_ACS_WB_CNT_OVF_ST:RO；位位置：[14]；默认值：1’b0；*/
/*description:该位用于指示dbus2逐出计数器溢出导致的中断。*/
#define EXTMEM_DBUS2_ACS_WB_CNT_OVF_ST  (BIT(14))
#define EXTMEM_DBUS2_ACS_WB_CNT_OVF_ST_M  (BIT(14))
#define EXTMEM_DBUS2_ACS_WB_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS2_ACS_WB_CNT_OVF_ST_S  14
/* EXTMEM_DBUS1_ACS_WB_CNT_OVF_ST:RO；位位置：[13]；默认值：1’b0；*/
/*description:该位用于指示dbus1逐出计数器溢出导致的中断。*/
#define EXTMEM_DBUS1_ACS_WB_CNT_OVF_ST  (BIT(13))
#define EXTMEM_DBUS1_ACS_WB_CNT_OVF_ST_M  (BIT(13))
#define EXTMEM_DBUS1_ACS_WB_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS1_ACS_WB_CNT_OVF_ST_S  13
/* EXTMEM_DBUS0_ACS_WB_CNT_vf_ST:RO；位位置：[12]；默认值：1’b0；*/
/*description:该位用于指示dbus0逐出计数器溢出导致的中断。*/
#define EXTMEM_DBUS0_ACS_WB_CNT_OVF_ST  (BIT(12))
#define EXTMEM_DBUS0_ACS_WB_CNT_OVF_ST_M  (BIT(12))
#define EXTMEM_DBUS0_ACS_WB_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS0_ACS_WB_CNT_OVF_ST_S  12
/* EXTMEM_DBUS2_ACS_MISS_CNT_vf_ST:RO；位位置：[10]；默认值：1’b0；*/
/*description:该位用于指示dbus2未命中计数器溢出导致的中断。*/
#define EXTMEM_DBUS2_ACS_MISS_CNT_OVF_ST  (BIT(10))
#define EXTMEM_DBUS2_ACS_MISS_CNT_OVF_ST_M  (BIT(10))
#define EXTMEM_DBUS2_ACS_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS2_ACS_MISS_CNT_OVF_ST_S  10
/* EXTMEM_DBUS1_ACS_MISS_CNT_vf_ST:RO；位位置：[9]；默认值：1’b0；*/
/*description:该位用于指示dbus1未命中计数器溢出导致的中断。*/
#define EXTMEM_DBUS1_ACS_MISS_CNT_OVF_ST  (BIT(9))
#define EXTMEM_DBUS1_ACS_MISS_CNT_OVF_ST_M  (BIT(9))
#define EXTMEM_DBUS1_ACS_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS1_ACS_MISS_CNT_OVF_ST_S  9
/* EXTMEM_DBUS0_ACS_MISS_CNT_OVF_ST:RO；位位置：[8]；默认值：1’b0；*/
/*description:该位用于指示dbus0未命中计数器溢出导致的中断。*/
#define EXTMEM_DBUS0_ACS_MISS_CNT_OVF_ST  (BIT(8))
#define EXTMEM_DBUS0_ACS_MISS_CNT_OVF_ST_M  (BIT(8))
#define EXTMEM_DBUS0_ACS_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS0_ACS_MISS_CNT_OVF_ST_S  8
/* EXTMEM_DBUS2_ACS_CNT_ov_ST:RO；位位置：[6]；默认值：1’b0；*/
/*description:该位用于指示dbus2计数器溢出导致的中断。*/
#define EXTMEM_DBUS2_ACS_CNT_OVF_ST  (BIT(6))
#define EXTMEM_DBUS2_ACS_CNT_OVF_ST_M  (BIT(6))
#define EXTMEM_DBUS2_ACS_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS2_ACS_CNT_OVF_ST_S  6
/* EXTMEM_DBUS1_ACS_CNT_ov_ST:RO；位位置：[5]；默认值：1’b0；*/
/*description:该位用于指示dbus1计数器溢出导致的中断。*/
#define EXTMEM_DBUS1_ACS_CNT_OVF_ST  (BIT(5))
#define EXTMEM_DBUS1_ACS_CNT_OVF_ST_M  (BIT(5))
#define EXTMEM_DBUS1_ACS_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS1_ACS_CNT_OVF_ST_S  5
/* EXTMEM_DBUS0_ACS_CNT_OVF_ST:RO；位位置：[4]；默认值：1’b0；*/
/*description:该位用于指示dbus0计数器溢出导致的中断。*/
#define EXTMEM_DBUS0_ACS_CNT_OVF_ST  (BIT(4))
#define EXTMEM_DBUS0_ACS_CNT_OVF_ST_M  (BIT(4))
#define EXTMEM_DBUS0_ACS_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS0_ACS_CNT_OVF_ST_S  4
/* EXTMEM_DBUS2_ACS_MSK_dache_ST:RO；位位置：[2]；默认值：1’b0；*/
/*描述：当dbus2被禁用或dcache被禁用（包括推测访问）时，该位用于指示cpu访问dcache的中断。*/
#define EXTMEM_DBUS2_ACS_MSK_DCACHE_ST  (BIT(2))
#define EXTMEM_DBUS2_ACS_MSK_DCACHE_ST_M  (BIT(2))
#define EXTMEM_DBUS2_ACS_MSK_DCACHE_ST_V  0x1
#define EXTMEM_DBUS2_ACS_MSK_DCACHE_ST_S  2
/* EXTMEM_DBUS1_ACS_MSK_dache_ST:RO；位位置：[1]；默认值：1’b0；*/
/*描述：当dbus1被禁用或dcache被禁用（包括推测访问）时，该位用于指示cpu访问dcache的中断。*/
#define EXTMEM_DBUS1_ACS_MSK_DCACHE_ST  (BIT(1))
#define EXTMEM_DBUS1_ACS_MSK_DCACHE_ST_M  (BIT(1))
#define EXTMEM_DBUS1_ACS_MSK_DCACHE_ST_V  0x1
#define EXTMEM_DBUS1_ACS_MSK_DCACHE_ST_S  1
/* EXTMEM_DBUS0_ACS_MSK_DCACHE_ST:RO；位位置：[0]；默认值：1’b0；*/
/*描述：当dbus0被禁用或dcache被禁用（包括推测访问）时，该位用于指示cpu访问dcache的中断。*/
#define EXTMEM_DBUS0_ACS_MSK_DCACHE_ST  (BIT(0))
#define EXTMEM_DBUS0_ACS_MSK_DCACHE_ST_M  (BIT(0))
#define EXTMEM_DBUS0_ACS_MSK_DCACHE_ST_V  0x1
#define EXTMEM_DBUS0_ACS_MSK_DCACHE_ST_S  0

#define EXTMEM_PRO_CACHE_ACS_CNT_CLR_REG          (DR_REG_EXTMEM_BASE + 0x0F8)
/* EXTMEM_PRO_cache_ACS_CNT_CLR:WOD；位位置：[1]；默认值：1’b0；*/
/*description:该位用于清除icache计数器，包括IC_PRELOAD_CNT_REG IC_PRELLOAD_MISS_CNT_REG IBUS0-2_ABANDON_CNT_REG IBUS 0-2_ACS_MISS_CNT _REG和IBUS0-2-ACS_CNT _REG。*/
#define EXTMEM_PRO_ICACHE_ACS_CNT_CLR  (BIT(1))
#define EXTMEM_PRO_ICACHE_ACS_CNT_CLR_M  (BIT(1))
#define EXTMEM_PRO_ICACHE_ACS_CNT_CLR_V  0x1
#define EXTMEM_PRO_ICACHE_ACS_CNT_CLR_S  1
/* EXTMEM_PRO_DCACHE_ACS_CNT_CLR:WOD；位位置：[0]；默认值：1’b0；*/
/*description:该位用于清除dcache计数器，包括DC_PRELOAD_CNT_REG DC_PRELLOAD_EVICT_CNT_REG、DC_PRELOAD_MISS_CNT_REG DBUS0-2_ABANDON_CNT_REG DBUS 0-2_ACS_WB_CNT_REG和DBUS0-2-ACS_MISS_CNT _REG。*/
#define EXTMEM_PRO_DCACHE_ACS_CNT_CLR  (BIT(0))
#define EXTMEM_PRO_DCACHE_ACS_CNT_CLR_M  (BIT(0))
#define EXTMEM_PRO_DCACHE_ACS_CNT_CLR_V  0x1
#define EXTMEM_PRO_DCACHE_ACS_CNT_CLR_S  0

#define EXTMEM_PRO_DCACHE_REJECT_ST_REG          (DR_REG_EXTMEM_BASE + 0x0FC)
/* EXTMEM_PRO_DCACHE_CPU_ATTR:RO；比特位置：[5:3]；默认值：3'b0；*/
/*description:这些位用于指示验证失败时CPU访问dcache的属性。0：无效1：可执行2：可读取4：可写入。*/
#define EXTMEM_PRO_DCACHE_CPU_ATTR  0x00000007
#define EXTMEM_PRO_DCACHE_CPU_ATTR_M  ((EXTMEM_PRO_DCACHE_CPU_ATTR_V)<<(EXTMEM_PRO_DCACHE_CPU_ATTR_S))
#define EXTMEM_PRO_DCACHE_CPU_ATTR_V  0x7
#define EXTMEM_PRO_DCACHE_CPU_ATTR_S  3
/* EXTMEM_PRO_DCACHE_TAG_ATTR:RO；位位置：[2:0]；默认值：3'b0；*/
/*description:这些位用于指示验证失败时来自外部存储器的数据的属性。0：无效1：可执行2：可读取4：可写入。*/
#define EXTMEM_PRO_DCACHE_TAG_ATTR  0x00000007
#define EXTMEM_PRO_DCACHE_TAG_ATTR_M  ((EXTMEM_PRO_DCACHE_TAG_ATTR_V)<<(EXTMEM_PRO_DCACHE_TAG_ATTR_S))
#define EXTMEM_PRO_DCACHE_TAG_ATTR_V  0x7
#define EXTMEM_PRO_DCACHE_TAG_ATTR_S  0

#define EXTMEM_PRO_DCACHE_REJECT_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x100)
/* EXTMEM_PRO_DCACHE_CPU_VADDR:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于指示验证失败时CPU访问dcache的虚拟地址。*/
#define EXTMEM_PRO_DCACHE_CPU_VADDR  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_CPU_VADDR_M  ((EXTMEM_PRO_DCACHE_CPU_VADDR_V)<<(EXTMEM_PRO_DCACHE_CPU_VADDR_S))
#define EXTMEM_PRO_DCACHE_CPU_VADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_DCACHE_CPU_VADDR_S  0

#define EXTMEM_PRO_ICACHE_REJECT_ST_REG          (DR_REG_EXTMEM_BASE + 0x104)
/* EXTMEM_PRO_cache_CPU_ATTR:RO；比特位置：[5:3]；默认值：3'b0；*/
/*description:这些位用于指示验证失败时CPU访问icache的属性。0：无效1：可执行2：可读取*/
#define EXTMEM_PRO_ICACHE_CPU_ATTR  0x00000007
#define EXTMEM_PRO_ICACHE_CPU_ATTR_M  ((EXTMEM_PRO_ICACHE_CPU_ATTR_V)<<(EXTMEM_PRO_ICACHE_CPU_ATTR_S))
#define EXTMEM_PRO_ICACHE_CPU_ATTR_V  0x7
#define EXTMEM_PRO_ICACHE_CPU_ATTR_S  3
/* EXTMEM_PRO_cache_TAG_ATTR:RO；位位置：[2:0]；默认值：3'b0；*/
/*description:这些位用于指示验证失败时来自外部存储器的数据的属性。0：无效1：可执行2：可读取4：可写入。*/
#define EXTMEM_PRO_ICACHE_TAG_ATTR  0x00000007
#define EXTMEM_PRO_ICACHE_TAG_ATTR_M  ((EXTMEM_PRO_ICACHE_TAG_ATTR_V)<<(EXTMEM_PRO_ICACHE_TAG_ATTR_S))
#define EXTMEM_PRO_ICACHE_TAG_ATTR_V  0x7
#define EXTMEM_PRO_ICACHE_TAG_ATTR_S  0

#define EXTMEM_PRO_ICACHE_REJECT_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x108)
/* EXTMEM_PRO_cache_CPU_VADDR:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:这些位用于指示验证失败时CPU访问icache的虚拟地址。*/
#define EXTMEM_PRO_ICACHE_CPU_VADDR  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_CPU_VADDR_M  ((EXTMEM_PRO_ICACHE_CPU_VADDR_V)<<(EXTMEM_PRO_ICACHE_CPU_VADDR_S))
#define EXTMEM_PRO_ICACHE_CPU_VADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_ICACHE_CPU_VADDR_S  0

#define EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT_REG          (DR_REG_EXTMEM_BASE + 0x10C)
/* EXTMEM_PRO_CACHE_MMU_FAULT_CODE:RO；比特位置：[19:17]；默认值：3'h0；*/
/*描述：位用于指示导致mmu故障发生的操作。0:默认值1:cpu未命中2:预加载未命中3:刷新4:cpu未命中逐出恢复地址5:加载未命中逐出回收地址6:外部dma tx 7:外部dma rx*/
#define EXTMEM_PRO_CACHE_MMU_FAULT_CODE  0x00000007
#define EXTMEM_PRO_CACHE_MMU_FAULT_CODE_M  ((EXTMEM_PRO_CACHE_MMU_FAULT_CODE_V)<<(EXTMEM_PRO_CACHE_MMU_FAULT_CODE_S))
#define EXTMEM_PRO_CACHE_MMU_FAULT_CODE_V  0x7
#define EXTMEM_PRO_CACHE_MMU_FAULT_CODE_S  17
/* EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT:RO；位位置：[16:0]；默认值：17'0；*/
/*description:位用于指示导致mmu故障的mmu条目的内容。。*/
#define EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT  0x0001FFFF
#define EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT_M  ((EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT_V)<<(EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT_S))
#define EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT_V  0x1FFFF
#define EXTMEM_PRO_CACHE_MMU_FAULT_CONTENT_S  0

#define EXTMEM_PRO_CACHE_MMU_FAULT_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x110)
/* EXTMEM_PRO_CACHE_MMU_FAULT_vadr:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:位用于指示导致mmu故障的虚拟地址。。*/
#define EXTMEM_PRO_CACHE_MMU_FAULT_VADDR  0xFFFFFFFF
#define EXTMEM_PRO_CACHE_MMU_FAULT_VADDR_M  ((EXTMEM_PRO_CACHE_MMU_FAULT_VADDR_V)<<(EXTMEM_PRO_CACHE_MMU_FAULT_VADDR_S))
#define EXTMEM_PRO_CACHE_MMU_FAULT_VADDR_V  0xFFFFFFFF
#define EXTMEM_PRO_CACHE_MMU_FAULT_VADDR_S  0

#define EXTMEM_PRO_CACHE_WRAP_AROUND_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x114)
/* EXTMEM_PRO_CACHE_SRAM_RD_WRAP_AROUND:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于在从spiram读取数据时启用环绕模式。*/
#define EXTMEM_PRO_CACHE_SRAM_RD_WRAP_AROUND  (BIT(1))
#define EXTMEM_PRO_CACHE_SRAM_RD_WRAP_AROUND_M  (BIT(1))
#define EXTMEM_PRO_CACHE_SRAM_RD_WRAP_AROUND_V  0x1
#define EXTMEM_PRO_CACHE_SRAM_RD_WRAP_AROUND_S  1
/* EXTMEM_PRO_che_FLASH_WRAP_AROUND：R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于在从闪存读取数据时启用环绕模式。*/
#define EXTMEM_PRO_CACHE_FLASH_WRAP_AROUND  (BIT(0))
#define EXTMEM_PRO_CACHE_FLASH_WRAP_AROUND_M  (BIT(0))
#define EXTMEM_PRO_CACHE_FLASH_WRAP_AROUND_V  0x1
#define EXTMEM_PRO_CACHE_FLASH_WRAP_AROUND_S  0

#define EXTMEM_PRO_CACHE_MMU_POWER_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x118)
/* EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PU:R/W；位位置：[2]；默认值：1’b1；*/
/*description:该位用于关闭mmu内存0:follow_rtc_lslp_pd 1:power-up*/
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PU  (BIT(2))
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PU_M  (BIT(2))
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PU_V  0x1
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PU_S  2
/* EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PD:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于关闭mmu内存0:follow_rtc_lslp_pd 1:关闭电源*/
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PD  (BIT(1))
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PD_M  (BIT(1))
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PD_V  0x1
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_PD_S  1
/* EXTMEM_PRO_CACHE_MMU_MEM_FORCE_ON:R/W；位位置：[0]；默认值：1’b1；*/
/*描述：当访问mmu内存0：启用1：禁用时，该位用于启用时钟门控以节省电源*/
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_ON  (BIT(0))
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_ON_M  (BIT(0))
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_ON_V  0x1
#define EXTMEM_PRO_CACHE_MMU_MEM_FORCE_ON_S  0

#define EXTMEM_PRO_CACHE_STATE_REG          (DR_REG_EXTMEM_BASE + 0x11C)
/* EXTMEM_PRO_DCACHE_STATE:RO；比特位置：[23:12]；默认值：12'0；*/
/*description:该位用于指示dcache主fsm是否处于空闲状态。1： 处于空闲状态0：不处于空闲状态*/
#define EXTMEM_PRO_DCACHE_STATE  0x00000FFF
#define EXTMEM_PRO_DCACHE_STATE_M  ((EXTMEM_PRO_DCACHE_STATE_V)<<(EXTMEM_PRO_DCACHE_STATE_S))
#define EXTMEM_PRO_DCACHE_STATE_V  0xFFF
#define EXTMEM_PRO_DCACHE_STATE_S  12
/* EXTMEM_PRO_cache_STATE:RO；位位置：[11:0]；默认值：12'0；*/
/*description:该位用于指示icache主fsm是否处于空闲状态。1： 处于空闲状态0：不处于空闲状态*/
#define EXTMEM_PRO_ICACHE_STATE  0x00000FFF
#define EXTMEM_PRO_ICACHE_STATE_M  ((EXTMEM_PRO_ICACHE_STATE_V)<<(EXTMEM_PRO_ICACHE_STATE_S))
#define EXTMEM_PRO_ICACHE_STATE_V  0xFFF
#define EXTMEM_PRO_ICACHE_STATE_S  0

#define EXTMEM_CACHE_ENCRYPT_DECRYPT_RECORD_DISABLE_REG          (DR_REG_EXTMEM_BASE + 0x120)
/* EXTMEM_RECORD_isable_G0CB_DECRYPT:R/W；位位置：[1]；默认值：1’b0；*/
/*description:保留。*/
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT  (BIT(1))
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT_M  (BIT(1))
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT_V  0x1
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT_S  1
/* EXTMEM_RECORD_isable_DB_ENCRYPT:R/W；位位置：[0]；默认值：1’b0；*/
/*description:保留。*/
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT  (BIT(0))
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT_M  (BIT(0))
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT_V  0x1
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT_S  0

#define EXTMEM_CACHE_ENCRYPT_DECRYPT_CLK_FORCE_ON_REG          (DR_REG_EXTMEM_BASE + 0x124)
/* EXTMEM_CLK_FORCE_ON_AUTOMATIC_ENCRYPT_DECRYPT:R/W；位位置：[2]；默认值：1’b1；*/
/*描述：该位用于关闭加密和解密时钟的时钟门控。1： 关闭门控0：打开时钟门控。*/
#define EXTMEM_CLK_FORCE_ON_AUTOMATIC_ENCRYPT_DECRYPT  (BIT(2))
#define EXTMEM_CLK_FORCE_ON_AUTOMATIC_ENCRYPT_DECRYPT_M  (BIT(2))
#define EXTMEM_CLK_FORCE_ON_AUTOMATIC_ENCRYPT_DECRYPT_V  0x1
#define EXTMEM_CLK_FORCE_ON_AUTOMATIC_ENCRYPT_DECRYPT_S  2
/* EXTMEM_CLK_FORCE_ON_G0CB_DECRYPT:R/W；位位置：[1]；默认值：1’b1；*/
/*description:该位用于关闭解密时钟的时钟门控。1： 关闭门控0：打开时钟门控。*/
#define EXTMEM_CLK_FORCE_ON_G0CB_DECRYPT  (BIT(1))
#define EXTMEM_CLK_FORCE_ON_G0CB_DECRYPT_M  (BIT(1))
#define EXTMEM_CLK_FORCE_ON_G0CB_DECRYPT_V  0x1
#define EXTMEM_CLK_FORCE_ON_G0CB_DECRYPT_S  1
/* EXTMEM_CLK_FORCE_ON_DB_ENCRYPT:R/W；位位置：[0]；默认值：1’b1；*/
/*description:该位用于关闭加密时钟的时钟门控。1： 关闭门控0：打开时钟门控。*/
#define EXTMEM_CLK_FORCE_ON_DB_ENCRYPT  (BIT(0))
#define EXTMEM_CLK_FORCE_ON_DB_ENCRYPT_M  (BIT(0))
#define EXTMEM_CLK_FORCE_ON_DB_ENCRYPT_V  0x1
#define EXTMEM_CLK_FORCE_ON_DB_ENCRYPT_S  0

#define EXTMEM_CACHE_BRIDGE_ARBITER_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x128)
/* EXTMEM_ALLOC_WB_HOLD_ARBITER:R/W；位位置：[0]；默认值：1’b0；*/
/*description:保留。*/
#define EXTMEM_ALLOC_WB_HOLD_ARBITER  (BIT(0))
#define EXTMEM_ALLOC_WB_HOLD_ARBITER_M  (BIT(0))
#define EXTMEM_ALLOC_WB_HOLD_ARBITER_V  0x1
#define EXTMEM_ALLOC_WB_HOLD_ARBITER_S  0

#define EXTMEM_CACHE_PRELOAD_INT_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x12C)
/* EXTMEM_PRO_DCACHE_proad_INT_CLR:WOD；位位置：[5]；默认值：1’b0；*/
/*description:该位用于通过dcache预加载完成来清除中断。*/
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_CLR  (BIT(5))
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_CLR_M  (BIT(5))
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_CLR_V  0x1
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_CLR_S  5
/* EXTMEM_PRO_DCACHE_proad_INT_ENA:R/W；位位置：[4]；默认值：1’b0；*/
/*description:该位用于通过dcache预加载完成启用中断。*/
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ENA  (BIT(4))
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ENA_M  (BIT(4))
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ENA_S  4
/* EXTMEM_PRO_DCACHE_proad_INT_ST:RO；位位置：[3]；默认值：1’b0；*/
/*description:该位用于指示dcache预加载完成的中断。*/
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ST  (BIT(3))
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ST_M  (BIT(3))
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ST_V  0x1
#define EXTMEM_PRO_DCACHE_PRELOAD_INT_ST_S  3
/* EXTMEM_PRO_cache_proad_INT_CLR:WOD；位位置：[2]；默认值：1’b0；*/
/*description:该位用于通过icache预加载完成来清除中断。*/
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_CLR  (BIT(2))
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_CLR_M  (BIT(2))
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_CLR_V  0x1
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_CLR_S  2
/* EXTMEM_PRO_cache_proad_INT_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于通过icache预加载完成启用中断。*/
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ENA  (BIT(1))
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ENA_M  (BIT(1))
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ENA_V  0x1
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ENA_S  1
/* EXTMEM_PRO_cache_proad_INT_ST:RO；位位置：[0]；默认值：1’b0；*/
/*description:该位用于指示icache预加载完成的中断。*/
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ST  (BIT(0))
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ST_M  (BIT(0))
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ST_V  0x1
#define EXTMEM_PRO_ICACHE_PRELOAD_INT_ST_S  0

#define EXTMEM_CACHE_SYNC_INT_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x130)
/* EXTMEM_PRO_DCACHE_SYNC_INT_CLR:WOD；位位置：[5]；默认值：1’b0；*/
/*description:该位用于通过dcache同步完成来清除中断。*/
#define EXTMEM_PRO_DCACHE_SYNC_INT_CLR  (BIT(5))
#define EXTMEM_PRO_DCACHE_SYNC_INT_CLR_M  (BIT(5))
#define EXTMEM_PRO_DCACHE_SYNC_INT_CLR_V  0x1
#define EXTMEM_PRO_DCACHE_SYNC_INT_CLR_S  5
/* EXTMEM_PRO_DCACHE_SYNC_INT_ENA:R/W；位位置：[4]；默认值：1’b0；*/
/*description:该位用于通过dcache sync done启用中断。*/
#define EXTMEM_PRO_DCACHE_SYNC_INT_ENA  (BIT(4))
#define EXTMEM_PRO_DCACHE_SYNC_INT_ENA_M  (BIT(4))
#define EXTMEM_PRO_DCACHE_SYNC_INT_ENA_V  0x1
#define EXTMEM_PRO_DCACHE_SYNC_INT_ENA_S  4
/* EXTMEM_PRO_DCACHE_SYNC_INT_ST:RO；位位置：[3]；默认值：1’b0；*/
/*description:该位用于指示dcache sync完成的中断。*/
#define EXTMEM_PRO_DCACHE_SYNC_INT_ST  (BIT(3))
#define EXTMEM_PRO_DCACHE_SYNC_INT_ST_M  (BIT(3))
#define EXTMEM_PRO_DCACHE_SYNC_INT_ST_V  0x1
#define EXTMEM_PRO_DCACHE_SYNC_INT_ST_S  3
/* EXTMEM_PRO_cache_SYNC_INT_CLR:WOD；位位置：[2]；默认值：1’b0；*/
/*description:该位用于通过完成icache同步来清除中断。*/
#define EXTMEM_PRO_ICACHE_SYNC_INT_CLR  (BIT(2))
#define EXTMEM_PRO_ICACHE_SYNC_INT_CLR_M  (BIT(2))
#define EXTMEM_PRO_ICACHE_SYNC_INT_CLR_V  0x1
#define EXTMEM_PRO_ICACHE_SYNC_INT_CLR_S  2
/* EXTMEM_PRO_cache_SYNC_INT_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于通过icache sync done启用中断。*/
#define EXTMEM_PRO_ICACHE_SYNC_INT_ENA  (BIT(1))
#define EXTMEM_PRO_ICACHE_SYNC_INT_ENA_M  (BIT(1))
#define EXTMEM_PRO_ICACHE_SYNC_INT_ENA_V  0x1
#define EXTMEM_PRO_ICACHE_SYNC_INT_ENA_S  1
/* EXTMEM_PRO_cache_SYNC_INT_ST:RO；位位置：[0]；默认值：1’b0；*/
/*description:该位用于指示icache sync完成的中断。*/
#define EXTMEM_PRO_ICACHE_SYNC_INT_ST  (BIT(0))
#define EXTMEM_PRO_ICACHE_SYNC_INT_ST_M  (BIT(0))
#define EXTMEM_PRO_ICACHE_SYNC_INT_ST_V  0x1
#define EXTMEM_PRO_ICACHE_SYNC_INT_ST_S  0

#define EXTMEM_CACHE_CONF_MISC_REG          (DR_REG_EXTMEM_BASE + 0x134)
/* EXTMEM_procache_IGNORE_SYNC_MMU_ENTRY_FAULT:R/W；位位置：[1]；默认值：1’b1；*/
/*description:该位用于通过同步操作禁用检查mmu条目错误。*/
#define EXTMEM_PRO_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT  (BIT(1))
#define EXTMEM_PRO_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT_M  (BIT(1))
#define EXTMEM_PRO_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT_V  0x1
#define EXTMEM_PRO_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT_S  1
/* EXTMEM_procache_IGNORE_proad_MMU_ENTRY_FAULT:R/W；位位置：[0]；默认值：1’b1；*/
/*描述：该位用于通过预加载操作禁用检查mmu条目故障。*/
#define EXTMEM_PRO_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT  (BIT(0))
#define EXTMEM_PRO_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT_M  (BIT(0))
#define EXTMEM_PRO_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT_V  0x1
#define EXTMEM_PRO_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT_S  0

#define EXTMEM_CLOCK_GATE_REG          (DR_REG_EXTMEM_BASE + 0x138)
/* EXTMEM_CLK_EN:R/W；位位置：[0]；默认值：1’b1；*/
/*description:保留。*/
#define EXTMEM_CLK_EN  (BIT(0))
#define EXTMEM_CLK_EN_M  (BIT(0))
#define EXTMEM_CLK_EN_V  0x1
#define EXTMEM_CLK_EN_S  0

#define EXTMEM_DATE_REG          (DR_REG_EXTMEM_BASE + 0x3FC)
/* EXTMEM_DATE:R/W；位位置：[27:0]；默认值：28'h1904180；*/
/*description:保留。*/
#define EXTMEM_DATE  0x0FFFFFFF
#define EXTMEM_DATE_M  ((EXTMEM_DATE_V)<<(EXTMEM_DATE_S))
#define EXTMEM_DATE_V  0xFFFFFFF
#define EXTMEM_DATE_S  0

#ifdef __cplusplus
}
#endif



#endif /*_SOC_EXTMEM_REG_H_ */

