/**
 *  SPDX文件版权文本：2021浓缩咖啡系统（上海）有限公司
 *
 *  SPDX许可证标识符：Apache-2.0
 */
#pragma once

#include <stdint.h>
#include "soc/soc.h"
#ifdef __cplusplus
extern "C" {
#endif

#define DR_REG_TIMG_BASE(i) REG_TIMG_BASE(i)

/* 需要写入TIMG_WDT_WKEY以启用WDT寄存器的值*/
#define TIMG_WDT_WKEY_VALUE 0x50D83AA1

/* TIMG_WDT_STGx的可能值*/
#define TIMG_WDT_STG_SEL_OFF 0
#define TIMG_WDT_STG_SEL_INT 1
#define TIMG_WDT_STG_SEL_RESET_CPU 2
#define TIMG_WDT_STG_SEL_RESET_SYSTEM 3

/* TIMG_WDT_CPU_RESET_LENGTH和TIMG_WDT_SYS_RESET_LENGTH的可能值*/
#define TIMG_WDT_RESET_LENGTH_100_NS    0
#define TIMG_WDT_RESET_LENGTH_200_NS    1
#define TIMG_WDT_RESET_LENGTH_300_NS    2
#define TIMG_WDT_RESET_LENGTH_400_NS    3
#define TIMG_WDT_RESET_LENGTH_500_NS    4
#define TIMG_WDT_RESET_LENGTH_800_NS    5
#define TIMG_WDT_RESET_LENGTH_1600_NS   6
#define TIMG_WDT_RESET_LENGTH_3200_NS   7

/** TIMG_T0CONFIG_REG寄存器定时器0配置寄存器
 */
#define TIMG_T0CONFIG_REG(i) (DR_REG_TIMG_BASE(i) + 0x0)
/** TIMG_T0_USE_XTAL:R/W；位位置：[9]；默认值：0；1： 使用XTAL_CLK作为定时器组的源时钟。0：使用APB_CLK作为定时器组的源时钟。
 */
#define TIMG_T0_USE_XTAL    (BIT(9))
#define TIMG_T0_USE_XTAL_M  (TIMG_T0_USE_XTAL_V << TIMG_T0_USE_XTAL_S)
#define TIMG_T0_USE_XTAL_V  0x00000001U
#define TIMG_T0_USE_XTAL_S  9
/** TIMG_T0_ALARM_EN:R/W；位位置：[10]；默认值：0；设置后，警报启用。一旦
 *
 *  发生报警。
 */
#define TIMG_T0_ALARM_EN    (BIT(10))
#define TIMG_T0_ALARM_EN_M  (TIMG_T0_ALARM_EN_V << TIMG_T0_ALARM_EN_S)
#define TIMG_T0_ALARM_EN_V  0x00000001U
#define TIMG_T0_ALARM_EN_S  10
/** TIMG_T0_LEVEL_INT_EN:R/W；位位置：[11]；默认值：0；设置后，警报将生成电平类型的中断。
 */
#define TIMG_T0_LEVEL_INT_EN    (BIT(11))
#define TIMG_T0_LEVEL_INT_EN_M  (TIMG_T0_LEVEL_INT_EN_V << TIMG_T0_LEVEL_INT_EN_S)
#define TIMG_T0_LEVEL_INT_EN_V  0x00000001U
#define TIMG_T0_LEVEL_INT_EN_S  11
/** TIMG_T0_EDGE_INT_EN:R/W；位位置：[12]；默认值：0；设置后，警报将生成边缘型中断。
 */
#define TIMG_T0_EDGE_INT_EN    (BIT(12))
#define TIMG_T0_EDGE_INT_EN_M  (TIMG_T0_EDGE_INT_EN_V << TIMG_T0_EDGE_INT_EN_S)
#define TIMG_T0_EDGE_INT_EN_V  0x00000001U
#define TIMG_T0_EDGE_INT_EN_S  12
/** TIMG_T0_DIVIDER:R/W；比特位置：[28:13]；默认值：1；计时器0时钟（T0_clk）预分频器值。
 */
#define TIMG_T0_DIVIDER    0x0000FFFFU
#define TIMG_T0_DIVIDER_M  (TIMG_T0_DIVIDER_V << TIMG_T0_DIVIDER_S)
#define TIMG_T0_DIVIDER_V  0x0000FFFFU
#define TIMG_T0_DIVIDER_S  13
/** TIMG_T0_AUTORELOAD:R/W；位位置：[29]；默认值：1；设置后，计时器0在报警时自动重新加载。
 */
#define TIMG_T0_AUTORELOAD    (BIT(29))
#define TIMG_T0_AUTORELOAD_M  (TIMG_T0_AUTORELOAD_V << TIMG_T0_AUTORELOAD_S)
#define TIMG_T0_AUTORELOAD_V  0x00000001U
#define TIMG_T0_AUTORELOAD_S  29
/** TIMG_T0_增加：R/W；位位置：[30]；默认值：1；设置后，计时器0时基计数器将在每个时钟周期递增。什么时候
 *
 *  清除，计时器0时基计数器将递减。
 */
#define TIMG_T0_INCREASE    (BIT(30))
#define TIMG_T0_INCREASE_M  (TIMG_T0_INCREASE_V << TIMG_T0_INCREASE_S)
#define TIMG_T0_INCREASE_V  0x00000001U
#define TIMG_T0_INCREASE_S  30
/** TIMG_T0_EN:R/W；位位置：[31]；默认值：0；设置后，启用计时器0时基计数器。
 */
#define TIMG_T0_EN    (BIT(31))
#define TIMG_T0_EN_M  (TIMG_T0_EN_V << TIMG_T0_EN_S)
#define TIMG_T0_EN_V  0x00000001U
#define TIMG_T0_EN_S  31

/** TIMG_T0LO_REG寄存器定时器0当前值，低32位
 */
#define TIMG_T0LO_REG(i) (DR_REG_TIMG_BASE(i) + 0x4)
/** TIMG_T0_LO:RO；位位置：[31:0]；默认值：0；写入TIMG_T0UPDATE_REG后，时基计数器的低32位
 *
 *  可以在此处读取计时器0的。
 */
#define TIMG_T0_LO    0xFFFFFFFFU
#define TIMG_T0_LO_M  (TIMG_T0_LO_V << TIMG_T0_LO_S)
#define TIMG_T0_LO_V  0xFFFFFFFFU
#define TIMG_T0_LO_S  0

/** TIMG_T0HI_REG寄存器定时器0当前值，高32位
 */
#define TIMG_T0HI_REG(i) (DR_REG_TIMG_BASE(i) + 0x8)
/** TIMG_T0_HI:RO；位位置：[31:0]；默认值：0；写入TIMG_T0UPDATE_REG后，时基计数器的高32位
 *
 *  可以在此处读取计时器0的。
 */
#define TIMG_T0_HI    0xFFFFFFFFU
#define TIMG_T0_HI_M  (TIMG_T0_HI_V << TIMG_T0_HI_S)
#define TIMG_T0_HI_V  0xFFFFFFFFU
#define TIMG_T0_HI_S  0

/** TIMG_T0UPDATE_REG寄存器写入以将当前计时器值复制到TIMGn_T0_（LO/HI）_REG
 */
#define TIMG_T0UPDATE_REG(i) (DR_REG_TIMG_BASE(i) + 0xc)
/** TIMG_T0_UPDATE:R/W；位位置：[31]；默认值：0；在将0或1写入TIMG_T0UPDATE_REG后，计数器值被锁存。
 */
#define TIMG_T0_UPDATE    (BIT(31))
#define TIMG_T0_UPDATE_M  (TIMG_T0_UPDATE_V << TIMG_T0_UPDATE_S)
#define TIMG_T0_UPDATE_V  0x00000001U
#define TIMG_T0_UPDATE_S  31

/** TIMG_T0ALARMLO_REG寄存器定时器0报警值，低32位
 */
#define TIMG_T0ALARMLO_REG(i) (DR_REG_TIMG_BASE(i) + 0x10)
/** TIMG_T0_ALARM_LO:R/W；位位置：[31:0]；默认值：0；定时器0报警触发时基计数器值，低32位。
 */
#define TIMG_T0_ALARM_LO    0xFFFFFFFFU
#define TIMG_T0_ALARM_LO_M  (TIMG_T0_ALARM_LO_V << TIMG_T0_ALARM_LO_S)
#define TIMG_T0_ALARM_LO_V  0xFFFFFFFFU
#define TIMG_T0_ALARM_LO_S  0

/** TIMG_T0ALARMHI_REG寄存器定时器0报警值，高位
 */
#define TIMG_T0ALARMHI_REG(i) (DR_REG_TIMG_BASE(i) + 0x14)
/** TIMG_T0_ALARM_HI:R/W；位位置：[31:0]；默认值：0；
 *
 * 计时器0报警触发时基计数器值，高32位。
 */
#define TIMG_T0_ALARM_HI    0xFFFFFFFFU
#define TIMG_T0_ALARM_HI_M  (TIMG_T0_ALARM_HI_V << TIMG_T0_ALARM_HI_S)
#define TIMG_T0_ALARM_HI_V  0xFFFFFFFFU
#define TIMG_T0_ALARM_HI_S  0

/** TIMG_T0LOADLO_REG寄存器定时器0重新加载值，低32位
 */
#define TIMG_T0LOADLO_REG(i) (DR_REG_TIMG_BASE(i) + 0x18)
/** TIMG_T0_LOAD_LO:R/W；位位置：[31:0]；默认值：0；
 *
 * 重新加载将加载到计时器0时基上的值的低32位
 *
 *  柜台
 */
#define TIMG_T0_LOAD_LO    0xFFFFFFFFU
#define TIMG_T0_LOAD_LO_M  (TIMG_T0_LOAD_LO_V << TIMG_T0_LOAD_LO_S)
#define TIMG_T0_LOAD_LO_V  0xFFFFFFFFU
#define TIMG_T0_LOAD_LO_S  0

/** TIMG_T0LOADHI_REG寄存器定时器0重新加载值，高32位
 */
#define TIMG_T0LOADHI_REG(i) (DR_REG_TIMG_BASE(i) + 0x1c)
/** TIMG_T0_LOAD_HI:R/W；位位置：[31:0]；默认值：0；
 *
 * 重载将加载到计时器0时基上的值的高32位
 *
 *  柜台
 */
#define TIMG_T0_LOAD_HI    0xFFFFFFFFU
#define TIMG_T0_LOAD_HI_M  (TIMG_T0_LOAD_HI_V << TIMG_T0_LOAD_HI_S)
#define TIMG_T0_LOAD_HI_V  0xFFFFFFFFU
#define TIMG_T0_LOAD_HI_S  0

/** TIMG_T0LOAD_REG寄存器从TIMG_T0_（LOADLOLOADHI）_REG写入重新加载计时器
 */
#define TIMG_T0LOAD_REG(i) (DR_REG_TIMG_BASE(i) + 0x20)
/** TIMG_T0_LOAD:WO；位位置：[31:0]；默认值：0；
 *
 * 写入任何值以触发计时器0时基计数器重新加载。
 */
#define TIMG_T0_LOAD    0xFFFFFFFFU
#define TIMG_T0_LOAD_M  (TIMG_T0_LOAD_V << TIMG_T0_LOAD_S)
#define TIMG_T0_LOAD_V  0xFFFFFFFFU
#define TIMG_T0_LOAD_S  0

/** TIMG_T1CONFIG_REG寄存器定时器1配置寄存器
 */
#define TIMG_T1CONFIG_REG(i) (DR_REG_TIMG_BASE(i) + 0x24)
/** TIMG_T0_USE_XTAL:R/W；位位置：[9]；默认值：0；1： 使用XTAL_CLK作为定时器组的源时钟。0：使用APB_CLK作为定时器组的源时钟。
 */
#define TIMG_T0_USE_XTAL    (BIT(9))
#define TIMG_T0_USE_XTAL_M  (TIMG_T0_USE_XTAL_V << TIMG_T0_USE_XTAL_S)
#define TIMG_T0_USE_XTAL_V  0x00000001U
#define TIMG_T0_USE_XTAL_S  9
/** TIMG_T0_ALARM_EN:R/W；位位置：[10]；默认值：0；设置后，警报启用。一旦
 *
 *  发生报警。
 */
#define TIMG_T0_ALARM_EN    (BIT(10))
#define TIMG_T0_ALARM_EN_M  (TIMG_T0_ALARM_EN_V << TIMG_T0_ALARM_EN_S)
#define TIMG_T0_ALARM_EN_V  0x00000001U
#define TIMG_T0_ALARM_EN_S  10
/** TIMG_T0_LEVEL_INT_EN:R/W；位位置：[11]；默认值：0；设置后，警报将生成电平类型的中断。
 */
#define TIMG_T0_LEVEL_INT_EN    (BIT(11))
#define TIMG_T0_LEVEL_INT_EN_M  (TIMG_T0_LEVEL_INT_EN_V << TIMG_T0_LEVEL_INT_EN_S)
#define TIMG_T0_LEVEL_INT_EN_V  0x00000001U
#define TIMG_T0_LEVEL_INT_EN_S  11
/** TIMG_T0_EDGE_INT_EN:R/W；位位置：[12]；默认值：0；设置后，警报将生成边缘型中断。
 */
#define TIMG_T0_EDGE_INT_EN    (BIT(12))
#define TIMG_T0_EDGE_INT_EN_M  (TIMG_T0_EDGE_INT_EN_V << TIMG_T0_EDGE_INT_EN_S)
#define TIMG_T0_EDGE_INT_EN_V  0x00000001U
#define TIMG_T0_EDGE_INT_EN_S  12
/** TIMG_T0_DIVIDER:R/W；比特位置：[28:13]；默认值：1；计时器1时钟（T1_clk）预分频器值。
 */
#define TIMG_T0_DIVIDER    0x0000FFFFU
#define TIMG_T0_DIVIDER_M  (TIMG_T0_DIVIDER_V << TIMG_T0_DIVIDER_S)
#define TIMG_T0_DIVIDER_V  0x0000FFFFU
#define TIMG_T0_DIVIDER_S  13
/** TIMG_T0_AUTORELOAD:R/W；位位置：[29]；默认值：1；设置后，计时器1在报警时自动重新加载。
 */
#define TIMG_T0_AUTORELOAD    (BIT(29))
#define TIMG_T0_AUTORELOAD_M  (TIMG_T0_AUTORELOAD_V << TIMG_T0_AUTORELOAD_S)
#define TIMG_T0_AUTORELOAD_V  0x00000001U
#define TIMG_T0_AUTORELOAD_S  29
/** TIMG_T0_增加：R/W；位位置：[30]；默认值：1；设置后，计时器1时基计数器将在每个时钟周期递增。什么时候
 *
 *  清除，计时器1时基计数器将递减。
 */
#define TIMG_T0_INCREASE    (BIT(30))
#define TIMG_T0_INCREASE_M  (TIMG_T0_INCREASE_V << TIMG_T0_INCREASE_S)
#define TIMG_T0_INCREASE_V  0x00000001U
#define TIMG_T0_INCREASE_S  30
/** TIMG_T0_EN:R/W；位位置：[31]；默认值：0；设置后，启用计时器1时基计数器。
 */
#define TIMG_T0_EN    (BIT(31))
#define TIMG_T0_EN_M  (TIMG_T0_EN_V << TIMG_T0_EN_S)
#define TIMG_T0_EN_V  0x00000001U
#define TIMG_T0_EN_S  31

/** TIMG_T1LO_REG寄存器定时器1当前值，低32位
 */
#define TIMG_T1LO_REG(i) (DR_REG_TIMG_BASE(i) + 0x28)
/** TIMG_T0_LO:RO；位位置：[31:0]；默认值：0；写入TIMG_T1UPDATE_REG后，时基计数器的低32位
 *
 *  这里可以读取计时器1的值。
 */
#define TIMG_T0_LO    0xFFFFFFFFU
#define TIMG_T0_LO_M  (TIMG_T0_LO_V << TIMG_T0_LO_S)
#define TIMG_T0_LO_V  0xFFFFFFFFU
#define TIMG_T0_LO_S  0

/** TIMG_T1HI_REG寄存器定时器1电流值，高32位
 */
#define TIMG_T1HI_REG(i) (DR_REG_TIMG_BASE(i) + 0x2c)
/** TIMG_T0_HI:RO；位位置：[31:0]；默认值：0；写入TIMG_T1UPDATE_REG后，时基计数器的高32位
 *
 *  这里可以读取计时器1的值。
 */
#define TIMG_T0_HI    0xFFFFFFFFU
#define TIMG_T0_HI_M  (TIMG_T0_HI_V << TIMG_T0_HI_S)
#define TIMG_T0_HI_V  0xFFFFFFFFU
#define TIMG_T0_HI_S  0

/** TIMG_T1UPDATE_REG寄存器写入以将当前计时器值复制到TIMGn_T1_（LO/HI）_REG
 */
#define TIMG_T1UPDATE_REG(i) (DR_REG_TIMG_BASE(i) + 0x30)
/** TIMG_T0_UPDATE:R/W；位位置：[31]；默认值：0；在将0或1写入TIMG_T1UPDATE_REG后，锁存计数器值。
 */
#define TIMG_T0_UPDATE    (BIT(31))
#define TIMG_T0_UPDATE_M  (TIMG_T0_UPDATE_V << TIMG_T0_UPDATE_S)
#define TIMG_T0_UPDATE_V  0x00000001U
#define TIMG_T0_UPDATE_S  31

/** TIMG_T1ALARMLO_REG寄存器定时器1报警值，低32位
 */
#define TIMG_T1ALARMLO_REG(i) (DR_REG_TIMG_BASE(i) + 0x34)
/** TIMG_T0_ALARM_LO:R/W；位位置：[31:0]；默认值：0；计时器1报警触发时基计数器值，低32位。
 */
#define TIMG_T0_ALARM_LO    0xFFFFFFFFU
#define TIMG_T0_ALARM_LO_M  (TIMG_T0_ALARM_LO_V << TIMG_T0_ALARM_LO_S)
#define TIMG_T0_ALARM_LO_V  0xFFFFFFFFU
#define TIMG_T0_ALARM_LO_S  0

/** TIMG_T1ALARMHI_REG寄存器定时器1报警值，高位
 */
#define TIMG_T1ALARMHI_REG(i) (DR_REG_TIMG_BASE(i) + 0x38)
/** TIMG_T0_ALARM_HI:R/W；位位置：[31:0]；默认值：0；
 *
 * 计时器1报警触发时基计数器值，高32位。
 */
#define TIMG_T0_ALARM_HI    0xFFFFFFFFU
#define TIMG_T0_ALARM_HI_M  (TIMG_T0_ALARM_HI_V << TIMG_T0_ALARM_HI_S)
#define TIMG_T0_ALARM_HI_V  0xFFFFFFFFU
#define TIMG_T0_ALARM_HI_S  0

/** TIMG_T1LOADLO_REG寄存器定时器1重新加载值，低32位
 */
#define TIMG_T1LOADLO_REG(i) (DR_REG_TIMG_BASE(i) + 0x3c)
/** TIMG_T0_LOAD_LO:R/W；位位置：[31:0]；默认值：0；
 *
 * 重新加载将加载到计时器1时基上的值的低32位
 *
 *  柜台
 */
#define TIMG_T0_LOAD_LO    0xFFFFFFFFU
#define TIMG_T0_LOAD_LO_M  (TIMG_T0_LOAD_LO_V << TIMG_T0_LOAD_LO_S)
#define TIMG_T0_LOAD_LO_V  0xFFFFFFFFU
#define TIMG_T0_LOAD_LO_S  0

/** TIMG_T1LOADHI_REG寄存器定时器1重新加载值，高32位
 */
#define TIMG_T1LOADHI_REG(i) (DR_REG_TIMG_BASE(i) + 0x40)
/** TIMG_T0_LOAD_HI:R/W；位位置：[31:0]；默认值：0；
 *
 * 重载将加载到计时器1时基上的值的高32位
 *
 *  柜台
 */
#define TIMG_T0_LOAD_HI    0xFFFFFFFFU
#define TIMG_T0_LOAD_HI_M  (TIMG_T0_LOAD_HI_V << TIMG_T0_LOAD_HI_S)
#define TIMG_T0_LOAD_HI_V  0xFFFFFFFFU
#define TIMG_T0_LOAD_HI_S  0

/** TIMG_T1LOAD_REG寄存器从TIMG_T0_（LOADLOLOADHI）_REG写入重新加载计时器
 */
#define TIMG_T1LOAD_REG(i) (DR_REG_TIMG_BASE(i) + 0x44)
/** TIMG_T0_LOAD:WO；位位置：[31:0]；默认值：0；
 *
 * 写入任何值以触发计时器1时基计数器重新加载。
 */
#define TIMG_T0_LOAD    0xFFFFFFFFU
#define TIMG_T0_LOAD_M  (TIMG_T0_LOAD_V << TIMG_T0_LOAD_S)
#define TIMG_T0_LOAD_V  0xFFFFFFFFU
#define TIMG_T0_LOAD_S  0

/** TIMG_WDTCONFIG0_REG寄存器看门狗定时器配置寄存器
 */
#define TIMG_WDTCONFIG0_REG(i) (DR_REG_TIMG_BASE(i) + 0x48)
/** TIMG_WDT_APPCPU_RESET_EN:R/W；位位置：[12]；默认值：0；保留
 */
#define TIMG_WDT_APPCPU_RESET_EN    (BIT(12))
#define TIMG_WDT_APPCPU_RESET_EN_M  (TIMG_WDT_APPCPU_RESET_EN_V << TIMG_WDT_APPCPU_RESET_EN_S)
#define TIMG_WDT_APPCPU_RESET_EN_V  0x00000001U
#define TIMG_WDT_APPCPU_RESET_EN_S  12
/** TIMG_WDT_PROCPU_RESET_EN:R/W；位位置：[13]；默认值：0；WDT重置CPU启用。
 */
#define TIMG_WDT_PROCPU_RESET_EN    (BIT(13))
#define TIMG_WDT_PROCPU_RESET_EN_M  (TIMG_WDT_PROCPU_RESET_EN_V << TIMG_WDT_PROCPU_RESET_EN_S)
#define TIMG_WDT_PROCPU_RESET_EN_V  0x00000001U
#define TIMG_WDT_PROCPU_RESET_EN_S  13
/** TIMG_WDT_FLASHBOOT_MOD_EN:R/W；位位置：[14]；默认值：1；设置后，将启用闪存启动保护。
 */
#define TIMG_WDT_FLASHBOOT_MOD_EN    (BIT(14))
#define TIMG_WDT_FLASHBOOT_MOD_EN_M  (TIMG_WDT_FLASHBOOT_MOD_EN_V << TIMG_WDT_FLASHBOOT_MOD_EN_S)
#define TIMG_WDT_FLASHBOOT_MOD_EN_V  0x00000001U
#define TIMG_WDT_FLASHBOOT_MOD_EN_S  14
/** TIMG_WDT_SYS_RESET_LENGTH:R/W；比特位置：[17:15]；默认值：1；系统复位信号长度选择。0：100纳秒、1：200纳秒，
 *
 *  2： 300纳秒，3:400纳秒，4:500纳秒，5:800纳秒，6:1.6微秒，7:3.2微秒。
 */
#define TIMG_WDT_SYS_RESET_LENGTH    0x00000007U
#define TIMG_WDT_SYS_RESET_LENGTH_M  (TIMG_WDT_SYS_RESET_LENGTH_V << TIMG_WDT_SYS_RESET_LENGTH_S)
#define TIMG_WDT_SYS_RESET_LENGTH_V  0x00000007U
#define TIMG_WDT_SYS_RESET_LENGTH_S  15
/** TIMG_WDT_CPU_RESET_LENGTH:R/W；比特位置：[20:18]；默认值：1；CPU复位信号长度选择。0：100纳秒、1：200纳秒，
 *
 *  2： 300纳秒，3:400纳秒，4:500纳秒，5:800纳秒，6:1.6微秒，7:3.2微秒。
 */
#define TIMG_WDT_CPU_RESET_LENGTH    0x00000007U
#define TIMG_WDT_CPU_RESET_LENGTH_M  (TIMG_WDT_CPU_RESET_LENGTH_V << TIMG_WDT_CPU_RESET_LENGTH_S)
#define TIMG_WDT_CPU_RESET_LENGTH_V  0x00000007U
#define TIMG_WDT_CPU_RESET_LENGTH_S  18
/** TIMG_WDT_LEVEL_INT_EN:R/W；位位置：[21]；默认值：0；设置后，在阶段超时时将发生级别类型中断
 *
 *  被配置为生成中断。
 */
#define TIMG_WDT_LEVEL_INT_EN    (BIT(21))
#define TIMG_WDT_LEVEL_INT_EN_M  (TIMG_WDT_LEVEL_INT_EN_V << TIMG_WDT_LEVEL_INT_EN_S)
#define TIMG_WDT_LEVEL_INT_EN_V  0x00000001U
#define TIMG_WDT_LEVEL_INT_EN_S  21
/** TIMG_WDT_EDGE_INT_EN:R/W；位位置：[22]；默认值：0；设置后，边缘类型中断将在阶段超时时发生
 *
 *  被配置为生成中断。
 */
#define TIMG_WDT_EDGE_INT_EN    (BIT(22))
#define TIMG_WDT_EDGE_INT_EN_M  (TIMG_WDT_EDGE_INT_EN_V << TIMG_WDT_EDGE_INT_EN_S)
#define TIMG_WDT_EDGE_INT_EN_V  0x00000001U
#define TIMG_WDT_EDGE_INT_EN_S  22
/** TIMG_WDT_STG3:R/W；位位置：[24:23]；默认值：0；第3阶段配置。0：关闭，1：中断，2：重置CPU，3：重置系统。
 *
 */
#define TIMG_WDT_STG3    0x00000003U
#define TIMG_WDT_STG3_M  (TIMG_WDT_STG3_V << TIMG_WDT_STG3_S)
#define TIMG_WDT_STG3_V  0x00000003U
#define TIMG_WDT_STG3_S  23
/** TIMG_WDT_STG2:R/W；比特位置：[26:25]；默认值：0；第2阶段配置。0：关闭，1：中断，2：重置CPU，3：重置系统。
 *
 */
#define TIMG_WDT_STG2    0x00000003U
#define TIMG_WDT_STG2_M  (TIMG_WDT_STG2_V << TIMG_WDT_STG2_S)
#define TIMG_WDT_STG2_V  0x00000003U
#define TIMG_WDT_STG2_S  25
/** TIMG_WDT_STG1:R/W；位位置：[28:27]；默认值：0；阶段1配置。0：关闭，1：中断，2：重置CPU，3：重置系统。
 *
 */
#define TIMG_WDT_STG1    0x00000003U
#define TIMG_WDT_STG1_M  (TIMG_WDT_STG1_V << TIMG_WDT_STG1_S)
#define TIMG_WDT_STG1_V  0x00000003U
#define TIMG_WDT_STG1_S  27
/** TIMG_WDT_STG0:R/W；位位置：[30:29]；默认值：0；阶段0配置。0：关闭，1：中断，2：重置CPU，3：重置系统。
 *
 */
#define TIMG_WDT_STG0    0x00000003U
#define TIMG_WDT_STG0_M  (TIMG_WDT_STG0_V << TIMG_WDT_STG0_S)
#define TIMG_WDT_STG0_V  0x00000003U
#define TIMG_WDT_STG0_S  29
/** TIMG_WDT_EN:R/W；位位置：[31]；默认值：0；设置后，MWDT启用。
 */
#define TIMG_WDT_EN    (BIT(31))
#define TIMG_WDT_EN_M  (TIMG_WDT_EN_V << TIMG_WDT_EN_S)
#define TIMG_WDT_EN_V  0x00000001U
#define TIMG_WDT_EN_S  31

/** TIMG_WDTCONFIG1_REG寄存器看门狗定时器预分频器寄存器
 */
#define TIMG_WDTCONFIG1_REG(i) (DR_REG_TIMG_BASE(i) + 0x4c)
/** TIMG_WDT_CLK_PRESCALER:R/W；比特位置：[31:16]；默认值：1；MWDT时钟预分频器值。MWDT时钟周期=12.5 ns
 *
 *  TIMG_WDT_CLK_PRESCALE.
 */
#define TIMG_WDT_CLK_PRESCALER    0x0000FFFFU
#define TIMG_WDT_CLK_PRESCALER_M  (TIMG_WDT_CLK_PRESCALER_V << TIMG_WDT_CLK_PRESCALER_S)
#define TIMG_WDT_CLK_PRESCALER_V  0x0000FFFFU
#define TIMG_WDT_CLK_PRESCALER_S  16

/** TIMG_WDTCONFIG2_REG寄存器看门狗定时器阶段0超时值
 */
#define TIMG_WDTCONFIG2_REG(i) (DR_REG_TIMG_BASE(i) + 0x50)
/** TIMG_WDT_STG0_HOLD:R/W；位位置：[31:0]；默认值：26000000；阶段0超时值，以MWDT时钟周期为单位。
 */
#define TIMG_WDT_STG0_HOLD    0xFFFFFFFFU
#define TIMG_WDT_STG0_HOLD_M  (TIMG_WDT_STG0_HOLD_V << TIMG_WDT_STG0_HOLD_S)
#define TIMG_WDT_STG0_HOLD_V  0xFFFFFFFFU
#define TIMG_WDT_STG0_HOLD_S  0

/** TIMG_WDTCONFIG3_REG寄存器看门狗定时器第1阶段超时值
 */
#define TIMG_WDTCONFIG3_REG(i) (DR_REG_TIMG_BASE(i) + 0x54)
/** TIMG_WDT_STG1_HOLD：R/W；位位置：[31:0]；默认值：134217727；阶段1超时值，以MWDT时钟周期为单位。
 */
#define TIMG_WDT_STG1_HOLD    0xFFFFFFFFU
#define TIMG_WDT_STG1_HOLD_M  (TIMG_WDT_STG1_HOLD_V << TIMG_WDT_STG1_HOLD_S)
#define TIMG_WDT_STG1_HOLD_V  0xFFFFFFFFU
#define TIMG_WDT_STG1_HOLD_S  0

/** TIMG_WDTCONFIG4_REG寄存器看门狗定时器第2阶段超时值
 */
#define TIMG_WDTCONFIG4_REG(i) (DR_REG_TIMG_BASE(i) + 0x58)
/** TIMG_WDT_STG2_HOLD:R/W；位位置：[31:0]；默认值：1048575；第2阶段超时值，以MWDT时钟周期为单位。
 */
#define TIMG_WDT_STG2_HOLD    0xFFFFFFFFU
#define TIMG_WDT_STG2_HOLD_M  (TIMG_WDT_STG2_HOLD_V << TIMG_WDT_STG2_HOLD_S)
#define TIMG_WDT_STG2_HOLD_V  0xFFFFFFFFU
#define TIMG_WDT_STG2_HOLD_S  0

/** TIMG_WDTCONFIG5_REG寄存器看门狗定时器第3阶段超时值
 */
#define TIMG_WDTCONFIG5_REG(i) (DR_REG_TIMG_BASE(i) + 0x5c)
/** TIMG_WDT_STG3_HOLD:R/W；位位置：[31:0]；默认值：1048575；阶段3超时值，以MWDT时钟周期为单位。
 */
#define TIMG_WDT_STG3_HOLD    0xFFFFFFFFU
#define TIMG_WDT_STG3_HOLD_M  (TIMG_WDT_STG3_HOLD_V << TIMG_WDT_STG3_HOLD_S)
#define TIMG_WDT_STG3_HOLD_V  0xFFFFFFFFU
#define TIMG_WDT_STG3_HOLD_S  0

/** TIMG_WDTFEED_REG寄存器写入以馈送看门狗计时器
 */
#define TIMG_WDTFEED_REG(i) (DR_REG_TIMG_BASE(i) + 0x60)
/** TIMG_WDT_FEED：WO；位位置：[31:0]；默认值：0；写入任何值以馈送MWDT。（WO）
 */
#define TIMG_WDT_FEED    0xFFFFFFFFU
#define TIMG_WDT_FEED_M  (TIMG_WDT_FEED_V << TIMG_WDT_FEED_S)
#define TIMG_WDT_FEED_V  0xFFFFFFFFU
#define TIMG_WDT_FEED_S  0

/** TIMG_WDTWPROTECT_REG寄存器看门狗写保护寄存器
 */
#define TIMG_WDTWPROTECT_REG(i) (DR_REG_TIMG_BASE(i) + 0x64)
/** TIMG_WDT_WKEY:R/W；位位置：[31:0]；默认值：1356348065；如果寄存器包含与其重置值不同的值，请写入
 *
 *  启用保护。
 */
#define TIMG_WDT_WKEY    0xFFFFFFFFU
#define TIMG_WDT_WKEY_M  (TIMG_WDT_WKEY_V << TIMG_WDT_WKEY_S)
#define TIMG_WDT_WKEY_V  0xFFFFFFFFU
#define TIMG_WDT_WKEY_S  0

/** TIMG_RTCCALICFG_REG寄存器RTC校准配置寄存器
 */
#define TIMG_RTCCALICFG_REG(i) (DR_REG_TIMG_BASE(i) + 0x68)
/** TIMG_RTC_CALI_START循环：R/W；位位置：[12]；默认值：1；保留
 */
#define TIMG_RTC_CALI_START_CYCLING    (BIT(12))
#define TIMG_RTC_CALI_START_CYCLING_M  (TIMG_RTC_CALI_START_CYCLING_V << TIMG_RTC_CALI_START_CYCLING_S)
#define TIMG_RTC_CALI_START_CYCLING_V  0x00000001U
#define TIMG_RTC_CALI_START_CYCLING_S  12
/** TIMG_RTC_CALI_CLK_SEL:R/W；比特位置：[14:13]；默认值：1；0:rtslowclock（实时时钟）。1： clk_80m。2： xtal_32k中。
 */
#define TIMG_RTC_CALI_CLK_SEL    0x00000003U
#define TIMG_RTC_CALI_CLK_SEL_M  (TIMG_RTC_CALI_CLK_SEL_V << TIMG_RTC_CALI_CLK_SEL_S)
#define TIMG_RTC_CALI_CLK_SEL_V  0x00000003U
#define TIMG_RTC_CALI_CLK_SEL_S  13
/** TIMG_RTC_CALI_RDY:RO；位位置：[15]；默认值：0；保留
 */
#define TIMG_RTC_CALI_RDY    (BIT(15))
#define TIMG_RTC_CALI_RDY_M  (TIMG_RTC_CALI_RDY_V << TIMG_RTC_CALI_RDY_S)
#define TIMG_RTC_CALI_RDY_V  0x00000001U
#define TIMG_RTC_CALI_RDY_S  15
/** TIMG_RTC_CALI_MAX：R/W；比特位置：[30:16]；默认值：1；保留
 */
#define TIMG_RTC_CALI_MAX    0x00007FFFU
#define TIMG_RTC_CALI_MAX_M  (TIMG_RTC_CALI_MAX_V << TIMG_RTC_CALI_MAX_S)
#define TIMG_RTC_CALI_MAX_V  0x00007FFFU
#define TIMG_RTC_CALI_MAX_S  16
/** TIMG_RTC_CALI_START：R/W；位位置：[31]；默认值：0；保留
 */
#define TIMG_RTC_CALI_START    (BIT(31))
#define TIMG_RTC_CALI_START_M  (TIMG_RTC_CALI_START_V << TIMG_RTC_CALI_START_S)
#define TIMG_RTC_CALI_START_V  0x00000001U
#define TIMG_RTC_CALI_START_S  31

/** TIMG_RTCCALICFG1_REG寄存器RTC校准配置1寄存器
 */
#define TIMG_RTCCALICFG1_REG(i) (DR_REG_TIMG_BASE(i) + 0x6c)
/** TIMG_RTC_CALI_CYCLING_DATA_VLD:RO；位位置：[0]；默认值：0；保留
 */
#define TIMG_RTC_CALI_CYCLING_DATA_VLD    (BIT(0))
#define TIMG_RTC_CALI_CYCLING_DATA_VLD_M  (TIMG_RTC_CALI_CYCLING_DATA_VLD_V << TIMG_RTC_CALI_CYCLING_DATA_VLD_S)
#define TIMG_RTC_CALI_CYCLING_DATA_VLD_V  0x00000001U
#define TIMG_RTC_CALI_CYCLING_DATA_VLD_S  0
/** TIMG_RTC_CALI_VALUE:RO；比特位置：[31:7]；默认值：0；保留
 */
#define TIMG_RTC_CALI_VALUE    0x01FFFFFFU
#define TIMG_RTC_CALI_VALUE_M  (TIMG_RTC_CALI_VALUE_V << TIMG_RTC_CALI_VALUE_S)
#define TIMG_RTC_CALI_VALUE_V  0x01FFFFFFU
#define TIMG_RTC_CALI_VALUE_S  7

/** TIMG_LACTCONFIG_REG寄存器LACT配置寄存器
 */
#define TIMG_LACTCONFIG_REG(i) (DR_REG_TIMG_BASE(i) + 0x70)
/** TIMG_LACT_USE_REFTICK:R/W；位位置：[6]；默认值：0；保留
 */
#define TIMG_LACT_USE_REFTICK    (BIT(6))
#define TIMG_LACT_USE_REFTICK_M  (TIMG_LACT_USE_REFTICK_V << TIMG_LACT_USE_REFTICK_S)
#define TIMG_LACT_USE_REFTICK_V  0x00000001U
#define TIMG_LACT_USE_REFTICK_S  6
/** TIMG_LACT_RTC_ONLY:R/W；位位置：[7]；默认值：0；保留
 */
#define TIMG_LACT_RTC_ONLY    (BIT(7))
#define TIMG_LACT_RTC_ONLY_M  (TIMG_LACT_RTC_ONLY_V << TIMG_LACT_RTC_ONLY_S)
#define TIMG_LACT_RTC_ONLY_V  0x00000001U
#define TIMG_LACT_RTC_ONLY_S  7
/** TIMG_LACT_CPST_EN:R/W；位位置：[8]；默认值：1；保留
 */
#define TIMG_LACT_CPST_EN    (BIT(8))
#define TIMG_LACT_CPST_EN_M  (TIMG_LACT_CPST_EN_V << TIMG_LACT_CPST_EN_S)
#define TIMG_LACT_CPST_EN_V  0x00000001U
#define TIMG_LACT_CPST_EN_S  8
/** TIMG_LACT_LAC_EN:R/W；位位置：[9]；默认值：1；保留
 */
#define TIMG_LACT_LAC_EN    (BIT(9))
#define TIMG_LACT_LAC_EN_M  (TIMG_LACT_LAC_EN_V << TIMG_LACT_LAC_EN_S)
#define TIMG_LACT_LAC_EN_V  0x00000001U
#define TIMG_LACT_LAC_EN_S  9
/** TIMG_LACT_ALARM_EN:R/W；位位置：[10]；默认值：0；保留
 */
#define TIMG_LACT_ALARM_EN    (BIT(10))
#define TIMG_LACT_ALARM_EN_M  (TIMG_LACT_ALARM_EN_V << TIMG_LACT_ALARM_EN_S)
#define TIMG_LACT_ALARM_EN_V  0x00000001U
#define TIMG_LACT_ALARM_EN_S  10
/** TIMG_LACT_LEVEL_INT_EN:R/W；位位置：[11]；默认值：0；保留
 */
#define TIMG_LACT_LEVEL_INT_EN    (BIT(11))
#define TIMG_LACT_LEVEL_INT_EN_M  (TIMG_LACT_LEVEL_INT_EN_V << TIMG_LACT_LEVEL_INT_EN_S)
#define TIMG_LACT_LEVEL_INT_EN_V  0x00000001U
#define TIMG_LACT_LEVEL_INT_EN_S  11
/** TIMG_LACT_EDGE_INT_EN:R/W；位位置：[12]；默认值：0；保留
 */
#define TIMG_LACT_EDGE_INT_EN    (BIT(12))
#define TIMG_LACT_EDGE_INT_EN_M  (TIMG_LACT_EDGE_INT_EN_V << TIMG_LACT_EDGE_INT_EN_S)
#define TIMG_LACT_EDGE_INT_EN_V  0x00000001U
#define TIMG_LACT_EDGE_INT_EN_S  12
/** TIMG_LACT_DIVIDER:R/W；比特位置：[28:13]；默认值：1；保留
 */
#define TIMG_LACT_DIVIDER    0x0000FFFFU
#define TIMG_LACT_DIVIDER_M  (TIMG_LACT_DIVIDER_V << TIMG_LACT_DIVIDER_S)
#define TIMG_LACT_DIVIDER_V  0x0000FFFFU
#define TIMG_LACT_DIVIDER_S  13
/** TIMG_LACT_AUTORELOAD:R/W；位位置：[29]；默认值：1；保留
 */
#define TIMG_LACT_AUTORELOAD    (BIT(29))
#define TIMG_LACT_AUTORELOAD_M  (TIMG_LACT_AUTORELOAD_V << TIMG_LACT_AUTORELOAD_S)
#define TIMG_LACT_AUTORELOAD_V  0x00000001U
#define TIMG_LACT_AUTORELOAD_S  29
/** TIMG_LACT_INCREASE:R/W；位位置：[30]；默认值：1；保留
 */
#define TIMG_LACT_INCREASE    (BIT(30))
#define TIMG_LACT_INCREASE_M  (TIMG_LACT_INCREASE_V << TIMG_LACT_INCREASE_S)
#define TIMG_LACT_INCREASE_V  0x00000001U
#define TIMG_LACT_INCREASE_S  30
/** TIMG_LACT_EN:R/W；位位置：[31]；默认值：0；保留
 */
#define TIMG_LACT_EN    (BIT(31))
#define TIMG_LACT_EN_M  (TIMG_LACT_EN_V << TIMG_LACT_EN_S)
#define TIMG_LACT_EN_V  0x00000001U
#define TIMG_LACT_EN_S  31

/** TIMG_LACTRTC_REG寄存器LACT RTC寄存器
 */
#define TIMG_LACTRTC_REG(i) (DR_REG_TIMG_BASE(i) + 0x74)
/** TIMG_LACT_RTC_STEP_LEN:R/W；位位置：[31:6]；默认值：0；保留
 */
#define TIMG_LACT_RTC_STEP_LEN    0x03FFFFFFU
#define TIMG_LACT_RTC_STEP_LEN_M  (TIMG_LACT_RTC_STEP_LEN_V << TIMG_LACT_RTC_STEP_LEN_S)
#define TIMG_LACT_RTC_STEP_LEN_V  0x03FFFFFFU
#define TIMG_LACT_RTC_STEP_LEN_S  6

/** TIMG_LACTLO_REG寄存器LACT低寄存器
 */
#define TIMG_LACTLO_REG(i) (DR_REG_TIMG_BASE(i) + 0x78)
/** TIMG_LACT_LO:RO；位位置：[31:0]；默认值：0；保留
 */
#define TIMG_LACT_LO    0xFFFFFFFFU
#define TIMG_LACT_LO_M  (TIMG_LACT_LO_V << TIMG_LACT_LO_S)
#define TIMG_LACT_LO_V  0xFFFFFFFFU
#define TIMG_LACT_LO_S  0

/** TIMG_LACTHI_REG寄存器LACT高寄存器
 */
#define TIMG_LACTHI_REG(i) (DR_REG_TIMG_BASE(i) + 0x7c)
/** TIMG_LACT_HI:RO；位位置：[31:0]；默认值：0；保留
 */
#define TIMG_LACT_HI    0xFFFFFFFFU
#define TIMG_LACT_HI_M  (TIMG_LACT_HI_V << TIMG_LACT_HI_S)
#define TIMG_LACT_HI_V  0xFFFFFFFFU
#define TIMG_LACT_HI_S  0

/** TIMG_LACTUPDATE_REG寄存器LACT更新寄存器
 */
#define TIMG_LACTUPDATE_REG(i) (DR_REG_TIMG_BASE(i) + 0x80)
/** TIMG_LACT_UPDATE:WO；位位置：[31:0]；默认值：0；保留
 */
#define TIMG_LACT_UPDATE    0xFFFFFFFFU
#define TIMG_LACT_UPDATE_M  (TIMG_LACT_UPDATE_V << TIMG_LACT_UPDATE_S)
#define TIMG_LACT_UPDATE_V  0xFFFFFFFFU
#define TIMG_LACT_UPDATE_S  0

/** TIMG_LACTALARMLO_REG寄存器LACT报警低寄存器
 */
#define TIMG_LACTALARMLO_REG(i) (DR_REG_TIMG_BASE(i) + 0x84)
/** TIMG_LACT_ALARM_LO:R/W；位位置：[31:0]；默认值：0；保留
 */
#define TIMG_LACT_ALARM_LO    0xFFFFFFFFU
#define TIMG_LACT_ALARM_LO_M  (TIMG_LACT_ALARM_LO_V << TIMG_LACT_ALARM_LO_S)
#define TIMG_LACT_ALARM_LO_V  0xFFFFFFFFU
#define TIMG_LACT_ALARM_LO_S  0

/** TIMG_LACTALARMHI_REG寄存器LACT报警高寄存器
 */
#define TIMG_LACTALARMHI_REG(i) (DR_REG_TIMG_BASE(i) + 0x88)
/** TIMG_LACT_ALARM-HI:R/W；位位置：[31:0]；默认值：0；保留
 */
#define TIMG_LACT_ALARM_HI    0xFFFFFFFFU
#define TIMG_LACT_ALARM_HI_M  (TIMG_LACT_ALARM_HI_V << TIMG_LACT_ALARM_HI_S)
#define TIMG_LACT_ALARM_HI_V  0xFFFFFFFFU
#define TIMG_LACT_ALARM_HI_S  0

/** TIMG_LACTLOADLO_REG寄存器LACT负载低寄存器
 */
#define TIMG_LACTLOADLO_REG(i) (DR_REG_TIMG_BASE(i) + 0x8c)
/** TIMG_LACT_LOAD_LO:R/W；位位置：[31:0]；默认值：0；保留
 */
#define TIMG_LACT_LOAD_LO    0xFFFFFFFFU
#define TIMG_LACT_LOAD_LO_M  (TIMG_LACT_LOAD_LO_V << TIMG_LACT_LOAD_LO_S)
#define TIMG_LACT_LOAD_LO_V  0xFFFFFFFFU
#define TIMG_LACT_LOAD_LO_S  0

/** TIMG_LACTLOADHI_REG寄存器定时器LACT加载高寄存器
 */
#define TIMG_LACTLOADHI_REG(i) (DR_REG_TIMG_BASE(i) + 0x90)
/** TIMG_LACT_LOAD_HI:R/W；位位置：[31:0]；默认值：0；保留
 */
#define TIMG_LACT_LOAD_HI    0xFFFFFFFFU
#define TIMG_LACT_LOAD_HI_M  (TIMG_LACT_LOAD_HI_V << TIMG_LACT_LOAD_HI_S)
#define TIMG_LACT_LOAD_HI_V  0xFFFFFFFFU
#define TIMG_LACT_LOAD_HI_S  0

/** TIMG_LACTLOAD_REG寄存器定时器LACT加载寄存器
 */
#define TIMG_LACTLOAD_REG(i) (DR_REG_TIMG_BASE(i) + 0x94)
/** TIMG_LACT_LOAD:WO；位位置：[31:0]；默认值：0；保留
 */
#define TIMG_LACT_LOAD    0xFFFFFFFFU
#define TIMG_LACT_LOAD_M  (TIMG_LACT_LOAD_V << TIMG_LACT_LOAD_S)
#define TIMG_LACT_LOAD_V  0xFFFFFFFFU
#define TIMG_LACT_LOAD_S  0

/** TIMG_INT_ENA_TIMERS_REG寄存器中断启用位
 */
#define TIMG_INT_ENA_TIMERS_REG(i) (DR_REG_TIMG_BASE(i) + 0x98)
/** TIMG_T0_INT_ENA:R/W；位位置：[0]；默认值：0；TIMG_T0_INT中断的中断启用位。
 */
#define TIMG_T0_INT_ENA    (BIT(0))
#define TIMG_T0_INT_ENA_M  (TIMG_T0_INT_ENA_V << TIMG_T0_INT_ENA_S)
#define TIMG_T0_INT_ENA_V  0x00000001U
#define TIMG_T0_INT_ENA_S  0
/** TIMG_T1_INT_ENA:R/W；位位置：[1]；默认值：0；TIMG_T1_INT中断的中断启用位。
 */
#define TIMG_T1_INT_ENA    (BIT(1))
#define TIMG_T1_INT_ENA_M  (TIMG_T1_INT_ENA_V << TIMG_T1_INT_ENA_S)
#define TIMG_T1_INT_ENA_V  0x00000001U
#define TIMG_T1_INT_ENA_S  1
/** TIMG_WDT_INT_ENA:R/W；位位置：[2]；默认值：0；TIMG_WDT_INT中断的中断启用位。
 */
#define TIMG_WDT_INT_ENA    (BIT(2))
#define TIMG_WDT_INT_ENA_M  (TIMG_WDT_INT_ENA_V << TIMG_WDT_INT_ENA_S)
#define TIMG_WDT_INT_ENA_V  0x00000001U
#define TIMG_WDT_INT_ENA_S  2
/** TIMG_LACT_INT_ENA:R/W；位位置：[3]；默认值：0；TIMG_LACT_INT中断的中断启用位。
 */
#define TIMG_LACT_INT_ENA    (BIT(3))
#define TIMG_LACT_INT_ENA_M  (TIMG_LACT_INT_ENA_V << TIMG_LACT_INT_ENA_S)
#define TIMG_LACT_INT_ENA_V  0x00000001U
#define TIMG_LACT_INT_ENA_S  3

/** TIMG_INT_RAW_TIMERS_REG寄存器原始中断状态
 */
#define TIMG_INT_RAW_TIMERS_REG(i) (DR_REG_TIMG_BASE(i) + 0x9c)
/** TIMG_T0_INT_RAW:RO；位位置：[0]；默认值：0；TIMG_T0_INT中断的原始中断状态位。
 */
#define TIMG_T0_INT_RAW    (BIT(0))
#define TIMG_T0_INT_RAW_M  (TIMG_T0_INT_RAW_V << TIMG_T0_INT_RAW_S)
#define TIMG_T0_INT_RAW_V  0x00000001U
#define TIMG_T0_INT_RAW_S  0
/** TIMG_T1_INT_RAW:RO；位位置：[1]；默认值：0；TIMG_T1_INT中断的原始中断状态位。
 */
#define TIMG_T1_INT_RAW    (BIT(1))
#define TIMG_T1_INT_RAW_M  (TIMG_T1_INT_RAW_V << TIMG_T1_INT_RAW_S)
#define TIMG_T1_INT_RAW_V  0x00000001U
#define TIMG_T1_INT_RAW_S  1
/** TIMG_WDT_INT_RAW:RO；位位置：[2]；默认值：0；TIMG_WDT_INT中断的原始中断状态位。
 */
#define TIMG_WDT_INT_RAW    (BIT(2))
#define TIMG_WDT_INT_RAW_M  (TIMG_WDT_INT_RAW_V << TIMG_WDT_INT_RAW_S)
#define TIMG_WDT_INT_RAW_V  0x00000001U
#define TIMG_WDT_INT_RAW_S  2
/** TIMG_LACT_INT_RO:RO；位位置：[3]；默认值：0；TIMG_LACT_INT中断的原始中断状态位。
 */
#define TIMG_LACT_INT_RAW    (BIT(3))
#define TIMG_LACT_INT_RAW_M  (TIMG_LACT_INT_RAW_V << TIMG_LACT_INT_RAW_S)
#define TIMG_LACT_INT_RAW_V  0x00000001U
#define TIMG_LACT_INT_RAW_S  3

/** TIMG_INT_ST_TIMERS_REG寄存器屏蔽中断状态
 */
#define TIMG_INT_ST_TIMERS_REG(i) (DR_REG_TIMG_BASE(i) + 0xa0)
/** TIMG_T0_INT_ST:RO；位位置：[0]；默认值：0；TIMG_T0_INT中断的屏蔽中断状态位。
 */
#define TIMG_T0_INT_ST    (BIT(0))
#define TIMG_T0_INT_ST_M  (TIMG_T0_INT_ST_V << TIMG_T0_INT_ST_S)
#define TIMG_T0_INT_ST_V  0x00000001U
#define TIMG_T0_INT_ST_S  0
/** TIMG_T1_INT_ST:RO；位位置：[1]；默认值：0；TIMG_T1_INT中断的屏蔽中断状态位。
 */
#define TIMG_T1_INT_ST    (BIT(1))
#define TIMG_T1_INT_ST_M  (TIMG_T1_INT_ST_V << TIMG_T1_INT_ST_S)
#define TIMG_T1_INT_ST_V  0x00000001U
#define TIMG_T1_INT_ST_S  1
/** TIMG_WDT_INT_ST:RO；位位置：[2]；默认值：0；TIMG_WDT_INT中断的屏蔽中断状态位。
 */
#define TIMG_WDT_INT_ST    (BIT(2))
#define TIMG_WDT_INT_ST_M  (TIMG_WDT_INT_ST_V << TIMG_WDT_INT_ST_S)
#define TIMG_WDT_INT_ST_V  0x00000001U
#define TIMG_WDT_INT_ST_S  2
/** TIMG_LACT_INT:RO；位位置：[3]；默认值：0；TIMG_LACT_INT中断的屏蔽中断状态位。
 */
#define TIMG_LACT_INT_ST    (BIT(3))
#define TIMG_LACT_INT_ST_M  (TIMG_LACT_INT_ST_V << TIMG_LACT_INT_ST_S)
#define TIMG_LACT_INT_ST_V  0x00000001U
#define TIMG_LACT_INT_ST_S  3

/** TIMG_INT_CLR_TIMERS_REG寄存器中断清除位
 */
#define TIMG_INT_CLR_TIMERS_REG(i) (DR_REG_TIMG_BASE(i) + 0xa4)
/** TIMG_T0_INT_CLR:WO；位位置：[0]；默认值：0；设置该位以清除TIMG_T0_INT中断。
 */
#define TIMG_T0_INT_CLR    (BIT(0))
#define TIMG_T0_INT_CLR_M  (TIMG_T0_INT_CLR_V << TIMG_T0_INT_CLR_S)
#define TIMG_T0_INT_CLR_V  0x00000001U
#define TIMG_T0_INT_CLR_S  0
/** TIMG_T1_INT_CLR:WO；位位置：[1]；默认值：0；设置该位以清除TIMG_T1_INT中断。
 */
#define TIMG_T1_INT_CLR    (BIT(1))
#define TIMG_T1_INT_CLR_M  (TIMG_T1_INT_CLR_V << TIMG_T1_INT_CLR_S)
#define TIMG_T1_INT_CLR_V  0x00000001U
#define TIMG_T1_INT_CLR_S  1
/** TIMG_WDT_INT_CLR:WO；位位置：[2]；默认值：0；设置该位以清除TIMG_WDT_INT中断。
 */
#define TIMG_WDT_INT_CLR    (BIT(2))
#define TIMG_WDT_INT_CLR_M  (TIMG_WDT_INT_CLR_V << TIMG_WDT_INT_CLR_S)
#define TIMG_WDT_INT_CLR_V  0x00000001U
#define TIMG_WDT_INT_CLR_S  2
/** TIMG_LACT_INT_CLR:WO；位位置：[3]；默认值：0；设置该位以清除TIMG_LACT_INT中断。
 */
#define TIMG_LACT_INT_CLR    (BIT(3))
#define TIMG_LACT_INT_CLR_M  (TIMG_LACT_INT_CLR_V << TIMG_LACT_INT_CLR_S)
#define TIMG_LACT_INT_CLR_V  0x00000001U
#define TIMG_LACT_INT_CLR_S  3

/** TIMG_RTCCALICFG2_REG寄存器定时器组校准寄存器
 */
#define TIMG_RTCCALICFG2_REG(i) (DR_REG_TIMG_BASE(i) + 0xa8)
/** TIMG_RTC_CALI_TIMEOUT:RO；位位置：[0]；默认值：0；RTC校准超时指示灯
 */
#define TIMG_RTC_CALI_TIMEOUT    (BIT(0))
#define TIMG_RTC_CALI_TIMEOUT_M  (TIMG_RTC_CALI_TIMEOUT_V << TIMG_RTC_CALI_TIMEOUT_S)
#define TIMG_RTC_CALI_TIMEOUT_V  0x00000001U
#define TIMG_RTC_CALI_TIMEOUT_S  0
/** TIMG_RTC_CALI_TIMEOUT_RST_CNT:R/W；比特位置：[6:3]；默认值：3；释放校准超时重置的周期
 */
#define TIMG_RTC_CALI_TIMEOUT_RST_CNT    0x0000000FU
#define TIMG_RTC_CALI_TIMEOUT_RST_CNT_M  (TIMG_RTC_CALI_TIMEOUT_RST_CNT_V << TIMG_RTC_CALI_TIMEOUT_RST_CNT_S)
#define TIMG_RTC_CALI_TIMEOUT_RST_CNT_V  0x0000000FU
#define TIMG_RTC_CALI_TIMEOUT_RST_CNT_S  3
/** TIMG_RTC_CALI_TIMEOUT_THRES:R/W；比特位置：[31:7]；默认值：33554431；RTC校准计时器的阈值。如果校准计时器的值超过此阈值，将触发超时。
 */
#define TIMG_RTC_CALI_TIMEOUT_THRES    0x01FFFFFFU
#define TIMG_RTC_CALI_TIMEOUT_THRES_M  (TIMG_RTC_CALI_TIMEOUT_THRES_V << TIMG_RTC_CALI_TIMEOUT_THRES_S)
#define TIMG_RTC_CALI_TIMEOUT_THRES_V  0x01FFFFFFU
#define TIMG_RTC_CALI_TIMEOUT_THRES_S  7

/** TIMG_TIMERS_DATE_REG寄存器版本控制寄存器
 */
#define TIMG_TIMERS_DATE_REG(i) (DR_REG_TIMG_BASE(i) + 0xf8)
/** TIMG_TIMERS_DATE:R/W；位位置：[27:0]；默认值：26243681；版本控制寄存器。
 */
#define TIMG_TIMERS_DATE    0x0FFFFFFFU
#define TIMG_TIMERS_DATE_M  (TIMG_TIMERS_DATE_V << TIMG_TIMERS_DATE_S)
#define TIMG_TIMERS_DATE_V  0x0FFFFFFFU
#define TIMG_TIMERS_DATE_S  0

/** TIMG_REGCLK_REG寄存器定时器组时钟门寄存器
 */
#define TIMG_REGCLK_REG(i) (DR_REG_TIMG_BASE(i) + 0xfc)
/** TIMG_CLK_EN:R/W；位位置：[31]；默认值：0；寄存器时钟门信号。1： 寄存器可以由软件读取和写入。0：软件无法读取或写入寄存器。
 */
#define TIMG_CLK_EN    (BIT(31))
#define TIMG_CLK_EN_M  (TIMG_CLK_EN_V << TIMG_CLK_EN_S)
#define TIMG_CLK_EN_V  0x00000001U
#define TIMG_CLK_EN_S  31

#ifdef __cplusplus
}
#endif

