// 版权所有2015-2016 Espressif Systems（上海）私人有限公司
//
// 根据Apache许可证2.0版（“许可证”）获得许可；
// 除非符合许可证，否则不得使用此文件。
// 您可以在以下地址获取许可证副本：
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// 除非适用法律要求或书面同意，软件
// 根据许可证分发的内容是按“原样”分发的，
// 无任何明示或暗示的保证或条件。
// 有关管理权限和
// 许可证下的限制。
#ifndef _SOC_APB_CTRL_REG_H_
#define _SOC_APB_CTRL_REG_H_

#include "soc.h"
#define APB_CTRL_SYSCLK_CONF_REG          (DR_REG_APB_CTRL_BASE + 0x0)
/* APB_CTRL_QUICK_CLK_CHNG:R/W；位位置：[13]；默认值：1’b1；*/
/*说明：*/
#define APB_CTRL_QUICK_CLK_CHNG  (BIT(13))
#define APB_CTRL_QUICK_CLK_CHNG_M  (BIT(13))
#define APB_CTRL_QUICK_CLK_CHNG_V  0x1
#define APB_CTRL_QUICK_CLK_CHNG_S  13
/* APB_CTRL_RST_TICK_CNT:R/W；位位置：[12]；默认值：1’b0；*/
/*说明：*/
#define APB_CTRL_RST_TICK_CNT  (BIT(12))
#define APB_CTRL_RST_TICK_CNT_M  (BIT(12))
#define APB_CTRL_RST_TICK_CNT_V  0x1
#define APB_CTRL_RST_TICK_CNT_S  12
/* APB_CTRL_CLK_EN:R/W；位位置：[11]；默认值：1’b0；*/
/*说明：*/
#define APB_CTRL_CLK_EN  (BIT(11))
#define APB_CTRL_CLK_EN_M  (BIT(11))
#define APB_CTRL_CLK_EN_V  0x1
#define APB_CTRL_CLK_EN_S  11
/* APB_CTRL_CLK_320M_EN:R/W；位位置：[10]；默认值：1’b0；*/
/*说明：*/
#define APB_CTRL_CLK_320M_EN  (BIT(10))
#define APB_CTRL_CLK_320M_EN_M  (BIT(10))
#define APB_CTRL_CLK_320M_EN_V  0x1
#define APB_CTRL_CLK_320M_EN_S  10
/* APB_CTRL_PRE_DIV_CNT:R/W；位位置：[9:0]；默认值：10'0；*/
/*说明：*/
#define APB_CTRL_PRE_DIV_CNT  0x000003FF
#define APB_CTRL_PRE_DIV_CNT_M  ((APB_CTRL_PRE_DIV_CNT_V)<<(APB_CTRL_PRE_DIV_CNT_S))
#define APB_CTRL_PRE_DIV_CNT_V  0x3FF
#define APB_CTRL_PRE_DIV_CNT_S  0

#define APB_CTRL_XTAL_TICK_CONF_REG          (DR_REG_APB_CTRL_BASE + 0x4)
/* APB_CTRL-XTAL_TICK_NUM:R/W；位位置：[7:0]；默认值：8'd39；*/
/*说明：*/
#define APB_CTRL_XTAL_TICK_NUM  0x000000FF
#define APB_CTRL_XTAL_TICK_NUM_M  ((APB_CTRL_XTAL_TICK_NUM_V)<<(APB_CTRL_XTAL_TICK_NUM_S))
#define APB_CTRL_XTAL_TICK_NUM_V  0xFF
#define APB_CTRL_XTAL_TICK_NUM_S  0

#define APB_CTRL_PLL_TICK_CONF_REG          (DR_REG_APB_CTRL_BASE + 0x8)
/* APB_CTRL_PLL_TICK_NUM:R/W；位位置：[7:0]；默认值：8'd79；*/
/*说明：*/
#define APB_CTRL_PLL_TICK_NUM  0x000000FF
#define APB_CTRL_PLL_TICK_NUM_M  ((APB_CTRL_PLL_TICK_NUM_V)<<(APB_CTRL_PLL_TICK_NUM_S))
#define APB_CTRL_PLL_TICK_NUM_V  0xFF
#define APB_CTRL_PLL_TICK_NUM_S  0

#define APB_CTRL_CK8M_TICK_CONF_REG          (DR_REG_APB_CTRL_BASE + 0xC)
/* APB_CTRL_CK8M_TICK_NUM:R/W；位位置：[7:0]；默认值：8'd11；*/
/*说明：*/
#define APB_CTRL_CK8M_TICK_NUM  0x000000FF
#define APB_CTRL_CK8M_TICK_NUM_M  ((APB_CTRL_CK8M_TICK_NUM_V)<<(APB_CTRL_CK8M_TICK_NUM_S))
#define APB_CTRL_CK8M_TICK_NUM_V  0xFF
#define APB_CTRL_CK8M_TICK_NUM_S  0

#define APB_CTRL_APB_SARADC_CTRL_REG          (DR_REG_APB_CTRL_BASE + 0x10)
/* APB_CTRL_SARADC_DATA_TO_I2S:R/W；位位置：[26]；默认值：1’b0；*/
/*描述：1:I2S输入数据来自SAR ADC（用于DMA）0:I2S输入信号来自GPIO矩阵*/
#define APB_CTRL_SARADC_DATA_TO_I2S  (BIT(26))
#define APB_CTRL_SARADC_DATA_TO_I2S_M  (BIT(26))
#define APB_CTRL_SARADC_DATA_TO_I2S_V  0x1
#define APB_CTRL_SARADC_DATA_TO_I2S_S  26
/* APB_CTRL_SARADC_DATA_SAR_SEL:R/W；位位置：[25]；默认值：1’b0；*/
/*描述：1:sar_sel将由16位输出数据的MSB编码，在这种情况下，分辨率不应大于11位。*/
#define APB_CTRL_SARADC_DATA_SAR_SEL  (BIT(25))
#define APB_CTRL_SARADC_DATA_SAR_SEL_M  (BIT(25))
#define APB_CTRL_SARADC_DATA_SAR_SEL_V  0x1
#define APB_CTRL_SARADC_DATA_SAR_SEL_S  25
/* APB_CTRL_SARADC_SAR2_PATT_P_CLEAR:R/W；位位置：[24]；默认值：1'd0；*/
/*描述：清除DIG ADC2 CTRL的模式表指针*/
#define APB_CTRL_SARADC_SAR2_PATT_P_CLEAR  (BIT(24))
#define APB_CTRL_SARADC_SAR2_PATT_P_CLEAR_M  (BIT(24))
#define APB_CTRL_SARADC_SAR2_PATT_P_CLEAR_V  0x1
#define APB_CTRL_SARADC_SAR2_PATT_P_CLEAR_S  24
/* APB_CTRL_SARADC_SAR1_PATT_P_CLEAR:R/W；位位置：[23]；默认值：1'd0；*/
/*描述：清除DIG ADC1 CTRL的模式表指针*/
#define APB_CTRL_SARADC_SAR1_PATT_P_CLEAR  (BIT(23))
#define APB_CTRL_SARADC_SAR1_PATT_P_CLEAR_M  (BIT(23))
#define APB_CTRL_SARADC_SAR1_PATT_P_CLEAR_V  0x1
#define APB_CTRL_SARADC_SAR1_PATT_P_CLEAR_S  23
/* APB_CTRL_SARADC_SAR2_PATT_LEN:R/W；比特位置：[22:19]；默认值：4'd15；*/
/*说明：0~15表示长度1~16*/
#define APB_CTRL_SARADC_SAR2_PATT_LEN  0x0000000F
#define APB_CTRL_SARADC_SAR2_PATT_LEN_M  ((APB_CTRL_SARADC_SAR2_PATT_LEN_V)<<(APB_CTRL_SARADC_SAR2_PATT_LEN_S))
#define APB_CTRL_SARADC_SAR2_PATT_LEN_V  0xF
#define APB_CTRL_SARADC_SAR2_PATT_LEN_S  19
/* APB_CTRL_SARADC_SAR1_PATT_LEN:R/W；比特位置：[18:15]；默认值：4'd15；*/
/*说明：0~15表示长度1~16*/
#define APB_CTRL_SARADC_SAR1_PATT_LEN  0x0000000F
#define APB_CTRL_SARADC_SAR1_PATT_LEN_M  ((APB_CTRL_SARADC_SAR1_PATT_LEN_V)<<(APB_CTRL_SARADC_SAR1_PATT_LEN_S))
#define APB_CTRL_SARADC_SAR1_PATT_LEN_V  0xF
#define APB_CTRL_SARADC_SAR1_PATT_LEN_S  15
/* APB_CTRL_SARADC_SAR_CLK_DIV:R/W；比特位置：[14:7]；默认值：8'd4；*/
/*描述：SAR时钟分频器*/
#define APB_CTRL_SARADC_SAR_CLK_DIV  0x000000FF
#define APB_CTRL_SARADC_SAR_CLK_DIV_M  ((APB_CTRL_SARADC_SAR_CLK_DIV_V)<<(APB_CTRL_SARADC_SAR_CLK_DIV_S))
#define APB_CTRL_SARADC_SAR_CLK_DIV_V  0xFF
#define APB_CTRL_SARADC_SAR_CLK_DIV_S  7
/* APB_CTRL_SARADC_SAR_CLK_GATED:R/W；位位置：[6]；默认值：1’b1；*/
/*说明：*/
#define APB_CTRL_SARADC_SAR_CLK_GATED  (BIT(6))
#define APB_CTRL_SARADC_SAR_CLK_GATED_M  (BIT(6))
#define APB_CTRL_SARADC_SAR_CLK_GATED_V  0x1
#define APB_CTRL_SARADC_SAR_CLK_GATED_S  6
/* APB_CTRL_SARADC_SAR_SEL:R/W；位位置：[5]；默认值：1'd0；*/
/*description:0:SAR1 1:SAR2仅适用于单SAR模式*/
#define APB_CTRL_SARADC_SAR_SEL  (BIT(5))
#define APB_CTRL_SARADC_SAR_SEL_M  (BIT(5))
#define APB_CTRL_SARADC_SAR_SEL_V  0x1
#define APB_CTRL_SARADC_SAR_SEL_S  5
/* APB_CTRL_SARADC_WORK_MODE：R/W；位位置：[4:3]；默认值：2'd0；*/
/*描述：0：单模式1：双模式2：交替模式*/
#define APB_CTRL_SARADC_WORK_MODE  0x00000003
#define APB_CTRL_SARADC_WORK_MODE_M  ((APB_CTRL_SARADC_WORK_MODE_V)<<(APB_CTRL_SARADC_WORK_MODE_S))
#define APB_CTRL_SARADC_WORK_MODE_V  0x3
#define APB_CTRL_SARADC_WORK_MODE_S  3
/* APB_CTRL_SARADC_SAR2_MUX:R/W；位位置：[2]；默认值：1'd0；*/
/*描述：1:SAR ADC2由DIG ADC2 CTRL控制0:SAR ADC2受PWDET CTRL控制*/
#define APB_CTRL_SARADC_SAR2_MUX  (BIT(2))
#define APB_CTRL_SARADC_SAR2_MUX_M  (BIT(2))
#define APB_CTRL_SARADC_SAR2_MUX_V  0x1
#define APB_CTRL_SARADC_SAR2_MUX_S  2
/* APB_CTRL_SARADC_START:R/W；位位置：[1]；默认值：1'd0；*/
/*说明：*/
#define APB_CTRL_SARADC_START  (BIT(1))
#define APB_CTRL_SARADC_START_M  (BIT(1))
#define APB_CTRL_SARADC_START_V  0x1
#define APB_CTRL_SARADC_START_S  1
/* APB_CTRL_SARADC_START_FORCE:R/W；位位置：[0]；默认值：1'd0；*/
/*说明：*/
#define APB_CTRL_SARADC_START_FORCE  (BIT(0))
#define APB_CTRL_SARADC_START_FORCE_M  (BIT(0))
#define APB_CTRL_SARADC_START_FORCE_V  0x1
#define APB_CTRL_SARADC_START_FORCE_S  0

#define APB_CTRL_APB_SARADC_CTRL2_REG          (DR_REG_APB_CTRL_BASE + 0x14)
/* APB_CTRL_SARADC_SAR2_INV:R/W；位位置：[10]；默认值：1'd0；*/
/*描述：1：DIG ADC2 CTRL的数据反转，否则不反转*/
#define APB_CTRL_SARADC_SAR2_INV  (BIT(10))
#define APB_CTRL_SARADC_SAR2_INV_M  (BIT(10))
#define APB_CTRL_SARADC_SAR2_INV_V  0x1
#define APB_CTRL_SARADC_SAR2_INV_S  10
/* APB_CTRL_SARADC_SAR1_INV:R/W；位位置：[9]；默认值：1'd0；*/
/*描述：1：DIG ADC1 CTRL的数据反转，否则不反转*/
#define APB_CTRL_SARADC_SAR1_INV  (BIT(9))
#define APB_CTRL_SARADC_SAR1_INV_M  (BIT(9))
#define APB_CTRL_SARADC_SAR1_INV_V  0x1
#define APB_CTRL_SARADC_SAR1_INV_S  9
/* APB_CTRL_SARADC_MAX_MEAS_NUM:R/W；位位置：[8:1]；默认值：8'd255；*/
/*description:最大转换数*/
#define APB_CTRL_SARADC_MAX_MEAS_NUM  0x000000FF
#define APB_CTRL_SARADC_MAX_MEAS_NUM_M  ((APB_CTRL_SARADC_MAX_MEAS_NUM_V)<<(APB_CTRL_SARADC_MAX_MEAS_NUM_S))
#define APB_CTRL_SARADC_MAX_MEAS_NUM_V  0xFF
#define APB_CTRL_SARADC_MAX_MEAS_NUM_S  1
/* APB_CTRL_SARADC_MEAS_NUM_LIMIT:R/W；位位置：[0]；默认值：1'd0；*/
/*说明：*/
#define APB_CTRL_SARADC_MEAS_NUM_LIMIT  (BIT(0))
#define APB_CTRL_SARADC_MEAS_NUM_LIMIT_M  (BIT(0))
#define APB_CTRL_SARADC_MEAS_NUM_LIMIT_V  0x1
#define APB_CTRL_SARADC_MEAS_NUM_LIMIT_S  0

#define APB_CTRL_APB_SARADC_FSM_REG          (DR_REG_APB_CTRL_BASE + 0x18)
/* APB_CTRL_SARADC_SAMPLE_CYCLE:R/W；位位置：[31:24]；默认值：8'd2；*/
/*描述：采样周期*/
#define APB_CTRL_SARADC_SAMPLE_CYCLE  0x000000FF
#define APB_CTRL_SARADC_SAMPLE_CYCLE_M  ((APB_CTRL_SARADC_SAMPLE_CYCLE_V)<<(APB_CTRL_SARADC_SAMPLE_CYCLE_S))
#define APB_CTRL_SARADC_SAMPLE_CYCLE_V  0xFF
#define APB_CTRL_SARADC_SAMPLE_CYCLE_S  24
/* APB_CTRL_SARADC_START_WAIT:R/W；比特位置：[23:16]；默认值：8'd8；*/
/*说明：*/
#define APB_CTRL_SARADC_START_WAIT  0x000000FF
#define APB_CTRL_SARADC_START_WAIT_M  ((APB_CTRL_SARADC_START_WAIT_V)<<(APB_CTRL_SARADC_START_WAIT_S))
#define APB_CTRL_SARADC_START_WAIT_V  0xFF
#define APB_CTRL_SARADC_START_WAIT_S  16
/* APB_CTRL_SARADC_STANDBY_WAIT:R/W；比特位置：[15:8]；默认值：8'd255；*/
/*说明：*/
#define APB_CTRL_SARADC_STANDBY_WAIT  0x000000FF
#define APB_CTRL_SARADC_STANDBY_WAIT_M  ((APB_CTRL_SARADC_STANDBY_WAIT_V)<<(APB_CTRL_SARADC_STANDBY_WAIT_S))
#define APB_CTRL_SARADC_STANDBY_WAIT_V  0xFF
#define APB_CTRL_SARADC_STANDBY_WAIT_S  8
/* APB_CTRL_SARADC_RSTB_WAIT:R/W；位位置：[7:0]；默认值：8'd8；*/
/*说明：*/
#define APB_CTRL_SARADC_RSTB_WAIT  0x000000FF
#define APB_CTRL_SARADC_RSTB_WAIT_M  ((APB_CTRL_SARADC_RSTB_WAIT_V)<<(APB_CTRL_SARADC_RSTB_WAIT_S))
#define APB_CTRL_SARADC_RSTB_WAIT_V  0xFF
#define APB_CTRL_SARADC_RSTB_WAIT_S  0

#define APB_CTRL_APB_SARADC_SAR1_PATT_TAB1_REG          (DR_REG_APB_CTRL_BASE + 0x1C)
/* APB_CTRL_SARADC_SAR1_PATT_TAB1:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表1的项目0~3（每个项目一个字节）*/
#define APB_CTRL_SARADC_SAR1_PATT_TAB1  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB1_M  ((APB_CTRL_SARADC_SAR1_PATT_TAB1_V)<<(APB_CTRL_SARADC_SAR1_PATT_TAB1_S))
#define APB_CTRL_SARADC_SAR1_PATT_TAB1_V  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB1_S  0

#define APB_CTRL_APB_SARADC_SAR1_PATT_TAB2_REG          (DR_REG_APB_CTRL_BASE + 0x20)
/* APB_CTRL_SARADC_SAR1_PATT_TAB2:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表1的项目4~7（每个项目一个字节）*/
#define APB_CTRL_SARADC_SAR1_PATT_TAB2  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB2_M  ((APB_CTRL_SARADC_SAR1_PATT_TAB2_V)<<(APB_CTRL_SARADC_SAR1_PATT_TAB2_S))
#define APB_CTRL_SARADC_SAR1_PATT_TAB2_V  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB2_S  0

#define APB_CTRL_APB_SARADC_SAR1_PATT_TAB3_REG          (DR_REG_APB_CTRL_BASE + 0x24)
/* APB_CTRL_SARADC_SAR1_PATT_TAB3:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表1的项目8~11（每个项目一个字节）*/
#define APB_CTRL_SARADC_SAR1_PATT_TAB3  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB3_M  ((APB_CTRL_SARADC_SAR1_PATT_TAB3_V)<<(APB_CTRL_SARADC_SAR1_PATT_TAB3_S))
#define APB_CTRL_SARADC_SAR1_PATT_TAB3_V  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB3_S  0

#define APB_CTRL_APB_SARADC_SAR1_PATT_TAB4_REG          (DR_REG_APB_CTRL_BASE + 0x28)
/* APB_CTRL_SARADC_SAR1_PATT_TAB4:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表1的项目12~15（每个项目一个字节）*/
#define APB_CTRL_SARADC_SAR1_PATT_TAB4  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB4_M  ((APB_CTRL_SARADC_SAR1_PATT_TAB4_V)<<(APB_CTRL_SARADC_SAR1_PATT_TAB4_S))
#define APB_CTRL_SARADC_SAR1_PATT_TAB4_V  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR1_PATT_TAB4_S  0

#define APB_CTRL_APB_SARADC_SAR2_PATT_TAB1_REG          (DR_REG_APB_CTRL_BASE + 0x2C)
/* APB_CTRL_SARADC_SAR2_PATT_TAB1:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表2的项目0~3（每个项目一个字节）*/
#define APB_CTRL_SARADC_SAR2_PATT_TAB1  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB1_M  ((APB_CTRL_SARADC_SAR2_PATT_TAB1_V)<<(APB_CTRL_SARADC_SAR2_PATT_TAB1_S))
#define APB_CTRL_SARADC_SAR2_PATT_TAB1_V  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB1_S  0

#define APB_CTRL_APB_SARADC_SAR2_PATT_TAB2_REG          (DR_REG_APB_CTRL_BASE + 0x30)
/* APB_CTRL_SARADC_SAR2_PATT_TAB2:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表2的项目4~7（每个项目一个字节）*/
#define APB_CTRL_SARADC_SAR2_PATT_TAB2  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB2_M  ((APB_CTRL_SARADC_SAR2_PATT_TAB2_V)<<(APB_CTRL_SARADC_SAR2_PATT_TAB2_S))
#define APB_CTRL_SARADC_SAR2_PATT_TAB2_V  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB2_S  0

#define APB_CTRL_APB_SARADC_SAR2_PATT_TAB3_REG          (DR_REG_APB_CTRL_BASE + 0x34)
/* APB_CTRL_SARADC_SAR2_PATT_TAB3:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表2的项目8~11（每个项目一个字节）*/
#define APB_CTRL_SARADC_SAR2_PATT_TAB3  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB3_M  ((APB_CTRL_SARADC_SAR2_PATT_TAB3_V)<<(APB_CTRL_SARADC_SAR2_PATT_TAB3_S))
#define APB_CTRL_SARADC_SAR2_PATT_TAB3_V  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB3_S  0

#define APB_CTRL_APB_SARADC_SAR2_PATT_TAB4_REG          (DR_REG_APB_CTRL_BASE + 0x38)
/* APB_CTRL_SARADC_SAR2_PATT_TAB4:R/W；位位置：[31:0]；默认值：32'hf0f0f；*/
/*description:模式表2的项目12~15（每个项目一个字节）*/
#define APB_CTRL_SARADC_SAR2_PATT_TAB4  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB4_M  ((APB_CTRL_SARADC_SAR2_PATT_TAB4_V)<<(APB_CTRL_SARADC_SAR2_PATT_TAB4_S))
#define APB_CTRL_SARADC_SAR2_PATT_TAB4_V  0xFFFFFFFF
#define APB_CTRL_SARADC_SAR2_PATT_TAB4_S  0

#define APB_CTRL_APLL_TICK_CONF_REG          (DR_REG_APB_CTRL_BASE + 0x3C)
/* APB_CTRL_apl_TICK_NUM:R/W；位位置：[7:0]；默认值：8'd99；*/
/*说明：*/
#define APB_CTRL_APLL_TICK_NUM  0x000000FF
#define APB_CTRL_APLL_TICK_NUM_M  ((APB_CTRL_APLL_TICK_NUM_V)<<(APB_CTRL_APLL_TICK_NUM_S))
#define APB_CTRL_APLL_TICK_NUM_V  0xFF
#define APB_CTRL_APLL_TICK_NUM_S  0

#define APB_CTRL_DATE_REG          (DR_REG_APB_CTRL_BASE + 0x7C)
/* APB_CTRL_DATE:R/W；位位置：[31:0]；默认值：32'h16042000；*/
/*说明：*/
#define APB_CTRL_DATE  0xFFFFFFFF
#define APB_CTRL_DATE_M  ((APB_CTRL_DATE_V)<<(APB_CTRL_DATE_S))
#define APB_CTRL_DATE_V  0xFFFFFFFF
#define APB_CTRL_DATE_S  0




#endif /*_SOC_APB_CTRL_REG_H_ */

