/*
 * SPDX文件版权文本：2015-2021浓缩咖啡系统（上海）有限公司
 *
 * SPDX许可证标识符：Apache-2.0
 */
#ifndef _SOC_EFUSE_REG_H_
#define _SOC_EFUSE_REG_H_


#include "soc.h"
#define EFUSE_BLK0_RDATA0_REG          (DR_REG_EFUSE_BASE + 0x000)
/* EFUSE_RD_FLASH_CRYPT_CNT:RO；位位置：[26:20]；默认值：7'b0；*/
/*description:读取flash_crypt_cnt*/
#define EFUSE_RD_FLASH_CRYPT_CNT  0x0000007F
#define EFUSE_RD_FLASH_CRYPT_CNT_M  ((EFUSE_RD_FLASH_CRYPT_CNT_V)<<(EFUSE_RD_FLASH_CRYPT_CNT_S))
#define EFUSE_RD_FLASH_CRYPT_CNT_V  0x7F
#define EFUSE_RD_FLASH_CRYPT_CNT_S  20
/* EFUSE_RD_EFUSE_RD-DIS:RO；比特位置：[19:16]；默认值：4'b0；*/
/*描述：读取efuse_rd_disable*/
#define EFUSE_RD_EFUSE_RD_DIS  0x0000000F
#define EFUSE_RD_EFUSE_RD_DIS_M  ((EFUSE_RD_EFUSE_RD_DIS_V)<<(EFUSE_RD_EFUSE_RD_DIS_S))
#define EFUSE_RD_EFUSE_RD_DIS_V  0xF
#define EFUSE_RD_EFUSE_RD_DIS_S  16

/* efuse块1-3的读取禁用位*/
#define EFUSE_RD_DIS_BLK1 (1<<16)
#define EFUSE_RD_DIS_BLK2 (1<<17)
#define EFUSE_RD_DIS_BLK3 (1<<18)
/* efuse块0中的读取禁用FLASH_CRYPT_CONFIG、CODING_SCHEME和KEY_STATUS
*/
#define EFUSE_RD_DIS_BLK0_PARTIAL (1<<19)

/* EFUSE_RD_EFUSE_WR_DIS:RO；比特位置：[15:0]；默认值：16'b0；*/
/*description:读取efuse_wr_disable*/
#define EFUSE_RD_EFUSE_WR_DIS  0x0000FFFF
#define EFUSE_RD_EFUSE_WR_DIS_M  ((EFUSE_RD_EFUSE_WR_DIS_V)<<(EFUSE_RD_EFUSE_WR_DIS_S))
#define EFUSE_RD_EFUSE_WR_DIS_V  0xFFFF
#define EFUSE_RD_EFUSE_WR_DIS_S  0

/* 写入禁用位*/
#define EFUSE_WR_DIS_RD_DIS (1<<0) /*<禁用写入读取禁用reg*/
#define EFUSE_WR_DIS_WR_DIS (1<<1) /*<禁用写入禁用reg*/
#define EFUSE_WR_DIS_FLASH_CRYPT_CNT (1<<2)
#define EFUSE_WR_DIS_MAC_SPI_CONFIG_HD (1<<3) /*<禁用写入MAC和SPI配置hd efuses*/
#define EFUSE_WR_DIS_XPD_SDIO (1<<5) /*<禁用写入SDIO配置文件*/
#define EFUSE_WR_DIS_SPI_PAD_CONFIG (1<<6) /*<禁用写入SPI_PAD_CONFIG efuses*/
#define EFUSE_WR_DIS_BLK1 (1<<7) /*<禁止写入BLK1 efuses*/
#define EFUSE_WR_DIS_BLK2 (1<<8) /*<禁止写入BLK2 efuses*/
#define EFUSE_WR_DIS_BLK3 (1<<9) /*<禁止写入BLK3 efuses*/
#define EFUSE_WR_DIS_FLASH_CRYPT_CODING_SCHEME (1<<10) /*<禁止写入FLASH_CRYPT_CONFIG和CODING_SCHEME efuses*/
#define EFUSE_WR_DIS_ABS_DONE_0 (1<<12) /*<禁止写入ABS_DONE_0 efuse*/
#define EFUSE_WR_DIS_ABS_DONE_1 (1<<13) /*<禁止写入ABS_DONE_1 efuse*/
#define EFUSE_WR_DIS_JTAG_DISABLE (1<<14) /*<禁用写入JTAG_disable efuse*/
#define EFUSE_WR_DIS_CONSOLE_DL_DISABLE (1<<15) /*<禁用写入CONSOLE_DEBUG_disable、disable_DL_ENCRYPT、disable-DL_DECRYPT和disable_DL-CACHE错误*/

#define EFUSE_BLK0_RDATA1_REG          (DR_REG_EFUSE_BASE + 0x004)
/* EFUSE_RD_WIFI_MAC_CRC_LOW:RO；位位置：[31:0]；默认值：32'b0；*/
/*description:读取低32位WIFIMAC_Address*/
#define EFUSE_RD_WIFI_MAC_CRC_LOW  0xFFFFFFFF
#define EFUSE_RD_WIFI_MAC_CRC_LOW_M  ((EFUSE_RD_WIFI_MAC_CRC_LOW_V)<<(EFUSE_RD_WIFI_MAC_CRC_LOW_S))
#define EFUSE_RD_WIFI_MAC_CRC_LOW_V  0xFFFFFFFF
#define EFUSE_RD_WIFI_MAC_CRC_LOW_S  0

#define EFUSE_BLK0_RDATA2_REG          (DR_REG_EFUSE_BASE + 0x008)
/* EFUSE_RD_WIFI_MAC_CRC_HIGH:RO；比特位置：[23:0]；默认值：24'b0；*/
/*description:读取高24位WIFIMAC_Address*/
#define EFUSE_RD_WIFI_MAC_CRC_HIGH  0x00FFFFFF
#define EFUSE_RD_WIFI_MAC_CRC_HIGH_M  ((EFUSE_RD_WIFI_MAC_CRC_HIGH_V)<<(EFUSE_RD_WIFI_MAC_CRC_HIGH_S))
#define EFUSE_RD_WIFI_MAC_CRC_HIGH_V  0xFFFFFF
#define EFUSE_RD_WIFI_MAC_CRC_HIGH_S  0

#define EFUSE_BLK0_RDATA3_REG          (DR_REG_EFUSE_BASE + 0x00c)
/* EFUSE_RD_CHIP_VER_REV1:R/W；位位置：[15]；默认值：1’b0；*/
/*描述：rev1硅的bit设置为1*/
#define EFUSE_RD_CHIP_VER_REV1  (BIT(15))
#define EFUSE_RD_CHIP_VER_REV1_M  ((EFUSE_RD_CHIP_VER_REV1_V)<<(EFUSE_RD_CHIP_VER_REV1_S))
#define EFUSE_RD_CHIP_VER_REV1_V  0x1
#define EFUSE_RD_CHIP_VER_REV1_S  15
/* EFUSE_RD_BLK3_PART_RESERVE:R/W；位位置：[14]；默认值：1’b0；*/
/*description:如果设置，则该位表示BLOCK3[143:96]保留供内部使用*/
#define EFUSE_RD_BLK3_PART_RESERVE  (BIT(14))
#define EFUSE_RD_BLK3_PART_RESERVE_M  ((EFUSE_RD_BLK3_PART_RESERVE_V)<<(EFUSE_RD_BLK3_PART_RESERVE_S))
#define EFUSE_RD_BLK3_PART_RESERVE_V  0x1
#define EFUSE_RD_BLK3_PART_RESERVE_S  14
/* EFUSE_RD_CHIP_CPU_fred_RATED:R/W；位位置：[13]；默认值：1’b0；*/
/*描述：如果设置，则已对ESP32的最大CPU频率进行评级*/
#define EFUSE_RD_CHIP_CPU_FREQ_RATED  (BIT(13))
#define EFUSE_RD_CHIP_CPU_FREQ_RATED_M  ((EFUSE_RD_CHIP_CPU_FREQ_RATED_V)<<(EFUSE_RD_CHIP_CPU_FREQ_RATED_S))
#define EFUSE_RD_CHIP_CPU_FREQ_RATED_V  0x1
#define EFUSE_RD_CHIP_CPU_FREQ_RATED_S  13
/* EFUSE_RD_CHIP_CPU_req_LOW:R/W；位位置：[12]；默认值：1’b0；*/
/*描述：如果与EFUSE_RD_CHIP_CPU_FREQ_RATED一起设置，则ESP32的最大CPU频率额定为160MHz。240MHz，否则*/
#define EFUSE_RD_CHIP_CPU_FREQ_LOW  (BIT(12))
#define EFUSE_RD_CHIP_CPU_FREQ_LOW_M  ((EFUSE_RD_CHIP_CPU_FREQ_LOW_V)<<(EFUSE_RD_CHIP_CPU_FREQ_LOW_S))
#define EFUSE_RD_CHIP_CPU_FREQ_LOW_V  0x1
#define EFUSE_RD_CHIP_CPU_FREQ_LOW_S  12
/* EFUSE_RD_CHIP_VER_PKG:R/W；比特位置：[11:9]；默认值：3'b0；*/
/*描述：芯片封装的最低有效位*/
#define EFUSE_RD_CHIP_VER_PKG  0x00000007
#define EFUSE_RD_CHIP_VER_PKG_M  ((EFUSE_RD_CHIP_VER_PKG_V)<<(EFUSE_RD_CHIP_VER_PKG_S))
#define EFUSE_RD_CHIP_VER_PKG_V  0x7
#define EFUSE_RD_CHIP_VER_PKG_S  9
#define EFUSE_RD_CHIP_VER_PKG_ESP32D0WDQ6  0
#define EFUSE_RD_CHIP_VER_PKG_ESP32D0WDQ5  1
#define EFUSE_RD_CHIP_VER_PKG_ESP32D2WDQ5  2
#define EFUSE_RD_CHIP_VER_PKG_ESP32PICOD2  4 /* 不推荐：此芯片从未大规模生产*/
#define EFUSE_RD_CHIP_VER_PKG_ESP32U4WDH   4
#define EFUSE_RD_CHIP_VER_PKG_ESP32PICOD4  5
#define EFUSE_RD_CHIP_VER_PKG_ESP32PICOV302  6
#define EFUSE_RD_CHIP_VER_PKG_ESP32D0WDR2V3  7
/* EFUSE_RD_SPI_PAD_CONFIG_HD:RO；比特位置：[8:4]；默认值：5’b0；*/
/*description:读取SPI_pad_config_hd*/
#define EFUSE_RD_SPI_PAD_CONFIG_HD  0x0000001F
#define EFUSE_RD_SPI_PAD_CONFIG_HD_M  ((EFUSE_RD_SPI_PAD_CONFIG_HD_V)<<(EFUSE_RD_SPI_PAD_CONFIG_HD_S))
#define EFUSE_RD_SPI_PAD_CONFIG_HD_V  0x1F
#define EFUSE_RD_SPI_PAD_CONFIG_HD_S  4
/* EFUSE_RD_CHIP_VER_DIS_CACHE:RO；位位置：[3]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_RD_CHIP_VER_DIS_CACHE  (BIT(3))
#define EFUSE_RD_CHIP_VER_DIS_CACHE_M  (BIT(3))
#define EFUSE_RD_CHIP_VER_DIS_CACHE_V  0x1
#define EFUSE_RD_CHIP_VER_DIS_CACHE_S  3
/* EFUSE_RD_CHIP_VER_PKG_4BIT:RO；位位置：[2]；默认值：1’b0；*/
/*描述：芯片封装的最高有效位*/
#define EFUSE_RD_CHIP_VER_PKG_4BIT  (BIT(2))
#define EFUSE_RD_CHIP_VER_PKG_4BIT_M  (BIT(2))
#define EFUSE_RD_CHIP_VER_PKG_4BIT_V  0x1
#define EFUSE_RD_CHIP_VER_PKG_4BIT_S  2
/* EFUSE_RD_CHIP_VER_DIS_BT:RO；位位置：[1]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_RD_CHIP_VER_DIS_BT  (BIT(1))
#define EFUSE_RD_CHIP_VER_DIS_BT_M  (BIT(1))
#define EFUSE_RD_CHIP_VER_DIS_BT_V  0x1
#define EFUSE_RD_CHIP_VER_DIS_BT_S  1
/* EFUSE_RD_CHIP_VER_DIS_APP_CPU:RO；位位置：[0]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_RD_CHIP_VER_DIS_APP_CPU  (BIT(0))
#define EFUSE_RD_CHIP_VER_DIS_APP_CPU_M  (BIT(0))
#define EFUSE_RD_CHIP_VER_DIS_APP_CPU_V  0x1
#define EFUSE_RD_CHIP_VER_DIS_APP_CPU_S  0

#define EFUSE_BLK0_RDATA4_REG          (DR_REG_EFUSE_BASE + 0x010)
/* EFUSE_RD_SDIO_FORCE:RO；位位置：[16]；默认值：1’b0；*/
/*description:读取sdio_force*/
#define EFUSE_RD_SDIO_FORCE  (BIT(16))
#define EFUSE_RD_SDIO_FORCE_M  (BIT(16))
#define EFUSE_RD_SDIO_FORCE_V  0x1
#define EFUSE_RD_SDIO_FORCE_S  16
/* EFUSE_RD_SDIO_TIEH:RO；位位置：[15]；默认值：1’b0；*/
/*description:读取SDIO_TIEH*/
#define EFUSE_RD_SDIO_TIEH  (BIT(15))
#define EFUSE_RD_SDIO_TIEH_M  (BIT(15))
#define EFUSE_RD_SDIO_TIEH_V  0x1
#define EFUSE_RD_SDIO_TIEH_S  15
/* EFUSE_RD_XPD_SDIO_REG:RO；位位置：[14]；默认值：1’b0；*/
/*description:读取XPD_SDIO_REG*/
#define EFUSE_RD_XPD_SDIO_REG  (BIT(14))
#define EFUSE_RD_XPD_SDIO_REG_M  (BIT(14))
#define EFUSE_RD_XPD_SDIO_REG_V  0x1
#define EFUSE_RD_XPD_SDIO_REG_S  14
/* EFUSE_RD_ADC_VREF:R/W；比特位置：[12:8]；默认值：5’b0；*/
/*description:真ADC参考电压*/
#define EFUSE_RD_ADC_VREF  0x0000001F
#define EFUSE_RD_ADC_VREF_M  ((EFUSE_RD_ADC_VREF_V)<<(EFUSE_RD_ADC_VREF_S))
#define EFUSE_RD_ADC_VREF_V  0x1F
#define EFUSE_RD_ADC_VREF_S  8
/* 注意：EFUSE_ADC_VREF和SDIO_DEFH/M/L共享相同的地址空间。较新版本的ESP32附带已刻录的EFUSE_ADC_VREF，因此SDIO_DDREFH/M/L仅在较旧版本的ESP 32中可用*/
/* EFUSE_RD_SDIO_DREFL:RO；比特位置：[13:12]；默认值：2’b0；*/
/*说明：*/
#define EFUSE_RD_SDIO_DREFL  0x00000003
#define EFUSE_RD_SDIO_DREFL_M  ((EFUSE_RD_SDIO_DREFL_V)<<(EFUSE_RD_SDIO_DREFL_S))
#define EFUSE_RD_SDIO_DREFL_V  0x3
#define EFUSE_RD_SDIO_DREFL_S  12
/* EFUSE_RD_SDIO_DREFM:RO；比特位置：[11:10]；默认值：2’b0；*/
/*说明：*/
#define EFUSE_RD_SDIO_DREFM  0x00000003
#define EFUSE_RD_SDIO_DREFM_M  ((EFUSE_RD_SDIO_DREFM_V)<<(EFUSE_RD_SDIO_DREFM_S))
#define EFUSE_RD_SDIO_DREFM_V  0x3
#define EFUSE_RD_SDIO_DREFM_S  10
/* EFUSE_RD_SDIO_DREFH:RO；比特位置：[9:8]；默认值：2’b0；*/
/*说明：*/
#define EFUSE_RD_SDIO_DREFH  0x00000003
#define EFUSE_RD_SDIO_DREFH_M  ((EFUSE_RD_SDIO_DREFH_V)<<(EFUSE_RD_SDIO_DREFH_S))
#define EFUSE_RD_SDIO_DREFH_V  0x3
#define EFUSE_RD_SDIO_DREFH_S  8
/* EFUSE_RD_CK8M_FREQ:RO；位位置：[7:0]；默认值：8'b0；*/
/*说明：*/
#define EFUSE_RD_CK8M_FREQ  0x000000FF
#define EFUSE_RD_CK8M_FREQ_M  ((EFUSE_RD_CK8M_FREQ_V)<<(EFUSE_RD_CK8M_FREQ_S))
#define EFUSE_RD_CK8M_FREQ_V  0xFF
#define EFUSE_RD_CK8M_FREQ_S  0

#define EFUSE_BLK0_RDATA5_REG          (DR_REG_EFUSE_BASE + 0x014)
/* EFUSE_RD_FLASH_CRYPT_CONFIG:RO；位位置：[31:28]；默认值：4'b0；*/
/*description:读取flash_crypt_config*/
#define EFUSE_RD_FLASH_CRYPT_CONFIG  0x0000000F
#define EFUSE_RD_FLASH_CRYPT_CONFIG_M  ((EFUSE_RD_FLASH_CRYPT_CONFIG_V)<<(EFUSE_RD_FLASH_CRYPT_CONFIG_S))
#define EFUSE_RD_FLASH_CRYPT_CONFIG_V  0xF
#define EFUSE_RD_FLASH_CRYPT_CONFIG_S  28
/* EFUSE_RD_DIG_VOL_L6:RO；位位置：[27:24]；*/
/*描述：此字段存储6级数字调节器电压与1.2 V之间的差值。（RO）BIT[27]是符号位，0:+，1:-BIT[26:24]是差值，单位：0.017V volt_lv6=BIT[27]？1.2-位[26:24]0.017:1.2+位[26:26]*0.017*/
#define EFUSE_RD_DIG_VOL_L6          0x0F
#define EFUSE_RD_DIG_VOL_L6_M        ((EFUSE_RD_DIG_VOL_L6_V)<<(EFUSE_RD_DIG_VOL_L6_S))
#define EFUSE_RD_DIG_VOL_L6_V        0x0F
#define EFUSE_RD_DIG_VOL_L6_S        24
/* EFUSE_RD_VOL_LEVEL_HP_INV:RO；位位置：[23:22]*/
/*description:此字段存储CPU以240 MHz运行或闪存/PSRAM以80 MHz运行的电压电平。0x0:级别7；0x1:6级；0x2:5级；0x3:4级。（RO）*/
#define EFUSE_RD_VOL_LEVEL_HP_INV    0x03
#define EFUSE_RD_VOL_LEVEL_HP_INV_M  ((EFUSE_RD_VOL_LEVEL_HP_INV_V)<<(EFUSE_RD_VOL_LEVEL_HP_INV_S))
#define EFUSE_RD_VOL_LEVEL_HP_INV_V  0x03
#define EFUSE_RD_VOL_LEVEL_HP_INV_S  22
/* EFUSE_RD_INST_CONFIG:RO；位位置：[27:20]；默认值：8'b0；*/
/* 已弃用*/
#define EFUSE_RD_INST_CONFIG  0x000000FF                                              /**已弃用**/
#define EFUSE_RD_INST_CONFIG_M  ((EFUSE_RD_INST_CONFIG_V)<<(EFUSE_RD_INST_CONFIG_S))  /**已弃用**/
#define EFUSE_RD_INST_CONFIG_V  0xFF                                                  /**已弃用**/
#define EFUSE_RD_INST_CONFIG_S  20                                                    /**已弃用**/
/* EFUSE_RD_SPI_PAD_CONFIG_CS0:RO；比特位置：[19:15]；默认值：5’b0；*/
/*描述：读取SPI_pad_config_cs0*/
#define EFUSE_RD_SPI_PAD_CONFIG_CS0  0x0000001F
#define EFUSE_RD_SPI_PAD_CONFIG_CS0_M  ((EFUSE_RD_SPI_PAD_CONFIG_CS0_V)<<(EFUSE_RD_SPI_PAD_CONFIG_CS0_S))
#define EFUSE_RD_SPI_PAD_CONFIG_CS0_V  0x1F
#define EFUSE_RD_SPI_PAD_CONFIG_CS0_S  15
/* EFUSE_RD_SPI_PAD_CONFIG_D:RO；比特位置：[14:10]；默认值：5’b0；*/
/*description:读取SPI_pad_config_d*/
#define EFUSE_RD_SPI_PAD_CONFIG_D  0x0000001F
#define EFUSE_RD_SPI_PAD_CONFIG_D_M  ((EFUSE_RD_SPI_PAD_CONFIG_D_V)<<(EFUSE_RD_SPI_PAD_CONFIG_D_S))
#define EFUSE_RD_SPI_PAD_CONFIG_D_V  0x1F
#define EFUSE_RD_SPI_PAD_CONFIG_D_S  10
/* EFUSE_RD_SPI_PAD_CONFIG_Q:RO；比特位置：[9:5]；默认值：5’b0；*/
/*description:读取SPI_pad_config_q*/
#define EFUSE_RD_SPI_PAD_CONFIG_Q  0x0000001F
#define EFUSE_RD_SPI_PAD_CONFIG_Q_M  ((EFUSE_RD_SPI_PAD_CONFIG_Q_V)<<(EFUSE_RD_SPI_PAD_CONFIG_Q_S))
#define EFUSE_RD_SPI_PAD_CONFIG_Q_V  0x1F
#define EFUSE_RD_SPI_PAD_CONFIG_Q_S  5
/* EFUSE_RD_SPI_PAD_CONFIG_CLK:RO；位位置：[4:0]；默认值：5’b0；*/
/*description:读取SPI_pad_config_clk*/
#define EFUSE_RD_SPI_PAD_CONFIG_CLK  0x0000001F
#define EFUSE_RD_SPI_PAD_CONFIG_CLK_M  ((EFUSE_RD_SPI_PAD_CONFIG_CLK_V)<<(EFUSE_RD_SPI_PAD_CONFIG_CLK_S))
#define EFUSE_RD_SPI_PAD_CONFIG_CLK_V  0x1F
#define EFUSE_RD_SPI_PAD_CONFIG_CLK_S  0

#define EFUSE_BLK0_RDATA6_REG          (DR_REG_EFUSE_BASE + 0x018)
/* EFUSE_RD_KEY_STATUS:RO；位位置：[10]；默认值：1’b0；*/
/*description:读取key_status*/
#define EFUSE_RD_KEY_STATUS  (BIT(10))
#define EFUSE_RD_KEY_STATUS_M  (BIT(10))
#define EFUSE_RD_KEY_STATUS_V  0x1
#define EFUSE_RD_KEY_STATUS_S  10
/* EFUSE_RD_DISABLE_DL_CACHE:RO；位位置：[9]；默认值：1’b0；*/
/*description:读取download_dis_cache*/
#define EFUSE_RD_DISABLE_DL_CACHE  (BIT(9))
#define EFUSE_RD_DISABLE_DL_CACHE_M  (BIT(9))
#define EFUSE_RD_DISABLE_DL_CACHE_V  0x1
#define EFUSE_RD_DISABLE_DL_CACHE_S  9
/* EFUSE_RD_DISABLE_DL_DECRYPT:RO；位位置：[8]；默认值：1’b0；*/
/*description:读取download_dis_decrypt*/
#define EFUSE_RD_DISABLE_DL_DECRYPT  (BIT(8))
#define EFUSE_RD_DISABLE_DL_DECRYPT_M  (BIT(8))
#define EFUSE_RD_DISABLE_DL_DECRYPT_V  0x1
#define EFUSE_RD_DISABLE_DL_DECRYPT_S  8
/* EFUSE_RD_DISABLE_DL_ENCRYPT:RO；位位置：[7]；默认值：1’b0；*/
/*description:读取download_dis_encrypt*/
#define EFUSE_RD_DISABLE_DL_ENCRYPT  (BIT(7))
#define EFUSE_RD_DISABLE_DL_ENCRYPT_M  (BIT(7))
#define EFUSE_RD_DISABLE_DL_ENCRYPT_V  0x1
#define EFUSE_RD_DISABLE_DL_ENCRYPT_S  7
/* EFUSE_RD_DISABLE_JTAG:RO；位位置：[6]；默认值：1’b0；*/
/*description:读取JTAG_disable*/
#define EFUSE_RD_DISABLE_JTAG  (BIT(6))
#define EFUSE_RD_DISABLE_JTAG_M  (BIT(6))
#define EFUSE_RD_DISABLE_JTAG_V  0x1
#define EFUSE_RD_DISABLE_JTAG_S  6
/* EFUSE_RD_ABS_DONE_1:RO；位位置：[5]；默认值：1’b0；*/
/*description:读取abstract_done1*/
#define EFUSE_RD_ABS_DONE_1  (BIT(5))
#define EFUSE_RD_ABS_DONE_1_M  (BIT(5))
#define EFUSE_RD_ABS_DONE_1_V  0x1
#define EFUSE_RD_ABS_DONE_1_S  5
/* EFUSE_RD_ABS_DONE_0:RO；位位置：[4]；默认值：1’b0；*/
/*description:阅读abstract_done_0*/
#define EFUSE_RD_ABS_DONE_0  (BIT(4))
#define EFUSE_RD_ABS_DONE_0_M  (BIT(4))
#define EFUSE_RD_ABS_DONE_0_V  0x1
#define EFUSE_RD_ABS_DONE_0_S  4
/* EFUSE_RD_DISABLE_SDIO_HOST:RO；位位置：[3]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_RD_DISABLE_SDIO_HOST  (BIT(3))
#define EFUSE_RD_DISABLE_SDIO_HOST_M  (BIT(3))
#define EFUSE_RD_DISABLE_SDIO_HOST_V  0x1
#define EFUSE_RD_DISABLE_SDIO_HOST_S  3
/* EFUSE_RD_CONSOLE_DEBUG_DISABLE:RO；位位置：[2]；默认值：1’b0；*/
/*description:读取console_debug_disable*/
#define EFUSE_RD_CONSOLE_DEBUG_DISABLE  (BIT(2))
#define EFUSE_RD_CONSOLE_DEBUG_DISABLE_M  (BIT(2))
#define EFUSE_RD_CONSOLE_DEBUG_DISABLE_V  0x1
#define EFUSE_RD_CONSOLE_DEBUG_DISABLE_S  2
/* EFUSE_RD_CODING_SCHEME:RO；位位置：[1:0]；默认值：2’b0；*/
/*description:读取coding_scheme*/
#define EFUSE_RD_CODING_SCHEME  0x00000003
#define EFUSE_RD_CODING_SCHEME_M  ((EFUSE_RD_CODING_SCHEME_V)<<(EFUSE_RD_CODING_SCHEME_S))
#define EFUSE_RD_CODING_SCHEME_V  0x3
#define EFUSE_RD_CODING_SCHEME_S  0

#define EFUSE_CODING_SCHEME_VAL_NONE 0x0
#define EFUSE_CODING_SCHEME_VAL_34   0x1
#define EFUSE_CODING_SCHEME_VAL_REPEAT   0x2

#define EFUSE_BLK0_WDATA0_REG          (DR_REG_EFUSE_BASE + 0x01c)
/* EFUSE_FLASH_CRYPT_CNT:R/W；位位置：[26:20]；默认值：7'b0；*/
/*description:flash_cryptcnt程序*/
#define EFUSE_FLASH_CRYPT_CNT  0x0000007F
#define EFUSE_FLASH_CRYPT_CNT_M  ((EFUSE_FLASH_CRYPT_CNT_V)<<(EFUSE_FLASH_CRYPT_CNT_S))
#define EFUSE_FLASH_CRYPT_CNT_V  0x7F
#define EFUSE_FLASH_CRYPT_CNT_S  20
/* EFUSE_RD_DIS:R/W；比特位置：[19:16]；默认值：4'b0；*/
/*描述：efuse_rd_disable程序*/
#define EFUSE_RD_DIS  0x0000000F
#define EFUSE_RD_DIS_M  ((EFUSE_RD_DIS_V)<<(EFUSE_RD_DIS_S))
#define EFUSE_RD_DIS_V  0xF
#define EFUSE_RD_DIS_S  16
/* EFUSE_WR_DIS:R/W；比特位置：[15:0]；默认值：16'b0；*/
/*描述：efuse_wr_disable程序*/
#define EFUSE_WR_DIS  0x0000FFFF
#define EFUSE_WR_DIS_M  ((EFUSE_WR_DIS_V)<<(EFUSE_WR_DIS_S))
#define EFUSE_WR_DIS_V  0xFFFF
#define EFUSE_WR_DIS_S  0

#define EFUSE_BLK0_WDATA1_REG          (DR_REG_EFUSE_BASE + 0x020)
/* EFUSE_WIFI_MAC_ccrc_LOW:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:低32位WIFIMAC_Address程序*/
#define EFUSE_WIFI_MAC_CRC_LOW  0xFFFFFFFF
#define EFUSE_WIFI_MAC_CRC_LOW_M  ((EFUSE_WIFI_MAC_CRC_LOW_V)<<(EFUSE_WIFI_MAC_CRC_LOW_S))
#define EFUSE_WIFI_MAC_CRC_LOW_V  0xFFFFFFFF
#define EFUSE_WIFI_MAC_CRC_LOW_S  0

#define EFUSE_BLK0_WDATA2_REG          (DR_REG_EFUSE_BASE + 0x024)
/* EFUSE_WIFI_MAC_CRC_HIGH:R/W；比特位置：[23:0]；默认值：24'b0；*/
/*description:高24位WIFIMAC_Address程序*/
#define EFUSE_WIFI_MAC_CRC_HIGH  0x00FFFFFF
#define EFUSE_WIFI_MAC_CRC_HIGH_M  ((EFUSE_WIFI_MAC_CRC_HIGH_V)<<(EFUSE_WIFI_MAC_CRC_HIGH_S))
#define EFUSE_WIFI_MAC_CRC_HIGH_V  0xFFFFFF
#define EFUSE_WIFI_MAC_CRC_HIGH_S  0

#define EFUSE_BLK0_WDATA3_REG          (DR_REG_EFUSE_BASE + 0x028)
/* EFUSE_CHIP_VER_REV1:R/W；位位置：[15]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_CHIP_VER_REV1  (BIT(15))
#define EFUSE_CHIP_VER_REV1_M  ((EFUSE_CHIP_VER_REV1_V)<<(EFUSE_CHIP_VER_REV1_S))
#define EFUSE_CHIP_VER_REV1_V  0x1
#define EFUSE_CHIP_VER_REV1_S  15
/* EFUSE_BLK3_PART_RESERVE:R/W；位位置：[14]；默认值：1’b0；*/
/*description:如果设置，则该位表示BLOCK3[143:96]保留供内部使用*/
#define EFUSE_BLK3_PART_RESERVE  (BIT(14))
#define EFUSE_BLK3_PART_RESERVE_M  ((EFUSE_BLK3_PART_RESERVE_V)<<(EFUSE_BLK3_PART_RESERVE_S))
#define EFUSE_BLK3_PART_RESERVE_V  0x1
#define EFUSE_BLK3_PART_RESERVE_S  14
/* EFUSE_CHIP_CPU_FREQ_RATED:R/W；位位置：[13]；默认值：1’b0；*/
/*描述：如果设置，则已对ESP32的最大CPU频率进行评级*/
#define EFUSE_CHIP_CPU_FREQ_RATED  (BIT(13))
#define EFUSE_CHIP_CPU_FREQ_RATED_M  ((EFUSE_CHIP_CPU_FREQ_RATED_V)<<(EFUSE_CHIP_CPU_FREQ_RATED_S))
#define EFUSE_CHIP_CPU_FREQ_RATED_V  0x1
#define EFUSE_CHIP_CPU_FREQ_RATED_S  13
/* EFUSE_CHIP_CPU_FREQ_LOW:R/W；位位置：[12]；默认值：1’b0；*/
/*描述：如果与EFUSE_CHIP_CPU_FREQ_RATED一起设置，则ESP32的最大CPU频率额定为160MHz。240MHz，否则*/
#define EFUSE_CHIP_CPU_FREQ_LOW  (BIT(12))
#define EFUSE_CHIP_CPU_FREQ_LOW_M  ((EFUSE_CHIP_CPU_FREQ_LOW_V)<<(EFUSE_CHIP_CPU_FREQ_LOW_S))
#define EFUSE_CHIP_CPU_FREQ_LOW_V  0x1
#define EFUSE_CHIP_CPU_FREQ_LOW_S  12
/* EFUSE_CHIP_VER_PKG：R/W；比特位置：[11:9]；默认值：3'b0；*/
/*描述：芯片封装的最低有效位*/
#define EFUSE_CHIP_VER_PKG  0x00000007
#define EFUSE_CHIP_VER_PKG_M  ((EFUSE_CHIP_VER_PKG_V)<<(EFUSE_CHIP_VER_PKG_S))
#define EFUSE_CHIP_VER_PKG_V  0x7
#define EFUSE_CHIP_VER_PKG_S  9
#define EFUSE_CHIP_VER_PKG_ESP32D0WDQ6  0
#define EFUSE_CHIP_VER_PKG_ESP32D0WDQ5  1
#define EFUSE_CHIP_VER_PKG_ESP32D2WDQ5  2
#define EFUSE_CHIP_VER_PKG_ESP32PICOD2  4
#define EFUSE_CHIP_VER_PKG_ESP32PICOD4  5
#define EFUSE_CHIP_VER_PKG_ESP32PICOV302  6
/* EFUSE_SPI_PAD_CONFIG_HD:R/W；比特位置：[8:4]；默认值：5’b0；*/
/*description:SPI_pad_config_hd的程序*/
#define EFUSE_SPI_PAD_CONFIG_HD  0x0000001F
#define EFUSE_SPI_PAD_CONFIG_HD_M  ((EFUSE_SPI_PAD_CONFIG_HD_V)<<(EFUSE_SPI_PAD_CONFIG_HD_S))
#define EFUSE_SPI_PAD_CONFIG_HD_V  0x1F
#define EFUSE_SPI_PAD_CONFIG_HD_S  4
/* EFUSE_CHIP_VER_DIS_CACHE:R/W；位位置：[3]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_CHIP_VER_DIS_CACHE  (BIT(3))
#define EFUSE_CHIP_VER_DIS_CACHE_M  (BIT(3))
#define EFUSE_CHIP_VER_DIS_CACHE_V  0x1
#define EFUSE_CHIP_VER_DIS_CACHE_S  3
/* EFUSE_CHIP_VER_PKG_4BIT:RO；位位置：[2]；默认值：1’b0；*/
/*描述：芯片封装的最高有效位*/
#define EFUSE_CHIP_VER_PKG_4BIT  (BIT(2))
#define EFUSE_CHIP_VER_PKG_4BIT_M  (BIT(2))
#define EFUSE_CHIP_VER_PKG_4BIT_V  0x1
#define EFUSE_CHIP_VER_PKG_4BIT_S  2
/* EFUSE_CHIP_VER_DIS_BT:R/W；位位置：[1]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_CHIP_VER_DIS_BT  (BIT(1))
#define EFUSE_CHIP_VER_DIS_BT_M  (BIT(1))
#define EFUSE_CHIP_VER_DIS_BT_V  0x1
#define EFUSE_CHIP_VER_DIS_BT_S  1
/* EFUSE_CHIP_VER_DIS_APP_CPU:R/W；位位置：[0]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_CHIP_VER_DIS_APP_CPU  (BIT(0))
#define EFUSE_CHIP_VER_DIS_APP_CPU_M  (BIT(0))
#define EFUSE_CHIP_VER_DIS_APP_CPU_V  0x1
#define EFUSE_CHIP_VER_DIS_APP_CPU_S  0

#define EFUSE_BLK0_WDATA4_REG          (DR_REG_EFUSE_BASE + 0x02c)
/* EFUSE_SDIO_FORCE:R/W；位位置：[16]；默认值：1’b0；*/
/*description:sdio_force程序*/
#define EFUSE_SDIO_FORCE  (BIT(16))
#define EFUSE_SDIO_FORCE_M  (BIT(16))
#define EFUSE_SDIO_FORCE_V  0x1
#define EFUSE_SDIO_FORCE_S  16
/* EFUSE_SDIO_TIEH:R/W；位位置：[15]；默认值：1’b0；*/
/*描述：SDIO_TIEH程序*/
#define EFUSE_SDIO_TIEH  (BIT(15))
#define EFUSE_SDIO_TIEH_M  (BIT(15))
#define EFUSE_SDIO_TIEH_V  0x1
#define EFUSE_SDIO_TIEH_S  15
/* EFUSE_XPD_SDIO_REG:R/W；位位置：[14]；默认值：1’b0；*/
/*description:XPD_SDIO_REG的程序*/
#define EFUSE_XPD_SDIO_REG  (BIT(14))
#define EFUSE_XPD_SDIO_REG_M  (BIT(14))
#define EFUSE_XPD_SDIO_REG_V  0x1
#define EFUSE_XPD_SDIO_REG_S  14
/* EFUSE_ADC_VREF：R/W；比特位置：[12:8]；默认值：5’b0；*/
/*description:真ADC参考电压*/
#define EFUSE_ADC_VREF  0x0000001F
#define EFUSE_ADC_VREF_M  ((EFUSE_ADC_VREF_V)<<(EFUSE_ADC_VREF_S))
#define EFUSE_ADC_VREF_V  0x1F
#define EFUSE_ADC_VREF_S  8
/* 注意：EFUSE_ADC_VREF和SDIO_DEFH/M/L共享相同的地址空间。较新版本的ESP32附带已刻录的EFUSE_ADC_VREF，因此SDIO_DDREFH/M/L仅在较旧版本的ESP 32中可用*/
/* EFUSE_SDIO_refl:R/W；比特位置：[13:12]；默认值：2’b0；*/
/*说明：*/
#define EFUSE_SDIO_DREFL  0x00000003
#define EFUSE_SDIO_DREFL_M  ((EFUSE_SDIO_DREFL_V)<<(EFUSE_SDIO_DREFL_S))
#define EFUSE_SDIO_DREFL_V  0x3
#define EFUSE_SDIO_DREFL_S  12
/* EFUSE_SDIO_refm:R/W；比特位置：[11:10]；默认值：2’b0；*/
/*说明：*/
#define EFUSE_SDIO_DREFM  0x00000003
#define EFUSE_SDIO_DREFM_M  ((EFUSE_SDIO_DREFM_V)<<(EFUSE_SDIO_DREFM_S))
#define EFUSE_SDIO_DREFM_V  0x3
#define EFUSE_SDIO_DREFM_S  10
/* EFUSE_SDIO_refh:R/W；比特位置：[9:8]；默认值：2’b0；*/
/*说明：*/
#define EFUSE_SDIO_DREFH  0x00000003
#define EFUSE_SDIO_DREFH_M  ((EFUSE_SDIO_DREFH_V)<<(EFUSE_SDIO_DREFH_S))
#define EFUSE_SDIO_DREFH_V  0x3
#define EFUSE_SDIO_DREFH_S  8
/* EFUSE_CK8M_FREQ:R/W；位位置：[7:0]；默认值：8'b0；*/
/*说明：*/
#define EFUSE_CK8M_FREQ  0x000000FF
#define EFUSE_CK8M_FREQ_M  ((EFUSE_CK8M_FREQ_V)<<(EFUSE_CK8M_FREQ_S))
#define EFUSE_CK8M_FREQ_V  0xFF
#define EFUSE_CK8M_FREQ_S  0

#define EFUSE_BLK0_WDATA5_REG          (DR_REG_EFUSE_BASE + 0x030)
/* EFUSE_FLASH_CRYPT_CONFIG:R/W；位位置：[31:28]；默认值：4'b0；*/
/*description:flash_crypt_config程序*/
#define EFUSE_FLASH_CRYPT_CONFIG  0x0000000F
#define EFUSE_FLASH_CRYPT_CONFIG_M  ((EFUSE_FLASH_CRYPT_CONFIG_V)<<(EFUSE_FLASH_CRYPT_CONFIG_S))
#define EFUSE_FLASH_CRYPT_CONFIG_V  0xF
#define EFUSE_FLASH_CRYPT_CONFIG_S  28
/* EFUSE_DIG_VOL_L6:R/W；位位置：[27:24]；*/
/*描述：此字段存储6级数字调节器电压与1.2 V之间的差值。（R/W）BIT[27]是符号位，0:+，1:-BIT[26:24]是差值，单位：0.017V volt_lv6=BIT[27]？1.2-位[26:24]0.017:1.2+位[26:26]*0.017*/
#define EFUSE_DIG_VOL_L6            0x0F
#define EFUSE_DIG_VOL_L6_M          ((EFUSE_RD_DIG_VOL_L6_V)<<(EFUSE_RD_DIG_VOL_L6_S))
#define EFUSE_DIG_VOL_L6_V          0x0F
#define EFUSE_DIG_VOL_L6_S          24
/* EFUSE_VOL_LEVEL_HP_INV:R/W；位位置：[23:22]*/
/*description:此字段存储CPU以240 MHz运行或闪存/PSRAM以80 MHz运行的电压电平。0x0:level 7；0x1:6级；0x2:5级；0x3:4级。（R/W）*/
#define EFUSE_VOL_LEVEL_HP_INV      0x03
#define EFUSE_VOL_LEVEL_HP_INV_M    ((EFUSE_RD_VOL_LEVEL_HP_INV_V)<<(EFUSE_RD_VOL_LEVEL_HP_INV_S))
#define EFUSE_VOL_LEVEL_HP_INV_V    0x03
#define EFUSE_VOL_LEVEL_HP_INV_S    22
/* EFUSE_INST_CONFIG:R/W；位位置：[27:20]；默认值：8'b0；*/
/* 已弃用*/
#define EFUSE_INST_CONFIG  0x000000FF                                        /**已弃用**/
#define EFUSE_INST_CONFIG_M  ((EFUSE_INST_CONFIG_V)<<(EFUSE_INST_CONFIG_S))  /**已弃用**/
#define EFUSE_INST_CONFIG_V  0xFF                                            /**已弃用**/
#define EFUSE_INST_CONFIG_S  20                                              /**已弃用**/
/* EFUSE_SPI_PAD_CONFIG_CS0:R/W；比特位置：[19:15]；默认值：5’b0；*/
/*描述：SPI_pad_config_cs0的程序*/
#define EFUSE_SPI_PAD_CONFIG_CS0  0x0000001F
#define EFUSE_SPI_PAD_CONFIG_CS0_M  ((EFUSE_SPI_PAD_CONFIG_CS0_V)<<(EFUSE_SPI_PAD_CONFIG_CS0_S))
#define EFUSE_SPI_PAD_CONFIG_CS0_V  0x1F
#define EFUSE_SPI_PAD_CONFIG_CS0_S  15
/* EFUSE_SPI_PAD_CONFIG_D:R/W；比特位置：[14:10]；默认值：5’b0；*/
/*description:SPI_pad_config_d的程序*/
#define EFUSE_SPI_PAD_CONFIG_D  0x0000001F
#define EFUSE_SPI_PAD_CONFIG_D_M  ((EFUSE_SPI_PAD_CONFIG_D_V)<<(EFUSE_SPI_PAD_CONFIG_D_S))
#define EFUSE_SPI_PAD_CONFIG_D_V  0x1F
#define EFUSE_SPI_PAD_CONFIG_D_S  10
/* EFUSE_SPI_PAD_CONFIG_Q:R/W；比特位置：[9:5]；默认值：5’b0；*/
/*description:SPI_pad_config_q的程序*/
#define EFUSE_SPI_PAD_CONFIG_Q  0x0000001F
#define EFUSE_SPI_PAD_CONFIG_Q_M  ((EFUSE_SPI_PAD_CONFIG_Q_V)<<(EFUSE_SPI_PAD_CONFIG_Q_S))
#define EFUSE_SPI_PAD_CONFIG_Q_V  0x1F
#define EFUSE_SPI_PAD_CONFIG_Q_S  5
/* EFUSE_SPI_PAD_CONFIG_CLK:R/W；位位置：[4:0]；默认值：5’b0；*/
/*description:SPI_pad_config_clk的程序*/
#define EFUSE_SPI_PAD_CONFIG_CLK  0x0000001F
#define EFUSE_SPI_PAD_CONFIG_CLK_M  ((EFUSE_SPI_PAD_CONFIG_CLK_V)<<(EFUSE_SPI_PAD_CONFIG_CLK_S))
#define EFUSE_SPI_PAD_CONFIG_CLK_V  0x1F
#define EFUSE_SPI_PAD_CONFIG_CLK_S  0

#define EFUSE_BLK0_WDATA6_REG          (DR_REG_EFUSE_BASE + 0x034)
/* EFUSE_KEY_STATUS:R/W；位位置：[10]；默认值：1’b0；*/
/*description:key_status程序*/
#define EFUSE_KEY_STATUS  (BIT(10))
#define EFUSE_KEY_STATUS_M  (BIT(10))
#define EFUSE_KEY_STATUS_V  0x1
#define EFUSE_KEY_STATUS_S  10
/* EFUSE_DISABLE_DL_CACHE：R/W；位位置：[9]；默认值：1’b0；*/
/*description:download_dis_cache程序*/
#define EFUSE_DISABLE_DL_CACHE  (BIT(9))
#define EFUSE_DISABLE_DL_CACHE_M  (BIT(9))
#define EFUSE_DISABLE_DL_CACHE_V  0x1
#define EFUSE_DISABLE_DL_CACHE_S  9
/* EFUSE_DISABLE_DL_DECRYPT：R/W；位位置：[8]；默认值：1’b0；*/
/*description:download_dis_decrypt程序*/
#define EFUSE_DISABLE_DL_DECRYPT  (BIT(8))
#define EFUSE_DISABLE_DL_DECRYPT_M  (BIT(8))
#define EFUSE_DISABLE_DL_DECRYPT_V  0x1
#define EFUSE_DISABLE_DL_DECRYPT_S  8
/* EFUSE_DISABLE_DL_ENCRYPT：R/W；位位置：[7]；默认值：1’b0；*/
/*description:download_dis_encrypt程序*/
#define EFUSE_DISABLE_DL_ENCRYPT  (BIT(7))
#define EFUSE_DISABLE_DL_ENCRYPT_M  (BIT(7))
#define EFUSE_DISABLE_DL_ENCRYPT_V  0x1
#define EFUSE_DISABLE_DL_ENCRYPT_S  7
/* EFUSE_DISABLE_JTAG:R/W；位位置：[6]；默认值：1’b0；*/
/*描述：JTAG_disable程序*/
#define EFUSE_DISABLE_JTAG  (BIT(6))
#define EFUSE_DISABLE_JTAG_M  (BIT(6))
#define EFUSE_DISABLE_JTAG_V  0x1
#define EFUSE_DISABLE_JTAG_S  6
/* EFUSE_ABS_DONE_1:R/W；位位置：[5]；默认值：1’b0；*/
/*description:abstract_done1程序*/
#define EFUSE_ABS_DONE_1  (BIT(5))
#define EFUSE_ABS_DONE_1_M  (BIT(5))
#define EFUSE_ABS_DONE_1_V  0x1
#define EFUSE_ABS_DONE_1_S  5
/* EFUSE_ABS_DONE_0:R/W；位位置：[4]；默认值：1’b0；*/
/*description:abstract_done0程序*/
#define EFUSE_ABS_DONE_0  (BIT(4))
#define EFUSE_ABS_DONE_0_M  (BIT(4))
#define EFUSE_ABS_DONE_0_V  0x1
#define EFUSE_ABS_DONE_0_S  4
/* EFUSE_DISABLE_SDIO_HOST:R/W；位位置：[3]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_DISABLE_SDIO_HOST  (BIT(3))
#define EFUSE_DISABLE_SDIO_HOST_M  (BIT(3))
#define EFUSE_DISABLE_SDIO_HOST_V  0x1
#define EFUSE_DISABLE_SDIO_HOST_S  3
/* EFUSE_CONSOLE_DEBUG_DISABLE:R/W；位位置：[2]；默认值：1’b0；*/
/*description:console_debug_disable程序*/
#define EFUSE_CONSOLE_DEBUG_DISABLE  (BIT(2))
#define EFUSE_CONSOLE_DEBUG_DISABLE_M  (BIT(2))
#define EFUSE_CONSOLE_DEBUG_DISABLE_V  0x1
#define EFUSE_CONSOLE_DEBUG_DISABLE_S  2
/* EFUSE_CODING_SCHEME:R/W；位位置：[1:0]；默认值：2’b0；*/
/*description:coding_scheme程序*/
#define EFUSE_CODING_SCHEME  0x00000003
#define EFUSE_CODING_SCHEME_M  ((EFUSE_CODING_SCHEME_V)<<(EFUSE_CODING_SCHEME_S))
#define EFUSE_CODING_SCHEME_V  0x3
#define EFUSE_CODING_SCHEME_S  0

#define EFUSE_BLK1_RDATA0_REG          (DR_REG_EFUSE_BASE + 0x038)
/* EFUSE_BLK1_DOUT0:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK1*/
#define EFUSE_BLK1_DOUT0  0xFFFFFFFF
#define EFUSE_BLK1_DOUT0_M  ((EFUSE_BLK1_DOUT0_V)<<(EFUSE_BLK1_DOUT0_S))
#define EFUSE_BLK1_DOUT0_V  0xFFFFFFFF
#define EFUSE_BLK1_DOUT0_S  0

#define EFUSE_BLK1_RDATA1_REG          (DR_REG_EFUSE_BASE + 0x03c)
/* EFUSE_BLK1_DOUT1:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK1*/
#define EFUSE_BLK1_DOUT1  0xFFFFFFFF
#define EFUSE_BLK1_DOUT1_M  ((EFUSE_BLK1_DOUT1_V)<<(EFUSE_BLK1_DOUT1_S))
#define EFUSE_BLK1_DOUT1_V  0xFFFFFFFF
#define EFUSE_BLK1_DOUT1_S  0

#define EFUSE_BLK1_RDATA2_REG          (DR_REG_EFUSE_BASE + 0x040)
/* EFUSE_BLK1_DOUT2:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK1*/
#define EFUSE_BLK1_DOUT2  0xFFFFFFFF
#define EFUSE_BLK1_DOUT2_M  ((EFUSE_BLK1_DOUT2_V)<<(EFUSE_BLK1_DOUT2_S))
#define EFUSE_BLK1_DOUT2_V  0xFFFFFFFF
#define EFUSE_BLK1_DOUT2_S  0

#define EFUSE_BLK1_RDATA3_REG          (DR_REG_EFUSE_BASE + 0x044)
/* EFUSE_BLK1_DOUT3:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK1*/
#define EFUSE_BLK1_DOUT3  0xFFFFFFFF
#define EFUSE_BLK1_DOUT3_M  ((EFUSE_BLK1_DOUT3_V)<<(EFUSE_BLK1_DOUT3_S))
#define EFUSE_BLK1_DOUT3_V  0xFFFFFFFF
#define EFUSE_BLK1_DOUT3_S  0

#define EFUSE_BLK1_RDATA4_REG          (DR_REG_EFUSE_BASE + 0x048)
/* EFUSE_BLK1_DOUT4:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK1*/
#define EFUSE_BLK1_DOUT4  0xFFFFFFFF
#define EFUSE_BLK1_DOUT4_M  ((EFUSE_BLK1_DOUT4_V)<<(EFUSE_BLK1_DOUT4_S))
#define EFUSE_BLK1_DOUT4_V  0xFFFFFFFF
#define EFUSE_BLK1_DOUT4_S  0

#define EFUSE_BLK1_RDATA5_REG          (DR_REG_EFUSE_BASE + 0x04c)
/* EFUSE_BLK1_DOUT5:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK1*/
#define EFUSE_BLK1_DOUT5  0xFFFFFFFF
#define EFUSE_BLK1_DOUT5_M  ((EFUSE_BLK1_DOUT5_V)<<(EFUSE_BLK1_DOUT5_S))
#define EFUSE_BLK1_DOUT5_V  0xFFFFFFFF
#define EFUSE_BLK1_DOUT5_S  0

#define EFUSE_BLK1_RDATA6_REG          (DR_REG_EFUSE_BASE + 0x050)
/* EFUSE_BLK1_DOUT6:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK1*/
#define EFUSE_BLK1_DOUT6  0xFFFFFFFF
#define EFUSE_BLK1_DOUT6_M  ((EFUSE_BLK1_DOUT6_V)<<(EFUSE_BLK1_DOUT6_S))
#define EFUSE_BLK1_DOUT6_V  0xFFFFFFFF
#define EFUSE_BLK1_DOUT6_S  0

#define EFUSE_BLK1_RDATA7_REG          (DR_REG_EFUSE_BASE + 0x054)
/* EFUSE_BLK1_DOUT7:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK1*/
#define EFUSE_BLK1_DOUT7  0xFFFFFFFF
#define EFUSE_BLK1_DOUT7_M  ((EFUSE_BLK1_DOUT7_V)<<(EFUSE_BLK1_DOUT7_S))
#define EFUSE_BLK1_DOUT7_V  0xFFFFFFFF
#define EFUSE_BLK1_DOUT7_S  0

#define EFUSE_BLK2_RDATA0_REG          (DR_REG_EFUSE_BASE + 0x058)
/* EFUSE_BLK2_DOUT0:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK2*/
#define EFUSE_BLK2_DOUT0  0xFFFFFFFF
#define EFUSE_BLK2_DOUT0_M  ((EFUSE_BLK2_DOUT0_V)<<(EFUSE_BLK2_DOUT0_S))
#define EFUSE_BLK2_DOUT0_V  0xFFFFFFFF
#define EFUSE_BLK2_DOUT0_S  0

#define EFUSE_BLK2_RDATA1_REG          (DR_REG_EFUSE_BASE + 0x05c)
/* EFUSE_BLK2_DOUT1:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK2*/
#define EFUSE_BLK2_DOUT1  0xFFFFFFFF
#define EFUSE_BLK2_DOUT1_M  ((EFUSE_BLK2_DOUT1_V)<<(EFUSE_BLK2_DOUT1_S))
#define EFUSE_BLK2_DOUT1_V  0xFFFFFFFF
#define EFUSE_BLK2_DOUT1_S  0

#define EFUSE_BLK2_RDATA2_REG          (DR_REG_EFUSE_BASE + 0x060)
/* EFUSE_BLK2_DOUT2:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK2*/
#define EFUSE_BLK2_DOUT2  0xFFFFFFFF
#define EFUSE_BLK2_DOUT2_M  ((EFUSE_BLK2_DOUT2_V)<<(EFUSE_BLK2_DOUT2_S))
#define EFUSE_BLK2_DOUT2_V  0xFFFFFFFF
#define EFUSE_BLK2_DOUT2_S  0

#define EFUSE_BLK2_RDATA3_REG          (DR_REG_EFUSE_BASE + 0x064)
/* EFUSE_BLK2_DOUT3:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK2*/
#define EFUSE_BLK2_DOUT3  0xFFFFFFFF
#define EFUSE_BLK2_DOUT3_M  ((EFUSE_BLK2_DOUT3_V)<<(EFUSE_BLK2_DOUT3_S))
#define EFUSE_BLK2_DOUT3_V  0xFFFFFFFF
#define EFUSE_BLK2_DOUT3_S  0

#define EFUSE_BLK2_RDATA4_REG          (DR_REG_EFUSE_BASE + 0x068)
/* EFUSE_BLK2_DOUT4:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK2*/
#define EFUSE_BLK2_DOUT4  0xFFFFFFFF
#define EFUSE_BLK2_DOUT4_M  ((EFUSE_BLK2_DOUT4_V)<<(EFUSE_BLK2_DOUT4_S))
#define EFUSE_BLK2_DOUT4_V  0xFFFFFFFF
#define EFUSE_BLK2_DOUT4_S  0

#define EFUSE_BLK2_RDATA5_REG          (DR_REG_EFUSE_BASE + 0x06c)
/* EFUSE_BLK2_DOUT5:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK2*/
#define EFUSE_BLK2_DOUT5  0xFFFFFFFF
#define EFUSE_BLK2_DOUT5_M  ((EFUSE_BLK2_DOUT5_V)<<(EFUSE_BLK2_DOUT5_S))
#define EFUSE_BLK2_DOUT5_V  0xFFFFFFFF
#define EFUSE_BLK2_DOUT5_S  0

#define EFUSE_BLK2_RDATA6_REG          (DR_REG_EFUSE_BASE + 0x070)
/* EFUSE_BLK2_DOUT6:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK2*/
#define EFUSE_BLK2_DOUT6  0xFFFFFFFF
#define EFUSE_BLK2_DOUT6_M  ((EFUSE_BLK2_DOUT6_V)<<(EFUSE_BLK2_DOUT6_S))
#define EFUSE_BLK2_DOUT6_V  0xFFFFFFFF
#define EFUSE_BLK2_DOUT6_S  0

#define EFUSE_BLK2_RDATA7_REG          (DR_REG_EFUSE_BASE + 0x074)
/* EFUSE_BLK2_DOUT7:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK2*/
#define EFUSE_BLK2_DOUT7  0xFFFFFFFF
#define EFUSE_BLK2_DOUT7_M  ((EFUSE_BLK2_DOUT7_V)<<(EFUSE_BLK2_DOUT7_S))
#define EFUSE_BLK2_DOUT7_V  0xFFFFFFFF
#define EFUSE_BLK2_DOUT7_S  0

#define EFUSE_BLK3_RDATA0_REG          (DR_REG_EFUSE_BASE + 0x078)
/* EFUSE_BLK3_DOUT0:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK3*/
#define EFUSE_BLK3_DOUT0  0xFFFFFFFF
#define EFUSE_BLK3_DOUT0_M  ((EFUSE_BLK3_DOUT0_V)<<(EFUSE_BLK3_DOUT0_S))
#define EFUSE_BLK3_DOUT0_V  0xFFFFFFFF
#define EFUSE_BLK3_DOUT0_S  0

#define EFUSE_BLK3_RDATA1_REG          (DR_REG_EFUSE_BASE + 0x07c)
/* EFUSE_BLK3_DOUT1:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK3*/
#define EFUSE_BLK3_DOUT1  0xFFFFFFFF
#define EFUSE_BLK3_DOUT1_M  ((EFUSE_BLK3_DOUT1_V)<<(EFUSE_BLK3_DOUT1_S))
#define EFUSE_BLK3_DOUT1_V  0xFFFFFFFF
#define EFUSE_BLK3_DOUT1_S  0

#define EFUSE_BLK3_RDATA2_REG          (DR_REG_EFUSE_BASE + 0x080)
/* EFUSE_BLK3_DOUT2:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK3*/
#define EFUSE_BLK3_DOUT2  0xFFFFFFFF
#define EFUSE_BLK3_DOUT2_M  ((EFUSE_BLK3_DOUT2_V)<<(EFUSE_BLK3_DOUT2_S))
#define EFUSE_BLK3_DOUT2_V  0xFFFFFFFF
#define EFUSE_BLK3_DOUT2_S  0

/* 注：较新的ESP32使用BLK3_DATA3和部分BLK3_DDATA4进行校准。此用法由EFUSE_RD_BLK3_PART_RESERVE位指示。*/
#define EFUSE_BLK3_RDATA3_REG          (DR_REG_EFUSE_BASE + 0x084)
/* EFUSE_BLK3_DOUT3:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK3*/
#define EFUSE_BLK3_DOUT3  0xFFFFFFFF
#define EFUSE_BLK3_DOUT3_M  ((EFUSE_BLK3_DOUT3_V)<<(EFUSE_BLK3_DOUT3_S))
#define EFUSE_BLK3_DOUT3_V  0xFFFFFFFF
#define EFUSE_BLK3_DOUT3_S  0
/* EFUSE_RD_ADC2_TP_HIGH:R/W；位位置：[31:23]；默认值：9'b0；*/
/*描述：ADC2两点校准高点。仅当EFUSE_RD_BLK3_PART_RESERVE时有效*/
#define EFUSE_RD_ADC2_TP_HIGH  0x1FF
#define EFUSE_RD_ADC2_TP_HIGH_M  ((EFUSE_RD_ADC2_TP_HIGH_V)<<(EFUSE_RD_ADC2_TP_HIGH_S))
#define EFUSE_RD_ADC2_TP_HIGH_V  0x1FF
#define EFUSE_RD_ADC2_TP_HIGH_S  23
/* EFUSE_RD_ADC2_TP_LOW:R/W；比特位置：[22:16]；默认值：7'b0；*/
/*描述：ADC2两点校准低点。仅当EFUSE_RD_BLK3_PART_RESERVE时有效*/
#define EFUSE_RD_ADC2_TP_LOW  0x7F
#define EFUSE_RD_ADC2_TP_LOW_M  ((EFUSE_RD_ADC2_TP_LOW_V)<<(EFUSE_RD_ADC2_TP_LOW_S))
#define EFUSE_RD_ADC2_TP_LOW_V  0x7F
#define EFUSE_RD_ADC2_TP_LOW_S  16
/* EFUSE_RD_ADC1_TP_HIGH:R/W；比特位置：[15:7]；默认值：9'b0；*/
/*描述：ADC1两点校准高点。仅当EFUSE_RD_BLK3_PART_RESERVE时有效*/
#define EFUSE_RD_ADC1_TP_HIGH  0x1FF
#define EFUSE_RD_ADC1_TP_HIGH_M  ((EFUSE_RD_ADC1_TP_HIGH_V)<<(EFUSE_RD_ADC1_TP_HIGH_S))
#define EFUSE_RD_ADC1_TP_HIGH_V  0x1FF
#define EFUSE_RD_ADC1_TP_HIGH_S  7
/* EFUSE_RD_ADC1_TP_LOW:R/W；比特位置：[6:0]；默认值：7'b0；*/
/*描述：ADC1两点校准低点。仅当EFUSE_RD_BLK3_PART_RESERVE时有效*/
#define EFUSE_RD_ADC1_TP_LOW  0x7F
#define EFUSE_RD_ADC1_TP_LOW_M  ((EFUSE_RD_ADC1_TP_LOW_V)<<(EFUSE_RD_ADC1_TP_LOW_S))
#define EFUSE_RD_ADC1_TP_LOW_V  0x7F
#define EFUSE_RD_ADC1_TP_LOW_S  0

#define EFUSE_BLK3_RDATA4_REG          (DR_REG_EFUSE_BASE + 0x088)
/* EFUSE_BLK3_DOUT4:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK3*/
#define EFUSE_BLK3_DOUT4  0xFFFFFFFF
#define EFUSE_BLK3_DOUT4_M  ((EFUSE_BLK3_DOUT4_V)<<(EFUSE_BLK3_DOUT4_S))
#define EFUSE_BLK3_DOUT4_V  0xFFFFFFFF
#define EFUSE_BLK3_DOUT4_S  0
/* EFUSE_RD_CAL_RESERVED:R/W；位位置：[0:15]；默认值：16'0；*/
/*description:保留供将来校准使用。由EFUSE_RD_BLK3_PART_RESERVE指示*/
#define EFUSE_RD_CAL_RESERVED  0x0000FFFF
#define EFUSE_RD_CAL_RESERVED_M  ((EFUSE_RD_CAL_RESERVED_V)<<(EFUSE_RD_CAL_RESERVED_S))
#define EFUSE_RD_CAL_RESERVED_V  0xFFFF
#define EFUSE_RD_CAL_RESERVED_S  0

#define EFUSE_BLK3_RDATA5_REG          (DR_REG_EFUSE_BASE + 0x08c)
/* EFUSE_BLK3_DOUT5:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK3*/
#define EFUSE_BLK3_DOUT5  0xFFFFFFFF
#define EFUSE_BLK3_DOUT5_M  ((EFUSE_BLK3_DOUT5_V)<<(EFUSE_BLK3_DOUT5_S))
#define EFUSE_BLK3_DOUT5_V  0xFFFFFFFF
#define EFUSE_BLK3_DOUT5_S  0

#define EFUSE_BLK3_RDATA6_REG          (DR_REG_EFUSE_BASE + 0x090)
/* EFUSE_BLK3_DOUT6:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK3*/
#define EFUSE_BLK3_DOUT6  0xFFFFFFFF
#define EFUSE_BLK3_DOUT6_M  ((EFUSE_BLK3_DOUT6_V)<<(EFUSE_BLK3_DOUT6_S))
#define EFUSE_BLK3_DOUT6_V  0xFFFFFFFF
#define EFUSE_BLK3_DOUT6_S  0

#define EFUSE_BLK3_RDATA7_REG          (DR_REG_EFUSE_BASE + 0x094)
/* EFUSE_BLK3_DOUT7:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:读取BLOCK3*/
#define EFUSE_BLK3_DOUT7  0xFFFFFFFF
#define EFUSE_BLK3_DOUT7_M  ((EFUSE_BLK3_DOUT7_V)<<(EFUSE_BLK3_DOUT7_S))
#define EFUSE_BLK3_DOUT7_V  0xFFFFFFFF
#define EFUSE_BLK3_DOUT7_S  0

#define EFUSE_BLK1_WDATA0_REG          (DR_REG_EFUSE_BASE + 0x098)
/* EFUSE_BLK1_DIN0:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK1的程序*/
#define EFUSE_BLK1_DIN0  0xFFFFFFFF
#define EFUSE_BLK1_DIN0_M  ((EFUSE_BLK1_DIN0_V)<<(EFUSE_BLK1_DIN0_S))
#define EFUSE_BLK1_DIN0_V  0xFFFFFFFF
#define EFUSE_BLK1_DIN0_S  0

#define EFUSE_BLK1_WDATA1_REG          (DR_REG_EFUSE_BASE + 0x09c)
/* EFUSE_BLK1_DIN1:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK1的程序*/
#define EFUSE_BLK1_DIN1  0xFFFFFFFF
#define EFUSE_BLK1_DIN1_M  ((EFUSE_BLK1_DIN1_V)<<(EFUSE_BLK1_DIN1_S))
#define EFUSE_BLK1_DIN1_V  0xFFFFFFFF
#define EFUSE_BLK1_DIN1_S  0

#define EFUSE_BLK1_WDATA2_REG          (DR_REG_EFUSE_BASE + 0x0a0)
/* EFUSE_BLK1_DIN2:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK1的程序*/
#define EFUSE_BLK1_DIN2  0xFFFFFFFF
#define EFUSE_BLK1_DIN2_M  ((EFUSE_BLK1_DIN2_V)<<(EFUSE_BLK1_DIN2_S))
#define EFUSE_BLK1_DIN2_V  0xFFFFFFFF
#define EFUSE_BLK1_DIN2_S  0

#define EFUSE_BLK1_WDATA3_REG          (DR_REG_EFUSE_BASE + 0x0a4)
/* EFUSE_BLK1_DIN3:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK1的程序*/
#define EFUSE_BLK1_DIN3  0xFFFFFFFF
#define EFUSE_BLK1_DIN3_M  ((EFUSE_BLK1_DIN3_V)<<(EFUSE_BLK1_DIN3_S))
#define EFUSE_BLK1_DIN3_V  0xFFFFFFFF
#define EFUSE_BLK1_DIN3_S  0

#define EFUSE_BLK1_WDATA4_REG          (DR_REG_EFUSE_BASE + 0x0a8)
/* EFUSE_BLK1_DIN4:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK1的程序*/
#define EFUSE_BLK1_DIN4  0xFFFFFFFF
#define EFUSE_BLK1_DIN4_M  ((EFUSE_BLK1_DIN4_V)<<(EFUSE_BLK1_DIN4_S))
#define EFUSE_BLK1_DIN4_V  0xFFFFFFFF
#define EFUSE_BLK1_DIN4_S  0

#define EFUSE_BLK1_WDATA5_REG          (DR_REG_EFUSE_BASE + 0x0ac)
/* EFUSE_BLK1_DIN5:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK1的程序*/
#define EFUSE_BLK1_DIN5  0xFFFFFFFF
#define EFUSE_BLK1_DIN5_M  ((EFUSE_BLK1_DIN5_V)<<(EFUSE_BLK1_DIN5_S))
#define EFUSE_BLK1_DIN5_V  0xFFFFFFFF
#define EFUSE_BLK1_DIN5_S  0

#define EFUSE_BLK1_WDATA6_REG          (DR_REG_EFUSE_BASE + 0x0b0)
/* EFUSE_BLK1_DIN6:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK1的程序*/
#define EFUSE_BLK1_DIN6  0xFFFFFFFF
#define EFUSE_BLK1_DIN6_M  ((EFUSE_BLK1_DIN6_V)<<(EFUSE_BLK1_DIN6_S))
#define EFUSE_BLK1_DIN6_V  0xFFFFFFFF
#define EFUSE_BLK1_DIN6_S  0

#define EFUSE_BLK1_WDATA7_REG          (DR_REG_EFUSE_BASE + 0x0b4)
/* EFUSE_BLK1_DIN7:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK1的程序*/
#define EFUSE_BLK1_DIN7  0xFFFFFFFF
#define EFUSE_BLK1_DIN7_M  ((EFUSE_BLK1_DIN7_V)<<(EFUSE_BLK1_DIN7_S))
#define EFUSE_BLK1_DIN7_V  0xFFFFFFFF
#define EFUSE_BLK1_DIN7_S  0

#define EFUSE_BLK2_WDATA0_REG          (DR_REG_EFUSE_BASE + 0x0b8)
/* EFUSE_BLK2_DIN0:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK2程序*/
#define EFUSE_BLK2_DIN0  0xFFFFFFFF
#define EFUSE_BLK2_DIN0_M  ((EFUSE_BLK2_DIN0_V)<<(EFUSE_BLK2_DIN0_S))
#define EFUSE_BLK2_DIN0_V  0xFFFFFFFF
#define EFUSE_BLK2_DIN0_S  0

#define EFUSE_BLK2_WDATA1_REG          (DR_REG_EFUSE_BASE + 0x0bc)
/* EFUSE_BLK2_DIN1:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK2程序*/
#define EFUSE_BLK2_DIN1  0xFFFFFFFF
#define EFUSE_BLK2_DIN1_M  ((EFUSE_BLK2_DIN1_V)<<(EFUSE_BLK2_DIN1_S))
#define EFUSE_BLK2_DIN1_V  0xFFFFFFFF
#define EFUSE_BLK2_DIN1_S  0

#define EFUSE_BLK2_WDATA2_REG          (DR_REG_EFUSE_BASE + 0x0c0)
/* EFUSE_BLK2_DIN2:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK2程序*/
#define EFUSE_BLK2_DIN2  0xFFFFFFFF
#define EFUSE_BLK2_DIN2_M  ((EFUSE_BLK2_DIN2_V)<<(EFUSE_BLK2_DIN2_S))
#define EFUSE_BLK2_DIN2_V  0xFFFFFFFF
#define EFUSE_BLK2_DIN2_S  0

#define EFUSE_BLK2_WDATA3_REG          (DR_REG_EFUSE_BASE + 0x0c4)
/* EFUSE_BLK2_DIN3:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK2程序*/
#define EFUSE_BLK2_DIN3  0xFFFFFFFF
#define EFUSE_BLK2_DIN3_M  ((EFUSE_BLK2_DIN3_V)<<(EFUSE_BLK2_DIN3_S))
#define EFUSE_BLK2_DIN3_V  0xFFFFFFFF
#define EFUSE_BLK2_DIN3_S  0

#define EFUSE_BLK2_WDATA4_REG          (DR_REG_EFUSE_BASE + 0x0c8)
/* EFUSE_BLK2_DIN4:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK2程序*/
#define EFUSE_BLK2_DIN4  0xFFFFFFFF
#define EFUSE_BLK2_DIN4_M  ((EFUSE_BLK2_DIN4_V)<<(EFUSE_BLK2_DIN4_S))
#define EFUSE_BLK2_DIN4_V  0xFFFFFFFF
#define EFUSE_BLK2_DIN4_S  0

#define EFUSE_BLK2_WDATA5_REG          (DR_REG_EFUSE_BASE + 0x0cc)
/* EFUSE_BLK2_DIN5:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK2程序*/
#define EFUSE_BLK2_DIN5  0xFFFFFFFF
#define EFUSE_BLK2_DIN5_M  ((EFUSE_BLK2_DIN5_V)<<(EFUSE_BLK2_DIN5_S))
#define EFUSE_BLK2_DIN5_V  0xFFFFFFFF
#define EFUSE_BLK2_DIN5_S  0

#define EFUSE_BLK2_WDATA6_REG          (DR_REG_EFUSE_BASE + 0x0d0)
/* EFUSE_BLK2_DIN6:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK2程序*/
#define EFUSE_BLK2_DIN6  0xFFFFFFFF
#define EFUSE_BLK2_DIN6_M  ((EFUSE_BLK2_DIN6_V)<<(EFUSE_BLK2_DIN6_S))
#define EFUSE_BLK2_DIN6_V  0xFFFFFFFF
#define EFUSE_BLK2_DIN6_S  0

#define EFUSE_BLK2_WDATA7_REG          (DR_REG_EFUSE_BASE + 0x0d4)
/* EFUSE_BLK2_DIN7:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK2程序*/
#define EFUSE_BLK2_DIN7  0xFFFFFFFF
#define EFUSE_BLK2_DIN7_M  ((EFUSE_BLK2_DIN7_V)<<(EFUSE_BLK2_DIN7_S))
#define EFUSE_BLK2_DIN7_V  0xFFFFFFFF
#define EFUSE_BLK2_DIN7_S  0

#define EFUSE_BLK3_WDATA0_REG          (DR_REG_EFUSE_BASE + 0x0d8)
/* EFUSE_BLK3_DIN0:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK3程序*/
#define EFUSE_BLK3_DIN0  0xFFFFFFFF
#define EFUSE_BLK3_DIN0_M  ((EFUSE_BLK3_DIN0_V)<<(EFUSE_BLK3_DIN0_S))
#define EFUSE_BLK3_DIN0_V  0xFFFFFFFF
#define EFUSE_BLK3_DIN0_S  0

#define EFUSE_BLK3_WDATA1_REG          (DR_REG_EFUSE_BASE + 0x0dc)
/* EFUSE_BLK3_DIN1:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK3程序*/
#define EFUSE_BLK3_DIN1  0xFFFFFFFF
#define EFUSE_BLK3_DIN1_M  ((EFUSE_BLK3_DIN1_V)<<(EFUSE_BLK3_DIN1_S))
#define EFUSE_BLK3_DIN1_V  0xFFFFFFFF
#define EFUSE_BLK3_DIN1_S  0

#define EFUSE_BLK3_WDATA2_REG          (DR_REG_EFUSE_BASE + 0x0e0)
/* EFUSE_BLK3_DIN2:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK3程序*/
#define EFUSE_BLK3_DIN2  0xFFFFFFFF
#define EFUSE_BLK3_DIN2_M  ((EFUSE_BLK3_DIN2_V)<<(EFUSE_BLK3_DIN2_S))
#define EFUSE_BLK3_DIN2_V  0xFFFFFFFF
#define EFUSE_BLK3_DIN2_S  0

/* 注：较新的ESP32使用BLK3_DATA3和部分BLK3_DDATA4进行校准。此用法由EFUSE_RD_BLK3_PART_RESERVE位指示。*/
#define EFUSE_BLK3_WDATA3_REG          (DR_REG_EFUSE_BASE + 0x0e4)
/* EFUSE_BLK3_DIN3:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK3程序*/
#define EFUSE_BLK3_DIN3  0xFFFFFFFF
#define EFUSE_BLK3_DIN3_M  ((EFUSE_BLK3_DIN3_V)<<(EFUSE_BLK3_DIN3_S))
#define EFUSE_BLK3_DIN3_V  0xFFFFFFFF
#define EFUSE_BLK3_DIN3_S  0
/* EFUSE_ADC2_TP_高：R/W；位位置：[31:23]；默认值：9'b0；*/
/*描述：ADC2两点校准高点。仅当EFUSE_RD_BLK3_PART_RESERVE时有效*/
#define EFUSE_ADC2_TP_HIGH  0x1FF
#define EFUSE_ADC2_TP_HIGH_M  ((EFUSE_ADC2_TP_HIGH_V)<<(EFUSE_ADC2_TP_HIGH_S))
#define EFUSE_ADC2_TP_HIGH_V  0x1FF
#define EFUSE_ADC2_TP_HIGH_S  23
/* EFUSE_ADC2_TP_LOW：R/W；比特位置：[22:16]；默认值：7'b0；*/
/*描述：ADC2两点校准低点。仅当EFUSE_RD_BLK3_PART_RESERVE时有效*/
#define EFUSE_ADC2_TP_LOW  0x7F
#define EFUSE_ADC2_TP_LOW_M  ((EFUSE_ADC2_TP_LOW_V)<<(EFUSE_ADC2_TP_LOW_S))
#define EFUSE_ADC2_TP_LOW_V  0x7F
#define EFUSE_ADC2_TP_LOW_S  16
/* EFUSE_ADC1_TP_高：R/W；比特位置：[15:7]；默认值：9'b0；*/
/*描述：ADC1两点校准高点。仅当EFUSE_RD_BLK3_PART_RESERVE时有效*/
#define EFUSE_ADC1_TP_HIGH  0x1FF
#define EFUSE_ADC1_TP_HIGH_M  ((EFUSE_ADC1_TP_HIGH_V)<<(EFUSE_ADC1_TP_HIGH_S))
#define EFUSE_ADC1_TP_HIGH_V  0x1FF
#define EFUSE_ADC1_TP_HIGH_S  7
/* EFUSE_ADC1_TP_LOW：R/W；比特位置：[6:0]；默认值：7'b0；*/
/*描述：ADC1两点校准低点。仅当EFUSE_RD_BLK3_PART_RESERVE时有效*/
#define EFUSE_ADC1_TP_LOW  0x7F
#define EFUSE_ADC1_TP_LOW_M  ((EFUSE_ADC1_TP_LOW_V)<<(EFUSE_ADC1_TP_LOW_S))
#define EFUSE_ADC1_TP_LOW_V  0x7F
#define EFUSE_ADC1_TP_LOW_S  0

#define EFUSE_BLK3_WDATA4_REG          (DR_REG_EFUSE_BASE + 0x0e8)
/* EFUSE_BLK3_DIN4:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK3程序*/
#define EFUSE_BLK3_DIN4  0xFFFFFFFF
#define EFUSE_BLK3_DIN4_M  ((EFUSE_BLK3_DIN4_V)<<(EFUSE_BLK3_DIN4_S))
#define EFUSE_BLK3_DIN4_V  0xFFFFFFFF
#define EFUSE_BLK3_DIN4_S  0
/* EFUSE_CAL_RESERVED:R/W；位位置：[0:15]；默认值：16'0；*/
/*description:保留供将来校准使用。由EFUSE_BLK3_PART_RESERVE指示*/
#define EFUSE_CAL_RESERVED  0x0000FFFF
#define EFUSE_CAL_RESERVED_M  ((EFUSE_CAL_RESERVED_V)<<(EFUSE_CAL_RESERVED_S))
#define EFUSE_CAL_RESERVED_V  0xFFFF
#define EFUSE_CAL_RESERVED_S  0

#define EFUSE_BLK3_WDATA5_REG          (DR_REG_EFUSE_BASE + 0x0ec)
/* EFUSE_BLK3_DIN5:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK3程序*/
#define EFUSE_BLK3_DIN5  0xFFFFFFFF
#define EFUSE_BLK3_DIN5_M  ((EFUSE_BLK3_DIN5_V)<<(EFUSE_BLK3_DIN5_S))
#define EFUSE_BLK3_DIN5_V  0xFFFFFFFF
#define EFUSE_BLK3_DIN5_S  0

#define EFUSE_BLK3_WDATA6_REG          (DR_REG_EFUSE_BASE + 0x0f0)
/* EFUSE_BLK3_DIN6:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK3程序*/
#define EFUSE_BLK3_DIN6  0xFFFFFFFF
#define EFUSE_BLK3_DIN6_M  ((EFUSE_BLK3_DIN6_V)<<(EFUSE_BLK3_DIN6_S))
#define EFUSE_BLK3_DIN6_V  0xFFFFFFFF
#define EFUSE_BLK3_DIN6_S  0

#define EFUSE_BLK3_WDATA7_REG          (DR_REG_EFUSE_BASE + 0x0f4)
/* EFUSE_BLK3_DIN7:R/W；位位置：[31:0]；默认值：32'h0；*/
/*description:BLOCK3程序*/
#define EFUSE_BLK3_DIN7  0xFFFFFFFF
#define EFUSE_BLK3_DIN7_M  ((EFUSE_BLK3_DIN7_V)<<(EFUSE_BLK3_DIN7_S))
#define EFUSE_BLK3_DIN7_V  0xFFFFFFFF
#define EFUSE_BLK3_DIN7_S  0

#define EFUSE_CLK_REG          (DR_REG_EFUSE_BASE + 0x0f8)
/* EFUSE_CLK_EN:R/W；位位置：[16]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_CLK_EN  (BIT(16))
#define EFUSE_CLK_EN_M  (BIT(16))
#define EFUSE_CLK_EN_V  0x1
#define EFUSE_CLK_EN_S  16
/* EFUSE_CLK_SEL1:R/W；比特位置：[15:8]；默认值：8'h40；*/
/*description:efuse定时配置*/
#define EFUSE_CLK_SEL1  0x000000FF
#define EFUSE_CLK_SEL1_M  ((EFUSE_CLK_SEL1_V)<<(EFUSE_CLK_SEL1_S))
#define EFUSE_CLK_SEL1_V  0xFF
#define EFUSE_CLK_SEL1_S  8
/* EFUSE_CLK_SEL0:R/W；位位置：[7:0]；默认值：8'h52；*/
/*description:efuse定时配置*/
#define EFUSE_CLK_SEL0  0x000000FF
#define EFUSE_CLK_SEL0_M  ((EFUSE_CLK_SEL0_V)<<(EFUSE_CLK_SEL0_S))
#define EFUSE_CLK_SEL0_V  0xFF
#define EFUSE_CLK_SEL0_S  0

#define EFUSE_CONF_REG          (DR_REG_EFUSE_BASE + 0x0fc)
/* EFUSE_FORCE_NO_WR_RD_DIS:R/W；位位置：[16]；默认值：1'h1；*/
/*说明：*/
#define EFUSE_FORCE_NO_WR_RD_DIS  (BIT(16))
#define EFUSE_FORCE_NO_WR_RD_DIS_M  (BIT(16))
#define EFUSE_FORCE_NO_WR_RD_DIS_V  0x1
#define EFUSE_FORCE_NO_WR_RD_DIS_S  16
/* EFUSE_OP_CODE:R/W；比特位置：[15:0]；默认值：16'0；*/
/*description:efuse操作代码*/
#define EFUSE_OP_CODE  0x0000FFFF
#define EFUSE_OP_CODE_M  ((EFUSE_OP_CODE_V)<<(EFUSE_OP_CODE_S))
#define EFUSE_OP_CODE_V  0xFFFF
#define EFUSE_OP_CODE_S  0

#define EFUSE_STATUS_REG          (DR_REG_EFUSE_BASE + 0x100)
/* EFUSE_DEBUG:RO；位位置：[31:0]；默认值：32'h0；*/
/*说明：*/
#define EFUSE_DEBUG  0xFFFFFFFF
#define EFUSE_DEBUG_M  ((EFUSE_DEBUG_V)<<(EFUSE_DEBUG_S))
#define EFUSE_DEBUG_V  0xFFFFFFFF
#define EFUSE_DEBUG_S  0

#define EFUSE_CMD_REG          (DR_REG_EFUSE_BASE + 0x104)
/* EFUSE_PGM_CMD:R/W；位位置：[1]；默认值：1’b0；*/
/*description:程序命令*/
#define EFUSE_PGM_CMD  (BIT(1))
#define EFUSE_PGM_CMD_M  (BIT(1))
#define EFUSE_PGM_CMD_V  0x1
#define EFUSE_PGM_CMD_S  1
/* EFUSE_READ_CMD:R/W；位位置：[0]；默认值：1’b0；*/
/*description:读取命令*/
#define EFUSE_READ_CMD  (BIT(0))
#define EFUSE_READ_CMD_M  (BIT(0))
#define EFUSE_READ_CMD_V  0x1
#define EFUSE_READ_CMD_S  0

#define EFUSE_INT_RAW_REG          (DR_REG_EFUSE_BASE + 0x108)
/* EFUSE_PGM_DONE_INT_RAW:RO；位位置：[1]；默认值：1’b0；*/
/*描述：程序完成中断原始状态*/
#define EFUSE_PGM_DONE_INT_RAW  (BIT(1))
#define EFUSE_PGM_DONE_INT_RAW_M  (BIT(1))
#define EFUSE_PGM_DONE_INT_RAW_V  0x1
#define EFUSE_PGM_DONE_INT_RAW_S  1
/* EFUSE_READ_DONE_INT_RAW:RO；位位置：[0]；默认值：1’b0；*/
/*描述：读取完成中断原始状态*/
#define EFUSE_READ_DONE_INT_RAW  (BIT(0))
#define EFUSE_READ_DONE_INT_RAW_M  (BIT(0))
#define EFUSE_READ_DONE_INT_RAW_V  0x1
#define EFUSE_READ_DONE_INT_RAW_S  0

#define EFUSE_INT_ST_REG          (DR_REG_EFUSE_BASE + 0x10c)
/* EFUSE_PGM_DONE_INT_ST:RO；位位置：[1]；默认值：1’b0；*/
/*描述：程序完成中断状态*/
#define EFUSE_PGM_DONE_INT_ST  (BIT(1))
#define EFUSE_PGM_DONE_INT_ST_M  (BIT(1))
#define EFUSE_PGM_DONE_INT_ST_V  0x1
#define EFUSE_PGM_DONE_INT_ST_S  1
/* EFUSE_READ_DONE_INT_ST:RO；位位置：[0]；默认值：1’b0；*/
/*description:读取完成中断状态*/
#define EFUSE_READ_DONE_INT_ST  (BIT(0))
#define EFUSE_READ_DONE_INT_ST_M  (BIT(0))
#define EFUSE_READ_DONE_INT_ST_V  0x1
#define EFUSE_READ_DONE_INT_ST_S  0

#define EFUSE_INT_ENA_REG          (DR_REG_EFUSE_BASE + 0x110)
/* EFUSE_PGM_DONE_INT_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*描述：程序完成中断启用*/
#define EFUSE_PGM_DONE_INT_ENA  (BIT(1))
#define EFUSE_PGM_DONE_INT_ENA_M  (BIT(1))
#define EFUSE_PGM_DONE_INT_ENA_V  0x1
#define EFUSE_PGM_DONE_INT_ENA_S  1
/* EFUSE_READ_DONE_INT_ENA:R/W；位位置：[0]；默认值：1’b0；*/
/*description:读完成中断启用*/
#define EFUSE_READ_DONE_INT_ENA  (BIT(0))
#define EFUSE_READ_DONE_INT_ENA_M  (BIT(0))
#define EFUSE_READ_DONE_INT_ENA_V  0x1
#define EFUSE_READ_DONE_INT_ENA_S  0

#define EFUSE_INT_CLR_REG          (DR_REG_EFUSE_BASE + 0x114)
/* EFUSE_PGM_DONE_INT_CLR:WO；位位置：[1]；默认值：1’b0；*/
/*描述：程序已完成中断清除*/
#define EFUSE_PGM_DONE_INT_CLR  (BIT(1))
#define EFUSE_PGM_DONE_INT_CLR_M  (BIT(1))
#define EFUSE_PGM_DONE_INT_CLR_V  0x1
#define EFUSE_PGM_DONE_INT_CLR_S  1
/* EFUSE_READ_DONE_INT_CLR:WO；位位置：[0]；默认值：1’b0；*/
/*description:读取完成中断清除*/
#define EFUSE_READ_DONE_INT_CLR  (BIT(0))
#define EFUSE_READ_DONE_INT_CLR_M  (BIT(0))
#define EFUSE_READ_DONE_INT_CLR_V  0x1
#define EFUSE_READ_DONE_INT_CLR_S  0

#define EFUSE_DAC_CONF_REG          (DR_REG_EFUSE_BASE + 0x118)
/* EFUSE_DAC_CLK_PAD_SEL：R/W；位位置：[8]；默认值：1’b0；*/
/*说明：*/
#define EFUSE_DAC_CLK_PAD_SEL  (BIT(8))
#define EFUSE_DAC_CLK_PAD_SEL_M  (BIT(8))
#define EFUSE_DAC_CLK_PAD_SEL_V  0x1
#define EFUSE_DAC_CLK_PAD_SEL_S  8
/* EFUSE_DAC_CLK_DIV:R/W；位位置：[7:0]；默认值：8'd40；*/
/*description:efuse定时配置*/
#define EFUSE_DAC_CLK_DIV  0x000000FF
#define EFUSE_DAC_CLK_DIV_M  ((EFUSE_DAC_CLK_DIV_V)<<(EFUSE_DAC_CLK_DIV_S))
#define EFUSE_DAC_CLK_DIV_V  0xFF
#define EFUSE_DAC_CLK_DIV_S  0

#define EFUSE_DEC_STATUS_REG          (DR_REG_EFUSE_BASE + 0x11c)
/* EFUSE_DEC_WARNINGS:RO；位位置：[11:0]；默认值：12'b0；*/
/*描述：3/4编码方案的解码结果有警告*/
#define EFUSE_DEC_WARNINGS  0x00000FFF
#define EFUSE_DEC_WARNINGS_M  ((EFUSE_DEC_WARNINGS_V)<<(EFUSE_DEC_WARNINGS_S))
#define EFUSE_DEC_WARNINGS_V  0xFFF
#define EFUSE_DEC_WARNINGS_S  0

#define EFUSE_DATE_REG          (DR_REG_EFUSE_BASE + 0x1FC)
/* EFUSE_DATE:R/W；位位置：[31:0]；默认值：32'h16042600；*/
/*说明：*/
#define EFUSE_DATE  0xFFFFFFFF
#define EFUSE_DATE_M  ((EFUSE_DATE_V)<<(EFUSE_DATE_S))
#define EFUSE_DATE_V  0xFFFFFFFF
#define EFUSE_DATE_S  0




#endif /*_SOC_EFUSE_REG_H_ */

