// 版权所有2015-2016 Espressif Systems（上海）私人有限公司
//
// 根据Apache许可证2.0版（“许可证”）获得许可；
// 除非符合许可证，否则不得使用此文件。
// 您可以在以下地址获取许可证副本：

//     http://www.apache.org/licenses/LICENSE-2.0
//
// 除非适用法律要求或书面同意，软件
// 根据许可证分发的内容是按“原样”分发的，
// 无任何明示或暗示的保证或条件。
// 有关管理权限和
// 许可证下的限制。
#ifndef _SOC_RTC_CNTL_REG_H_
#define _SOC_RTC_CNTL_REG_H_

/* 需要写入RTC_CNTL_WDT_WKEY以启用WDT寄存器的值*/
#define RTC_CNTL_WDT_WKEY_VALUE 0x50D83AA1

/* RTC_CNTL_WDT_CPU_REST_LENGTH和RTC_CNTL-WDT_SYS_RESET_LENGTH的可能值*/
#define RTC_WDT_RESET_LENGTH_100_NS    0
#define RTC_WDT_RESET_LENGTH_200_NS    1
#define RTC_WDT_RESET_LENGTH_300_NS    2
#define RTC_WDT_RESET_LENGTH_400_NS    3
#define RTC_WDT_RESET_LENGTH_500_NS    4
#define RTC_WDT_RESET_LENGTH_800_NS    5
#define RTC_WDT_RESET_LENGTH_1600_NS   6
#define RTC_WDT_RESET_LENGTH_3200_NS   7

#include "soc.h"
#define RTC_CNTL_OPTIONS0_REG          (DR_REG_RTCCNTL_BASE + 0x0)
/* RTC_CNTL_SW_SYS_RST:WO；位位置：[31]；默认值：1'd0；*/
/*description:SW系统复位*/
#define RTC_CNTL_SW_SYS_RST  (BIT(31))
#define RTC_CNTL_SW_SYS_RST_M  (BIT(31))
#define RTC_CNTL_SW_SYS_RST_V  0x1
#define RTC_CNTL_SW_SYS_RST_S  31
/* RTC_CNTL_DG_WRAP_FORCE_NORST:R/W；位位置：[30]；默认值：1'd0；*/
/*描述：数字核心力在深度睡眠中不复位*/
#define RTC_CNTL_DG_WRAP_FORCE_NORST  (BIT(30))
#define RTC_CNTL_DG_WRAP_FORCE_NORST_M  (BIT(30))
#define RTC_CNTL_DG_WRAP_FORCE_NORST_V  0x1
#define RTC_CNTL_DG_WRAP_FORCE_NORST_S  30
/* RTC_CNTL_DG_WRAP_FORCE_RST:R/W；位位置：[29]；默认值：1'd0；*/
/*描述：深度睡眠中的数字包裹力重置*/
#define RTC_CNTL_DG_WRAP_FORCE_RST  (BIT(29))
#define RTC_CNTL_DG_WRAP_FORCE_RST_M  (BIT(29))
#define RTC_CNTL_DG_WRAP_FORCE_RST_V  0x1
#define RTC_CNTL_DG_WRAP_FORCE_RST_S  29
/* RTC_CNTL_analogy_FORCE_NOISO:R/W；位位置：[28]；默认值：1'd1；*/
/*说明：*/
#define RTC_CNTL_ANALOG_FORCE_NOISO  (BIT(28))
#define RTC_CNTL_ANALOG_FORCE_NOISO_M  (BIT(28))
#define RTC_CNTL_ANALOG_FORCE_NOISO_V  0x1
#define RTC_CNTL_ANALOG_FORCE_NOISO_S  28
/* RTC_CNTL_PLL_FORCE_NOISO:R/W；位位置：[27]；默认值：1'd1；*/
/*说明：*/
#define RTC_CNTL_PLL_FORCE_NOISO  (BIT(27))
#define RTC_CNTL_PLL_FORCE_NOISO_M  (BIT(27))
#define RTC_CNTL_PLL_FORCE_NOISO_V  0x1
#define RTC_CNTL_PLL_FORCE_NOISO_S  27
/* RTC_CNTL-XTL-FORCE_NOISO:R/W；位位置：[26]；默认值：1'd1；*/
/*说明：*/
#define RTC_CNTL_XTL_FORCE_NOISO  (BIT(26))
#define RTC_CNTL_XTL_FORCE_NOISO_M  (BIT(26))
#define RTC_CNTL_XTL_FORCE_NOISO_V  0x1
#define RTC_CNTL_XTL_FORCE_NOISO_S  26
/* RTC_CNTL_analogy_FORCE_ISO:R/W；位位置：[25]；默认值：1'd0；*/
/*说明：*/
#define RTC_CNTL_ANALOG_FORCE_ISO  (BIT(25))
#define RTC_CNTL_ANALOG_FORCE_ISO_M  (BIT(25))
#define RTC_CNTL_ANALOG_FORCE_ISO_V  0x1
#define RTC_CNTL_ANALOG_FORCE_ISO_S  25
/* RTC_CNTL_PLL_FORCE_ISO:R/W；位位置：[24]；默认值：1'd0；*/
/*说明：*/
#define RTC_CNTL_PLL_FORCE_ISO  (BIT(24))
#define RTC_CNTL_PLL_FORCE_ISO_M  (BIT(24))
#define RTC_CNTL_PLL_FORCE_ISO_V  0x1
#define RTC_CNTL_PLL_FORCE_ISO_S  24
/* RTC_CNTL-XTL-FORCE_ISO:R/W；位位置：[23]；默认值：1'd0；*/
/*说明：*/
#define RTC_CNTL_XTL_FORCE_ISO  (BIT(23))
#define RTC_CNTL_XTL_FORCE_ISO_M  (BIT(23))
#define RTC_CNTL_XTL_FORCE_ISO_V  0x1
#define RTC_CNTL_XTL_FORCE_ISO_S  23
/* RTC_CNTL_BIAS_CORE_FORCE_PU:R/W；位位置：[22]；默认值：1'd1；*/
/*description:BIAS_CORE强制加电*/
#define RTC_CNTL_BIAS_CORE_FORCE_PU  (BIT(22))
#define RTC_CNTL_BIAS_CORE_FORCE_PU_M  (BIT(22))
#define RTC_CNTL_BIAS_CORE_FORCE_PU_V  0x1
#define RTC_CNTL_BIAS_CORE_FORCE_PU_S  22
/* RTC_CNTL_BIAS_CORE_FORCE_PD:R/W；位位置：[21]；默认值：1’b0；*/
/*description:BIAS_CORE强制断电*/
#define RTC_CNTL_BIAS_CORE_FORCE_PD  (BIT(21))
#define RTC_CNTL_BIAS_CORE_FORCE_PD_M  (BIT(21))
#define RTC_CNTL_BIAS_CORE_FORCE_PD_V  0x1
#define RTC_CNTL_BIAS_CORE_FORCE_PD_S  21
/* RTC_CNTL_BIAS_CORE_FOLW_8M:R/W；位位置：[20]；默认值：1'd0；*/
/*description:BIAS_CORE遵循CK8M*/
#define RTC_CNTL_BIAS_CORE_FOLW_8M  (BIT(20))
#define RTC_CNTL_BIAS_CORE_FOLW_8M_M  (BIT(20))
#define RTC_CNTL_BIAS_CORE_FOLW_8M_V  0x1
#define RTC_CNTL_BIAS_CORE_FOLW_8M_S  20
/* RTC_CNTL_BIAS_I2C_FORCE_PU:R/W；位位置：[19]；默认值：1'd1；*/
/*description:BIAS_I2C强制加电*/
#define RTC_CNTL_BIAS_I2C_FORCE_PU  (BIT(19))
#define RTC_CNTL_BIAS_I2C_FORCE_PU_M  (BIT(19))
#define RTC_CNTL_BIAS_I2C_FORCE_PU_V  0x1
#define RTC_CNTL_BIAS_I2C_FORCE_PU_S  19
/* RTC_CNTL_BIAS_I2C_FORCE_PD:R/W；位位置：[18]；默认值：1’b0；*/
/*description:BIAS_I2C强制断电*/
#define RTC_CNTL_BIAS_I2C_FORCE_PD  (BIT(18))
#define RTC_CNTL_BIAS_I2C_FORCE_PD_M  (BIT(18))
#define RTC_CNTL_BIAS_I2C_FORCE_PD_V  0x1
#define RTC_CNTL_BIAS_I2C_FORCE_PD_S  18
/* RTC_CNTL_BIAS_I2C_FOLW_8M:R/W；位位置：[17]；默认值：1'd0；*/
/*说明：BIAS_I2C遵循CK8M*/
#define RTC_CNTL_BIAS_I2C_FOLW_8M  (BIT(17))
#define RTC_CNTL_BIAS_I2C_FOLW_8M_M  (BIT(17))
#define RTC_CNTL_BIAS_I2C_FOLW_8M_V  0x1
#define RTC_CNTL_BIAS_I2C_FOLW_8M_S  17
/* RTC_CNTL_BIAS_FORCE_NOSLEEP:R/W；位位置：[16]；默认值：1'd1；*/
/*description:BIAS_LEEP强制不休眠*/
#define RTC_CNTL_BIAS_FORCE_NOSLEEP  (BIT(16))
#define RTC_CNTL_BIAS_FORCE_NOSLEEP_M  (BIT(16))
#define RTC_CNTL_BIAS_FORCE_NOSLEEP_V  0x1
#define RTC_CNTL_BIAS_FORCE_NOSLEEP_S  16
/* RTC_CNTL_BIAS_FORCE_SLEEP:R/W；位位置：[15]；默认值：1’b0；*/
/*description:BIAS_LEEP强制休眠*/
#define RTC_CNTL_BIAS_FORCE_SLEEP  (BIT(15))
#define RTC_CNTL_BIAS_FORCE_SLEEP_M  (BIT(15))
#define RTC_CNTL_BIAS_FORCE_SLEEP_V  0x1
#define RTC_CNTL_BIAS_FORCE_SLEEP_S  15
/* RTC_CNTL_BIAS_SLEEP_FOLW_8M:R/W；位位置：[14]；默认值：1’b0；*/
/*description:BIAS_LEEP遵循CK8M*/
#define RTC_CNTL_BIAS_SLEEP_FOLW_8M  (BIT(14))
#define RTC_CNTL_BIAS_SLEEP_FOLW_8M_M  (BIT(14))
#define RTC_CNTL_BIAS_SLEEP_FOLW_8M_V  0x1
#define RTC_CNTL_BIAS_SLEEP_FOLW_8M_S  14
/* RTC_CNTL-XTL_FORCE_PU:R/W；位位置：[13]；默认值：1'd1；*/
/*description:crystallforce通电*/
#define RTC_CNTL_XTL_FORCE_PU  (BIT(13))
#define RTC_CNTL_XTL_FORCE_PU_M  (BIT(13))
#define RTC_CNTL_XTL_FORCE_PU_V  0x1
#define RTC_CNTL_XTL_FORCE_PU_S  13
/* RTC_CNTL-XTL_FORCE_PD:R/W；位位置：[12]；默认值：1’b0；*/
/*description:水晶力断电*/
#define RTC_CNTL_XTL_FORCE_PD  (BIT(12))
#define RTC_CNTL_XTL_FORCE_PD_M  (BIT(12))
#define RTC_CNTL_XTL_FORCE_PD_V  0x1
#define RTC_CNTL_XTL_FORCE_PD_S  12
/* RTC_CNTL_bpll_FORCE_PU:R/W；位位置：[11]；默认值：1'd0；*/
/*description:BB_PLL强制加电*/
#define RTC_CNTL_BBPLL_FORCE_PU  (BIT(11))
#define RTC_CNTL_BBPLL_FORCE_PU_M  (BIT(11))
#define RTC_CNTL_BBPLL_FORCE_PU_V  0x1
#define RTC_CNTL_BBPLL_FORCE_PU_S  11
/* RTC_CNTL_bpll_FORCE_PD:R/W；位位置：[10]；默认值：1’b0；*/
/*description:BB_PLL强制断电*/
#define RTC_CNTL_BBPLL_FORCE_PD  (BIT(10))
#define RTC_CNTL_BBPLL_FORCE_PD_M  (BIT(10))
#define RTC_CNTL_BBPLL_FORCE_PD_V  0x1
#define RTC_CNTL_BBPLL_FORCE_PD_S  10
/* RTC_CNTL_bpll_I2C_FORCE_PU:R/W；位位置：[9]；默认值：1'd0；*/
/*description:BB_PLL_I2C强制加电*/
#define RTC_CNTL_BBPLL_I2C_FORCE_PU  (BIT(9))
#define RTC_CNTL_BBPLL_I2C_FORCE_PU_M  (BIT(9))
#define RTC_CNTL_BBPLL_I2C_FORCE_PU_V  0x1
#define RTC_CNTL_BBPLL_I2C_FORCE_PU_S  9
/* RTC_CNTL_bpll_I2C_FORCE_PD:R/W；位位置：[8]；默认值：1’b0；*/
/*description:BB_PLL_I2C强制断电*/
#define RTC_CNTL_BBPLL_I2C_FORCE_PD  (BIT(8))
#define RTC_CNTL_BBPLL_I2C_FORCE_PD_M  (BIT(8))
#define RTC_CNTL_BBPLL_I2C_FORCE_PD_V  0x1
#define RTC_CNTL_BBPLL_I2C_FORCE_PD_S  8
/* RTC_CNTL_BB_I2C_FORCE_PU:R/W；位位置：[7]；默认值：1'd0；*/
/*description:BB_I2C强制加电*/
#define RTC_CNTL_BB_I2C_FORCE_PU  (BIT(7))
#define RTC_CNTL_BB_I2C_FORCE_PU_M  (BIT(7))
#define RTC_CNTL_BB_I2C_FORCE_PU_V  0x1
#define RTC_CNTL_BB_I2C_FORCE_PU_S  7
/* RTC_CNTL_BB_I2C_FORCE_PD:R/W；位位置：[6]；默认值：1’b0；*/
/*description:BB_I2C强制断电*/
#define RTC_CNTL_BB_I2C_FORCE_PD  (BIT(6))
#define RTC_CNTL_BB_I2C_FORCE_PD_M  (BIT(6))
#define RTC_CNTL_BB_I2C_FORCE_PD_V  0x1
#define RTC_CNTL_BB_I2C_FORCE_PD_S  6
/* RTC_CNTL_SW_PROCPU_RST:WO；位位置：[5]；默认值：1’b0；*/
/*description:PRO CPU SW复位*/
#define RTC_CNTL_SW_PROCPU_RST  (BIT(5))
#define RTC_CNTL_SW_PROCPU_RST_M  (BIT(5))
#define RTC_CNTL_SW_PROCPU_RST_V  0x1
#define RTC_CNTL_SW_PROCPU_RST_S  5
/* RTC_CNTL_SW_APPCPU_RST:WO；位位置：[4]；默认值：1’b0；*/
/*description:APP CPU SW复位*/
#define RTC_CNTL_SW_APPCPU_RST  (BIT(4))
#define RTC_CNTL_SW_APPCPU_RST_M  (BIT(4))
#define RTC_CNTL_SW_APPCPU_RST_V  0x1
#define RTC_CNTL_SW_APPCPU_RST_S  4
/* RTC_CNTL_SW_STALL_PROCPU_C0:R/W；位位置：[3:2]；默认值：2’b0；*/
/*描述：｛reg_sw_stall_procpu_c1[5:0]reg_sw_stall_procpu_c0[1:0]｝==0x86将停止PRO CPU*/
#define RTC_CNTL_SW_STALL_PROCPU_C0  0x00000003
#define RTC_CNTL_SW_STALL_PROCPU_C0_M  ((RTC_CNTL_SW_STALL_PROCPU_C0_V)<<(RTC_CNTL_SW_STALL_PROCPU_C0_S))
#define RTC_CNTL_SW_STALL_PROCPU_C0_V  0x3
#define RTC_CNTL_SW_STALL_PROCPU_C0_S  2
/* RTC_CNTL_SW_STALL_APPCPU_C0:R/W；位位置：[1:0]；默认值：2’b0；*/
/*描述：｛reg_sw_stall_appcpu_c1[5:0]reg_sw_stall_appcp u_c0[1:0]｝==0x86将停止APP CPU*/
#define RTC_CNTL_SW_STALL_APPCPU_C0  0x00000003
#define RTC_CNTL_SW_STALL_APPCPU_C0_M  ((RTC_CNTL_SW_STALL_APPCPU_C0_V)<<(RTC_CNTL_SW_STALL_APPCPU_C0_S))
#define RTC_CNTL_SW_STALL_APPCPU_C0_V  0x3
#define RTC_CNTL_SW_STALL_APPCPU_C0_S  0

#define RTC_CNTL_SLP_TIMER0_REG          (DR_REG_RTCCNTL_BASE + 0x4)
/* RTC_CNTL_SLP_VAL_LO:R/W；位位置：[31:0]；默认值：32'h0；*/
/*描述：RTC睡眠定时器低32位*/
#define RTC_CNTL_SLP_VAL_LO  0xFFFFFFFF
#define RTC_CNTL_SLP_VAL_LO_M  ((RTC_CNTL_SLP_VAL_LO_V)<<(RTC_CNTL_SLP_VAL_LO_S))
#define RTC_CNTL_SLP_VAL_LO_V  0xFFFFFFFF
#define RTC_CNTL_SLP_VAL_LO_S  0

#define RTC_CNTL_SLP_TIMER1_REG          (DR_REG_RTCCNTL_BASE + 0x8)
/* RTC_CNTL_MAIN_TIMER_ALARM_EN:R/W；位位置：[16]；默认值：1'0；*/
/*描述：定时器报警启用位*/
#define RTC_CNTL_MAIN_TIMER_ALARM_EN  (BIT(16))
#define RTC_CNTL_MAIN_TIMER_ALARM_EN_M  (BIT(16))
#define RTC_CNTL_MAIN_TIMER_ALARM_EN_V  0x1
#define RTC_CNTL_MAIN_TIMER_ALARM_EN_S  16
/* RTC_CNTL_SLP_VAL_HI:R/W；比特位置：[15:0]；默认值：16'0；*/
/*描述：RTC休眠定时器高16位*/
#define RTC_CNTL_SLP_VAL_HI  0x0000FFFF
#define RTC_CNTL_SLP_VAL_HI_M  ((RTC_CNTL_SLP_VAL_HI_V)<<(RTC_CNTL_SLP_VAL_HI_S))
#define RTC_CNTL_SLP_VAL_HI_V  0xFFFF
#define RTC_CNTL_SLP_VAL_HI_S  0

#define RTC_CNTL_TIME_UPDATE_REG          (DR_REG_RTCCNTL_BASE + 0xc)
/* RTC_CNTL_TIME_UPDATE:WO；位位置：[31]；默认值：1'0；*/
/*description:设置1：用RTC计时器更新寄存器*/
#define RTC_CNTL_TIME_UPDATE  (BIT(31))
#define RTC_CNTL_TIME_UPDATE_M  (BIT(31))
#define RTC_CNTL_TIME_UPDATE_V  0x1
#define RTC_CNTL_TIME_UPDATE_S  31
/* RTC_CNTL_TIME_VALID:RO；位位置：[30]；默认值：1’b0；*/
/*description:表示寄存器已更新*/
#define RTC_CNTL_TIME_VALID  (BIT(30))
#define RTC_CNTL_TIME_VALID_M  (BIT(30))
#define RTC_CNTL_TIME_VALID_V  0x1
#define RTC_CNTL_TIME_VALID_S  30

#define RTC_CNTL_TIME0_REG          (DR_REG_RTCCNTL_BASE + 0x10)
/* RTC_CNTL_TIME_LO:RO；位位置：[31:0]；默认值：32'h0；*/
/*描述：RTC定时器低32位*/
#define RTC_CNTL_TIME_LO  0xFFFFFFFF
#define RTC_CNTL_TIME_LO_M  ((RTC_CNTL_TIME_LO_V)<<(RTC_CNTL_TIME_LO_S))
#define RTC_CNTL_TIME_LO_V  0xFFFFFFFF
#define RTC_CNTL_TIME_LO_S  0

#define RTC_CNTL_TIME1_REG          (DR_REG_RTCCNTL_BASE + 0x14)
/* RTC_CNTL_TIME_HI:RO；比特位置：[15:0]；默认值：16'0；*/
/*描述：RTC定时器高16位*/
#define RTC_CNTL_TIME_HI  0x0000FFFF
#define RTC_CNTL_TIME_HI_M  ((RTC_CNTL_TIME_HI_V)<<(RTC_CNTL_TIME_HI_S))
#define RTC_CNTL_TIME_HI_V  0xFFFF
#define RTC_CNTL_TIME_HI_S  0

#define RTC_CNTL_STATE0_REG          (DR_REG_RTCCNTL_BASE + 0x18)
/* RTC_CNTL_SLEEP_EN:R/W；位位置：[31]；默认值：1'd0；*/
/*description:休眠启用位*/
#define RTC_CNTL_SLEEP_EN  (BIT(31))
#define RTC_CNTL_SLEEP_EN_M  (BIT(31))
#define RTC_CNTL_SLEEP_EN_V  0x1
#define RTC_CNTL_SLEEP_EN_S  31
/* RTC_CNTL_SLP拒绝：R/W；位位置：[30]；默认值：1'd0；*/
/*description:休眠拒绝位*/
#define RTC_CNTL_SLP_REJECT  (BIT(30))
#define RTC_CNTL_SLP_REJECT_M  (BIT(30))
#define RTC_CNTL_SLP_REJECT_V  0x1
#define RTC_CNTL_SLP_REJECT_S  30
/* RTC_CNTL_SLP_唤醒：R/W；位位置：[29]；默认值：1'd0；*/
/*description:睡眠唤醒位*/
#define RTC_CNTL_SLP_WAKEUP  (BIT(29))
#define RTC_CNTL_SLP_WAKEUP_M  (BIT(29))
#define RTC_CNTL_SLP_WAKEUP_V  0x1
#define RTC_CNTL_SLP_WAKEUP_S  29
/* RTC_CNTL_SDIO_ACTIVE_IND:RO；位位置：[28]；默认值：1'd0；*/
/*描述：SDIO激活指示*/
#define RTC_CNTL_SDIO_ACTIVE_IND  (BIT(28))
#define RTC_CNTL_SDIO_ACTIVE_IND_M  (BIT(28))
#define RTC_CNTL_SDIO_ACTIVE_IND_V  0x1
#define RTC_CNTL_SDIO_ACTIVE_IND_S  28
/* RTC_CNTL_ULP_CP_SLP_TIMER_EN:R/W；位位置：[24]；默认值：1'd0；*/
/*描述：ULP协处理器定时器启用位*/
#define RTC_CNTL_ULP_CP_SLP_TIMER_EN  (BIT(24))
#define RTC_CNTL_ULP_CP_SLP_TIMER_EN_M  (BIT(24))
#define RTC_CNTL_ULP_CP_SLP_TIMER_EN_V  0x1
#define RTC_CNTL_ULP_CP_SLP_TIMER_EN_S  24
/* RTC_CNTL_TOUCH_SLP_TIMER_EN:R/W；位位置：[23]；默认值：1'd0；*/
/*description:触摸计时器启用位*/
#define RTC_CNTL_TOUCH_SLP_TIMER_EN  (BIT(23))
#define RTC_CNTL_TOUCH_SLP_TIMER_EN_M  (BIT(23))
#define RTC_CNTL_TOUCH_SLP_TIMER_EN_V  0x1
#define RTC_CNTL_TOUCH_SLP_TIMER_EN_S  23
/* RTC_CNTL_APB2RTC_BRIDGE_SEL:R/W；位位置：[22]；默认值：1'd0；*/
/*描述：1:APB到RTC使用网桥0:APB到RTC使用同步*/
#define RTC_CNTL_APB2RTC_BRIDGE_SEL  (BIT(22))
#define RTC_CNTL_APB2RTC_BRIDGE_SEL_M  (BIT(22))
#define RTC_CNTL_APB2RTC_BRIDGE_SEL_V  0x1
#define RTC_CNTL_APB2RTC_BRIDGE_SEL_S  22
/* RTC_CNTL_ULP_CP_WAKEUP_FORCE_EN:R/W；位位置：[21]；默认值：1'd1；*/
/*描述：ULP协处理器强制唤醒*/
#define RTC_CNTL_ULP_CP_WAKEUP_FORCE_EN  (BIT(21))
#define RTC_CNTL_ULP_CP_WAKEUP_FORCE_EN_M  (BIT(21))
#define RTC_CNTL_ULP_CP_WAKEUP_FORCE_EN_V  0x1
#define RTC_CNTL_ULP_CP_WAKEUP_FORCE_EN_S  21
/* RTC_CNTL_TOUCH_WAKEUP_FORCE_EN:R/W；位位置：[20]；默认值：1'd1；*/
/*描述：触摸控制器强制唤醒*/
#define RTC_CNTL_TOUCH_WAKEUP_FORCE_EN  (BIT(20))
#define RTC_CNTL_TOUCH_WAKEUP_FORCE_EN_M  (BIT(20))
#define RTC_CNTL_TOUCH_WAKEUP_FORCE_EN_V  0x1
#define RTC_CNTL_TOUCH_WAKEUP_FORCE_EN_S  20

#define RTC_CNTL_TIMER1_REG          (DR_REG_RTCCNTL_BASE + 0x1c)
/* RTC_CNTL_PLL_BUF_WAIT:R/W；位位置：[31:24]；默认值：8'd40；*/
/*描述：PLL等待周期为slow_clk_rtc*/
#define RTC_CNTL_PLL_BUF_WAIT  0x000000FF
#define RTC_CNTL_PLL_BUF_WAIT_M  ((RTC_CNTL_PLL_BUF_WAIT_V)<<(RTC_CNTL_PLL_BUF_WAIT_S))
#define RTC_CNTL_PLL_BUF_WAIT_V  0xFF
#define RTC_CNTL_PLL_BUF_WAIT_S  24
#define RTC_CNTL_PLL_BUF_WAIT_DEFAULT  20
/* RTC_CNTL-XTL_BUF_WAIT:R/W；比特位置：[23:14]；默认值：10'd80；*/
/*description:slow_clk_rtc中的XTAL等待周期*/
#define RTC_CNTL_XTL_BUF_WAIT  0x000003FF
#define RTC_CNTL_XTL_BUF_WAIT_M  ((RTC_CNTL_XTL_BUF_WAIT_V)<<(RTC_CNTL_XTL_BUF_WAIT_S))
#define RTC_CNTL_XTL_BUF_WAIT_V  0x3FF
#define RTC_CNTL_XTL_BUF_WAIT_S  14
#define RTC_CNTL_XTL_BUF_WAIT_DEFAULT  20
/* RTC_CNTL_CK8M_WAIT:R/W；比特位置：[13:6]；默认值：8'h10；*/
/*描述：慢_clk_rtc中的CK8M等待周期*/
#define RTC_CNTL_CK8M_WAIT  0x000000FF
#define RTC_CNTL_CK8M_WAIT_M  ((RTC_CNTL_CK8M_WAIT_V)<<(RTC_CNTL_CK8M_WAIT_S))
#define RTC_CNTL_CK8M_WAIT_V  0xFF
#define RTC_CNTL_CK8M_WAIT_S  6
#define RTC_CNTL_CK8M_WAIT_DEFAULT  20
/* RTC_CNTL_CPU_STALL_WAIT:R/W；比特位置：[5:1]；默认值：5'd1；*/
/*描述：fast_clk_rtc中的CPU暂停等待周期*/
#define RTC_CNTL_CPU_STALL_WAIT  0x0000001F
#define RTC_CNTL_CPU_STALL_WAIT_M  ((RTC_CNTL_CPU_STALL_WAIT_V)<<(RTC_CNTL_CPU_STALL_WAIT_S))
#define RTC_CNTL_CPU_STALL_WAIT_V  0x1F
#define RTC_CNTL_CPU_STALL_WAIT_S  1
/* RTC_CNTL_CPU_STALL_EN:R/W；位位置：[0]；默认值：1'd1；*/
/*description:CPU暂停启用位*/
#define RTC_CNTL_CPU_STALL_EN  (BIT(0))
#define RTC_CNTL_CPU_STALL_EN_M  (BIT(0))
#define RTC_CNTL_CPU_STALL_EN_V  0x1
#define RTC_CNTL_CPU_STALL_EN_S  0

#define RTC_CNTL_TIMER2_REG          (DR_REG_RTCCNTL_BASE + 0x20)
/* RTC_CNTL_MIN_TIME_CK8M_OFF:R/W；位位置：[31:24]；默认值：8'h1；*/
/*描述：处于断电状态的CK8M在slow_clk_rtc中的最小周期*/
#define RTC_CNTL_MIN_TIME_CK8M_OFF  0x000000FF
#define RTC_CNTL_MIN_TIME_CK8M_OFF_M  ((RTC_CNTL_MIN_TIME_CK8M_OFF_V)<<(RTC_CNTL_MIN_TIME_CK8M_OFF_S))
#define RTC_CNTL_MIN_TIME_CK8M_OFF_V  0xFF
#define RTC_CNTL_MIN_TIME_CK8M_OFF_S  24
/* RTC_CNTL_upp_TOUCH_START_WAIT:R/W；比特位置：[23:15]；默认值：9'h10；*/
/*描述：ULP协处理器/触摸控制器开始工作之前，在slow_clk_rtc中等待周期*/
#define RTC_CNTL_ULPCP_TOUCH_START_WAIT  0x000001FF
#define RTC_CNTL_ULPCP_TOUCH_START_WAIT_M  ((RTC_CNTL_ULPCP_TOUCH_START_WAIT_V)<<(RTC_CNTL_ULPCP_TOUCH_START_WAIT_S))
#define RTC_CNTL_ULPCP_TOUCH_START_WAIT_V  0x1FF
#define RTC_CNTL_ULPCP_TOUCH_START_WAIT_S  15

#define RTC_CNTL_TIMER3_REG          (DR_REG_RTCCNTL_BASE + 0x24)
/* RTC_CNTL_ROM_RAM_power_TIMER:R/W；位位置：[31:25]；默认值：7'd10；*/
/*说明：*/
#define RTC_CNTL_ROM_RAM_POWERUP_TIMER  0x0000007F
#define RTC_CNTL_ROM_RAM_POWERUP_TIMER_M  ((RTC_CNTL_ROM_RAM_POWERUP_TIMER_V)<<(RTC_CNTL_ROM_RAM_POWERUP_TIMER_S))
#define RTC_CNTL_ROM_RAM_POWERUP_TIMER_V  0x7F
#define RTC_CNTL_ROM_RAM_POWERUP_TIMER_S  25
/* RTC_CNTL_ROM_WAIT_TIMER:R/W；比特位置：[24:16]；默认值：9'h16；*/
/*说明：*/
#define RTC_CNTL_ROM_RAM_WAIT_TIMER  0x000001FF
#define RTC_CNTL_ROM_RAM_WAIT_TIMER_M  ((RTC_CNTL_ROM_RAM_WAIT_TIMER_V)<<(RTC_CNTL_ROM_RAM_WAIT_TIMER_S))
#define RTC_CNTL_ROM_RAM_WAIT_TIMER_V  0x1FF
#define RTC_CNTL_ROM_RAM_WAIT_TIMER_S  16
/* RTC_CNTL-WIFI_POWERUP_TIMER:R/W；比特位置：[15:9]；默认值：7'h5；*/
/*说明：*/
#define RTC_CNTL_WIFI_POWERUP_TIMER  0x0000007F
#define RTC_CNTL_WIFI_POWERUP_TIMER_M  ((RTC_CNTL_WIFI_POWERUP_TIMER_V)<<(RTC_CNTL_WIFI_POWERUP_TIMER_S))
#define RTC_CNTL_WIFI_POWERUP_TIMER_V  0x7F
#define RTC_CNTL_WIFI_POWERUP_TIMER_S  9
/* RTC_CNTL-WIFI_WAIT_TIMER:R/W；位位置：[8:0]；默认值：9'h8；*/
/*说明：*/
#define RTC_CNTL_WIFI_WAIT_TIMER  0x000001FF
#define RTC_CNTL_WIFI_WAIT_TIMER_M  ((RTC_CNTL_WIFI_WAIT_TIMER_V)<<(RTC_CNTL_WIFI_WAIT_TIMER_S))
#define RTC_CNTL_WIFI_WAIT_TIMER_V  0x1FF
#define RTC_CNTL_WIFI_WAIT_TIMER_S  0

#define RTC_CNTL_TIMER4_REG          (DR_REG_RTCCNTL_BASE + 0x28)
/* RTC_CNTL_DG_WRAP_power_TIMER:R/W；位位置：[31:25]；默认值：7'h8；*/
/*说明：*/
#define RTC_CNTL_DG_WRAP_POWERUP_TIMER  0x0000007F
#define RTC_CNTL_DG_WRAP_POWERUP_TIMER_M  ((RTC_CNTL_DG_WRAP_POWERUP_TIMER_V)<<(RTC_CNTL_DG_WRAP_POWERUP_TIMER_S))
#define RTC_CNTL_DG_WRAP_POWERUP_TIMER_V  0x7F
#define RTC_CNTL_DG_WRAP_POWERUP_TIMER_S  25
/* RTC_CNTL_DG_WRAP_WAIT_TIMER:R/W；比特位置：[24:16]；默认值：9'h20；*/
/*说明：*/
#define RTC_CNTL_DG_WRAP_WAIT_TIMER  0x000001FF
#define RTC_CNTL_DG_WRAP_WAIT_TIMER_M  ((RTC_CNTL_DG_WRAP_WAIT_TIMER_V)<<(RTC_CNTL_DG_WRAP_WAIT_TIMER_S))
#define RTC_CNTL_DG_WRAP_WAIT_TIMER_V  0x1FF
#define RTC_CNTL_DG_WRAP_WAIT_TIMER_S  16
/* RTC_CNTL_power_TIMER:R/W；比特位置：[15:9]；默认值：7'h5；*/
/*说明：*/
#define RTC_CNTL_POWERUP_TIMER  0x0000007F
#define RTC_CNTL_POWERUP_TIMER_M  ((RTC_CNTL_POWERUP_TIMER_V)<<(RTC_CNTL_POWERUP_TIMER_S))
#define RTC_CNTL_POWERUP_TIMER_V  0x7F
#define RTC_CNTL_POWERUP_TIMER_S  9
/* RTC_CNTL_WAIT_TIMER:R/W；位位置：[8:0]；默认值：9'h8；*/
/*说明：*/
#define RTC_CNTL_WAIT_TIMER  0x000001FF
#define RTC_CNTL_WAIT_TIMER_M  ((RTC_CNTL_WAIT_TIMER_V)<<(RTC_CNTL_WAIT_TIMER_S))
#define RTC_CNTL_WAIT_TIMER_V  0x1FF
#define RTC_CNTL_WAIT_TIMER_S  0

#define RTC_CNTL_TIMER5_REG          (DR_REG_RTCCNTL_BASE + 0x2c)
/* RTC_CNTL.rtcem_power_TIMER:R/W；位位置：[31:25]；默认值：7'h9；*/
/*说明：*/
#define RTC_CNTL_RTCMEM_POWERUP_TIMER  0x0000007F
#define RTC_CNTL_RTCMEM_POWERUP_TIMER_M  ((RTC_CNTL_RTCMEM_POWERUP_TIMER_V)<<(RTC_CNTL_RTCMEM_POWERUP_TIMER_S))
#define RTC_CNTL_RTCMEM_POWERUP_TIMER_V  0x7F
#define RTC_CNTL_RTCMEM_POWERUP_TIMER_S  25
/* RTC_CNTL-RTCMEM_WAIT_TIMER:R/W；比特位置：[24:16]；默认值：9'h14；*/
/*说明：*/
#define RTC_CNTL_RTCMEM_WAIT_TIMER  0x000001FF
#define RTC_CNTL_RTCMEM_WAIT_TIMER_M  ((RTC_CNTL_RTCMEM_WAIT_TIMER_V)<<(RTC_CNTL_RTCMEM_WAIT_TIMER_S))
#define RTC_CNTL_RTCMEM_WAIT_TIMER_V  0x1FF
#define RTC_CNTL_RTCMEM_WAIT_TIMER_S  16
/* RTC_CNTL_MIN_SLP_VAL:R/W；比特位置：[15:8]；默认值：8'h80；*/
/*描述：slowclkrtc中的最小睡眠周期*/
#define RTC_CNTL_MIN_SLP_VAL  0x000000FF
#define RTC_CNTL_MIN_SLP_VAL_M  ((RTC_CNTL_MIN_SLP_VAL_V)<<(RTC_CNTL_MIN_SLP_VAL_S))
#define RTC_CNTL_MIN_SLP_VAL_V  0xFF
#define RTC_CNTL_MIN_SLP_VAL_S  8
#define RTC_CNTL_MIN_SLP_VAL_MIN 2
/* RTC_CNTL_ULP_CP_SUBTIMER_predv:R/W；位位置：[7:0]；默认值：8'd1；*/
/*说明：*/
#define RTC_CNTL_ULP_CP_SUBTIMER_PREDIV  0x000000FF
#define RTC_CNTL_ULP_CP_SUBTIMER_PREDIV_M  ((RTC_CNTL_ULP_CP_SUBTIMER_PREDIV_V)<<(RTC_CNTL_ULP_CP_SUBTIMER_PREDIV_S))
#define RTC_CNTL_ULP_CP_SUBTIMER_PREDIV_V  0xFF
#define RTC_CNTL_ULP_CP_SUBTIMER_PREDIV_S  0

#define RTC_CNTL_ANA_CONF_REG          (DR_REG_RTCCNTL_BASE + 0x30)
/* RTC_CNTL_pl_I2C_PU:R/W；位位置：[31]；默认值：1'd0；*/
/*description:1:PLL_I2C通电，否则断电*/
#define RTC_CNTL_PLL_I2C_PU  (BIT(31))
#define RTC_CNTL_PLL_I2C_PU_M  (BIT(31))
#define RTC_CNTL_PLL_I2C_PU_V  0x1
#define RTC_CNTL_PLL_I2C_PU_S  31
/* RTC_CNTL_cckgen_I2C_PU:R/W；位位置：[30]；默认值：1'd0；*/
/*description:1:CKGEN_I2C通电，否则断电*/
#define RTC_CNTL_CKGEN_I2C_PU  (BIT(30))
#define RTC_CNTL_CKGEN_I2C_PU_M  (BIT(30))
#define RTC_CNTL_CKGEN_I2C_PU_V  0x1
#define RTC_CNTL_CKGEN_I2C_PU_S  30
/* RTC_CNTL-RFRX_PBUS_PU:R/W；位位置：[28]；默认值：1'd0；*/
/*description:1:RFRX_PBUS通电，否则断电*/
#define RTC_CNTL_RFRX_PBUS_PU  (BIT(28))
#define RTC_CNTL_RFRX_PBUS_PU_M  (BIT(28))
#define RTC_CNTL_RFRX_PBUS_PU_V  0x1
#define RTC_CNTL_RFRX_PBUS_PU_S  28
/* RTC_CNTL_TXRF_I2C_PU:R/W；位位置：[27]；默认值：1'd0；*/
/*description:1:TXRF_I2C通电否则断电*/
#define RTC_CNTL_TXRF_I2C_PU  (BIT(27))
#define RTC_CNTL_TXRF_I2C_PU_M  (BIT(27))
#define RTC_CNTL_TXRF_I2C_PU_V  0x1
#define RTC_CNTL_TXRF_I2C_PU_S  27
/* RTC_CNTL-pvtom_PU:R/W；位位置：[26]；默认值：1’b0；*/
/*description:1:PVTMON通电否则断电*/
#define RTC_CNTL_PVTMON_PU  (BIT(26))
#define RTC_CNTL_PVTMON_PU_M  (BIT(26))
#define RTC_CNTL_PVTMON_PU_V  0x1
#define RTC_CNTL_PVTMON_PU_S  26
/* RTC_CNTL_bpll_CAL_SLP_START:R/W；位位置：[25]；默认值：1’b0；*/
/*描述：在休眠期间启动BBPLL校准*/
#define RTC_CNTL_BBPLL_CAL_SLP_START  (BIT(25))
#define RTC_CNTL_BBPLL_CAL_SLP_START_M  (BIT(25))
#define RTC_CNTL_BBPLL_CAL_SLP_START_V  0x1
#define RTC_CNTL_BBPLL_CAL_SLP_START_S  25
/* RTC_CNTL_pla_FORCE_PU:R/W；位位置：[24]；默认值：1’b0；*/
/*描述：PLLA强制加电*/
#define RTC_CNTL_PLLA_FORCE_PU  (BIT(24))
#define RTC_CNTL_PLLA_FORCE_PU_M  (BIT(24))
#define RTC_CNTL_PLLA_FORCE_PU_V  0x1
#define RTC_CNTL_PLLA_FORCE_PU_S  24
/* RTC_CNTL_pla_FORCE_PD:R/W；位位置：[23]；默认值：1’b1；*/
/*描述：PLLA强制断电*/
#define RTC_CNTL_PLLA_FORCE_PD  (BIT(23))
#define RTC_CNTL_PLLA_FORCE_PD_M  (BIT(23))
#define RTC_CNTL_PLLA_FORCE_PD_V  0x1
#define RTC_CNTL_PLLA_FORCE_PD_S  23

#define RTC_CNTL_RESET_STATE_REG          (DR_REG_RTCCNTL_BASE + 0x34)
/* RTC_CNTL_PROCPU_STAT_VECTOR_SEL:R/W；位位置：[13]；默认值：1’b1；*/
/*description:PRO CPU状态向量sel*/
#define RTC_CNTL_PROCPU_STAT_VECTOR_SEL  (BIT(13))
#define RTC_CNTL_PROCPU_STAT_VECTOR_SEL_M  (BIT(13))
#define RTC_CNTL_PROCPU_STAT_VECTOR_SEL_V  0x1
#define RTC_CNTL_PROCPU_STAT_VECTOR_SEL_S  13
/* RTC_CNTL_APPCPU_STAT_VECTOR_SEL:R/W；位位置：[12]；默认值：1’b1；*/
/*description:APP CPU状态向量sel*/
#define RTC_CNTL_APPCPU_STAT_VECTOR_SEL  (BIT(12))
#define RTC_CNTL_APPCPU_STAT_VECTOR_SEL_M  (BIT(12))
#define RTC_CNTL_APPCPU_STAT_VECTOR_SEL_V  0x1
#define RTC_CNTL_APPCPU_STAT_VECTOR_SEL_S  12
/* RTC_cntlreset_CAUSE_APPCPU:RO；位位置：[11:6]；默认值：0；*/
/*description:APP CPU复位原因*/
#define RTC_CNTL_RESET_CAUSE_APPCPU  0x0000003F
#define RTC_CNTL_RESET_CAUSE_APPCPU_M  ((RTC_CNTL_RESET_CAUSE_APPCPU_V)<<(RTC_CNTL_RESET_CAUSE_APPCPU_S))
#define RTC_CNTL_RESET_CAUSE_APPCPU_V  0x3F
#define RTC_CNTL_RESET_CAUSE_APPCPU_S  6
/* RTC_cntlreset_CAUSE_procp:RO；比特位置：[5:0]；默认值：0；*/
/*description:PRO CPU复位原因*/
#define RTC_CNTL_RESET_CAUSE_PROCPU  0x0000003F
#define RTC_CNTL_RESET_CAUSE_PROCPU_M  ((RTC_CNTL_RESET_CAUSE_PROCPU_V)<<(RTC_CNTL_RESET_CAUSE_PROCPU_S))
#define RTC_CNTL_RESET_CAUSE_PROCPU_V  0x3F
#define RTC_CNTL_RESET_CAUSE_PROCPU_S  0

#define RTC_CNTL_WAKEUP_STATE_REG          (DR_REG_RTCCNTL_BASE + 0x38)
/* RTC_CNTL_GPIO_唤醒过滤器：R/W；位位置：[22]；默认值：1'd0；*/
/*description:为gpio唤醒事件启用筛选器*/
#define RTC_CNTL_GPIO_WAKEUP_FILTER  (BIT(22))
#define RTC_CNTL_GPIO_WAKEUP_FILTER_M  (BIT(22))
#define RTC_CNTL_GPIO_WAKEUP_FILTER_V  0x1
#define RTC_CNTL_GPIO_WAKEUP_FILTER_S  22
/* RTC_CNTL-WAKEUP_ENA:R/W；比特位置：[21:11]；默认值：11'b1100；*/
/*描述：唤醒启用位图*/
#define RTC_CNTL_WAKEUP_ENA  0x000007FF
#define RTC_CNTL_WAKEUP_ENA_M  ((RTC_CNTL_WAKEUP_ENA_V)<<(RTC_CNTL_WAKEUP_ENA_S))
#define RTC_CNTL_WAKEUP_ENA_V  0x7FF
#define RTC_CNTL_WAKEUP_ENA_S  11
/* RTC_CNTL-WAKEUP_CAUSE:RO；位位置：[10:0]；默认值：11'0；*/
/*description:唤醒原因*/
#define RTC_CNTL_WAKEUP_CAUSE  0x000007FF
#define RTC_CNTL_WAKEUP_CAUSE_M  ((RTC_CNTL_WAKEUP_CAUSE_V)<<(RTC_CNTL_WAKEUP_CAUSE_S))
#define RTC_CNTL_WAKEUP_CAUSE_V  0x7FF
#define RTC_CNTL_WAKEUP_CAUSE_S  0

#define RTC_CNTL_INT_ENA_REG          (DR_REG_RTCCNTL_BASE + 0x3c)
/* RTC_CNTL_MAIN_TIMER_INT_ENA:R/W；位位置：[8]；默认值：1’b0；*/
/*description:启用RTC主计时器中断*/
#define RTC_CNTL_MAIN_TIMER_INT_ENA  (BIT(8))
#define RTC_CNTL_MAIN_TIMER_INT_ENA_M  (BIT(8))
#define RTC_CNTL_MAIN_TIMER_INT_ENA_V  0x1
#define RTC_CNTL_MAIN_TIMER_INT_ENA_S  8
/* RTC_CNTL_BROWN_OUT_INT_ENA:R/W；位位置：[7]；默认值：1’b0；*/
/*描述：启用棕色中断*/
#define RTC_CNTL_BROWN_OUT_INT_ENA  (BIT(7))
#define RTC_CNTL_BROWN_OUT_INT_ENA_M  (BIT(7))
#define RTC_CNTL_BROWN_OUT_INT_ENA_V  0x1
#define RTC_CNTL_BROWN_OUT_INT_ENA_S  7
/* RTC_CNTL_TOUCH_INT_ENA:R/W；位位置：[6]；默认值：1’b0；*/
/*description:启用触摸中断*/
#define RTC_CNTL_TOUCH_INT_ENA  (BIT(6))
#define RTC_CNTL_TOUCH_INT_ENA_M  (BIT(6))
#define RTC_CNTL_TOUCH_INT_ENA_V  0x1
#define RTC_CNTL_TOUCH_INT_ENA_S  6
/* RTC_CNTL_ULP_CP_INT_ENA:R/W；位位置：[5]；默认值：1’b0；*/
/*description:启用ULP协处理器中断*/
#define RTC_CNTL_ULP_CP_INT_ENA  (BIT(5))
#define RTC_CNTL_ULP_CP_INT_ENA_M  (BIT(5))
#define RTC_CNTL_ULP_CP_INT_ENA_V  0x1
#define RTC_CNTL_ULP_CP_INT_ENA_S  5
/* RTC_CNTL_TIME_VALID_INT_ENA:R/W；位位置：[4]；默认值：1’b0；*/
/*description:启用RTC时间有效中断*/
#define RTC_CNTL_TIME_VALID_INT_ENA  (BIT(4))
#define RTC_CNTL_TIME_VALID_INT_ENA_M  (BIT(4))
#define RTC_CNTL_TIME_VALID_INT_ENA_V  0x1
#define RTC_CNTL_TIME_VALID_INT_ENA_S  4
/* RTC_CNTL_WDT_INT_ENA:R/W；位位置：[3]；默认值：1’b0；*/
/*description:启用RTC WDT中断*/
#define RTC_CNTL_WDT_INT_ENA  (BIT(3))
#define RTC_CNTL_WDT_INT_ENA_M  (BIT(3))
#define RTC_CNTL_WDT_INT_ENA_V  0x1
#define RTC_CNTL_WDT_INT_ENA_S  3
/* RTC_CNTL_SDIO_IDLE_INT_ENA：R/W；位位置：[2]；默认值：1’b0；*/
/*description:启用SDIO空闲中断*/
#define RTC_CNTL_SDIO_IDLE_INT_ENA  (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_ENA_M  (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_ENA_V  0x1
#define RTC_CNTL_SDIO_IDLE_INT_ENA_S  2
/* RTC_CNTL_SLP_REJECT_INT_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*description:启用睡眠拒绝中断*/
#define RTC_CNTL_SLP_REJECT_INT_ENA  (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_ENA_M  (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_ENA_V  0x1
#define RTC_CNTL_SLP_REJECT_INT_ENA_S  1
/* RTC_CNTL_SLP-WAKEUP_INT_ENA：R/W；位位置：[0]；默认值：1’b0；*/
/*描述：启用睡眠唤醒中断*/
#define RTC_CNTL_SLP_WAKEUP_INT_ENA  (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_ENA_M  (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_ENA_V  0x1
#define RTC_CNTL_SLP_WAKEUP_INT_ENA_S  0

#define RTC_CNTL_INT_RAW_REG          (DR_REG_RTCCNTL_BASE + 0x40)
/* RTC_CNTL_MAIN_TIMER_INT_RAW:RO；位位置：[8]；默认值：1’b0；*/
/*description:RTC主计时器中断raw*/
#define RTC_CNTL_MAIN_TIMER_INT_RAW  (BIT(8))
#define RTC_CNTL_MAIN_TIMER_INT_RAW_M  (BIT(8))
#define RTC_CNTL_MAIN_TIMER_INT_RAW_V  0x1
#define RTC_CNTL_MAIN_TIMER_INT_RAW_S  8
/* RTC_CNTL_BROWN_OUT_INT_RAW:RO；位位置：[7]；默认值：1’b0；*/
/*描述：棕色中断原始*/
#define RTC_CNTL_BROWN_OUT_INT_RAW  (BIT(7))
#define RTC_CNTL_BROWN_OUT_INT_RAW_M  (BIT(7))
#define RTC_CNTL_BROWN_OUT_INT_RAW_V  0x1
#define RTC_CNTL_BROWN_OUT_INT_RAW_S  7
/* RTC_CNTL_TOUCH_INT_RAW:RO；位位置：[6]；默认值：1’b0；*/
/*description:触摸中断raw*/
#define RTC_CNTL_TOUCH_INT_RAW  (BIT(6))
#define RTC_CNTL_TOUCH_INT_RAW_M  (BIT(6))
#define RTC_CNTL_TOUCH_INT_RAW_V  0x1
#define RTC_CNTL_TOUCH_INT_RAW_S  6
/* RTC_CNTL_ULP_CP_INT_RAW:RO；位位置：[5]；默认值：1’b0；*/
/*描述：ULP协处理器中断原始*/
#define RTC_CNTL_ULP_CP_INT_RAW  (BIT(5))
#define RTC_CNTL_ULP_CP_INT_RAW_M  (BIT(5))
#define RTC_CNTL_ULP_CP_INT_RAW_V  0x1
#define RTC_CNTL_ULP_CP_INT_RAW_S  5
/* RTC_CNTL_TIME_VALID_INT_RAW:RO；位位置：[4]；默认值：1’b0；*/
/*description:RTC时间有效中断原始*/
#define RTC_CNTL_TIME_VALID_INT_RAW  (BIT(4))
#define RTC_CNTL_TIME_VALID_INT_RAW_M  (BIT(4))
#define RTC_CNTL_TIME_VALID_INT_RAW_V  0x1
#define RTC_CNTL_TIME_VALID_INT_RAW_S  4
/* RTC_CNTL_WDT_INT_RAW:RO；位位置：[3]；默认值：1’b0；*/
/*description:RTC WDT中断原始*/
#define RTC_CNTL_WDT_INT_RAW  (BIT(3))
#define RTC_CNTL_WDT_INT_RAW_M  (BIT(3))
#define RTC_CNTL_WDT_INT_RAW_V  0x1
#define RTC_CNTL_WDT_INT_RAW_S  3
/* RTC_CNTL_SDIO_IDLE_INT_RAW:RO；位位置：[2]；默认值：1’b0；*/
/*描述：SDIO空闲中断原始*/
#define RTC_CNTL_SDIO_IDLE_INT_RAW  (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_RAW_M  (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_RAW_V  0x1
#define RTC_CNTL_SDIO_IDLE_INT_RAW_S  2
/* RTC_CNTL_SLP_REJECT_INT_RAW:RO；位位置：[1]；默认值：1’b0；*/
/*描述：睡眠拒绝中断原始*/
#define RTC_CNTL_SLP_REJECT_INT_RAW  (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_RAW_M  (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_RAW_V  0x1
#define RTC_CNTL_SLP_REJECT_INT_RAW_S  1
/* RTC_CNTL_SLP-WAKEUP_INT_RAW:RO；位位置：[0]；默认值：1’b0；*/
/*描述：睡眠唤醒中断raw*/
#define RTC_CNTL_SLP_WAKEUP_INT_RAW  (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_RAW_M  (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_RAW_V  0x1
#define RTC_CNTL_SLP_WAKEUP_INT_RAW_S  0

#define RTC_CNTL_INT_ST_REG          (DR_REG_RTCCNTL_BASE + 0x44)
/* RTC_CNTL_MAIN_TIMER_INT_ST:RO；位位置：[8]；默认值：1’b0；*/
/*description:RTC主定时器中断状态*/
#define RTC_CNTL_MAIN_TIMER_INT_ST  (BIT(8))
#define RTC_CNTL_MAIN_TIMER_INT_ST_M  (BIT(8))
#define RTC_CNTL_MAIN_TIMER_INT_ST_V  0x1
#define RTC_CNTL_MAIN_TIMER_INT_ST_S  8
/* RTC_CNTL_BROWN_OUT_INT_ST:RO；位位置：[7]；默认值：1’b0；*/
/*描述：断电中断状态*/
#define RTC_CNTL_BROWN_OUT_INT_ST  (BIT(7))
#define RTC_CNTL_BROWN_OUT_INT_ST_M  (BIT(7))
#define RTC_CNTL_BROWN_OUT_INT_ST_V  0x1
#define RTC_CNTL_BROWN_OUT_INT_ST_S  7
/* RTC_CNTL-TOUCH_INT_ST:RO；位位置：[6]；默认值：1’b0；*/
/*description:触摸中断状态*/
#define RTC_CNTL_TOUCH_INT_ST  (BIT(6))
#define RTC_CNTL_TOUCH_INT_ST_M  (BIT(6))
#define RTC_CNTL_TOUCH_INT_ST_V  0x1
#define RTC_CNTL_TOUCH_INT_ST_S  6
/* RTC_CNTL_SAR_INT_ST:RO；位位置：[5]；默认值：1’b0；*/
/*描述：ULP协处理器中断状态*/
#define RTC_CNTL_SAR_INT_ST  (BIT(5))
#define RTC_CNTL_SAR_INT_ST_M  (BIT(5))
#define RTC_CNTL_SAR_INT_ST_V  0x1
#define RTC_CNTL_SAR_INT_ST_S  5
/* RTC_CNTL_TIME_VALID_INT_ST:RO；位位置：[4]；默认值：1’b0；*/
/*description:RTC时间有效中断状态*/
#define RTC_CNTL_TIME_VALID_INT_ST  (BIT(4))
#define RTC_CNTL_TIME_VALID_INT_ST_M  (BIT(4))
#define RTC_CNTL_TIME_VALID_INT_ST_V  0x1
#define RTC_CNTL_TIME_VALID_INT_ST_S  4
/* RTC_CNTL_WDT_INT_ST:RO；位位置：[3]；默认值：1’b0；*/
/*description:RTC WDT中断状态*/
#define RTC_CNTL_WDT_INT_ST  (BIT(3))
#define RTC_CNTL_WDT_INT_ST_M  (BIT(3))
#define RTC_CNTL_WDT_INT_ST_V  0x1
#define RTC_CNTL_WDT_INT_ST_S  3
/* RTC_CNTL_SDIO_IDLE_INT_ST:RO；位位置：[2]；默认值：1’b0；*/
/*描述：SDIO空闲中断状态*/
#define RTC_CNTL_SDIO_IDLE_INT_ST  (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_ST_M  (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_ST_V  0x1
#define RTC_CNTL_SDIO_IDLE_INT_ST_S  2
/* RTC_CNTL_SLP_REJECT_INT_ST:RO；位位置：[1]；默认值：1’b0；*/
/*描述：睡眠拒绝中断状态*/
#define RTC_CNTL_SLP_REJECT_INT_ST  (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_ST_M  (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_ST_V  0x1
#define RTC_CNTL_SLP_REJECT_INT_ST_S  1
/* RTC_CNTL_SLP-WAKEUP_INT_ST:RO；位位置：[0]；默认值：1’b0；*/
/*描述：睡眠唤醒中断状态*/
#define RTC_CNTL_SLP_WAKEUP_INT_ST  (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_ST_M  (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_ST_V  0x1
#define RTC_CNTL_SLP_WAKEUP_INT_ST_S  0

#define RTC_CNTL_INT_CLR_REG          (DR_REG_RTCCNTL_BASE + 0x48)
/* RTC_CNTL_MAIN_TIMER_INT_CLR:WO；位位置：[8]；默认值：1’b0；*/
/*description:清除RTC主计时器中断状态*/
#define RTC_CNTL_MAIN_TIMER_INT_CLR  (BIT(8))
#define RTC_CNTL_MAIN_TIMER_INT_CLR_M  (BIT(8))
#define RTC_CNTL_MAIN_TIMER_INT_CLR_V  0x1
#define RTC_CNTL_MAIN_TIMER_INT_CLR_S  8
/* RTC_CNTL_BROWN_OUT_INT_CLR:WO；位位置：[7]；默认值：1’b0；*/
/*description:清除棕色中断状态*/
#define RTC_CNTL_BROWN_OUT_INT_CLR  (BIT(7))
#define RTC_CNTL_BROWN_OUT_INT_CLR_M  (BIT(7))
#define RTC_CNTL_BROWN_OUT_INT_CLR_V  0x1
#define RTC_CNTL_BROWN_OUT_INT_CLR_S  7
/* RTC_CNTL-TOUCH_INT_CLR:WO；位位置：[6]；默认值：1’b0；*/
/*description:清除触摸中断状态*/
#define RTC_CNTL_TOUCH_INT_CLR  (BIT(6))
#define RTC_CNTL_TOUCH_INT_CLR_M  (BIT(6))
#define RTC_CNTL_TOUCH_INT_CLR_V  0x1
#define RTC_CNTL_TOUCH_INT_CLR_S  6
/* RTC_CNTL_SAR_INT_CLR:WO；位位置：[5]；默认值：1’b0；*/
/*description:清除ULP协处理器中断状态*/
#define RTC_CNTL_SAR_INT_CLR  (BIT(5))
#define RTC_CNTL_SAR_INT_CLR_M  (BIT(5))
#define RTC_CNTL_SAR_INT_CLR_V  0x1
#define RTC_CNTL_SAR_INT_CLR_S  5
/* RTC_CNTL_TIME_VALID_INT_CLR:WO；位位置：[4]；默认值：1’b0；*/
/*description:清除RTC时间有效中断状态*/
#define RTC_CNTL_TIME_VALID_INT_CLR  (BIT(4))
#define RTC_CNTL_TIME_VALID_INT_CLR_M  (BIT(4))
#define RTC_CNTL_TIME_VALID_INT_CLR_V  0x1
#define RTC_CNTL_TIME_VALID_INT_CLR_S  4
/* RTC_CNTL_WDT_INT_CLR:WO；位位置：[3]；默认值：1’b0；*/
/*description:清除RTC WDT中断状态*/
#define RTC_CNTL_WDT_INT_CLR  (BIT(3))
#define RTC_CNTL_WDT_INT_CLR_M  (BIT(3))
#define RTC_CNTL_WDT_INT_CLR_V  0x1
#define RTC_CNTL_WDT_INT_CLR_S  3
/* RTC_CNTL_SDIO_IDLE_INT_CLR:WO；位位置：[2]；默认值：1’b0；*/
/*description:清除SDIO空闲中断状态*/
#define RTC_CNTL_SDIO_IDLE_INT_CLR  (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_CLR_M  (BIT(2))
#define RTC_CNTL_SDIO_IDLE_INT_CLR_V  0x1
#define RTC_CNTL_SDIO_IDLE_INT_CLR_S  2
/* RTC_CNTL_SLP_REJECT_INT_CLR:WO；位位置：[1]；默认值：1’b0；*/
/*description:清除睡眠拒绝中断状态*/
#define RTC_CNTL_SLP_REJECT_INT_CLR  (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_CLR_M  (BIT(1))
#define RTC_CNTL_SLP_REJECT_INT_CLR_V  0x1
#define RTC_CNTL_SLP_REJECT_INT_CLR_S  1
/* RTC_CNTL_SLP_WAKEUP_INT_CLR:WO；位位置：[0]；默认值：1’b0；*/
/*description:清除睡眠唤醒中断状态*/
#define RTC_CNTL_SLP_WAKEUP_INT_CLR  (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_CLR_M  (BIT(0))
#define RTC_CNTL_SLP_WAKEUP_INT_CLR_V  0x1
#define RTC_CNTL_SLP_WAKEUP_INT_CLR_S  0

#define RTC_CNTL_STORE0_REG          (DR_REG_RTCCNTL_BASE + 0x4c)
/* RTC_CNTL_SCRATCH0:R/W；位位置：[31:0]；默认值：0；*/
/*description:32位通用保留寄存器*/
#define RTC_CNTL_SCRATCH0  0xFFFFFFFF
#define RTC_CNTL_SCRATCH0_M  ((RTC_CNTL_SCRATCH0_V)<<(RTC_CNTL_SCRATCH0_S))
#define RTC_CNTL_SCRATCH0_V  0xFFFFFFFF
#define RTC_CNTL_SCRATCH0_S  0

#define RTC_CNTL_STORE1_REG          (DR_REG_RTCCNTL_BASE + 0x50)
/* RTC_CNTL_SCRATCH1:R/W；位位置：[31:0]；默认值：0；*/
/*description:32位通用保留寄存器*/
#define RTC_CNTL_SCRATCH1  0xFFFFFFFF
#define RTC_CNTL_SCRATCH1_M  ((RTC_CNTL_SCRATCH1_V)<<(RTC_CNTL_SCRATCH1_S))
#define RTC_CNTL_SCRATCH1_V  0xFFFFFFFF
#define RTC_CNTL_SCRATCH1_S  0

#define RTC_CNTL_STORE2_REG          (DR_REG_RTCCNTL_BASE + 0x54)
/* RTC_CNTL_SCRATCH2:R/W；位位置：[31:0]；默认值：0；*/
/*description:32位通用保留寄存器*/
#define RTC_CNTL_SCRATCH2  0xFFFFFFFF
#define RTC_CNTL_SCRATCH2_M  ((RTC_CNTL_SCRATCH2_V)<<(RTC_CNTL_SCRATCH2_S))
#define RTC_CNTL_SCRATCH2_V  0xFFFFFFFF
#define RTC_CNTL_SCRATCH2_S  0

#define RTC_CNTL_STORE3_REG          (DR_REG_RTCCNTL_BASE + 0x58)
/* RTC_CNTL_SCRATCH3:R/W；位位置：[31:0]；默认值：0；*/
/*description:32位通用保留寄存器*/
#define RTC_CNTL_SCRATCH3  0xFFFFFFFF
#define RTC_CNTL_SCRATCH3_M  ((RTC_CNTL_SCRATCH3_V)<<(RTC_CNTL_SCRATCH3_S))
#define RTC_CNTL_SCRATCH3_V  0xFFFFFFFF
#define RTC_CNTL_SCRATCH3_S  0

#define RTC_CNTL_EXT_XTL_CONF_REG          (DR_REG_RTCCNTL_BASE + 0x5c)
/* RTC_CNTL-XTL_EXT_CTR_EN:R/W；位位置：[31]；默认值：1’b0；*/
/*description:通过外部焊盘启用控制XTAL*/
#define RTC_CNTL_XTL_EXT_CTR_EN  (BIT(31))
#define RTC_CNTL_XTL_EXT_CTR_EN_M  (BIT(31))
#define RTC_CNTL_XTL_EXT_CTR_EN_V  0x1
#define RTC_CNTL_XTL_EXT_CTR_EN_S  31
/* RTC_CNTL-XTL_EXT_CTR_LV:R/W；位位置：[30]；默认值：1’b0；*/
/*description:0：高电平关闭XTAL 1：低电平关闭XTL*/
#define RTC_CNTL_XTL_EXT_CTR_LV  (BIT(30))
#define RTC_CNTL_XTL_EXT_CTR_LV_M  (BIT(30))
#define RTC_CNTL_XTL_EXT_CTR_LV_V  0x1
#define RTC_CNTL_XTL_EXT_CTR_LV_S  30

#define RTC_CNTL_EXT_WAKEUP_CONF_REG          (DR_REG_RTCCNTL_BASE + 0x60)
/* RTC_CNTL_EXT_WAKEUP1_LV:R/W；位位置：[31]；默认值：1’b0；*/
/*描述：0：低电平外部唤醒1：高电平外部唤醒*/
#define RTC_CNTL_EXT_WAKEUP1_LV  (BIT(31))
#define RTC_CNTL_EXT_WAKEUP1_LV_M  (BIT(31))
#define RTC_CNTL_EXT_WAKEUP1_LV_V  0x1
#define RTC_CNTL_EXT_WAKEUP1_LV_S  31
/* RTC_CNTL_EXT_WAKEUP0_LV:R/W；位位置：[30]；默认值：1’b0；*/
/*描述：0：低电平外部唤醒1：高电平外部唤醒*/
#define RTC_CNTL_EXT_WAKEUP0_LV  (BIT(30))
#define RTC_CNTL_EXT_WAKEUP0_LV_M  (BIT(30))
#define RTC_CNTL_EXT_WAKEUP0_LV_V  0x1
#define RTC_CNTL_EXT_WAKEUP0_LV_S  30

#define RTC_CNTL_SLP_REJECT_CONF_REG          (DR_REG_RTCCNTL_BASE + 0x64)
/* RTC_CNTL拒绝原因：RO；位位置：[31:28]；默认值：4'b0；*/
/*description:睡眠拒绝原因*/
#define RTC_CNTL_REJECT_CAUSE  0x0000000F
#define RTC_CNTL_REJECT_CAUSE_M  ((RTC_CNTL_REJECT_CAUSE_V)<<(RTC_CNTL_REJECT_CAUSE_S))
#define RTC_CNTL_REJECT_CAUSE_V  0xF
#define RTC_CNTL_REJECT_CAUSE_S  28
/* RTC_CNTL_dep_SLP_REJECT_EN:R/W；位位置：[27]；默认值：1’b0；*/
/*description:启用深度睡眠拒绝*/
#define RTC_CNTL_DEEP_SLP_REJECT_EN  (BIT(27))
#define RTC_CNTL_DEEP_SLP_REJECT_EN_M  (BIT(27))
#define RTC_CNTL_DEEP_SLP_REJECT_EN_V  0x1
#define RTC_CNTL_DEEP_SLP_REJECT_EN_S  27
/* RTC_CNTL_LIGHT_SLP_REJECT_EN:R/W；位位置：[26]；默认值：1’b0；*/
/*description:启用轻睡眠拒绝*/
#define RTC_CNTL_LIGHT_SLP_REJECT_EN  (BIT(26))
#define RTC_CNTL_LIGHT_SLP_REJECT_EN_M  (BIT(26))
#define RTC_CNTL_LIGHT_SLP_REJECT_EN_V  0x1
#define RTC_CNTL_LIGHT_SLP_REJECT_EN_S  26
/* RTC_CNTL_SDIO_project_EN:R/W；位位置：[25]；默认值：1’b0；*/
/*description:启用SDIO拒绝*/
#define RTC_CNTL_SDIO_REJECT_EN  (BIT(25))
#define RTC_CNTL_SDIO_REJECT_EN_M  (BIT(25))
#define RTC_CNTL_SDIO_REJECT_EN_V  0x1
#define RTC_CNTL_SDIO_REJECT_EN_S  25
/* RTC_CNTL_GPIO_project_EN:R/W；位位置：[24]；默认值：1’b0；*/
/*description:启用GPIO拒绝*/
#define RTC_CNTL_GPIO_REJECT_EN  (BIT(24))
#define RTC_CNTL_GPIO_REJECT_EN_M  (BIT(24))
#define RTC_CNTL_GPIO_REJECT_EN_V  0x1
#define RTC_CNTL_GPIO_REJECT_EN_S  24

#define RTC_CNTL_CPU_PERIOD_CONF_REG          (DR_REG_RTCCNTL_BASE + 0x68)
/* RTC_CNTL_cuperiod_SEL:R/W；比特位置：[31:30]；默认值：2’00；*/
/*description:CPU周期选择*/
#define RTC_CNTL_CPUPERIOD_SEL  0x00000003
#define RTC_CNTL_CPUPERIOD_SEL_M  ((RTC_CNTL_CPUPERIOD_SEL_V)<<(RTC_CNTL_CPUPERIOD_SEL_S))
#define RTC_CNTL_CPUPERIOD_SEL_V  0x3
#define RTC_CNTL_CPUPERIOD_SEL_S  30
/* RTC_CNTL_cusel_CONF:R/W；位位置：[29]；默认值：1’b0；*/
/*description:CPU sel选项*/
#define RTC_CNTL_CPUSEL_CONF  (BIT(29))
#define RTC_CNTL_CPUSEL_CONF_M  (BIT(29))
#define RTC_CNTL_CPUSEL_CONF_V  0x1
#define RTC_CNTL_CPUSEL_CONF_S  29

#define RTC_CNTL_SDIO_ACT_CONF_REG          (DR_REG_RTCCNTL_BASE + 0x6c)
/* RTC_CNTL_SDIO_ACT_DNUM:R/W；位位置：[31:22]；默认值：10'b0；*/
/*说明：*/
#define RTC_CNTL_SDIO_ACT_DNUM  0x000003FF
#define RTC_CNTL_SDIO_ACT_DNUM_M  ((RTC_CNTL_SDIO_ACT_DNUM_V)<<(RTC_CNTL_SDIO_ACT_DNUM_S))
#define RTC_CNTL_SDIO_ACT_DNUM_V  0x3FF
#define RTC_CNTL_SDIO_ACT_DNUM_S  22

#define RTC_CNTL_CLK_CONF_REG          (DR_REG_RTCCNTL_BASE + 0x70)
/* RTC_CNTL_ANA_CLK_RTC_SEL:R/W；比特位置：[31:30]；默认值：2'd0；*/
/*描述：slow_clk_rtc sel。0:SLOW_CK 1:CK_XTAL_32K 2:CK8M_D256_OUT*/
#define RTC_CNTL_ANA_CLK_RTC_SEL  0x00000003
#define RTC_CNTL_ANA_CLK_RTC_SEL_M  ((RTC_CNTL_ANA_CLK_RTC_SEL_V)<<(RTC_CNTL_ANA_CLK_RTC_SEL_S))
#define RTC_CNTL_ANA_CLK_RTC_SEL_V  0x3
#define RTC_CNTL_ANA_CLK_RTC_SEL_S  30
/* RTC_CNTL_FAST_CLK_RTC_SEL:R/W；位位置：[29]；默认值：1’b0；*/
/*description:fast_clk_rtc sel。0:XTAL分区4 1:CK8M*/
#define RTC_CNTL_FAST_CLK_RTC_SEL  (BIT(29))
#define RTC_CNTL_FAST_CLK_RTC_SEL_M  (BIT(29))
#define RTC_CNTL_FAST_CLK_RTC_SEL_V  0x1
#define RTC_CNTL_FAST_CLK_RTC_SEL_S  29
/* RTC_CNTL_SOC_CLK_SEL:R/W；位位置：[28:27]；默认值：2'd0；*/
/*描述：SOC时钟选择。0:XTAL 1:PLL 2:CK8M 3:APLL*/
#define RTC_CNTL_SOC_CLK_SEL  0x00000003
#define RTC_CNTL_SOC_CLK_SEL_M  ((RTC_CNTL_SOC_CLK_SEL_V)<<(RTC_CNTL_SOC_CLK_SEL_S))
#define RTC_CNTL_SOC_CLK_SEL_V  0x3
#define RTC_CNTL_SOC_CLK_SEL_S  27
#define RTC_CNTL_SOC_CLK_SEL_XTL    0
#define RTC_CNTL_SOC_CLK_SEL_PLL    1
#define RTC_CNTL_SOC_CLK_SEL_8M     2
#define RTC_CNTL_SOC_CLK_SEL_APLL   3
/* RTC_CNTL_CK8M_FORCE_PU:R/W；位位置：[26]；默认值：1'd0；*/
/*说明：CK8M强制加电*/
#define RTC_CNTL_CK8M_FORCE_PU  (BIT(26))
#define RTC_CNTL_CK8M_FORCE_PU_M  (BIT(26))
#define RTC_CNTL_CK8M_FORCE_PU_V  0x1
#define RTC_CNTL_CK8M_FORCE_PU_S  26
/* RTC_CNTL_CK8M_FORCE_PD:R/W；位位置：[25]；默认值：1'd0；*/
/*描述：CK8M强制断电*/
#define RTC_CNTL_CK8M_FORCE_PD  (BIT(25))
#define RTC_CNTL_CK8M_FORCE_PD_M  (BIT(25))
#define RTC_CNTL_CK8M_FORCE_PD_V  0x1
#define RTC_CNTL_CK8M_FORCE_PD_S  25
/* RTC_CNTL_CK8M_DFREQ:R/W；比特位置：[24:17]；默认值：8'd0；*/
/*说明：CK8M_DFREQ*/
#define RTC_CNTL_CK8M_DFREQ  0x000000FF
#define RTC_CNTL_CK8M_DFREQ_M  ((RTC_CNTL_CK8M_DFREQ_V)<<(RTC_CNTL_CK8M_DFREQ_S))
#define RTC_CNTL_CK8M_DFREQ_V  0xFF
#define RTC_CNTL_CK8M_DFREQ_S  17
#define RTC_CNTL_CK8M_DFREQ_DEFAULT 172
/* RTC_CNTL_CK8M_FORCE_noting:R/W；位位置：[16]；默认值：1'd0；*/
/*描述：CK8M在睡眠期间强制无门控*/
#define RTC_CNTL_CK8M_FORCE_NOGATING  (BIT(16))
#define RTC_CNTL_CK8M_FORCE_NOGATING_M  (BIT(16))
#define RTC_CNTL_CK8M_FORCE_NOGATING_V  0x1
#define RTC_CNTL_CK8M_FORCE_NOGATING_S  16
/* RTC_CNTL-XTAL-FORCE_noting:R/W；位位置：[15]；默认值：1'd0；*/
/*description:XTAL在睡眠期间强制无门控*/
#define RTC_CNTL_XTAL_FORCE_NOGATING  (BIT(15))
#define RTC_CNTL_XTAL_FORCE_NOGATING_M  (BIT(15))
#define RTC_CNTL_XTAL_FORCE_NOGATING_V  0x1
#define RTC_CNTL_XTAL_FORCE_NOGATING_S  15
/* RTC_CNTL_ckm_DIV_SEL:R/W；比特位置：[14:12]；默认值：3'd2；*/
/*描述：除法器=reg_ck8m_div_sel+1*/
#define RTC_CNTL_CK8M_DIV_SEL  0x00000007
#define RTC_CNTL_CK8M_DIV_SEL_M  ((RTC_CNTL_CK8M_DIV_SEL_V)<<(RTC_CNTL_CK8M_DIV_SEL_S))
#define RTC_CNTL_CK8M_DIV_SEL_V  0x7
#define RTC_CNTL_CK8M_DIV_SEL_S  12
/* RTC_CNTL_CK8M_DFREQ_FORCE:R/W；位位置：[11]；默认值：1'd0；*/
/*说明：*/
#define RTC_CNTL_CK8M_DFREQ_FORCE  (BIT(11))
#define RTC_CNTL_CK8M_DFREQ_FORCE_M  (BIT(11))
#define RTC_CNTL_CK8M_DFREQ_FORCE_V  0x1
#define RTC_CNTL_CK8M_DFREQ_FORCE_S  11
/* RTC_CNTL_DIG_CLK8M_EN:R/W；位位置：[10]；默认值：1'd0；*/
/*description:为数字核心启用CK8M（与RTC核心没有关系）*/
#define RTC_CNTL_DIG_CLK8M_EN  (BIT(10))
#define RTC_CNTL_DIG_CLK8M_EN_M  (BIT(10))
#define RTC_CNTL_DIG_CLK8M_EN_V  0x1
#define RTC_CNTL_DIG_CLK8M_EN_S  10
/* RTC_CNTL_DIG_CLK8M_D256_EN:R/W；位位置：[9]；默认值：1'd1；*/
/*description:为数字核心启用CK8M_D256_OUT（与RTC核心无关系）*/
#define RTC_CNTL_DIG_CLK8M_D256_EN  (BIT(9))
#define RTC_CNTL_DIG_CLK8M_D256_EN_M  (BIT(9))
#define RTC_CNTL_DIG_CLK8M_D256_EN_V  0x1
#define RTC_CNTL_DIG_CLK8M_D256_EN_S  9
/* RTC_CNTL_DIG_XTAL32K_EN:R/W；位位置：[8]；默认值：1'd0；*/
/*description:为数字核心启用CK_XTAL_32K（与RTC核心没有关系）*/
#define RTC_CNTL_DIG_XTAL32K_EN  (BIT(8))
#define RTC_CNTL_DIG_XTAL32K_EN_M  (BIT(8))
#define RTC_CNTL_DIG_XTAL32K_EN_V  0x1
#define RTC_CNTL_DIG_XTAL32K_EN_S  8
/* RTC_CNTL_ENB_CK8M_DIV:R/W；位位置：[7]；默认值：1'd0；*/
/*description:1:CK8M_D256_OUT实际上是CK8M 0:CK8M_D256 _OUT是CK8MM除以256*/
#define RTC_CNTL_ENB_CK8M_DIV  (BIT(7))
#define RTC_CNTL_ENB_CK8M_DIV_M  (BIT(7))
#define RTC_CNTL_ENB_CK8M_DIV_V  0x1
#define RTC_CNTL_ENB_CK8M_DIV_S  7
/* RTC_CNTL_ENB_CK8M:R/W；位位置：[6]；默认值：1'd0；*/
/*描述：禁用CK8M和CK8M_D256_OUT*/
#define RTC_CNTL_ENB_CK8M  (BIT(6))
#define RTC_CNTL_ENB_CK8M_M  (BIT(6))
#define RTC_CNTL_ENB_CK8M_V  0x1
#define RTC_CNTL_ENB_CK8M_S  6
/* RTC_CNTL_CK8M_DIV:R/W；比特位置：[5:4]；默认值：2'b01；*/
/*description:CK8M_D256_OUT除法器。00:div128 01:div256 10:div512 11:div1024。*/
#define RTC_CNTL_CK8M_DIV  0x00000003
#define RTC_CNTL_CK8M_DIV_M  ((RTC_CNTL_CK8M_DIV_V)<<(RTC_CNTL_CK8M_DIV_S))
#define RTC_CNTL_CK8M_DIV_V  0x3
#define RTC_CNTL_CK8M_DIV_S  4

#define RTC_CNTL_SDIO_CONF_REG          (DR_REG_RTCCNTL_BASE + 0x74)
/* RTC_CNTL-XPD_SDIO_REG:R/W；位位置：[31]；默认值：1'd0；*/
/*description:XPD_SDIO_REG的SW选项。仅当reg_sdio_force=1时激活*/
#define RTC_CNTL_XPD_SDIO_REG  (BIT(31))
#define RTC_CNTL_XPD_SDIO_REG_M  (BIT(31))
#define RTC_CNTL_XPD_SDIO_REG_V  0x1
#define RTC_CNTL_XPD_SDIO_REG_S  31
/* RTC_CNTL_DREFH_SDIO:R/W；位位置：[30:29]；默认值：2’00；*/
/*description:DREFH_SDIO的SW选项。仅当reg_sdio_force=1时激活*/
#define RTC_CNTL_DREFH_SDIO  0x00000003
#define RTC_CNTL_DREFH_SDIO_M  ((RTC_CNTL_DREFH_SDIO_V)<<(RTC_CNTL_DREFH_SDIO_S))
#define RTC_CNTL_DREFH_SDIO_V  0x3
#define RTC_CNTL_DREFH_SDIO_S  29
/* RTC_CNTL_defm_广播：R/W；位位置：[28:27]；默认值：2’00；*/
/*description:DREFM_SDIO的SW选项。仅当reg_sdio_force=1时激活*/
#define RTC_CNTL_DREFM_SDIO  0x00000003
#define RTC_CNTL_DREFM_SDIO_M  ((RTC_CNTL_DREFM_SDIO_V)<<(RTC_CNTL_DREFM_SDIO_S))
#define RTC_CNTL_DREFM_SDIO_V  0x3
#define RTC_CNTL_DREFM_SDIO_S  27
/* RTC_CNTL_DREFL_SDIO:R/W；比特位置：[26:25]；默认值：2'b01；*/
/*description:DREFL_SDIO的SW选项。仅当reg_sdio_force=1时激活*/
#define RTC_CNTL_DREFL_SDIO  0x00000003
#define RTC_CNTL_DREFL_SDIO_M  ((RTC_CNTL_DREFL_SDIO_V)<<(RTC_CNTL_DREFL_SDIO_S))
#define RTC_CNTL_DREFL_SDIO_V  0x3
#define RTC_CNTL_DREFL_SDIO_S  25
/* RTC_CNTL_REG1P8_READY:RO；位位置：[24]；默认值：1'd0；*/
/*description:REG1P8_READY的只读寄存器*/
#define RTC_CNTL_REG1P8_READY  (BIT(24))
#define RTC_CNTL_REG1P8_READY_M  (BIT(24))
#define RTC_CNTL_REG1P8_READY_V  0x1
#define RTC_CNTL_REG1P8_READY_S  24
/* RTC_CNTL_SDIO_TIEH:R/W；位位置：[23]；默认值：1'd1；*/
/*description:SDIO_TIEH的SW选项。仅当reg_sdio_force=1时激活*/
#define RTC_CNTL_SDIO_TIEH  (BIT(23))
#define RTC_CNTL_SDIO_TIEH_M  (BIT(23))
#define RTC_CNTL_SDIO_TIEH_V  0x1
#define RTC_CNTL_SDIO_TIEH_S  23
/* RTC_CNTL_SDIO_FORCE:R/W；位位置：[22]；默认值：1'd0；*/
/*description:1:使用SW选项控制SDIO_REG 0:使用状态机*/
#define RTC_CNTL_SDIO_FORCE  (BIT(22))
#define RTC_CNTL_SDIO_FORCE_M  (BIT(22))
#define RTC_CNTL_SDIO_FORCE_V  0x1
#define RTC_CNTL_SDIO_FORCE_S  22
/* RTC_CNTL_SDIO_PD_EN:R/W；位位置：[21]；默认值：1'd1；*/
/*描述：睡眠状态下关闭SDIO_REG。仅当reg_sdio_force=0时激活*/
#define RTC_CNTL_SDIO_PD_EN  (BIT(21))
#define RTC_CNTL_SDIO_PD_EN_M  (BIT(21))
#define RTC_CNTL_SDIO_PD_EN_V  0x1
#define RTC_CNTL_SDIO_PD_EN_S  21

#define RTC_CNTL_BIAS_CONF_REG          (DR_REG_RTCCNTL_BASE + 0x78)
/* RTC_CNTL_RST_BIAS_I2C：R/W；位位置：[31]；默认值：1'd0；*/
/*说明：RST_BIAS_I2C*/
#define RTC_CNTL_RST_BIAS_I2C  (BIT(31))
#define RTC_CNTL_RST_BIAS_I2C_M  (BIT(31))
#define RTC_CNTL_RST_BIAS_I2C_V  0x1
#define RTC_CNTL_RST_BIAS_I2C_S  31
/* RTC_CNTL_DEC_HEARTBEAT_WIDTH:R/W；位位置：[30]；默认值：1'd0；*/
/*描述：DEC_HEARTBEAT_WIDTH*/
#define RTC_CNTL_DEC_HEARTBEAT_WIDTH  (BIT(30))
#define RTC_CNTL_DEC_HEARTBEAT_WIDTH_M  (BIT(30))
#define RTC_CNTL_DEC_HEARTBEAT_WIDTH_V  0x1
#define RTC_CNTL_DEC_HEARTBEAT_WIDTH_S  30
/* RTC_CNTL_INC_HEARTBEAT_PERIOD:R/W；位位置：[29]；默认值：1'd0；*/
/*description:INC_HEARTBEAT_PERIOD*/
#define RTC_CNTL_INC_HEARTBEAT_PERIOD  (BIT(29))
#define RTC_CNTL_INC_HEARTBEAT_PERIOD_M  (BIT(29))
#define RTC_CNTL_INC_HEARTBEAT_PERIOD_V  0x1
#define RTC_CNTL_INC_HEARTBEAT_PERIOD_S  29
/* RTC_CNTL_DEC_HEARTBEAT_PERIOD:R/W；位位置：[28]；默认值：1'd0；*/
/*描述：DEC_HEARTBEAT_PERIOD*/
#define RTC_CNTL_DEC_HEARTBEAT_PERIOD  (BIT(28))
#define RTC_CNTL_DEC_HEARTBEAT_PERIOD_M  (BIT(28))
#define RTC_CNTL_DEC_HEARTBEAT_PERIOD_V  0x1
#define RTC_CNTL_DEC_HEARTBEAT_PERIOD_S  28
/* RTC_CNTL_INC_HEARTBEAT_REFRESH:R/W；位位置：[27]；默认值：1'd0；*/
/*description:INC_HEARTBEAT_FRESH*/
#define RTC_CNTL_INC_HEARTBEAT_REFRESH  (BIT(27))
#define RTC_CNTL_INC_HEARTBEAT_REFRESH_M  (BIT(27))
#define RTC_CNTL_INC_HEARTBEAT_REFRESH_V  0x1
#define RTC_CNTL_INC_HEARTBEAT_REFRESH_S  27
/* RTC_CNTL_ENB_SCK_XTAL:R/W；位位置：[26]；默认值：1'd0；*/
/*说明：ENB_SCK_XTAL*/
#define RTC_CNTL_ENB_SCK_XTAL  (BIT(26))
#define RTC_CNTL_ENB_SCK_XTAL_M  (BIT(26))
#define RTC_CNTL_ENB_SCK_XTAL_V  0x1
#define RTC_CNTL_ENB_SCK_XTAL_S  26
/* RTC_CNTL_DBG_ATTEN:R/W；位位置：[25:24]；默认值：2’00；*/
/*description:DBG_ATTEN*/
#define RTC_CNTL_DBG_ATTEN  0x00000003
#define RTC_CNTL_DBG_ATTEN_M  ((RTC_CNTL_DBG_ATTEN_V)<<(RTC_CNTL_DBG_ATTEN_S))
#define RTC_CNTL_DBG_ATTEN_V  0x3
#define RTC_CNTL_DBG_ATTEN_S  24
#define RTC_CNTL_DBG_ATTEN_DEFAULT  3
#define RTC_CNTL_REG          (DR_REG_RTCCNTL_BASE + 0x7c)
/* RTC_CNTL_FORCE_PU:R/W；位位置：[31]；默认值：1'd1；*/
/*description:RTC_REG强制加电*/
#define RTC_CNTL_FORCE_PU  (BIT(31))
#define RTC_CNTL_FORCE_PU_M  (BIT(31))
#define RTC_CNTL_FORCE_PU_V  0x1
#define RTC_CNTL_FORCE_PU_S  31
/* RTC_CNTL_FORCE_PD:R/W；位位置：[30]；默认值：1'd0；*/
/*描述：RTC_REG强制断电（对于RTC_REG断电，意味着将电压降至0.8v或更低）*/
#define RTC_CNTL_FORCE_PD  (BIT(30))
#define RTC_CNTL_FORCE_PD_M  (BIT(30))
#define RTC_CNTL_FORCE_PD_V  0x1
#define RTC_CNTL_FORCE_PD_S  30
/* RTC_CNTL_DBOOST_FORCE_PU:R/W；位位置：[29]；默认值：1'd1；*/
/*description:RTC_DBOOST强制加电*/
#define RTC_CNTL_DBOOST_FORCE_PU  (BIT(29))
#define RTC_CNTL_DBOOST_FORCE_PU_M  (BIT(29))
#define RTC_CNTL_DBOOST_FORCE_PU_V  0x1
#define RTC_CNTL_DBOOST_FORCE_PU_S  29
/* RTC_CNTL_DBOOST_FORCE_PD:R/W；位位置：[28]；默认值：1'd0；*/
/*description:RTC_DBOOST强制断电*/
#define RTC_CNTL_DBOOST_FORCE_PD  (BIT(28))
#define RTC_CNTL_DBOOST_FORCE_PD_M  (BIT(28))
#define RTC_CNTL_DBOOST_FORCE_PD_V  0x1
#define RTC_CNTL_DBOOST_FORCE_PD_S  28
/* RTC_CNTL_DBIAS_WAK:R/W；位位置：[27:25]；默认值：3'd4；*/
/*描述：唤醒期间RTC_DBIAS*/
#define RTC_CNTL_DBIAS_WAK  0x00000007
#define RTC_CNTL_DBIAS_WAK_M  ((RTC_CNTL_DBIAS_WAK_V)<<(RTC_CNTL_DBIAS_WAK_S))
#define RTC_CNTL_DBIAS_WAK_V  0x7
#define RTC_CNTL_DBIAS_WAK_S  25
/* RTC_CNTL_DBIAS_SLP:R/W；位位置：[24:22]；默认值：3'd4；*/
/*描述：睡眠期间RTC_DBIAS*/
#define RTC_CNTL_DBIAS_SLP  0x00000007
#define RTC_CNTL_DBIAS_SLP_M  ((RTC_CNTL_DBIAS_SLP_V)<<(RTC_CNTL_DBIAS_SLP_S))
#define RTC_CNTL_DBIAS_SLP_V  0x7
#define RTC_CNTL_DBIAS_SLP_S  22
/* RTC_CNTL_SCK_DCAP:R/W；比特位置：[21:14]；默认值：8'd0；*/
/*描述：SCK_DCAP*/
#define RTC_CNTL_SCK_DCAP  0x000000FF
#define RTC_CNTL_SCK_DCAP_M  ((RTC_CNTL_SCK_DCAP_V)<<(RTC_CNTL_SCK_DCAP_S))
#define RTC_CNTL_SCK_DCAP_V  0xFF
#define RTC_CNTL_SCK_DCAP_S  14
#define RTC_CNTL_SCK_DCAP_DEFAULT   255
/* RTC_CNTL_DIG_DBIAS_WAK:R/W；比特位置：[13:11]；默认值：3'd4；*/
/*description:唤醒期间DIG_REG_DBIAS*/
#define RTC_CNTL_DIG_DBIAS_WAK  0x00000007
#define RTC_CNTL_DIG_DBIAS_WAK_M  ((RTC_CNTL_DIG_DBIAS_WAK_V)<<(RTC_CNTL_DIG_DBIAS_WAK_S))
#define RTC_CNTL_DIG_DBIAS_WAK_V  0x7
#define RTC_CNTL_DIG_DBIAS_WAK_S  11
/* RTC_CNTL_DIG_DBIAS_SLP:R/W；比特位置：[10:8]；默认值：3'd4；*/
/*description:休眠期间DIG_REG_DBIAS*/
#define RTC_CNTL_DIG_DBIAS_SLP  0x00000007
#define RTC_CNTL_DIG_DBIAS_SLP_M  ((RTC_CNTL_DIG_DBIAS_SLP_V)<<(RTC_CNTL_DIG_DBIAS_SLP_S))
#define RTC_CNTL_DIG_DBIAS_SLP_V  0x7
#define RTC_CNTL_DIG_DBIAS_SLP_S  8
/* RTC_CNTL_SCK_DCAP_FORCE:R/W；位位置：[7]；默认值：1'd0；*/
/*说明：不适用*/
#define RTC_CNTL_SCK_DCAP_FORCE  (BIT(7))
#define RTC_CNTL_SCK_DCAP_FORCE_M  (BIT(7))
#define RTC_CNTL_SCK_DCAP_FORCE_V  0x1
#define RTC_CNTL_SCK_DCAP_FORCE_S  7

/* 电压与RTC_CNTL_DBIAS_WAK、RTC_CNTL_DBIAS_SLP、RTC_CNTL_DIG_BIAS_WAK值的近似映射。如果RTC_CNTL_DBG_ATTEN为0，则有效。
 */
#define RTC_CNTL_DBIAS_0V90 0
#define RTC_CNTL_DBIAS_0V95 1
#define RTC_CNTL_DBIAS_1V00 2
#define RTC_CNTL_DBIAS_1V05 3
#define RTC_CNTL_DBIAS_1V10 4
#define RTC_CNTL_DBIAS_1V15 5
#define RTC_CNTL_DBIAS_1V20 6
#define RTC_CNTL_DBIAS_1V25 7

#define RTC_CNTL_PWC_REG          (DR_REG_RTCCNTL_BASE + 0x80)
/* RTC_CNTL_PD_EN:R/W；位位置：[20]；默认值：1'd0；*/
/*描述：在睡眠中启用掉电rtc_peri*/
#define RTC_CNTL_PD_EN  (BIT(20))
#define RTC_CNTL_PD_EN_M  (BIT(20))
#define RTC_CNTL_PD_EN_V  0x1
#define RTC_CNTL_PD_EN_S  20
/* RTC_CNTL_FORCE_PU:R/W；位位置：[19]；默认值：1'd0；*/
/*description:rtc_periforce通电*/
#define RTC_CNTL_PWC_FORCE_PU  (BIT(19))
#define RTC_CNTL_PWC_FORCE_PU_M  (BIT(19))
#define RTC_CNTL_PWC_FORCE_PU_V  0x1
#define RTC_CNTL_PWC_FORCE_PU_S  19
/* RTC_CNTL_FORCE_PD:R/W；位位置：[18]；默认值：1’b0；*/
/*description:rtc_periforce断电*/
#define RTC_CNTL_PWC_FORCE_PD  (BIT(18))
#define RTC_CNTL_PWC_FORCE_PD_M  (BIT(18))
#define RTC_CNTL_PWC_FORCE_PD_V  0x1
#define RTC_CNTL_PWC_FORCE_PD_S  18
/* RTC_CNTL_SLOWMEM_PD_EN:R/W；位位置：[17]；默认值：1’b0；*/
/*description:在休眠状态下启用掉电RTC内存*/
#define RTC_CNTL_SLOWMEM_PD_EN  (BIT(17))
#define RTC_CNTL_SLOWMEM_PD_EN_M  (BIT(17))
#define RTC_CNTL_SLOWMEM_PD_EN_V  0x1
#define RTC_CNTL_SLOWMEM_PD_EN_S  17
/* RTC_CNTL_SLOWMEM_FORCE_PU:R/W；位位置：[16]；默认值：1’b1；*/
/*description:RTC内存强制加电*/
#define RTC_CNTL_SLOWMEM_FORCE_PU  (BIT(16))
#define RTC_CNTL_SLOWMEM_FORCE_PU_M  (BIT(16))
#define RTC_CNTL_SLOWMEM_FORCE_PU_V  0x1
#define RTC_CNTL_SLOWMEM_FORCE_PU_S  16
/* RTC_CNTL_SLOWMEM_FORCE_PD:R/W；位位置：[15]；默认值：1’b0；*/
/*description:RTC内存强制断电*/
#define RTC_CNTL_SLOWMEM_FORCE_PD  (BIT(15))
#define RTC_CNTL_SLOWMEM_FORCE_PD_M  (BIT(15))
#define RTC_CNTL_SLOWMEM_FORCE_PD_V  0x1
#define RTC_CNTL_SLOWMEM_FORCE_PD_S  15
/* RTC_CNTL_FASTMEM_PD_EN:R/W；位位置：[14]；默认值：1’b0；*/
/*description:在休眠状态下启用快速RTC内存断电*/
#define RTC_CNTL_FASTMEM_PD_EN  (BIT(14))
#define RTC_CNTL_FASTMEM_PD_EN_M  (BIT(14))
#define RTC_CNTL_FASTMEM_PD_EN_V  0x1
#define RTC_CNTL_FASTMEM_PD_EN_S  14
/* RTC_CNTL_FASTMEM_FORCE_PU:R/W；位位置：[13]；默认值：1’b1；*/
/*description:快速RTC内存强制加电*/
#define RTC_CNTL_FASTMEM_FORCE_PU  (BIT(13))
#define RTC_CNTL_FASTMEM_FORCE_PU_M  (BIT(13))
#define RTC_CNTL_FASTMEM_FORCE_PU_V  0x1
#define RTC_CNTL_FASTMEM_FORCE_PU_S  13
/* RTC_CNTL_FASTMEM_FORCE_PD:R/W；位位置：[12]；默认值：1’b0；*/
/*description:快速RTC内存强制断电*/
#define RTC_CNTL_FASTMEM_FORCE_PD  (BIT(12))
#define RTC_CNTL_FASTMEM_FORCE_PD_M  (BIT(12))
#define RTC_CNTL_FASTMEM_FORCE_PD_V  0x1
#define RTC_CNTL_FASTMEM_FORCE_PD_S  12
/* RTC_CNTL_SLOWMEM_FORCE_LPU:R/W；位位置：[11]；默认值：1’b1；*/
/*description:RTC内存强制无PD*/
#define RTC_CNTL_SLOWMEM_FORCE_LPU  (BIT(11))
#define RTC_CNTL_SLOWMEM_FORCE_LPU_M  (BIT(11))
#define RTC_CNTL_SLOWMEM_FORCE_LPU_V  0x1
#define RTC_CNTL_SLOWMEM_FORCE_LPU_S  11
/* RTC_CNTL_SLOWMEM_FORCE_LPD:R/W；位位置：[10]；默认值：1’b0；*/
/*description:RTC记忆力PD*/
#define RTC_CNTL_SLOWMEM_FORCE_LPD  (BIT(10))
#define RTC_CNTL_SLOWMEM_FORCE_LPD_M  (BIT(10))
#define RTC_CNTL_SLOWMEM_FORCE_LPD_V  0x1
#define RTC_CNTL_SLOWMEM_FORCE_LPD_S  10
/* RTC_CNTL_SLOWMEM_FOLW_CPU:R/W；位位置：[9]；默认值：1’b0；*/
/*描述：1:RTC内存PD跟随CPU 0:RTC内存PD跟着RTC状态机*/
#define RTC_CNTL_SLOWMEM_FOLW_CPU  (BIT(9))
#define RTC_CNTL_SLOWMEM_FOLW_CPU_M  (BIT(9))
#define RTC_CNTL_SLOWMEM_FOLW_CPU_V  0x1
#define RTC_CNTL_SLOWMEM_FOLW_CPU_S  9
/* RTC_CNTL_FASTMEM_FORCE_LPU:R/W；位位置：[8]；默认值：1’b1；*/
/*description:快速RTC内存强制无PD*/
#define RTC_CNTL_FASTMEM_FORCE_LPU  (BIT(8))
#define RTC_CNTL_FASTMEM_FORCE_LPU_M  (BIT(8))
#define RTC_CNTL_FASTMEM_FORCE_LPU_V  0x1
#define RTC_CNTL_FASTMEM_FORCE_LPU_S  8
/* RTC_CNTL_FASTMEM_FORCE_LPD:R/W；位位置：[7]；默认值：1’b0；*/
/*description:快速RTC记忆力PD*/
#define RTC_CNTL_FASTMEM_FORCE_LPD  (BIT(7))
#define RTC_CNTL_FASTMEM_FORCE_LPD_M  (BIT(7))
#define RTC_CNTL_FASTMEM_FORCE_LPD_V  0x1
#define RTC_CNTL_FASTMEM_FORCE_LPD_S  7
/* RTC_CNTL_FASTMEM_FOLW_CPU:R/W；位位置：[6]；默认值：1’b0；*/
/*描述：1：快速RTC内存PD跟随CPU 0：快速RTC存储器PD跟随RTC状态机*/
#define RTC_CNTL_FASTMEM_FOLW_CPU  (BIT(6))
#define RTC_CNTL_FASTMEM_FOLW_CPU_M  (BIT(6))
#define RTC_CNTL_FASTMEM_FOLW_CPU_V  0x1
#define RTC_CNTL_FASTMEM_FOLW_CPU_S  6
/* RTC_CNTL_FORCE_NOISO:R/W；位位置：[5]；默认值：1'd1；*/
/*description:rtc_periforce无ISO*/
#define RTC_CNTL_FORCE_NOISO  (BIT(5))
#define RTC_CNTL_FORCE_NOISO_M  (BIT(5))
#define RTC_CNTL_FORCE_NOISO_V  0x1
#define RTC_CNTL_FORCE_NOISO_S  5
/* RTC_CNTL_FORCE_ISO:R/W；位位置：[4]；默认值：1'd0；*/
/*description:rtc_periforce ISO*/
#define RTC_CNTL_FORCE_ISO  (BIT(4))
#define RTC_CNTL_FORCE_ISO_M  (BIT(4))
#define RTC_CNTL_FORCE_ISO_V  0x1
#define RTC_CNTL_FORCE_ISO_S  4
/* RTC_CNTL_SLOWMEM_FORCE_ISO：R/W；位位置：[3]；默认值：1’b0；*/
/*description:RTC内存强制ISO*/
#define RTC_CNTL_SLOWMEM_FORCE_ISO  (BIT(3))
#define RTC_CNTL_SLOWMEM_FORCE_ISO_M  (BIT(3))
#define RTC_CNTL_SLOWMEM_FORCE_ISO_V  0x1
#define RTC_CNTL_SLOWMEM_FORCE_ISO_S  3
/* RTC_CNTL_SLOWMEM_FORCE_NOISO:R/W；位位置：[2]；默认值：1’b1；*/
/*description:RTC内存强制无ISO*/
#define RTC_CNTL_SLOWMEM_FORCE_NOISO  (BIT(2))
#define RTC_CNTL_SLOWMEM_FORCE_NOISO_M  (BIT(2))
#define RTC_CNTL_SLOWMEM_FORCE_NOISO_V  0x1
#define RTC_CNTL_SLOWMEM_FORCE_NOISO_S  2
/* RTC_CNTL_FASTMEM_FORCE_ISO：R/W；位位置：[1]；默认值：1’b0；*/
/*description:快速RTC内存力ISO*/
#define RTC_CNTL_FASTMEM_FORCE_ISO  (BIT(1))
#define RTC_CNTL_FASTMEM_FORCE_ISO_M  (BIT(1))
#define RTC_CNTL_FASTMEM_FORCE_ISO_V  0x1
#define RTC_CNTL_FASTMEM_FORCE_ISO_S  1
/* RTC_CNTL_FASTMEM_FORCE_NOISO:R/W；位位置：[0]；默认值：1’b1；*/
/*description:快速RTC内存强制无ISO*/
#define RTC_CNTL_FASTMEM_FORCE_NOISO  (BIT(0))
#define RTC_CNTL_FASTMEM_FORCE_NOISO_M  (BIT(0))
#define RTC_CNTL_FASTMEM_FORCE_NOISO_V  0x1
#define RTC_CNTL_FASTMEM_FORCE_NOISO_S  0

/* RTC_CNTL_PWC_REG位的有用组*/
#define RTC_CNTL_MEM_FORCE_ISO    \
    (RTC_CNTL_SLOWMEM_FORCE_ISO | RTC_CNTL_FASTMEM_FORCE_ISO)
#define RTC_CNTL_MEM_FORCE_NOISO  \
    (RTC_CNTL_SLOWMEM_FORCE_NOISO | RTC_CNTL_FASTMEM_FORCE_NOISO)
#define RTC_CNTL_MEM_PD_EN        \
    (RTC_CNTL_SLOWMEM_PD_EN | RTC_CNTL_FASTMEM_PD_EN)
#define RTC_CNTL_MEM_FORCE_PU     \
    (RTC_CNTL_SLOWMEM_FORCE_PU | RTC_CNTL_FASTMEM_FORCE_PU)
#define RTC_CNTL_MEM_FORCE_PD     \
    (RTC_CNTL_SLOWMEM_FORCE_PD | RTC_CNTL_FASTMEM_FORCE_PD)
#define RTC_CNTL_MEM_FOLW_CPU     \
    (RTC_CNTL_SLOWMEM_FOLW_CPU | RTC_CNTL_FASTMEM_FOLW_CPU)
#define RTC_CNTL_MEM_FORCE_LPU    \
    (RTC_CNTL_SLOWMEM_FORCE_LPU | RTC_CNTL_FASTMEM_FORCE_LPU)
#define RTC_CNTL_MEM_FORCE_LPD    \
    (RTC_CNTL_SLOWMEM_FORCE_LPD | RTC_CNTL_FASTMEM_FORCE_LPD)

#define RTC_CNTL_DIG_PWC_REG          (DR_REG_RTCCNTL_BASE + 0x84)
/* RTC_CNTL_DG_WRAP_PD_EN:R/W；位位置：[31]；默认值：0；*/
/*描述：在休眠状态下启用数字内核断电*/
#define RTC_CNTL_DG_WRAP_PD_EN  (BIT(31))
#define RTC_CNTL_DG_WRAP_PD_EN_M  (BIT(31))
#define RTC_CNTL_DG_WRAP_PD_EN_V  0x1
#define RTC_CNTL_DG_WRAP_PD_EN_S  31
/* RTC_CNTL-WIFI_PD_EN:R/W；位位置：[30]；默认值：0；*/
/*描述：在睡眠中关闭wifi*/
#define RTC_CNTL_WIFI_PD_EN  (BIT(30))
#define RTC_CNTL_WIFI_PD_EN_M  (BIT(30))
#define RTC_CNTL_WIFI_PD_EN_V  0x1
#define RTC_CNTL_WIFI_PD_EN_S  30
/* RTC_CNTL_INTER_RAM4_PD_EN:R/W；位位置：[29]；默认值：0；*/
/*描述：启用休眠状态下的内部SRAM 4断电*/
#define RTC_CNTL_INTER_RAM4_PD_EN  (BIT(29))
#define RTC_CNTL_INTER_RAM4_PD_EN_M  (BIT(29))
#define RTC_CNTL_INTER_RAM4_PD_EN_V  0x1
#define RTC_CNTL_INTER_RAM4_PD_EN_S  29
/* RTC_CNTL_INTER_RAM3_PD_EN:R/W；位位置：[28]；默认值：0；*/
/*描述：启用休眠状态下的内部SRAM 3断电*/
#define RTC_CNTL_INTER_RAM3_PD_EN  (BIT(28))
#define RTC_CNTL_INTER_RAM3_PD_EN_M  (BIT(28))
#define RTC_CNTL_INTER_RAM3_PD_EN_V  0x1
#define RTC_CNTL_INTER_RAM3_PD_EN_S  28
/* RTC_CNTL_INTER_RAM2_PD_EN:R/W；位位置：[27]；默认值：0；*/
/*描述：启用休眠状态下的内部SRAM 2断电*/
#define RTC_CNTL_INTER_RAM2_PD_EN  (BIT(27))
#define RTC_CNTL_INTER_RAM2_PD_EN_M  (BIT(27))
#define RTC_CNTL_INTER_RAM2_PD_EN_V  0x1
#define RTC_CNTL_INTER_RAM2_PD_EN_S  27
/* RTC_CNTL_INTER_RAM1_PD_EN:R/W；位位置：[26]；默认值：0；*/
/*描述：启用休眠状态下的内部SRAM 1断电*/
#define RTC_CNTL_INTER_RAM1_PD_EN  (BIT(26))
#define RTC_CNTL_INTER_RAM1_PD_EN_M  (BIT(26))
#define RTC_CNTL_INTER_RAM1_PD_EN_V  0x1
#define RTC_CNTL_INTER_RAM1_PD_EN_S  26
/* RTC_CNTL_INTER_RAM0_PD_EN:R/W；位位置：[25]；默认值：0；*/
/*描述：启用休眠状态下的内部SRAM 0断电*/
#define RTC_CNTL_INTER_RAM0_PD_EN  (BIT(25))
#define RTC_CNTL_INTER_RAM0_PD_EN_M  (BIT(25))
#define RTC_CNTL_INTER_RAM0_PD_EN_V  0x1
#define RTC_CNTL_INTER_RAM0_PD_EN_S  25
/* RTC_CNTL_ROM0_PD_EN:R/W；位位置：[24]；默认值：0；*/
/*描述：启用休眠状态下的断电ROM*/
#define RTC_CNTL_ROM0_PD_EN  (BIT(24))
#define RTC_CNTL_ROM0_PD_EN_M  (BIT(24))
#define RTC_CNTL_ROM0_PD_EN_V  0x1
#define RTC_CNTL_ROM0_PD_EN_S  24
/* RTC_CNTL_DG_WRAP_FORCE_PU:R/W；位位置：[20]；默认值：1'd1；*/
/*描述：数字核心力量通电*/
#define RTC_CNTL_DG_WRAP_FORCE_PU  (BIT(20))
#define RTC_CNTL_DG_WRAP_FORCE_PU_M  (BIT(20))
#define RTC_CNTL_DG_WRAP_FORCE_PU_V  0x1
#define RTC_CNTL_DG_WRAP_FORCE_PU_S  20
/* RTC_CNTL_DG_WRAP_FORCE_PD:R/W；位位置：[19]；默认值：1’b0；*/
/*描述：数字核心力量断电*/
#define RTC_CNTL_DG_WRAP_FORCE_PD  (BIT(19))
#define RTC_CNTL_DG_WRAP_FORCE_PD_M  (BIT(19))
#define RTC_CNTL_DG_WRAP_FORCE_PD_V  0x1
#define RTC_CNTL_DG_WRAP_FORCE_PD_S  19
/* RTC_CNTL-WIFI_FORCE_PU:R/W；位位置：[18]；默认值：1'd1；*/
/*描述：wifi强制通电*/
#define RTC_CNTL_WIFI_FORCE_PU  (BIT(18))
#define RTC_CNTL_WIFI_FORCE_PU_M  (BIT(18))
#define RTC_CNTL_WIFI_FORCE_PU_V  0x1
#define RTC_CNTL_WIFI_FORCE_PU_S  18
/* RTC_CNTL-WIFI_FORCE_PD:R/W；位位置：[17]；默认值：1’b0；*/
/*描述：wifi强制断电*/
#define RTC_CNTL_WIFI_FORCE_PD  (BIT(17))
#define RTC_CNTL_WIFI_FORCE_PD_M  (BIT(17))
#define RTC_CNTL_WIFI_FORCE_PD_V  0x1
#define RTC_CNTL_WIFI_FORCE_PD_S  17
/* RTC_CNTL_INTER_RAM4_FORCE_PU:R/W；位位置：[16]；默认值：1'd1；*/
/*描述：内部SRAM 4强制加电*/
#define RTC_CNTL_INTER_RAM4_FORCE_PU  (BIT(16))
#define RTC_CNTL_INTER_RAM4_FORCE_PU_M  (BIT(16))
#define RTC_CNTL_INTER_RAM4_FORCE_PU_V  0x1
#define RTC_CNTL_INTER_RAM4_FORCE_PU_S  16
/* RTC_CNTL_INTER_RAM4_FORCE_PD:R/W；位位置：[15]；默认值：1’b0；*/
/*描述：内部SRAM 4强制断电*/
#define RTC_CNTL_INTER_RAM4_FORCE_PD  (BIT(15))
#define RTC_CNTL_INTER_RAM4_FORCE_PD_M  (BIT(15))
#define RTC_CNTL_INTER_RAM4_FORCE_PD_V  0x1
#define RTC_CNTL_INTER_RAM4_FORCE_PD_S  15
/* RTC_CNTL_INTER_RAM3_FORCE_PU:R/W；位位置：[14]；默认值：1'd1；*/
/*描述：内部SRAM 3强制加电*/
#define RTC_CNTL_INTER_RAM3_FORCE_PU  (BIT(14))
#define RTC_CNTL_INTER_RAM3_FORCE_PU_M  (BIT(14))
#define RTC_CNTL_INTER_RAM3_FORCE_PU_V  0x1
#define RTC_CNTL_INTER_RAM3_FORCE_PU_S  14
/* RTC_CNTL_INTER_RAM3_FORCE_PD:R/W；位位置：[13]；默认值：1’b0；*/
/*描述：内部SRAM 3强制断电*/
#define RTC_CNTL_INTER_RAM3_FORCE_PD  (BIT(13))
#define RTC_CNTL_INTER_RAM3_FORCE_PD_M  (BIT(13))
#define RTC_CNTL_INTER_RAM3_FORCE_PD_V  0x1
#define RTC_CNTL_INTER_RAM3_FORCE_PD_S  13
/* RTC_CNTL_INTER_RAM2_FORCE_PU:R/W；位位置：[12]；默认值：1'd1；*/
/*描述：内部SRAM 2强制加电*/
#define RTC_CNTL_INTER_RAM2_FORCE_PU  (BIT(12))
#define RTC_CNTL_INTER_RAM2_FORCE_PU_M  (BIT(12))
#define RTC_CNTL_INTER_RAM2_FORCE_PU_V  0x1
#define RTC_CNTL_INTER_RAM2_FORCE_PU_S  12
/* RTC_CNTL_INTER_RAM2_FORCE_PD:R/W；位位置：[11]；默认值：1’b0；*/
/*描述：内部SRAM 2强制断电*/
#define RTC_CNTL_INTER_RAM2_FORCE_PD  (BIT(11))
#define RTC_CNTL_INTER_RAM2_FORCE_PD_M  (BIT(11))
#define RTC_CNTL_INTER_RAM2_FORCE_PD_V  0x1
#define RTC_CNTL_INTER_RAM2_FORCE_PD_S  11
/* RTC_CNTL_INTER_RAM1_FORCE_PU:R/W；位位置：[10]；默认值：1'd1；*/
/*描述：内部SRAM 1强制加电*/
#define RTC_CNTL_INTER_RAM1_FORCE_PU  (BIT(10))
#define RTC_CNTL_INTER_RAM1_FORCE_PU_M  (BIT(10))
#define RTC_CNTL_INTER_RAM1_FORCE_PU_V  0x1
#define RTC_CNTL_INTER_RAM1_FORCE_PU_S  10
/* RTC_CNTL_INTER_RAM1_FORCE_PD:R/W；位位置：[9]；默认值：1’b0；*/
/*描述：内部SRAM 1强制断电*/
#define RTC_CNTL_INTER_RAM1_FORCE_PD  (BIT(9))
#define RTC_CNTL_INTER_RAM1_FORCE_PD_M  (BIT(9))
#define RTC_CNTL_INTER_RAM1_FORCE_PD_V  0x1
#define RTC_CNTL_INTER_RAM1_FORCE_PD_S  9
/* RTC_CNTL_INTER_RAM0_FORCE_PU:R/W；位位置：[8]；默认值：1'd1；*/
/*描述：内部SRAM 0强制加电*/
#define RTC_CNTL_INTER_RAM0_FORCE_PU  (BIT(8))
#define RTC_CNTL_INTER_RAM0_FORCE_PU_M  (BIT(8))
#define RTC_CNTL_INTER_RAM0_FORCE_PU_V  0x1
#define RTC_CNTL_INTER_RAM0_FORCE_PU_S  8
/* RTC_CNTL_INTER_RAM0_FORCE_PD:R/W；位位置：[7]；默认值：1’b0；*/
/*描述：内部SRAM 0强制断电*/
#define RTC_CNTL_INTER_RAM0_FORCE_PD  (BIT(7))
#define RTC_CNTL_INTER_RAM0_FORCE_PD_M  (BIT(7))
#define RTC_CNTL_INTER_RAM0_FORCE_PD_V  0x1
#define RTC_CNTL_INTER_RAM0_FORCE_PD_S  7
/* RTC_CNTL_ROM0_FORCE_PU:R/W；位位置：[6]；默认值：1'd1；*/
/*描述：ROM强制加电*/
#define RTC_CNTL_ROM0_FORCE_PU  (BIT(6))
#define RTC_CNTL_ROM0_FORCE_PU_M  (BIT(6))
#define RTC_CNTL_ROM0_FORCE_PU_V  0x1
#define RTC_CNTL_ROM0_FORCE_PU_S  6
/* RTC_CNTL_ROM0_FORCE_PD:R/W；位位置：[5]；默认值：1’b0；*/
/*描述：ROM强制断电*/
#define RTC_CNTL_ROM0_FORCE_PD  (BIT(5))
#define RTC_CNTL_ROM0_FORCE_PD_M  (BIT(5))
#define RTC_CNTL_ROM0_FORCE_PD_V  0x1
#define RTC_CNTL_ROM0_FORCE_PD_S  5
/* RTC_CNTL_LSLP_MEM_FORCE_PU:R/W；位位置：[4]；默认值：1’b1；*/
/*描述：数字核心中的记忆迫使睡眠中没有PD*/
#define RTC_CNTL_LSLP_MEM_FORCE_PU  (BIT(4))
#define RTC_CNTL_LSLP_MEM_FORCE_PU_M  (BIT(4))
#define RTC_CNTL_LSLP_MEM_FORCE_PU_V  0x1
#define RTC_CNTL_LSLP_MEM_FORCE_PU_S  4
/* RTC_CNTL_LSLP_MEM_FORCE_PD:R/W；位位置：[3]；默认值：1’b0；*/
/*描述：睡眠中数字核心力量PD中的记忆*/
#define RTC_CNTL_LSLP_MEM_FORCE_PD  (BIT(3))
#define RTC_CNTL_LSLP_MEM_FORCE_PD_M  (BIT(3))
#define RTC_CNTL_LSLP_MEM_FORCE_PD_V  0x1
#define RTC_CNTL_LSLP_MEM_FORCE_PD_S  3

/* RTC_CNTL_DIG_PWC_REG位的有用组*/
#define RTC_CNTL_CPU_ROM_RAM_PD_EN \
    (RTC_CNTL_INTER_RAM4_PD_EN | RTC_CNTL_INTER_RAM3_PD_EN |\
     RTC_CNTL_INTER_RAM2_PD_EN | RTC_CNTL_INTER_RAM1_PD_EN |\
     RTC_CNTL_INTER_RAM0_PD_EN | RTC_CNTL_ROM0_PD_EN)
#define RTC_CNTL_CPU_ROM_RAM_FORCE_PU \
    (RTC_CNTL_INTER_RAM4_FORCE_PU | RTC_CNTL_INTER_RAM3_FORCE_PU |\
     RTC_CNTL_INTER_RAM2_FORCE_PU | RTC_CNTL_INTER_RAM1_FORCE_PU |\
     RTC_CNTL_INTER_RAM0_FORCE_PU | RTC_CNTL_ROM0_FORCE_PU)
#define RTC_CNTL_CPU_ROM_RAM_FORCE_PD \
    (RTC_CNTL_INTER_RAM4_FORCE_PD | RTC_CNTL_INTER_RAM3_FORCE_PD |\
     RTC_CNTL_INTER_RAM2_FORCE_PD | RTC_CNTL_INTER_RAM1_FORCE_PD |\
     RTC_CNTL_INTER_RAM0_FORCE_PD | RTC_CNTL_ROM0_FORCE_PD

#define RTC_CNTL_DIG_ISO_REG          (DR_REG_RTCCNTL_BASE + 0x88)
/* RTC_CNTL_DG_WRAP_FORCE_NOISO:R/W；位位置：[31]；默认值：1'd1；*/
/*描述：数字核心力量无ISO*/
#define RTC_CNTL_DG_WRAP_FORCE_NOISO  (BIT(31))
#define RTC_CNTL_DG_WRAP_FORCE_NOISO_M  (BIT(31))
#define RTC_CNTL_DG_WRAP_FORCE_NOISO_V  0x1
#define RTC_CNTL_DG_WRAP_FORCE_NOISO_S  31
/* RTC_CNTL_DG_WRAP_FORCE_ISO:R/W；位位置：[30]；默认值：1'd0；*/
/*描述：数字核心力ISO*/
#define RTC_CNTL_DG_WRAP_FORCE_ISO  (BIT(30))
#define RTC_CNTL_DG_WRAP_FORCE_ISO_M  (BIT(30))
#define RTC_CNTL_DG_WRAP_FORCE_ISO_V  0x1
#define RTC_CNTL_DG_WRAP_FORCE_ISO_S  30
/* RTC_CNTL-WIFI_FORCE_NOISO:R/W；位位置：[29]；默认值：1'd1；*/
/*描述：wifi强制无ISO*/
#define RTC_CNTL_WIFI_FORCE_NOISO  (BIT(29))
#define RTC_CNTL_WIFI_FORCE_NOISO_M  (BIT(29))
#define RTC_CNTL_WIFI_FORCE_NOISO_V  0x1
#define RTC_CNTL_WIFI_FORCE_NOISO_S  29
/* RTC_CNTL-WIFI_FORCE_ISO:R/W；位位置：[28]；默认值：1'd0；*/
/*description:wifi强制ISO*/
#define RTC_CNTL_WIFI_FORCE_ISO  (BIT(28))
#define RTC_CNTL_WIFI_FORCE_ISO_M  (BIT(28))
#define RTC_CNTL_WIFI_FORCE_ISO_V  0x1
#define RTC_CNTL_WIFI_FORCE_ISO_S  28
/* RTC_CNTL_INTER_RAM4_FORCE_NOISO:R/W；位位置：[27]；默认值：1'd1；*/
/*描述：内部SRAM 4强制无ISO*/
#define RTC_CNTL_INTER_RAM4_FORCE_NOISO  (BIT(27))
#define RTC_CNTL_INTER_RAM4_FORCE_NOISO_M  (BIT(27))
#define RTC_CNTL_INTER_RAM4_FORCE_NOISO_V  0x1
#define RTC_CNTL_INTER_RAM4_FORCE_NOISO_S  27
/* RTC_CNTL_INTER_RAM4_FORCE_ISO:R/W；位位置：[26]；默认值：1'd0；*/
/*描述：内部SRAM 4 force ISO*/
#define RTC_CNTL_INTER_RAM4_FORCE_ISO  (BIT(26))
#define RTC_CNTL_INTER_RAM4_FORCE_ISO_M  (BIT(26))
#define RTC_CNTL_INTER_RAM4_FORCE_ISO_V  0x1
#define RTC_CNTL_INTER_RAM4_FORCE_ISO_S  26
/* RTC_CNTL_INTER_RAM3_FORCE_NOISO:R/W；位位置：[25]；默认值：1'd1；*/
/*描述：内部SRAM 3强制无ISO*/
#define RTC_CNTL_INTER_RAM3_FORCE_NOISO  (BIT(25))
#define RTC_CNTL_INTER_RAM3_FORCE_NOISO_M  (BIT(25))
#define RTC_CNTL_INTER_RAM3_FORCE_NOISO_V  0x1
#define RTC_CNTL_INTER_RAM3_FORCE_NOISO_S  25
/* RTC_CNTL_INTER_RAM3_FORCE_ISO:R/W；位位置：[24]；默认值：1'd0；*/
/*描述：内部SRAM 3 force ISO*/
#define RTC_CNTL_INTER_RAM3_FORCE_ISO  (BIT(24))
#define RTC_CNTL_INTER_RAM3_FORCE_ISO_M  (BIT(24))
#define RTC_CNTL_INTER_RAM3_FORCE_ISO_V  0x1
#define RTC_CNTL_INTER_RAM3_FORCE_ISO_S  24
/* RTC_CNTL_INTER_RAM2_FORCE_NOISO:R/W；位位置：[23]；默认值：1'd1；*/
/*描述：内部SRAM 2强制无ISO*/
#define RTC_CNTL_INTER_RAM2_FORCE_NOISO  (BIT(23))
#define RTC_CNTL_INTER_RAM2_FORCE_NOISO_M  (BIT(23))
#define RTC_CNTL_INTER_RAM2_FORCE_NOISO_V  0x1
#define RTC_CNTL_INTER_RAM2_FORCE_NOISO_S  23
/* RTC_CNTL_INTER_RAM2_FORCE_ISO:R/W；位位置：[22]；默认值：1'd0；*/
/*描述：内部SRAM 2 force ISO*/
#define RTC_CNTL_INTER_RAM2_FORCE_ISO  (BIT(22))
#define RTC_CNTL_INTER_RAM2_FORCE_ISO_M  (BIT(22))
#define RTC_CNTL_INTER_RAM2_FORCE_ISO_V  0x1
#define RTC_CNTL_INTER_RAM2_FORCE_ISO_S  22
/* RTC_CNTL_INTER_RAM1_FORCE_NOISO:R/W；位位置：[21]；默认值：1'd1；*/
/*描述：内部SRAM 1强制无ISO*/
#define RTC_CNTL_INTER_RAM1_FORCE_NOISO  (BIT(21))
#define RTC_CNTL_INTER_RAM1_FORCE_NOISO_M  (BIT(21))
#define RTC_CNTL_INTER_RAM1_FORCE_NOISO_V  0x1
#define RTC_CNTL_INTER_RAM1_FORCE_NOISO_S  21
/* RTC_CNTL_INTER_RAM1_FORCE_ISO:R/W；位位置：[20]；默认值：1'd0；*/
/*描述：内部SRAM 1 force ISO*/
#define RTC_CNTL_INTER_RAM1_FORCE_ISO  (BIT(20))
#define RTC_CNTL_INTER_RAM1_FORCE_ISO_M  (BIT(20))
#define RTC_CNTL_INTER_RAM1_FORCE_ISO_V  0x1
#define RTC_CNTL_INTER_RAM1_FORCE_ISO_S  20
/* RTC_CNTL_INTER_RAM0_FORCE_NOISO:R/W；位位置：[19]；默认值：1'd1；*/
/*描述：内部SRAM 0强制无ISO*/
#define RTC_CNTL_INTER_RAM0_FORCE_NOISO  (BIT(19))
#define RTC_CNTL_INTER_RAM0_FORCE_NOISO_M  (BIT(19))
#define RTC_CNTL_INTER_RAM0_FORCE_NOISO_V  0x1
#define RTC_CNTL_INTER_RAM0_FORCE_NOISO_S  19
/* RTC_CNTL_INTER_RAM0_FORCE_ISO:R/W；位位置：[18]；默认值：1'd0；*/
/*description:内部SRAM 0 force ISO*/
#define RTC_CNTL_INTER_RAM0_FORCE_ISO  (BIT(18))
#define RTC_CNTL_INTER_RAM0_FORCE_ISO_M  (BIT(18))
#define RTC_CNTL_INTER_RAM0_FORCE_ISO_V  0x1
#define RTC_CNTL_INTER_RAM0_FORCE_ISO_S  18
/* RTC_CNTL_ROM0_FORCE_NOISO:R/W；位位置：[17]；默认值：1'd1；*/
/*描述：ROM强制无ISO*/
#define RTC_CNTL_ROM0_FORCE_NOISO  (BIT(17))
#define RTC_CNTL_ROM0_FORCE_NOISO_M  (BIT(17))
#define RTC_CNTL_ROM0_FORCE_NOISO_V  0x1
#define RTC_CNTL_ROM0_FORCE_NOISO_S  17
/* RTC_CNTL_ROM0_FORCE_ISO:R/W；位位置：[16]；默认值：1'd0；*/
/*描述：ROM强制ISO*/
#define RTC_CNTL_ROM0_FORCE_ISO  (BIT(16))
#define RTC_CNTL_ROM0_FORCE_ISO_M  (BIT(16))
#define RTC_CNTL_ROM0_FORCE_ISO_V  0x1
#define RTC_CNTL_ROM0_FORCE_ISO_S  16
/* RTC_CNTL_DG_PAD_FORCE_HOLD:R/W；位位置：[15]；默认值：1'd0；*/
/*描述：数字垫力保持*/
#define RTC_CNTL_DG_PAD_FORCE_HOLD  (BIT(15))
#define RTC_CNTL_DG_PAD_FORCE_HOLD_M  (BIT(15))
#define RTC_CNTL_DG_PAD_FORCE_HOLD_V  0x1
#define RTC_CNTL_DG_PAD_FORCE_HOLD_S  15
/* RTC_CNTL_DG_PAD_FORCE_UNHOLD:R/W；位位置：[14]；默认值：1'd1；*/
/*描述：数字垫力取消保持*/
#define RTC_CNTL_DG_PAD_FORCE_UNHOLD  (BIT(14))
#define RTC_CNTL_DG_PAD_FORCE_UNHOLD_M  (BIT(14))
#define RTC_CNTL_DG_PAD_FORCE_UNHOLD_V  0x1
#define RTC_CNTL_DG_PAD_FORCE_UNHOLD_S  14
/* RTC_CNTL_DG_PAD_FORCE_ISO:R/W；位位置：[13]；默认值：1'd0；*/
/*description:数字垫力ISO*/
#define RTC_CNTL_DG_PAD_FORCE_ISO  (BIT(13))
#define RTC_CNTL_DG_PAD_FORCE_ISO_M  (BIT(13))
#define RTC_CNTL_DG_PAD_FORCE_ISO_V  0x1
#define RTC_CNTL_DG_PAD_FORCE_ISO_S  13
/* RTC_CNTL_DG_PAD_FORCE_NOISO:R/W；位位置：[12]；默认值：1'd1；*/
/*描述：数字垫力无ISO*/
#define RTC_CNTL_DG_PAD_FORCE_NOISO  (BIT(12))
#define RTC_CNTL_DG_PAD_FORCE_NOISO_M  (BIT(12))
#define RTC_CNTL_DG_PAD_FORCE_NOISO_V  0x1
#define RTC_CNTL_DG_PAD_FORCE_NOISO_S  12
/* RTC_CNTL_DG_PAD_AUTOHOLD_EN:R/W；位位置：[11]；默认值：1'd0；*/
/*描述：数字键盘启用自动保持*/
#define RTC_CNTL_DG_PAD_AUTOHOLD_EN  (BIT(11))
#define RTC_CNTL_DG_PAD_AUTOHOLD_EN_M  (BIT(11))
#define RTC_CNTL_DG_PAD_AUTOHOLD_EN_V  0x1
#define RTC_CNTL_DG_PAD_AUTOHOLD_EN_S  11
/* RTC_CNTL_CLR_DG_pd自动保持：WO；位位置：[10]；默认值：1'd0；*/
/*说明：wtite仅用于清除数字焊盘自动保持的寄存器*/
#define RTC_CNTL_CLR_DG_PAD_AUTOHOLD  (BIT(10))
#define RTC_CNTL_CLR_DG_PAD_AUTOHOLD_M  (BIT(10))
#define RTC_CNTL_CLR_DG_PAD_AUTOHOLD_V  0x1
#define RTC_CNTL_CLR_DG_PAD_AUTOHOLD_S  10
/* RTC_CNTL_DG_PAD_AUTOHOLD:RO；位位置：[9]；默认值：1'd0；*/
/*描述：只读寄存器，用于指示数字焊盘自动保持状态*/
#define RTC_CNTL_DG_PAD_AUTOHOLD  (BIT(9))
#define RTC_CNTL_DG_PAD_AUTOHOLD_M  (BIT(9))
#define RTC_CNTL_DG_PAD_AUTOHOLD_V  0x1
#define RTC_CNTL_DG_PAD_AUTOHOLD_S  9
/* RTC_CNTL_DIG_ISO-FORCE_ON:R/W；位位置：[8]；默认值：1'd0；*/
/*说明：*/
#define RTC_CNTL_DIG_ISO_FORCE_ON  (BIT(8))
#define RTC_CNTL_DIG_ISO_FORCE_ON_M  (BIT(8))
#define RTC_CNTL_DIG_ISO_FORCE_ON_V  0x1
#define RTC_CNTL_DIG_ISO_FORCE_ON_S  8
/* RTC_CNTL_DIG_ISO-FORCE_OFF:R/W；位位置：[7]；默认值：1'd0；*/
/*说明：*/
#define RTC_CNTL_DIG_ISO_FORCE_OFF  (BIT(7))
#define RTC_CNTL_DIG_ISO_FORCE_OFF_M  (BIT(7))
#define RTC_CNTL_DIG_ISO_FORCE_OFF_V  0x1
#define RTC_CNTL_DIG_ISO_FORCE_OFF_S  7

/* RTC_CNTL_DIG_ISO_REG位的有用组*/
#define RTC_CNTL_CPU_ROM_RAM_FORCE_ISO   \
    (RTC_CNTL_INTER_RAM4_FORCE_ISO | RTC_CNTL_INTER_RAM3_FORCE_ISO |\
     RTC_CNTL_INTER_RAM2_FORCE_ISO | RTC_CNTL_INTER_RAM1_FORCE_ISO |\
     RTC_CNTL_INTER_RAM0_FORCE_ISO | RTC_CNTL_ROM0_FORCE_ISO)
#define RTC_CNTL_CPU_ROM_RAM_FORCE_NOISO \
    (RTC_CNTL_INTER_RAM4_FORCE_NOISO | RTC_CNTL_INTER_RAM3_FORCE_NOISO |\
     RTC_CNTL_INTER_RAM2_FORCE_NOISO | RTC_CNTL_INTER_RAM1_FORCE_NOISO |\
     RTC_CNTL_INTER_RAM0_FORCE_NOISO | RTC_CNTL_ROM0_FORCE_NOISO)

#define RTC_CNTL_WDTCONFIG0_REG          (DR_REG_RTCCNTL_BASE + 0x8c)
/* RTC_CNTL_WDT_EN:R/W；位位置：[31]；默认值：1'0；*/
/*description:启用RTC WDT*/
#define RTC_CNTL_WDT_EN  (BIT(31))
#define RTC_CNTL_WDT_EN_M  (BIT(31))
#define RTC_CNTL_WDT_EN_V  0x1
#define RTC_CNTL_WDT_EN_S  31
/* RTC_CNTL_WDT_STG0:R/W；位位置：[30:28]；默认值：3'h0；*/
/*描述：1：中断阶段en 2：CPU重置阶段en 3：系统重置阶段en 4：RTC重置阶段en*/
#define RTC_CNTL_WDT_STG0  0x00000007
#define RTC_CNTL_WDT_STG0_M  ((RTC_CNTL_WDT_STG0_V)<<(RTC_CNTL_WDT_STG0_S))
#define RTC_CNTL_WDT_STG0_V  0x7
#define RTC_CNTL_WDT_STG0_S  28
/* RTC_CNTL_WDT_STG1:R/W；位位置：[27:25]；默认值：3'h0；*/
/*描述：1：中断阶段en 2：CPU重置阶段en 3：系统重置阶段en 4：RTC重置阶段en*/
#define RTC_CNTL_WDT_STG1  0x00000007
#define RTC_CNTL_WDT_STG1_M  ((RTC_CNTL_WDT_STG1_V)<<(RTC_CNTL_WDT_STG1_S))
#define RTC_CNTL_WDT_STG1_V  0x7
#define RTC_CNTL_WDT_STG1_S  25
/* RTC_CNTL_WDT_STG2:R/W；位位置：[24:22]；默认值：3'h0；*/
/*描述：1：中断阶段en 2：CPU重置阶段en 3：系统重置阶段en 4：RTC重置阶段en*/
#define RTC_CNTL_WDT_STG2  0x00000007
#define RTC_CNTL_WDT_STG2_M  ((RTC_CNTL_WDT_STG2_V)<<(RTC_CNTL_WDT_STG2_S))
#define RTC_CNTL_WDT_STG2_V  0x7
#define RTC_CNTL_WDT_STG2_S  22
/* RTC_CNTL_WDT_STG3:R/W；比特位置：[21:19]；默认值：3'h0；*/
/*描述：1：中断阶段en 2：CPU重置阶段en 3：系统重置阶段en 4：RTC重置阶段en*/
#define RTC_CNTL_WDT_STG3  0x00000007
#define RTC_CNTL_WDT_STG3_M  ((RTC_CNTL_WDT_STG3_V)<<(RTC_CNTL_WDT_STG3_S))
#define RTC_CNTL_WDT_STG3_V  0x7
#define RTC_CNTL_WDT_STG3_S  19
/* RTC_CNTL_WDT_EDGE_INT_EN:R/W；位位置：[18]；默认值：1'0；*/
/*说明：不适用*/
#define RTC_CNTL_WDT_EDGE_INT_EN  (BIT(18))
#define RTC_CNTL_WDT_EDGE_INT_EN_M  (BIT(18))
#define RTC_CNTL_WDT_EDGE_INT_EN_V  0x1
#define RTC_CNTL_WDT_EDGE_INT_EN_S  18
/* RTC_CNTL_WDT_LEVEL_INT_EN:R/W；位位置：[17]；默认值：1'0；*/
/*说明：不适用*/
#define RTC_CNTL_WDT_LEVEL_INT_EN  (BIT(17))
#define RTC_CNTL_WDT_LEVEL_INT_EN_M  (BIT(17))
#define RTC_CNTL_WDT_LEVEL_INT_EN_V  0x1
#define RTC_CNTL_WDT_LEVEL_INT_EN_S  17
/* RTC_CNTL_WDT_CPU_RESET_LENGTH:R/W；比特位置：[16:14]；默认值：3'h1；*/
/*description:CPU重置计数器长度*/
#define RTC_CNTL_WDT_CPU_RESET_LENGTH  0x00000007
#define RTC_CNTL_WDT_CPU_RESET_LENGTH_M  ((RTC_CNTL_WDT_CPU_RESET_LENGTH_V)<<(RTC_CNTL_WDT_CPU_RESET_LENGTH_S))
#define RTC_CNTL_WDT_CPU_RESET_LENGTH_V  0x7
#define RTC_CNTL_WDT_CPU_RESET_LENGTH_S  14
/* RTC_CNTL_WDT_SYS_RESET_LENGTH:R/W；比特位置：[13:11]；默认值：3'h1；*/
/*描述：系统重置计数器长度*/
#define RTC_CNTL_WDT_SYS_RESET_LENGTH  0x00000007
#define RTC_CNTL_WDT_SYS_RESET_LENGTH_M  ((RTC_CNTL_WDT_SYS_RESET_LENGTH_V)<<(RTC_CNTL_WDT_SYS_RESET_LENGTH_S))
#define RTC_CNTL_WDT_SYS_RESET_LENGTH_V  0x7
#define RTC_CNTL_WDT_SYS_RESET_LENGTH_S  11
/* RTC_CNTL_WDT_FLASHBOOT_MOD_EN:R/W；位位置：[10]；默认值：1'h1；*/
/*description:在闪存引导中启用WDT*/
#define RTC_CNTL_WDT_FLASHBOOT_MOD_EN  (BIT(10))
#define RTC_CNTL_WDT_FLASHBOOT_MOD_EN_M  (BIT(10))
#define RTC_CNTL_WDT_FLASHBOOT_MOD_EN_V  0x1
#define RTC_CNTL_WDT_FLASHBOOT_MOD_EN_S  10
/* RTC_CNTL_WDT_PROCPU_RESET_EN:R/W；位位置：[9]；默认值：1'd0；*/
/*description:启用WDT重置PRO CPU*/
#define RTC_CNTL_WDT_PROCPU_RESET_EN  (BIT(9))
#define RTC_CNTL_WDT_PROCPU_RESET_EN_M  (BIT(9))
#define RTC_CNTL_WDT_PROCPU_RESET_EN_V  0x1
#define RTC_CNTL_WDT_PROCPU_RESET_EN_S  9
/* RTC_CNTL_WDT_APPCPU_RESET_EN:R/W；位位置：[8]；默认值：1'd0；*/
/*description:启用WDT重置APP CPU*/
#define RTC_CNTL_WDT_APPCPU_RESET_EN  (BIT(8))
#define RTC_CNTL_WDT_APPCPU_RESET_EN_M  (BIT(8))
#define RTC_CNTL_WDT_APPCPU_RESET_EN_V  0x1
#define RTC_CNTL_WDT_APPCPU_RESET_EN_S  8
/* RTC_CNTL_WDT_PAUSE_IN_SLP:R/W；位位置：[7]；默认值：1'd1；*/
/*description:休眠时暂停WDT*/
#define RTC_CNTL_WDT_PAUSE_IN_SLP  (BIT(7))
#define RTC_CNTL_WDT_PAUSE_IN_SLP_M  (BIT(7))
#define RTC_CNTL_WDT_PAUSE_IN_SLP_V  0x1
#define RTC_CNTL_WDT_PAUSE_IN_SLP_S  7
/* RTC_CNTL_WDT_STGX : */
/*描述：阶段动作选择值*/
#define RTC_WDT_STG_SEL_OFF             0
#define RTC_WDT_STG_SEL_INT             1
#define RTC_WDT_STG_SEL_RESET_CPU       2
#define RTC_WDT_STG_SEL_RESET_SYSTEM    3
#define RTC_WDT_STG_SEL_RESET_RTC       4

#define RTC_CNTL_WDTCONFIG1_REG          (DR_REG_RTCCNTL_BASE + 0x90)
/* RTC_CNTL_WDT_STG0_HOLD:R/W；位位置：[31:0]；默认值：32'd128000；*/
/*说明：*/
#define RTC_CNTL_WDT_STG0_HOLD  0xFFFFFFFF
#define RTC_CNTL_WDT_STG0_HOLD_M  ((RTC_CNTL_WDT_STG0_HOLD_V)<<(RTC_CNTL_WDT_STG0_HOLD_S))
#define RTC_CNTL_WDT_STG0_HOLD_V  0xFFFFFFFF
#define RTC_CNTL_WDT_STG0_HOLD_S  0

#define RTC_CNTL_WDTCONFIG2_REG          (DR_REG_RTCCNTL_BASE + 0x94)
/* RTC_CNTL_WDT_STG1_HOLD:R/W；位位置：[31:0]；默认值：32'd80000；*/
/*说明：*/
#define RTC_CNTL_WDT_STG1_HOLD  0xFFFFFFFF
#define RTC_CNTL_WDT_STG1_HOLD_M  ((RTC_CNTL_WDT_STG1_HOLD_V)<<(RTC_CNTL_WDT_STG1_HOLD_S))
#define RTC_CNTL_WDT_STG1_HOLD_V  0xFFFFFFFF
#define RTC_CNTL_WDT_STG1_HOLD_S  0

#define RTC_CNTL_WDTCONFIG3_REG          (DR_REG_RTCCNTL_BASE + 0x98)
/* RTC_CNTL_WDT_STG2_HOLD:R/W；位位置：[31:0]；默认值：32'fff；*/
/*说明：*/
#define RTC_CNTL_WDT_STG2_HOLD  0xFFFFFFFF
#define RTC_CNTL_WDT_STG2_HOLD_M  ((RTC_CNTL_WDT_STG2_HOLD_V)<<(RTC_CNTL_WDT_STG2_HOLD_S))
#define RTC_CNTL_WDT_STG2_HOLD_V  0xFFFFFFFF
#define RTC_CNTL_WDT_STG2_HOLD_S  0

#define RTC_CNTL_WDTCONFIG4_REG          (DR_REG_RTCCNTL_BASE + 0x9c)
/* RTC_CNTL_WDT_STG3_HOLD:R/W；位位置：[31:0]；默认值：32'fff；*/
/*说明：*/
#define RTC_CNTL_WDT_STG3_HOLD  0xFFFFFFFF
#define RTC_CNTL_WDT_STG3_HOLD_M  ((RTC_CNTL_WDT_STG3_HOLD_V)<<(RTC_CNTL_WDT_STG3_HOLD_S))
#define RTC_CNTL_WDT_STG3_HOLD_V  0xFFFFFFFF
#define RTC_CNTL_WDT_STG3_HOLD_S  0

#define RTC_CNTL_WDTFEED_REG          (DR_REG_RTCCNTL_BASE + 0xa0)
/* RTC_CNTL_WDT_FEED:WO；位位置：[31]；默认值：1'd0；*/
/*说明：*/
#define RTC_CNTL_WDT_FEED  (BIT(31))
#define RTC_CNTL_WDT_FEED_M  (BIT(31))
#define RTC_CNTL_WDT_FEED_V  0x1
#define RTC_CNTL_WDT_FEED_S  31

#define RTC_CNTL_WDTWPROTECT_REG          (DR_REG_RTCCNTL_BASE + 0xa4)
/* RTC_CNTL_WDT_WKEY：R/W；位位置：[31:0]；默认值：32'h50d83aa1；*/
/*说明：*/
#define RTC_CNTL_WDT_WKEY  0xFFFFFFFF
#define RTC_CNTL_WDT_WKEY_M  ((RTC_CNTL_WDT_WKEY_V)<<(RTC_CNTL_WDT_WKEY_S))
#define RTC_CNTL_WDT_WKEY_V  0xFFFFFFFF
#define RTC_CNTL_WDT_WKEY_S  0

#define RTC_CNTL_TEST_MUX_REG          (DR_REG_RTCCNTL_BASE + 0xa8)
/* RTC_CNTL_DTEST_RTC:R/W；比特位置：[31:30]；默认值：2'd0；*/
/*描述：DTEST_RTC*/
#define RTC_CNTL_DTEST_RTC  0x00000003
#define RTC_CNTL_DTEST_RTC_M  ((RTC_CNTL_DTEST_RTC_V)<<(RTC_CNTL_DTEST_RTC_S))
#define RTC_CNTL_DTEST_RTC_V  0x3
#define RTC_CNTL_DTEST_RTC_S  30
/* RTC_CNTL_ENT_RTC:R/W；位位置：[29]；默认值：1'd0；*/
/*描述：ENT_RTC*/
#define RTC_CNTL_ENT_RTC  (BIT(29))
#define RTC_CNTL_ENT_RTC_M  (BIT(29))
#define RTC_CNTL_ENT_RTC_V  0x1
#define RTC_CNTL_ENT_RTC_S  29

#define RTC_CNTL_SW_CPU_STALL_REG          (DR_REG_RTCCNTL_BASE + 0xac)
/* RTC_CNTL_SW_STALL_PROCPU_C1:R/W；位位置：[31:26]；默认值：6'b0；*/
/*描述：｛reg_sw_stall_procpu_c1[5:0]reg_sw_stall_procpu_c0[1:0]｝==0x86将停止PRO CPU*/
#define RTC_CNTL_SW_STALL_PROCPU_C1  0x0000003F
#define RTC_CNTL_SW_STALL_PROCPU_C1_M  ((RTC_CNTL_SW_STALL_PROCPU_C1_V)<<(RTC_CNTL_SW_STALL_PROCPU_C1_S))
#define RTC_CNTL_SW_STALL_PROCPU_C1_V  0x3F
#define RTC_CNTL_SW_STALL_PROCPU_C1_S  26
/* RTC_CNTL_SW_STALL_APPCPU_C1:R/W；位位置：[25:20]；默认值：6'b0；*/
/*描述：｛reg_sw_stall_appcpu_c1[5:0]reg_sw_stall_appcp u_c0[1:0]｝==0x86将停止APP CPU*/
#define RTC_CNTL_SW_STALL_APPCPU_C1  0x0000003F
#define RTC_CNTL_SW_STALL_APPCPU_C1_M  ((RTC_CNTL_SW_STALL_APPCPU_C1_V)<<(RTC_CNTL_SW_STALL_APPCPU_C1_S))
#define RTC_CNTL_SW_STALL_APPCPU_C1_V  0x3F
#define RTC_CNTL_SW_STALL_APPCPU_C1_S  20

#define RTC_CNTL_STORE4_REG          (DR_REG_RTCCNTL_BASE + 0xb0)
/* RTC_CNTL_SCRATCH4:R/W；位位置：[31:0]；默认值：0；*/
/*description:32位通用保留寄存器*/
#define RTC_CNTL_SCRATCH4  0xFFFFFFFF
#define RTC_CNTL_SCRATCH4_M  ((RTC_CNTL_SCRATCH4_V)<<(RTC_CNTL_SCRATCH4_S))
#define RTC_CNTL_SCRATCH4_V  0xFFFFFFFF
#define RTC_CNTL_SCRATCH4_S  0

#define RTC_CNTL_STORE5_REG          (DR_REG_RTCCNTL_BASE + 0xb4)
/* RTC_CNTL_SCRATCH5:R/W；位位置：[31:0]；默认值：0；*/
/*description:32位通用保留寄存器*/
#define RTC_CNTL_SCRATCH5  0xFFFFFFFF
#define RTC_CNTL_SCRATCH5_M  ((RTC_CNTL_SCRATCH5_V)<<(RTC_CNTL_SCRATCH5_S))
#define RTC_CNTL_SCRATCH5_V  0xFFFFFFFF
#define RTC_CNTL_SCRATCH5_S  0

#define RTC_CNTL_STORE6_REG          (DR_REG_RTCCNTL_BASE + 0xb8)
/* RTC_CNTL_SCRATCH6:R/W；位位置：[31:0]；默认值：0；*/
/*description:32位通用保留寄存器*/
#define RTC_CNTL_SCRATCH6  0xFFFFFFFF
#define RTC_CNTL_SCRATCH6_M  ((RTC_CNTL_SCRATCH6_V)<<(RTC_CNTL_SCRATCH6_S))
#define RTC_CNTL_SCRATCH6_V  0xFFFFFFFF
#define RTC_CNTL_SCRATCH6_S  0

#define RTC_CNTL_STORE7_REG          (DR_REG_RTCCNTL_BASE + 0xbc)
/* RTC_CNTL_SCRATCH7:R/W；位位置：[31:0]；默认值：0；*/
/*description:32位通用保留寄存器*/
#define RTC_CNTL_SCRATCH7  0xFFFFFFFF
#define RTC_CNTL_SCRATCH7_M  ((RTC_CNTL_SCRATCH7_V)<<(RTC_CNTL_SCRATCH7_S))
#define RTC_CNTL_SCRATCH7_V  0xFFFFFFFF
#define RTC_CNTL_SCRATCH7_S  0

#define RTC_CNTL_LOW_POWER_ST_REG          (DR_REG_RTCCNTL_BASE + 0xc0)
/* 用于唤醒的RTC_CNTL_RDY:R/0；位位置：[19]；默认值：0*/
/*description:如果RTC控制器准备好执行WAKE指令，则为1，否则为0*/
#define RTC_CNTL_RDY_FOR_WAKEUP  (BIT(19))
#define RTC_CNTL_RDY_FOR_WAKEUP_M  (BIT(19))
#define RTC_CNTL_RDY_FOR_WAKEUP_V  0x1
#define RTC_CNTL_RDY_FOR_WAKEUP_S  19

/* 兼容性定义*/
#define RTC_CNTL_DIAG0_REG RTC_CNTL_LOW_POWER_ST_REG
/* RTC_CNTL_LOW_POWER_DIAG0:RO；位位置：[31:0]；默认值：0；*/
/*说明：*/
#define RTC_CNTL_LOW_POWER_DIAG0  0xFFFFFFFF
#define RTC_CNTL_LOW_POWER_DIAG0_M  ((RTC_CNTL_LOW_POWER_DIAG0_V)<<(RTC_CNTL_LOW_POWER_DIAG0_S))
#define RTC_CNTL_LOW_POWER_DIAG0_V  0xFFFFFFFF
#define RTC_CNTL_LOW_POWER_DIAG0_S  0

#define RTC_CNTL_DIAG1_REG          (DR_REG_RTCCNTL_BASE + 0xc4)
/* RTC_CNTL_LOW_POWER_DIAG1:RO；位位置：[31:0]；默认值：0；*/
/*说明：*/
#define RTC_CNTL_LOW_POWER_DIAG1  0xFFFFFFFF
#define RTC_CNTL_LOW_POWER_DIAG1_M  ((RTC_CNTL_LOW_POWER_DIAG1_V)<<(RTC_CNTL_LOW_POWER_DIAG1_S))
#define RTC_CNTL_LOW_POWER_DIAG1_V  0xFFFFFFFF
#define RTC_CNTL_LOW_POWER_DIAG1_S  0

#define RTC_CNTL_HOLD_FORCE_REG          (DR_REG_RTCCNTL_BASE + 0xc8)
/* RTC_cntlx32n_HOLD_FORCE:R/W；位位置：[17]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_X32N_HOLD_FORCE  (BIT(17))
#define RTC_CNTL_X32N_HOLD_FORCE_M  (BIT(17))
#define RTC_CNTL_X32N_HOLD_FORCE_V  0x1
#define RTC_CNTL_X32N_HOLD_FORCE_S  17
/* RTC_cntlx32p_HOLD_FORCE:R/W；位位置：[16]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_X32P_HOLD_FORCE  (BIT(16))
#define RTC_CNTL_X32P_HOLD_FORCE_M  (BIT(16))
#define RTC_CNTL_X32P_HOLD_FORCE_V  0x1
#define RTC_CNTL_X32P_HOLD_FORCE_S  16
/* RTC_CNTL_TOUCH_PAD7_HOLD_FORCE:R/W；位位置：[15]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_TOUCH_PAD7_HOLD_FORCE  (BIT(15))
#define RTC_CNTL_TOUCH_PAD7_HOLD_FORCE_M  (BIT(15))
#define RTC_CNTL_TOUCH_PAD7_HOLD_FORCE_V  0x1
#define RTC_CNTL_TOUCH_PAD7_HOLD_FORCE_S  15
/* RTC_CNTL_TOUCH_PAD6_HOLD_FORCE:R/W；位位置：[14]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_TOUCH_PAD6_HOLD_FORCE  (BIT(14))
#define RTC_CNTL_TOUCH_PAD6_HOLD_FORCE_M  (BIT(14))
#define RTC_CNTL_TOUCH_PAD6_HOLD_FORCE_V  0x1
#define RTC_CNTL_TOUCH_PAD6_HOLD_FORCE_S  14
/* RTC_CNTL_TOUCH_PAD5_HOLD_FORCE:R/W；位位置：[13]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_TOUCH_PAD5_HOLD_FORCE  (BIT(13))
#define RTC_CNTL_TOUCH_PAD5_HOLD_FORCE_M  (BIT(13))
#define RTC_CNTL_TOUCH_PAD5_HOLD_FORCE_V  0x1
#define RTC_CNTL_TOUCH_PAD5_HOLD_FORCE_S  13
/* RTC_CNTL_TOUCH_PAD4_HOLD_FORCE:R/W；位位置：[12]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_TOUCH_PAD4_HOLD_FORCE  (BIT(12))
#define RTC_CNTL_TOUCH_PAD4_HOLD_FORCE_M  (BIT(12))
#define RTC_CNTL_TOUCH_PAD4_HOLD_FORCE_V  0x1
#define RTC_CNTL_TOUCH_PAD4_HOLD_FORCE_S  12
/* RTC_CNTL_TOUCH_PAD3_HOLD_FORCE:R/W；位位置：[11]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_TOUCH_PAD3_HOLD_FORCE  (BIT(11))
#define RTC_CNTL_TOUCH_PAD3_HOLD_FORCE_M  (BIT(11))
#define RTC_CNTL_TOUCH_PAD3_HOLD_FORCE_V  0x1
#define RTC_CNTL_TOUCH_PAD3_HOLD_FORCE_S  11
/* RTC_CNTL_TOUCH_PAD2_HOLD_FORCE:R/W；位位置：[10]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_TOUCH_PAD2_HOLD_FORCE  (BIT(10))
#define RTC_CNTL_TOUCH_PAD2_HOLD_FORCE_M  (BIT(10))
#define RTC_CNTL_TOUCH_PAD2_HOLD_FORCE_V  0x1
#define RTC_CNTL_TOUCH_PAD2_HOLD_FORCE_S  10
/* RTC_CNTL_TOUCH_PAD1_HOLD_FORCE:R/W；位位置：[9]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_TOUCH_PAD1_HOLD_FORCE  (BIT(9))
#define RTC_CNTL_TOUCH_PAD1_HOLD_FORCE_M  (BIT(9))
#define RTC_CNTL_TOUCH_PAD1_HOLD_FORCE_V  0x1
#define RTC_CNTL_TOUCH_PAD1_HOLD_FORCE_S  9
/* RTC_CNTL_TOUCH_PAD0_HOLD_FORCE:R/W；位位置：[8]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_TOUCH_PAD0_HOLD_FORCE  (BIT(8))
#define RTC_CNTL_TOUCH_PAD0_HOLD_FORCE_M  (BIT(8))
#define RTC_CNTL_TOUCH_PAD0_HOLD_FORCE_V  0x1
#define RTC_CNTL_TOUCH_PAD0_HOLD_FORCE_S  8
/* RTC_CNTL_SENSE4_HOLD_FORCE:R/W；位位置：[7]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_SENSE4_HOLD_FORCE  (BIT(7))
#define RTC_CNTL_SENSE4_HOLD_FORCE_M  (BIT(7))
#define RTC_CNTL_SENSE4_HOLD_FORCE_V  0x1
#define RTC_CNTL_SENSE4_HOLD_FORCE_S  7
/* RTC_CNTL_SENSE3_HOLD_FORCE:R/W；位位置：[6]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_SENSE3_HOLD_FORCE  (BIT(6))
#define RTC_CNTL_SENSE3_HOLD_FORCE_M  (BIT(6))
#define RTC_CNTL_SENSE3_HOLD_FORCE_V  0x1
#define RTC_CNTL_SENSE3_HOLD_FORCE_S  6
/* RTC_CNTL_SENSE2_HOLD_FORCE:R/W；位位置：[5]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_SENSE2_HOLD_FORCE  (BIT(5))
#define RTC_CNTL_SENSE2_HOLD_FORCE_M  (BIT(5))
#define RTC_CNTL_SENSE2_HOLD_FORCE_V  0x1
#define RTC_CNTL_SENSE2_HOLD_FORCE_S  5
/* RTC_CNTL_SENSE1_HOLD_FORCE:R/W；位位置：[4]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_SENSE1_HOLD_FORCE  (BIT(4))
#define RTC_CNTL_SENSE1_HOLD_FORCE_M  (BIT(4))
#define RTC_CNTL_SENSE1_HOLD_FORCE_V  0x1
#define RTC_CNTL_SENSE1_HOLD_FORCE_S  4
/* RTC_CNTL_PDAC2_HOLD_FORCE:R/W；位位置：[3]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_PDAC2_HOLD_FORCE  (BIT(3))
#define RTC_CNTL_PDAC2_HOLD_FORCE_M  (BIT(3))
#define RTC_CNTL_PDAC2_HOLD_FORCE_V  0x1
#define RTC_CNTL_PDAC2_HOLD_FORCE_S  3
/* RTC_CNTL_PDAC1_HOLD_FORCE:R/W；位位置：[2]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_PDAC1_HOLD_FORCE  (BIT(2))
#define RTC_CNTL_PDAC1_HOLD_FORCE_M  (BIT(2))
#define RTC_CNTL_PDAC1_HOLD_FORCE_V  0x1
#define RTC_CNTL_PDAC1_HOLD_FORCE_S  2
/* RTC_CNTL_ADC2_HOLD_FORCE:R/W；位位置：[1]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_ADC2_HOLD_FORCE  (BIT(1))
#define RTC_CNTL_ADC2_HOLD_FORCE_M  (BIT(1))
#define RTC_CNTL_ADC2_HOLD_FORCE_V  0x1
#define RTC_CNTL_ADC2_HOLD_FORCE_S  1
/* RTC_CNTL_ADC1_HOLD_FORCE:R/W；位位置：[0]；默认值：1’b0；*/
/*说明：*/
#define RTC_CNTL_ADC1_HOLD_FORCE  (BIT(0))
#define RTC_CNTL_ADC1_HOLD_FORCE_M  (BIT(0))
#define RTC_CNTL_ADC1_HOLD_FORCE_V  0x1
#define RTC_CNTL_ADC1_HOLD_FORCE_S  0

#define RTC_CNTL_EXT_WAKEUP1_REG          (DR_REG_RTCCNTL_BASE + 0xcc)
/* RTC_CNTL_EXT_WAKEUP1_STATUS_CLR:WO；位位置：[18]；默认值：1'd0；*/
/*描述：清除ext唤醒1状态*/
#define RTC_CNTL_EXT_WAKEUP1_STATUS_CLR  (BIT(18))
#define RTC_CNTL_EXT_WAKEUP1_STATUS_CLR_M  (BIT(18))
#define RTC_CNTL_EXT_WAKEUP1_STATUS_CLR_V  0x1
#define RTC_CNTL_EXT_WAKEUP1_STATUS_CLR_S  18
/* RTC_CNTL_EXT_WAKEUP1_SEL：R/W；比特位置：[17:00]；默认值：18'd0；*/
/*description:为ext唤醒选择RTC焊盘的位图1*/
#define RTC_CNTL_EXT_WAKEUP1_SEL  0x0003FFFF
#define RTC_CNTL_EXT_WAKEUP1_SEL_M  ((RTC_CNTL_EXT_WAKEUP1_SEL_V)<<(RTC_CNTL_EXT_WAKEUP1_SEL_S))
#define RTC_CNTL_EXT_WAKEUP1_SEL_V  0x3FFFF
#define RTC_CNTL_EXT_WAKEUP1_SEL_S  0

#define RTC_CNTL_EXT_WAKEUP1_STATUS_REG          (DR_REG_RTCCNTL_BASE + 0xd0)
/* RTC_CNTL_EXT_WAKEUP1_STATUS：RO；比特位置：[17:00]；默认值：18'd0；*/
/*描述：ext唤醒1状态*/
#define RTC_CNTL_EXT_WAKEUP1_STATUS  0x0003FFFF
#define RTC_CNTL_EXT_WAKEUP1_STATUS_M  ((RTC_CNTL_EXT_WAKEUP1_STATUS_V)<<(RTC_CNTL_EXT_WAKEUP1_STATUS_S))
#define RTC_CNTL_EXT_WAKEUP1_STATUS_V  0x3FFFF
#define RTC_CNTL_EXT_WAKEUP1_STATUS_S  0

#define RTC_CNTL_BROWN_OUT_REG          (DR_REG_RTCCNTL_BASE + 0xd4)
/* RTC_CNTL_BROWN_OUT_DET:RO；位位置：[31]；默认值：1’b0；*/
/*描述：棕色检测*/
#define RTC_CNTL_BROWN_OUT_DET  (BIT(31))
#define RTC_CNTL_BROWN_OUT_DET_M  (BIT(31))
#define RTC_CNTL_BROWN_OUT_DET_V  0x1
#define RTC_CNTL_BROWN_OUT_DET_S  31
/* RTC_CNTL_BROWN_OUT_ENA:R/W；位位置：[30]；默认值：1’b0；*/
/*description:启用褐化*/
#define RTC_CNTL_BROWN_OUT_ENA  (BIT(30))
#define RTC_CNTL_BROWN_OUT_ENA_M  (BIT(30))
#define RTC_CNTL_BROWN_OUT_ENA_V  0x1
#define RTC_CNTL_BROWN_OUT_ENA_S  30
/* RTC_CNTL_DBROWN_OUT_THRES:R/W；位位置：[29:27]；默认值：3'b010；*/
/*描述：褐化阈值*/
#define RTC_CNTL_DBROWN_OUT_THRES  0x00000007
#define RTC_CNTL_DBROWN_OUT_THRES_M  ((RTC_CNTL_DBROWN_OUT_THRES_V)<<(RTC_CNTL_DBROWN_OUT_THRES_S))
#define RTC_CNTL_DBROWN_OUT_THRES_V  0x7
#define RTC_CNTL_DBROWN_OUT_THRES_S  27
/* RTC_CNTL_BROWN_OUT_RST_ENA:R/W；位位置：[26]；默认值：1’b0；*/
/*description:启用褐化重置*/
#define RTC_CNTL_BROWN_OUT_RST_ENA  (BIT(26))
#define RTC_CNTL_BROWN_OUT_RST_ENA_M  (BIT(26))
#define RTC_CNTL_BROWN_OUT_RST_ENA_V  0x1
#define RTC_CNTL_BROWN_OUT_RST_ENA_S  26
/* RTC_CNTL_BROWN_OUT_RST_WAIT:R/W；比特位置：[25:16]；默认值：10'h3ff；*/
/*描述：棕色重置等待周期*/
#define RTC_CNTL_BROWN_OUT_RST_WAIT  0x000003FF
#define RTC_CNTL_BROWN_OUT_RST_WAIT_M  ((RTC_CNTL_BROWN_OUT_RST_WAIT_V)<<(RTC_CNTL_BROWN_OUT_RST_WAIT_S))
#define RTC_CNTL_BROWN_OUT_RST_WAIT_V  0x3FF
#define RTC_CNTL_BROWN_OUT_RST_WAIT_S  16
/* RTC_CNTL_BROWN_OUT_PD_RF_ENA:R/W；位位置：[15]；默认值：1’b0；*/
/*描述：发生断电时启用断电RF*/
#define RTC_CNTL_BROWN_OUT_PD_RF_ENA  (BIT(15))
#define RTC_CNTL_BROWN_OUT_PD_RF_ENA_M  (BIT(15))
#define RTC_CNTL_BROWN_OUT_PD_RF_ENA_V  0x1
#define RTC_CNTL_BROWN_OUT_PD_RF_ENA_S  15
/* RTC_CNTL_BROWN_OUT_CLOSE_FLASH_ENA:R/W；位位置：[14]；默认值：1’b0；*/
/*描述：在发生断电时启用关闭闪光灯*/
#define RTC_CNTL_BROWN_OUT_CLOSE_FLASH_ENA  (BIT(14))
#define RTC_CNTL_BROWN_OUT_CLOSE_FLASH_ENA_M  (BIT(14))
#define RTC_CNTL_BROWN_OUT_CLOSE_FLASH_ENA_V  0x1
#define RTC_CNTL_BROWN_OUT_CLOSE_FLASH_ENA_S  14

#define RTC_MEM_CONF            (DR_REG_RTCCNTL_BASE + 0x40 * 4)
#define RTC_MEM_CRC_FINISH      (BIT(31))
#define RTC_MEM_CRC_FINISH_M    (BIT(31))
#define RTC_MEM_CRC_FINISH_V    0x1
#define RTC_MEM_CRC_FINISH_S    31
#define RTC_MEM_CRC_LEN         (0x7ff)
#define RTC_MEM_CRC_LEN_M       ((RTC_MEM_CRC_LEN_V)<<(RTC_MEM_CRC_LEN_S))
#define RTC_MEM_CRC_LEN_V       0x7ff
#define RTC_MEM_CRC_LEN_S       20
#define RTC_MEM_CRC_ADDR        0x7ff
#define RTC_MEM_CRC_ADDR_M      ((RTC_MEM_CRC_ADDR_V)<<(RTC_MEM_CRC_ADDR_S))
#define RTC_MEM_CRC_ADDR_V      0x7ff
#define RTC_MEM_CRC_ADDR_S      9
#define RTC_MEM_CRC_START       (BIT(8))
#define RTC_MEM_CRC_START_M     (BIT(8))
#define RTC_MEM_CRC_START_V     0x1
#define RTC_MEM_CRC_START_S     8
#define RTC_MEM_PID_CONF        0xff
#define RTC_MEM_PID_CONF_M      0xff
#define RTC_MEM_PID_CONF_V      0xff
#define RTC_MEM_PID_CONF_S      0

#define RTC_MEM_CRC_RES         (DR_REG_RTCCNTL_BASE + 0x41 * 4)

#define RTC_CNTL_DATE_REG          (DR_REG_RTCCNTL_BASE + 0x13c)
/* RTC_CNTL_CNTL_DATE:R/W；位位置：[27:0]；默认值：28'h1604280；*/
/*说明：*/
#define RTC_CNTL_CNTL_DATE  0x0FFFFFFF
#define RTC_CNTL_CNTL_DATE_M  ((RTC_CNTL_CNTL_DATE_V)<<(RTC_CNTL_CNTL_DATE_S))
#define RTC_CNTL_CNTL_DATE_V  0xFFFFFFF
#define RTC_CNTL_CNTL_DATE_S  0
#define RTC_CNTL_RTC_CNTL_DATE_VERSION 0x1604280




#endif /*_SOC_RTC_CNTL_REG_H_ */

