// 版权所有2017-2021 Espressif Systems（Shanghai）PTE LTD
//
// 根据Apache许可证2.0版（“许可证”）获得许可；
// 除非符合许可证，否则不得使用此文件。
// 您可以在以下地址获取许可证副本：
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// 除非适用法律要求或书面同意，软件
// 根据许可证分发的内容是按“原样”分发的，
// 无任何明示或暗示的保证或条件。
// 有关管理权限和
// 许可证下的限制。
#ifndef _SOC_INTERRUPT_CORE1_REG_H_
#define _SOC_INTERRUPT_CORE1_REG_H_


#include "soc.h"
#ifdef __cplusplus
extern "C" {
#endif

#define DR_REG_INTERRUPT_CORE1_BASE                 DR_REG_INTERRUPT_BASE

#define INTERRUPT_CORE1_MAC_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x800)
/* 中断CORE1_MAC_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_MAC_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_MAC_INTR_MAP_M  ((INTERRUPT_CORE1_MAC_INTR_MAP_V)<<(INTERRUPT_CORE1_MAC_INTR_MAP_S))
#define INTERRUPT_CORE1_MAC_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_MAC_INTR_MAP_S  0

#define INTERRUPT_CORE1_MAC_NMI_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x804)
/* 中断CORE1_MAC_NMI_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_MAC_NMI_MAP  0x0000001F
#define INTERRUPT_CORE1_MAC_NMI_MAP_M  ((INTERRUPT_CORE1_MAC_NMI_MAP_V)<<(INTERRUPT_CORE1_MAC_NMI_MAP_S))
#define INTERRUPT_CORE1_MAC_NMI_MAP_V  0x1F
#define INTERRUPT_CORE1_MAC_NMI_MAP_S  0

#define INTERRUPT_CORE1_PWR_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x808)
/* 中断CORE1_PWR_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_PWR_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_PWR_INTR_MAP_M  ((INTERRUPT_CORE1_PWR_INTR_MAP_V)<<(INTERRUPT_CORE1_PWR_INTR_MAP_S))
#define INTERRUPT_CORE1_PWR_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_PWR_INTR_MAP_S  0

#define INTERRUPT_CORE1_BB_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x80C)
/* 中断CORE1_BB_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_BB_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_BB_INT_MAP_M  ((INTERRUPT_CORE1_BB_INT_MAP_V)<<(INTERRUPT_CORE1_BB_INT_MAP_S))
#define INTERRUPT_CORE1_BB_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_BB_INT_MAP_S  0

#define INTERRUPT_CORE1_BT_MAC_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x810)
/* 中断CORE1_BT_MAC_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_BT_MAC_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_BT_MAC_INT_MAP_M  ((INTERRUPT_CORE1_BT_MAC_INT_MAP_V)<<(INTERRUPT_CORE1_BT_MAC_INT_MAP_S))
#define INTERRUPT_CORE1_BT_MAC_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_BT_MAC_INT_MAP_S  0

#define INTERRUPT_CORE1_BT_BB_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x814)
/* 中断CORE1_BT_BB_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_BT_BB_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_BT_BB_INT_MAP_M  ((INTERRUPT_CORE1_BT_BB_INT_MAP_V)<<(INTERRUPT_CORE1_BT_BB_INT_MAP_S))
#define INTERRUPT_CORE1_BT_BB_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_BT_BB_INT_MAP_S  0

#define INTERRUPT_CORE1_BT_BB_NMI_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x818)
/* 中断CORE1_BT_BB_NMI_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_BT_BB_NMI_MAP  0x0000001F
#define INTERRUPT_CORE1_BT_BB_NMI_MAP_M  ((INTERRUPT_CORE1_BT_BB_NMI_MAP_V)<<(INTERRUPT_CORE1_BT_BB_NMI_MAP_S))
#define INTERRUPT_CORE1_BT_BB_NMI_MAP_V  0x1F
#define INTERRUPT_CORE1_BT_BB_NMI_MAP_S  0

#define INTERRUPT_CORE1_RWBT_IRQ_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x81C)
/* 中断CORE1_RWBT_IRQ_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_RWBT_IRQ_MAP  0x0000001F
#define INTERRUPT_CORE1_RWBT_IRQ_MAP_M  ((INTERRUPT_CORE1_RWBT_IRQ_MAP_V)<<(INTERRUPT_CORE1_RWBT_IRQ_MAP_S))
#define INTERRUPT_CORE1_RWBT_IRQ_MAP_V  0x1F
#define INTERRUPT_CORE1_RWBT_IRQ_MAP_S  0

#define INTERRUPT_CORE1_RWBLE_IRQ_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x820)
/* 中断CORE1_RWBLE_IRQ_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_RWBLE_IRQ_MAP  0x0000001F
#define INTERRUPT_CORE1_RWBLE_IRQ_MAP_M  ((INTERRUPT_CORE1_RWBLE_IRQ_MAP_V)<<(INTERRUPT_CORE1_RWBLE_IRQ_MAP_S))
#define INTERRUPT_CORE1_RWBLE_IRQ_MAP_V  0x1F
#define INTERRUPT_CORE1_RWBLE_IRQ_MAP_S  0

#define INTERRUPT_CORE1_RWBT_NMI_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x824)
/* 中断CORE1_RWBT_NMI_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_RWBT_NMI_MAP  0x0000001F
#define INTERRUPT_CORE1_RWBT_NMI_MAP_M  ((INTERRUPT_CORE1_RWBT_NMI_MAP_V)<<(INTERRUPT_CORE1_RWBT_NMI_MAP_S))
#define INTERRUPT_CORE1_RWBT_NMI_MAP_V  0x1F
#define INTERRUPT_CORE1_RWBT_NMI_MAP_S  0

#define INTERRUPT_CORE1_RWBLE_NMI_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x828)
/* 中断CORE1_RWBLE_NMI_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_RWBLE_NMI_MAP  0x0000001F
#define INTERRUPT_CORE1_RWBLE_NMI_MAP_M  ((INTERRUPT_CORE1_RWBLE_NMI_MAP_V)<<(INTERRUPT_CORE1_RWBLE_NMI_MAP_S))
#define INTERRUPT_CORE1_RWBLE_NMI_MAP_V  0x1F
#define INTERRUPT_CORE1_RWBLE_NMI_MAP_S  0

#define INTERRUPT_CORE1_I2C_MST_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x82C)
/* 中断CORE1_I2C_MST_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_I2C_MST_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_I2C_MST_INT_MAP_M  ((INTERRUPT_CORE1_I2C_MST_INT_MAP_V)<<(INTERRUPT_CORE1_I2C_MST_INT_MAP_S))
#define INTERRUPT_CORE1_I2C_MST_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_I2C_MST_INT_MAP_S  0

#define INTERRUPT_CORE1_SLC0_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x830)
/* 中断CORE1_SLC0_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SLC0_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_SLC0_INTR_MAP_M  ((INTERRUPT_CORE1_SLC0_INTR_MAP_V)<<(INTERRUPT_CORE1_SLC0_INTR_MAP_S))
#define INTERRUPT_CORE1_SLC0_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_SLC0_INTR_MAP_S  0

#define INTERRUPT_CORE1_SLC1_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x834)
/* 中断CORE1_SLC1_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SLC1_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_SLC1_INTR_MAP_M  ((INTERRUPT_CORE1_SLC1_INTR_MAP_V)<<(INTERRUPT_CORE1_SLC1_INTR_MAP_S))
#define INTERRUPT_CORE1_SLC1_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_SLC1_INTR_MAP_S  0

#define INTERRUPT_CORE1_UHCI0_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x838)
/* 中断CORE1_UHCI0_INTR-MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_UHCI0_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_UHCI0_INTR_MAP_M  ((INTERRUPT_CORE1_UHCI0_INTR_MAP_V)<<(INTERRUPT_CORE1_UHCI0_INTR_MAP_S))
#define INTERRUPT_CORE1_UHCI0_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_UHCI0_INTR_MAP_S  0

#define INTERRUPT_CORE1_UHCI1_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x83C)
/* 中断CORE1_UHCI1_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_UHCI1_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_UHCI1_INTR_MAP_M  ((INTERRUPT_CORE1_UHCI1_INTR_MAP_V)<<(INTERRUPT_CORE1_UHCI1_INTR_MAP_S))
#define INTERRUPT_CORE1_UHCI1_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_UHCI1_INTR_MAP_S  0

#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x840)
/* INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_MAP  0x0000001F
#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_MAP_M  ((INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_MAP_V)<<(INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_MAP_S))
#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_MAP_V  0x1F
#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_MAP_S  0

#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_NMI_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x844)
/* INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_NMI_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_NMI_MAP  0x0000001F
#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_NMI_MAP_M  ((INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_NMI_MAP_V)<<(INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_NMI_MAP_S))
#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_NMI_MAP_V  0x1F
#define INTERRUPT_CORE1_GPIO_INTERRUPT_PRO_NMI_MAP_S  0

#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x848)
/* INTERRUPT_CORE1_GPIO_INTERRUPT_APP_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_MAP  0x0000001F
#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_MAP_M  ((INTERRUPT_CORE1_GPIO_INTERRUPT_APP_MAP_V)<<(INTERRUPT_CORE1_GPIO_INTERRUPT_APP_MAP_S))
#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_MAP_V  0x1F
#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_MAP_S  0

#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_NMI_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x84C)
/* INTERRUPT_CORE1_GPIO_INTERRUPT_APP_NMI_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_NMI_MAP  0x0000001F
#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_NMI_MAP_M  ((INTERRUPT_CORE1_GPIO_INTERRUPT_APP_NMI_MAP_V)<<(INTERRUPT_CORE1_GPIO_INTERRUPT_APP_NMI_MAP_S))
#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_NMI_MAP_V  0x1F
#define INTERRUPT_CORE1_GPIO_INTERRUPT_APP_NMI_MAP_S  0

#define INTERRUPT_CORE1_SPI_INTR_1_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x850)
/* 中断CORE1_SPI_INTR_1_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SPI_INTR_1_MAP  0x0000001F
#define INTERRUPT_CORE1_SPI_INTR_1_MAP_M  ((INTERRUPT_CORE1_SPI_INTR_1_MAP_V)<<(INTERRUPT_CORE1_SPI_INTR_1_MAP_S))
#define INTERRUPT_CORE1_SPI_INTR_1_MAP_V  0x1F
#define INTERRUPT_CORE1_SPI_INTR_1_MAP_S  0

#define INTERRUPT_CORE1_SPI_INTR_2_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x854)
/* 中断CORE1_SPI_INTR_2_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SPI_INTR_2_MAP  0x0000001F
#define INTERRUPT_CORE1_SPI_INTR_2_MAP_M  ((INTERRUPT_CORE1_SPI_INTR_2_MAP_V)<<(INTERRUPT_CORE1_SPI_INTR_2_MAP_S))
#define INTERRUPT_CORE1_SPI_INTR_2_MAP_V  0x1F
#define INTERRUPT_CORE1_SPI_INTR_2_MAP_S  0

#define INTERRUPT_CORE1_SPI_INTR_3_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x858)
/* 中断CORE1_SPI_INTR_3_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SPI_INTR_3_MAP  0x0000001F
#define INTERRUPT_CORE1_SPI_INTR_3_MAP_M  ((INTERRUPT_CORE1_SPI_INTR_3_MAP_V)<<(INTERRUPT_CORE1_SPI_INTR_3_MAP_S))
#define INTERRUPT_CORE1_SPI_INTR_3_MAP_V  0x1F
#define INTERRUPT_CORE1_SPI_INTR_3_MAP_S  0

#define INTERRUPT_CORE1_SPI_INTR_4_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x85C)
/* 中断CORE1_SPI_INTR_4_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SPI_INTR_4_MAP  0x0000001F
#define INTERRUPT_CORE1_SPI_INTR_4_MAP_M  ((INTERRUPT_CORE1_SPI_INTR_4_MAP_V)<<(INTERRUPT_CORE1_SPI_INTR_4_MAP_S))
#define INTERRUPT_CORE1_SPI_INTR_4_MAP_V  0x1F
#define INTERRUPT_CORE1_SPI_INTR_4_MAP_S  0

#define INTERRUPT_CORE1_LCD_CAM_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x860)
/* 中断CORE1_LCD_CAM_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_LCD_CAM_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_LCD_CAM_INT_MAP_M  ((INTERRUPT_CORE1_LCD_CAM_INT_MAP_V)<<(INTERRUPT_CORE1_LCD_CAM_INT_MAP_S))
#define INTERRUPT_CORE1_LCD_CAM_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_LCD_CAM_INT_MAP_S  0

#define INTERRUPT_CORE1_I2S0_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x864)
/* 中断CORE1_I2S0_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_I2S0_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_I2S0_INT_MAP_M  ((INTERRUPT_CORE1_I2S0_INT_MAP_V)<<(INTERRUPT_CORE1_I2S0_INT_MAP_S))
#define INTERRUPT_CORE1_I2S0_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_I2S0_INT_MAP_S  0

#define INTERRUPT_CORE1_I2S1_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x868)
/* 中断CORE1_I2S1_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_I2S1_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_I2S1_INT_MAP_M  ((INTERRUPT_CORE1_I2S1_INT_MAP_V)<<(INTERRUPT_CORE1_I2S1_INT_MAP_S))
#define INTERRUPT_CORE1_I2S1_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_I2S1_INT_MAP_S  0

#define INTERRUPT_CORE1_UART_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x86C)
/* 中断CORE1_UART_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_UART_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_UART_INTR_MAP_M  ((INTERRUPT_CORE1_UART_INTR_MAP_V)<<(INTERRUPT_CORE1_UART_INTR_MAP_S))
#define INTERRUPT_CORE1_UART_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_UART_INTR_MAP_S  0

#define INTERRUPT_CORE1_UART1_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x870)
/* 中断CORE1_UART1_INTR_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_UART1_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_UART1_INTR_MAP_M  ((INTERRUPT_CORE1_UART1_INTR_MAP_V)<<(INTERRUPT_CORE1_UART1_INTR_MAP_S))
#define INTERRUPT_CORE1_UART1_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_UART1_INTR_MAP_S  0

#define INTERRUPT_CORE1_UART2_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x874)
/* 中断CORE1_UART2_INTR_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_UART2_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_UART2_INTR_MAP_M  ((INTERRUPT_CORE1_UART2_INTR_MAP_V)<<(INTERRUPT_CORE1_UART2_INTR_MAP_S))
#define INTERRUPT_CORE1_UART2_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_UART2_INTR_MAP_S  0

#define INTERRUPT_CORE1_SDIO_HOST_INTERRUPT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x878)
/* INTERRUPT_CORE1_SDIO_HOST_INTERRUPT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SDIO_HOST_INTERRUPT_MAP  0x0000001F
#define INTERRUPT_CORE1_SDIO_HOST_INTERRUPT_MAP_M  ((INTERRUPT_CORE1_SDIO_HOST_INTERRUPT_MAP_V)<<(INTERRUPT_CORE1_SDIO_HOST_INTERRUPT_MAP_S))
#define INTERRUPT_CORE1_SDIO_HOST_INTERRUPT_MAP_V  0x1F
#define INTERRUPT_CORE1_SDIO_HOST_INTERRUPT_MAP_S  0

#define INTERRUPT_CORE1_PWM0_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x87C)
/* 中断CORE1_PWM0_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_PWM0_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_PWM0_INTR_MAP_M  ((INTERRUPT_CORE1_PWM0_INTR_MAP_V)<<(INTERRUPT_CORE1_PWM0_INTR_MAP_S))
#define INTERRUPT_CORE1_PWM0_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_PWM0_INTR_MAP_S  0

#define INTERRUPT_CORE1_PWM1_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x880)
/* 中断CORE1_PWM1_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_PWM1_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_PWM1_INTR_MAP_M  ((INTERRUPT_CORE1_PWM1_INTR_MAP_V)<<(INTERRUPT_CORE1_PWM1_INTR_MAP_S))
#define INTERRUPT_CORE1_PWM1_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_PWM1_INTR_MAP_S  0

#define INTERRUPT_CORE1_PWM2_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x884)
/* 中断CORE1_PWM2_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_PWM2_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_PWM2_INTR_MAP_M  ((INTERRUPT_CORE1_PWM2_INTR_MAP_V)<<(INTERRUPT_CORE1_PWM2_INTR_MAP_S))
#define INTERRUPT_CORE1_PWM2_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_PWM2_INTR_MAP_S  0

#define INTERRUPT_CORE1_PWM3_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x888)
/* 中断CORE1_PWM3_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_PWM3_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_PWM3_INTR_MAP_M  ((INTERRUPT_CORE1_PWM3_INTR_MAP_V)<<(INTERRUPT_CORE1_PWM3_INTR_MAP_S))
#define INTERRUPT_CORE1_PWM3_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_PWM3_INTR_MAP_S  0

#define INTERRUPT_CORE1_LEDC_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x88C)
/* 中断CORE1_LEDC_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_LEDC_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_LEDC_INT_MAP_M  ((INTERRUPT_CORE1_LEDC_INT_MAP_V)<<(INTERRUPT_CORE1_LEDC_INT_MAP_S))
#define INTERRUPT_CORE1_LEDC_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_LEDC_INT_MAP_S  0

#define INTERRUPT_CORE1_EFUSE_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x890)
/* 中断CORE1_EFUSE_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_EFUSE_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_EFUSE_INT_MAP_M  ((INTERRUPT_CORE1_EFUSE_INT_MAP_V)<<(INTERRUPT_CORE1_EFUSE_INT_MAP_S))
#define INTERRUPT_CORE1_EFUSE_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_EFUSE_INT_MAP_S  0

#define INTERRUPT_CORE1_CAN_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x894)
/* 中断CORE1_CAN_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CAN_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_CAN_INT_MAP_M  ((INTERRUPT_CORE1_CAN_INT_MAP_V)<<(INTERRUPT_CORE1_CAN_INT_MAP_S))
#define INTERRUPT_CORE1_CAN_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_CAN_INT_MAP_S  0

#define INTERRUPT_CORE1_USB_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x898)
/* 中断CORE1_USB_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_USB_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_USB_INTR_MAP_M  ((INTERRUPT_CORE1_USB_INTR_MAP_V)<<(INTERRUPT_CORE1_USB_INTR_MAP_S))
#define INTERRUPT_CORE1_USB_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_USB_INTR_MAP_S  0

#define INTERRUPT_CORE1_RTC_CORE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x89C)
/* 中断CORE1_RTC_CORE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_RTC_CORE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_RTC_CORE_INTR_MAP_M  ((INTERRUPT_CORE1_RTC_CORE_INTR_MAP_V)<<(INTERRUPT_CORE1_RTC_CORE_INTR_MAP_S))
#define INTERRUPT_CORE1_RTC_CORE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_RTC_CORE_INTR_MAP_S  0

#define INTERRUPT_CORE1_RMT_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8A0)
/* 中断CORE1_RMT_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_RMT_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_RMT_INTR_MAP_M  ((INTERRUPT_CORE1_RMT_INTR_MAP_V)<<(INTERRUPT_CORE1_RMT_INTR_MAP_S))
#define INTERRUPT_CORE1_RMT_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_RMT_INTR_MAP_S  0

#define INTERRUPT_CORE1_PCNT_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8A4)
/* 中断CORE1_PCNT_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_PCNT_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_PCNT_INTR_MAP_M  ((INTERRUPT_CORE1_PCNT_INTR_MAP_V)<<(INTERRUPT_CORE1_PCNT_INTR_MAP_S))
#define INTERRUPT_CORE1_PCNT_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_PCNT_INTR_MAP_S  0

#define INTERRUPT_CORE1_I2C_EXT0_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8A8)
/* 中断CORE1_I2C_EXT0_INTR-MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_I2C_EXT0_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_I2C_EXT0_INTR_MAP_M  ((INTERRUPT_CORE1_I2C_EXT0_INTR_MAP_V)<<(INTERRUPT_CORE1_I2C_EXT0_INTR_MAP_S))
#define INTERRUPT_CORE1_I2C_EXT0_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_I2C_EXT0_INTR_MAP_S  0

#define INTERRUPT_CORE1_I2C_EXT1_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8AC)
/* 中断CORE1_I2C_EXT1_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_I2C_EXT1_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_I2C_EXT1_INTR_MAP_M  ((INTERRUPT_CORE1_I2C_EXT1_INTR_MAP_V)<<(INTERRUPT_CORE1_I2C_EXT1_INTR_MAP_S))
#define INTERRUPT_CORE1_I2C_EXT1_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_I2C_EXT1_INTR_MAP_S  0

#define INTERRUPT_CORE1_SPI2_DMA_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8B0)
/* 中断CORE1_SPI2_DMA_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SPI2_DMA_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_SPI2_DMA_INT_MAP_M  ((INTERRUPT_CORE1_SPI2_DMA_INT_MAP_V)<<(INTERRUPT_CORE1_SPI2_DMA_INT_MAP_S))
#define INTERRUPT_CORE1_SPI2_DMA_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_SPI2_DMA_INT_MAP_S  0

#define INTERRUPT_CORE1_SPI3_DMA_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8B4)
/* 中断CORE1_SPI3_DMA_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SPI3_DMA_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_SPI3_DMA_INT_MAP_M  ((INTERRUPT_CORE1_SPI3_DMA_INT_MAP_V)<<(INTERRUPT_CORE1_SPI3_DMA_INT_MAP_S))
#define INTERRUPT_CORE1_SPI3_DMA_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_SPI3_DMA_INT_MAP_S  0

#define INTERRUPT_CORE1_SPI4_DMA_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8B8)
/* 中断CORE1_SPI4_DMA_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SPI4_DMA_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_SPI4_DMA_INT_MAP_M  ((INTERRUPT_CORE1_SPI4_DMA_INT_MAP_V)<<(INTERRUPT_CORE1_SPI4_DMA_INT_MAP_S))
#define INTERRUPT_CORE1_SPI4_DMA_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_SPI4_DMA_INT_MAP_S  0

#define INTERRUPT_CORE1_WDG_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8BC)
/* 中断CORE1_WDG_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_WDG_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_WDG_INT_MAP_M  ((INTERRUPT_CORE1_WDG_INT_MAP_V)<<(INTERRUPT_CORE1_WDG_INT_MAP_S))
#define INTERRUPT_CORE1_WDG_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_WDG_INT_MAP_S  0

#define INTERRUPT_CORE1_TIMER_INT1_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8C0)
/* 中断CORE1_TIMER_INT1_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_TIMER_INT1_MAP  0x0000001F
#define INTERRUPT_CORE1_TIMER_INT1_MAP_M  ((INTERRUPT_CORE1_TIMER_INT1_MAP_V)<<(INTERRUPT_CORE1_TIMER_INT1_MAP_S))
#define INTERRUPT_CORE1_TIMER_INT1_MAP_V  0x1F
#define INTERRUPT_CORE1_TIMER_INT1_MAP_S  0

#define INTERRUPT_CORE1_TIMER_INT2_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8C4)
/* 中断CORE1_TIMER_INT2_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_TIMER_INT2_MAP  0x0000001F
#define INTERRUPT_CORE1_TIMER_INT2_MAP_M  ((INTERRUPT_CORE1_TIMER_INT2_MAP_V)<<(INTERRUPT_CORE1_TIMER_INT2_MAP_S))
#define INTERRUPT_CORE1_TIMER_INT2_MAP_V  0x1F
#define INTERRUPT_CORE1_TIMER_INT2_MAP_S  0

#define INTERRUPT_CORE1_TG_T0_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8C8)
/* 中断CORE1_TG_T0_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_TG_T0_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_TG_T0_INT_MAP_M  ((INTERRUPT_CORE1_TG_T0_INT_MAP_V)<<(INTERRUPT_CORE1_TG_T0_INT_MAP_S))
#define INTERRUPT_CORE1_TG_T0_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_TG_T0_INT_MAP_S  0

#define INTERRUPT_CORE1_TG_T1_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8CC)
/* 中断CORE1_TG_T1_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_TG_T1_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_TG_T1_INT_MAP_M  ((INTERRUPT_CORE1_TG_T1_INT_MAP_V)<<(INTERRUPT_CORE1_TG_T1_INT_MAP_S))
#define INTERRUPT_CORE1_TG_T1_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_TG_T1_INT_MAP_S  0

#define INTERRUPT_CORE1_TG_WDT_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8D0)
/* 中断CORE1_TG_WDT_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_TG_WDT_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_TG_WDT_INT_MAP_M  ((INTERRUPT_CORE1_TG_WDT_INT_MAP_V)<<(INTERRUPT_CORE1_TG_WDT_INT_MAP_S))
#define INTERRUPT_CORE1_TG_WDT_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_TG_WDT_INT_MAP_S  0

#define INTERRUPT_CORE1_TG1_T0_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8D4)
/* 中断CORE1_TG1_T0_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_TG1_T0_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_TG1_T0_INT_MAP_M  ((INTERRUPT_CORE1_TG1_T0_INT_MAP_V)<<(INTERRUPT_CORE1_TG1_T0_INT_MAP_S))
#define INTERRUPT_CORE1_TG1_T0_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_TG1_T0_INT_MAP_S  0

#define INTERRUPT_CORE1_TG1_T1_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8D8)
/* 中断CORE1_TG1_T1_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_TG1_T1_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_TG1_T1_INT_MAP_M  ((INTERRUPT_CORE1_TG1_T1_INT_MAP_V)<<(INTERRUPT_CORE1_TG1_T1_INT_MAP_S))
#define INTERRUPT_CORE1_TG1_T1_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_TG1_T1_INT_MAP_S  0

#define INTERRUPT_CORE1_TG1_WDT_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8DC)
/* 中断CORE1_TG1_WDT_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_TG1_WDT_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_TG1_WDT_INT_MAP_M  ((INTERRUPT_CORE1_TG1_WDT_INT_MAP_V)<<(INTERRUPT_CORE1_TG1_WDT_INT_MAP_S))
#define INTERRUPT_CORE1_TG1_WDT_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_TG1_WDT_INT_MAP_S  0

#define INTERRUPT_CORE1_CACHE_IA_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8E0)
/* 中断CORE1_CACHE_IA_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CACHE_IA_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_CACHE_IA_INT_MAP_M  ((INTERRUPT_CORE1_CACHE_IA_INT_MAP_V)<<(INTERRUPT_CORE1_CACHE_IA_INT_MAP_S))
#define INTERRUPT_CORE1_CACHE_IA_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_CACHE_IA_INT_MAP_S  0

#define INTERRUPT_CORE1_SYSTIMER_TARGET0_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8E4)
/* 中断CORE1_SYSTIMER_TARGET0_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SYSTIMER_TARGET0_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_SYSTIMER_TARGET0_INT_MAP_M  ((INTERRUPT_CORE1_SYSTIMER_TARGET0_INT_MAP_V)<<(INTERRUPT_CORE1_SYSTIMER_TARGET0_INT_MAP_S))
#define INTERRUPT_CORE1_SYSTIMER_TARGET0_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_SYSTIMER_TARGET0_INT_MAP_S  0

#define INTERRUPT_CORE1_SYSTIMER_TARGET1_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8E8)
/* 中断CORE1_SYSTIMER_TARGET1_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SYSTIMER_TARGET1_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_SYSTIMER_TARGET1_INT_MAP_M  ((INTERRUPT_CORE1_SYSTIMER_TARGET1_INT_MAP_V)<<(INTERRUPT_CORE1_SYSTIMER_TARGET1_INT_MAP_S))
#define INTERRUPT_CORE1_SYSTIMER_TARGET1_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_SYSTIMER_TARGET1_INT_MAP_S  0

#define INTERRUPT_CORE1_SYSTIMER_TARGET2_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8EC)
/* 中断CORE1_SYSTIMER_TARGET2_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SYSTIMER_TARGET2_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_SYSTIMER_TARGET2_INT_MAP_M  ((INTERRUPT_CORE1_SYSTIMER_TARGET2_INT_MAP_V)<<(INTERRUPT_CORE1_SYSTIMER_TARGET2_INT_MAP_S))
#define INTERRUPT_CORE1_SYSTIMER_TARGET2_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_SYSTIMER_TARGET2_INT_MAP_S  0

#define INTERRUPT_CORE1_SPI_MEM_REJECT_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8F0)
/* 中断CORE1_SPI_MEM_REJECT_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SPI_MEM_REJECT_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_SPI_MEM_REJECT_INTR_MAP_M  ((INTERRUPT_CORE1_SPI_MEM_REJECT_INTR_MAP_V)<<(INTERRUPT_CORE1_SPI_MEM_REJECT_INTR_MAP_S))
#define INTERRUPT_CORE1_SPI_MEM_REJECT_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_SPI_MEM_REJECT_INTR_MAP_S  0

#define INTERRUPT_CORE1_DCACHE_PRELOAD_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8F4)
/* 中断CORE1_DCACHE_proad_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DCACHE_PRELOAD_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DCACHE_PRELOAD_INT_MAP_M  ((INTERRUPT_CORE1_DCACHE_PRELOAD_INT_MAP_V)<<(INTERRUPT_CORE1_DCACHE_PRELOAD_INT_MAP_S))
#define INTERRUPT_CORE1_DCACHE_PRELOAD_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DCACHE_PRELOAD_INT_MAP_S  0

#define INTERRUPT_CORE1_ICACHE_PRELOAD_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8F8)
/* 中断CORE1_ICACHE_proad_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_ICACHE_PRELOAD_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_ICACHE_PRELOAD_INT_MAP_M  ((INTERRUPT_CORE1_ICACHE_PRELOAD_INT_MAP_V)<<(INTERRUPT_CORE1_ICACHE_PRELOAD_INT_MAP_S))
#define INTERRUPT_CORE1_ICACHE_PRELOAD_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_ICACHE_PRELOAD_INT_MAP_S  0

#define INTERRUPT_CORE1_DCACHE_SYNC_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x8FC)
/* 中断CORE1_DCACHE_SYNC_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DCACHE_SYNC_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DCACHE_SYNC_INT_MAP_M  ((INTERRUPT_CORE1_DCACHE_SYNC_INT_MAP_V)<<(INTERRUPT_CORE1_DCACHE_SYNC_INT_MAP_S))
#define INTERRUPT_CORE1_DCACHE_SYNC_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DCACHE_SYNC_INT_MAP_S  0

#define INTERRUPT_CORE1_ICACHE_SYNC_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x900)
/* 中断CORE1_ICACHE_SYNC_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_ICACHE_SYNC_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_ICACHE_SYNC_INT_MAP_M  ((INTERRUPT_CORE1_ICACHE_SYNC_INT_MAP_V)<<(INTERRUPT_CORE1_ICACHE_SYNC_INT_MAP_S))
#define INTERRUPT_CORE1_ICACHE_SYNC_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_ICACHE_SYNC_INT_MAP_S  0

#define INTERRUPT_CORE1_APB_ADC_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x904)
/* 中断CORE1_APB_ADC_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_APB_ADC_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_APB_ADC_INT_MAP_M  ((INTERRUPT_CORE1_APB_ADC_INT_MAP_V)<<(INTERRUPT_CORE1_APB_ADC_INT_MAP_S))
#define INTERRUPT_CORE1_APB_ADC_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_APB_ADC_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_IN_CH0_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x908)
/* 中断CORE1_DMA_IN_CH0_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_IN_CH0_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_IN_CH0_INT_MAP_M  ((INTERRUPT_CORE1_DMA_IN_CH0_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_IN_CH0_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_IN_CH0_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_IN_CH0_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_IN_CH1_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x90C)
/* 中断CORE1_DMA_IN_CH1_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_IN_CH1_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_IN_CH1_INT_MAP_M  ((INTERRUPT_CORE1_DMA_IN_CH1_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_IN_CH1_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_IN_CH1_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_IN_CH1_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_IN_CH2_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x910)
/* 中断CORE1_DMA_IN_CH2_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_IN_CH2_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_IN_CH2_INT_MAP_M  ((INTERRUPT_CORE1_DMA_IN_CH2_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_IN_CH2_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_IN_CH2_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_IN_CH2_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_IN_CH3_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x914)
/* 中断CORE1_DMA_IN_CH3_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_IN_CH3_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_IN_CH3_INT_MAP_M  ((INTERRUPT_CORE1_DMA_IN_CH3_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_IN_CH3_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_IN_CH3_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_IN_CH3_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_IN_CH4_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x918)
/* 中断CORE1_DMA_IN_CH4_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_IN_CH4_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_IN_CH4_INT_MAP_M  ((INTERRUPT_CORE1_DMA_IN_CH4_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_IN_CH4_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_IN_CH4_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_IN_CH4_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_OUT_CH0_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x91C)
/* 中断CORE1_DMA_OUT_CH0_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_OUT_CH0_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_OUT_CH0_INT_MAP_M  ((INTERRUPT_CORE1_DMA_OUT_CH0_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_OUT_CH0_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_OUT_CH0_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_OUT_CH0_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_OUT_CH1_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x920)
/* 中断CORE1_DMA_OUT_CH1_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_OUT_CH1_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_OUT_CH1_INT_MAP_M  ((INTERRUPT_CORE1_DMA_OUT_CH1_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_OUT_CH1_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_OUT_CH1_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_OUT_CH1_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_OUT_CH2_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x924)
/* 中断CORE1_DMA_OUT_CH2_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_OUT_CH2_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_OUT_CH2_INT_MAP_M  ((INTERRUPT_CORE1_DMA_OUT_CH2_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_OUT_CH2_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_OUT_CH2_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_OUT_CH2_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_OUT_CH3_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x928)
/* 中断CORE1_DMA_OUT_CH3_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_OUT_CH3_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_OUT_CH3_INT_MAP_M  ((INTERRUPT_CORE1_DMA_OUT_CH3_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_OUT_CH3_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_OUT_CH3_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_OUT_CH3_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_OUT_CH4_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x92C)
/* 中断CORE1_DMA_OUT_CH4_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_OUT_CH4_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_OUT_CH4_INT_MAP_M  ((INTERRUPT_CORE1_DMA_OUT_CH4_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_OUT_CH4_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_OUT_CH4_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_OUT_CH4_INT_MAP_S  0

#define INTERRUPT_CORE1_RSA_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x930)
/* INTERRUPT_CORE1_RSA_t_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_RSA_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_RSA_INT_MAP_M  ((INTERRUPT_CORE1_RSA_INT_MAP_V)<<(INTERRUPT_CORE1_RSA_INT_MAP_S))
#define INTERRUPT_CORE1_RSA_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_RSA_INT_MAP_S  0

#define INTERRUPT_CORE1_AES_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x934)
/* 中断CORE1_AES_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_AES_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_AES_INT_MAP_M  ((INTERRUPT_CORE1_AES_INT_MAP_V)<<(INTERRUPT_CORE1_AES_INT_MAP_S))
#define INTERRUPT_CORE1_AES_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_AES_INT_MAP_S  0

#define INTERRUPT_CORE1_SHA_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x938)
/* 中断CORE1_SHA_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_SHA_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_SHA_INT_MAP_M  ((INTERRUPT_CORE1_SHA_INT_MAP_V)<<(INTERRUPT_CORE1_SHA_INT_MAP_S))
#define INTERRUPT_CORE1_SHA_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_SHA_INT_MAP_S  0

#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_0_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x93C)
/* 中断CORE1_CPU_INTR_FROM_CPU_0_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_0_MAP  0x0000001F
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_0_MAP_M  ((INTERRUPT_CORE1_CPU_INTR_FROM_CPU_0_MAP_V)<<(INTERRUPT_CORE1_CPU_INTR_FROM_CPU_0_MAP_S))
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_0_MAP_V  0x1F
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_0_MAP_S  0

#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_1_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x940)
/* 中断CORE1_CPU_INTR_FROM_CPU_1_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_1_MAP  0x0000001F
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_1_MAP_M  ((INTERRUPT_CORE1_CPU_INTR_FROM_CPU_1_MAP_V)<<(INTERRUPT_CORE1_CPU_INTR_FROM_CPU_1_MAP_S))
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_1_MAP_V  0x1F
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_1_MAP_S  0

#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_2_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x944)
/* 中断CORE1_CPU_INTR_FROM_CPU_2_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_2_MAP  0x0000001F
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_2_MAP_M  ((INTERRUPT_CORE1_CPU_INTR_FROM_CPU_2_MAP_V)<<(INTERRUPT_CORE1_CPU_INTR_FROM_CPU_2_MAP_S))
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_2_MAP_V  0x1F
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_2_MAP_S  0

#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_3_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x948)
/* 中断CORE1_CPU_INTR_FROM_CPU_3_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_3_MAP  0x0000001F
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_3_MAP_M  ((INTERRUPT_CORE1_CPU_INTR_FROM_CPU_3_MAP_V)<<(INTERRUPT_CORE1_CPU_INTR_FROM_CPU_3_MAP_S))
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_3_MAP_V  0x1F
#define INTERRUPT_CORE1_CPU_INTR_FROM_CPU_3_MAP_S  0

#define INTERRUPT_CORE1_ASSIST_DEBUG_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x94C)
/* 中断CORE1_ASSIST_DEBUG_INTR_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_ASSIST_DEBUG_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_ASSIST_DEBUG_INTR_MAP_M  ((INTERRUPT_CORE1_ASSIST_DEBUG_INTR_MAP_V)<<(INTERRUPT_CORE1_ASSIST_DEBUG_INTR_MAP_S))
#define INTERRUPT_CORE1_ASSIST_DEBUG_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_ASSIST_DEBUG_INTR_MAP_S  0

#define INTERRUPT_CORE1_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x950)
/* 中断CORE1_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP_M  ((INTERRUPT_CORE1_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP_V)<<(INTERRUPT_CORE1_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP_S))
#define INTERRUPT_CORE1_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP_S  0

#define INTERRUPT_CORE1_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x954)
/* 中断CORE1_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_M  ((INTERRUPT_CORE1_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_V)<<(INTERRUPT_CORE1_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_S))
#define INTERRUPT_CORE1_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_S  0

#define INTERRUPT_CORE1_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x958)
/* 中断CORE1_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_M  ((INTERRUPT_CORE1_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_V)<<(INTERRUPT_CORE1_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_S))
#define INTERRUPT_CORE1_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_S  0

#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x95C)
/* 中断CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_M  ((INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_V)<<(INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_S))
#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_S  0

#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x960)
/* 中断CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_M  ((INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_V)<<(INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_S))
#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_S  0

#define INTERRUPT_CORE1_CORE_1_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x964)
/* 中断CORE1_CORE_1_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CORE_1_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_CORE_1_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_M  ((INTERRUPT_CORE1_CORE_1_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_V)<<(INTERRUPT_CORE1_CORE_1_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_S))
#define INTERRUPT_CORE1_CORE_1_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_CORE_1_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_S  0

#define INTERRUPT_CORE1_CORE_1_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x968)
/* 中断CORE1_CORE_1_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CORE_1_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_CORE_1_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_M  ((INTERRUPT_CORE1_CORE_1_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_V)<<(INTERRUPT_CORE1_CORE_1_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_S))
#define INTERRUPT_CORE1_CORE_1_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_CORE_1_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_S  0

#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x96C)
/* 中断CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_M  ((INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_V)<<(INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_S))
#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_S  0

#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x970)
/* 中断CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_M  ((INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_V)<<(INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_S))
#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_CORE_1_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_S  0

#define INTERRUPT_CORE1_BACKUP_PMS_VIOLATE_INTR_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x974)
/* 中断CORE1_BACKUP_PMS_VIOLATE_INTR_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_BACKUP_PMS_VIOLATE_INTR_MAP  0x0000001F
#define INTERRUPT_CORE1_BACKUP_PMS_VIOLATE_INTR_MAP_M  ((INTERRUPT_CORE1_BACKUP_PMS_VIOLATE_INTR_MAP_V)<<(INTERRUPT_CORE1_BACKUP_PMS_VIOLATE_INTR_MAP_S))
#define INTERRUPT_CORE1_BACKUP_PMS_VIOLATE_INTR_MAP_V  0x1F
#define INTERRUPT_CORE1_BACKUP_PMS_VIOLATE_INTR_MAP_S  0

#define INTERRUPT_CORE1_CACHE_CORE0_ACS_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x978)
/* 中断CORE1_CACHE_CORE0_ACS_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CACHE_CORE0_ACS_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_CACHE_CORE0_ACS_INT_MAP_M  ((INTERRUPT_CORE1_CACHE_CORE0_ACS_INT_MAP_V)<<(INTERRUPT_CORE1_CACHE_CORE0_ACS_INT_MAP_S))
#define INTERRUPT_CORE1_CACHE_CORE0_ACS_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_CACHE_CORE0_ACS_INT_MAP_S  0

#define INTERRUPT_CORE1_CACHE_CORE1_ACS_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x97C)
/* 中断CORE1_CACHE_CORE1_ACS_INT_MAP:R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_CACHE_CORE1_ACS_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_CACHE_CORE1_ACS_INT_MAP_M  ((INTERRUPT_CORE1_CACHE_CORE1_ACS_INT_MAP_V)<<(INTERRUPT_CORE1_CACHE_CORE1_ACS_INT_MAP_S))
#define INTERRUPT_CORE1_CACHE_CORE1_ACS_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_CACHE_CORE1_ACS_INT_MAP_S  0

#define INTERRUPT_CORE1_USB_DEVICE_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x980)
/* 中断CORE1_USB_DEVICE_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_USB_DEVICE_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_USB_DEVICE_INT_MAP_M  ((INTERRUPT_CORE1_USB_DEVICE_INT_MAP_V)<<(INTERRUPT_CORE1_USB_DEVICE_INT_MAP_S))
#define INTERRUPT_CORE1_USB_DEVICE_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_USB_DEVICE_INT_MAP_S  0

#define INTERRUPT_CORE1_PERI_BACKUP_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x984)
/* 中断CORE1_PERI_BACKUP_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_PERI_BACKUP_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_PERI_BACKUP_INT_MAP_M  ((INTERRUPT_CORE1_PERI_BACKUP_INT_MAP_V)<<(INTERRUPT_CORE1_PERI_BACKUP_INT_MAP_S))
#define INTERRUPT_CORE1_PERI_BACKUP_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_PERI_BACKUP_INT_MAP_S  0

#define INTERRUPT_CORE1_DMA_EXTMEM_REJECT_INT_MAP_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x988)
/* 中断CORE1_DMA_EXTMEM_REJECT_INT_MAP：R/W；位位置：[4:0]；默认值：5'd16；*/
/*说明：*/
#define INTERRUPT_CORE1_DMA_EXTMEM_REJECT_INT_MAP  0x0000001F
#define INTERRUPT_CORE1_DMA_EXTMEM_REJECT_INT_MAP_M  ((INTERRUPT_CORE1_DMA_EXTMEM_REJECT_INT_MAP_V)<<(INTERRUPT_CORE1_DMA_EXTMEM_REJECT_INT_MAP_S))
#define INTERRUPT_CORE1_DMA_EXTMEM_REJECT_INT_MAP_V  0x1F
#define INTERRUPT_CORE1_DMA_EXTMEM_REJECT_INT_MAP_S  0

#define INTERRUPT_CORE1_INTR_STATUS_0_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x98C)
/* 中断CORE1_INTR_STATUS_0:RO；位位置：[31:0]；默认值：32'h0；*/
/*说明：*/
#define INTERRUPT_CORE1_INTR_STATUS_0  0xFFFFFFFF
#define INTERRUPT_CORE1_INTR_STATUS_0_M  ((INTERRUPT_CORE1_INTR_STATUS_0_V)<<(INTERRUPT_CORE1_INTR_STATUS_0_S))
#define INTERRUPT_CORE1_INTR_STATUS_0_V  0xFFFFFFFF
#define INTERRUPT_CORE1_INTR_STATUS_0_S  0

#define INTERRUPT_CORE1_INTR_STATUS_1_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x990)
/* 中断CORE1_INTR_STATUS_1:RO；位位置：[31:0]；默认值：32'h0；*/
/*说明：*/
#define INTERRUPT_CORE1_INTR_STATUS_1  0xFFFFFFFF
#define INTERRUPT_CORE1_INTR_STATUS_1_M  ((INTERRUPT_CORE1_INTR_STATUS_1_V)<<(INTERRUPT_CORE1_INTR_STATUS_1_S))
#define INTERRUPT_CORE1_INTR_STATUS_1_V  0xFFFFFFFF
#define INTERRUPT_CORE1_INTR_STATUS_1_S  0

#define INTERRUPT_CORE1_INTR_STATUS_2_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x994)
/* 中断CORE1_INTR_STATUS_2:RO；位位置：[31:0]；默认值：32'h0；*/
/*说明：*/
#define INTERRUPT_CORE1_INTR_STATUS_2  0xFFFFFFFF
#define INTERRUPT_CORE1_INTR_STATUS_2_M  ((INTERRUPT_CORE1_INTR_STATUS_2_V)<<(INTERRUPT_CORE1_INTR_STATUS_2_S))
#define INTERRUPT_CORE1_INTR_STATUS_2_V  0xFFFFFFFF
#define INTERRUPT_CORE1_INTR_STATUS_2_S  0

#define INTERRUPT_CORE1_INTR_STATUS_3_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x998)
/* 中断CORE1_INTR_STATUS_3:RO；位位置：[31:0]；默认值：32'h0；*/
/*说明：*/
#define INTERRUPT_CORE1_INTR_STATUS_3  0xFFFFFFFF
#define INTERRUPT_CORE1_INTR_STATUS_3_M  ((INTERRUPT_CORE1_INTR_STATUS_3_V)<<(INTERRUPT_CORE1_INTR_STATUS_3_S))
#define INTERRUPT_CORE1_INTR_STATUS_3_V  0xFFFFFFFF
#define INTERRUPT_CORE1_INTR_STATUS_3_S  0

#define INTERRUPT_CORE1_CLOCK_GATE_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0x99c)
/* 中断CORE1_CLK_EN:R/W；位位置：[0]；默认值：1’b1；*/
/*说明：*/
#define INTERRUPT_CORE1_CLK_EN  (BIT(0))
#define INTERRUPT_CORE1_CLK_EN_M  (BIT(0))
#define INTERRUPT_CORE1_CLK_EN_V  0x1
#define INTERRUPT_CORE1_CLK_EN_S  0

#define INTERRUPT_CORE1_INTERRUPT_DATE_REG          (DR_REG_INTERRUPT_CORE1_BASE + 0xFFC)
/* INTERRUPT_CORE1_INTERRUPT_DATE:R/W；位位置：[27:0]；默认值：28'h2012300；*/
/*说明：*/
#define INTERRUPT_CORE1_INTERRUPT_DATE  0x0FFFFFFF
#define INTERRUPT_CORE1_INTERRUPT_DATE_M  ((INTERRUPT_CORE1_INTERRUPT_DATE_V)<<(INTERRUPT_CORE1_INTERRUPT_DATE_S))
#define INTERRUPT_CORE1_INTERRUPT_DATE_V  0xFFFFFFF
#define INTERRUPT_CORE1_INTERRUPT_DATE_S  0

#ifdef __cplusplus
}
#endif



#endif /*_SOC_INTERRUPT_CORE1_REG_H_ */

