/*
 *  版权所有（c）2019，The OpenThread作者。保留所有权利。
 *
 *  在满足以下条件的情况下，允许以源代码和二进制形式重新分发和使用，无论是否进行修改：1.重新分发源代码必须保留上述版权声明、本条件列表和以下免责声明。2.二进制形式的再发行必须在随发行提供的文档和/或其他材料中复制上述版权声明、本条件列表和以下免责声明。3.未经事先书面许可，不得使用版权持有人的姓名或其贡献者的姓名为本软件衍生的产品背书或推广。
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * @file 此文件包括DNS客户端的编译时配置。
 *
 */

#ifndef CONFIG_DNS_CLIENT_H_
#define CONFIG_DNS_CLIENT_H_

#include "config/srp_client.h"

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_ENABLE
 *
 * 定义为1以启用DNS客户端支持。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_ENABLE
#define OPENTHREAD_CONFIG_DNS_CLIENT_ENABLE 0
#endif

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_NAT64_ENABLE
 *
 * 定义为1以在DNS客户端解析地址期间启用NAT64地址转换（从IPv4到IPv6）支持。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_NAT64_ENABLE
#define OPENTHREAD_CONFIG_DNS_CLIENT_NAT64_ENABLE 1
#endif

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_NAT64_ALLOWED
 *
 * 指定默认NAT64模式，即在DNS客户端地址解析过程中是否允许或不允许NAT64地址转换。此模式仅在启用“OPENTHREAD_CONFIG_DNS_CLIENT_NAME64_ENABLE”时可用。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_NAT64_ALLOWED
#define OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_NAT64_ALLOWED 1
#endif

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_SERVICE_DISCOVERY_ENABLE
 *
 * 定义为1以启用基于DNS的服务发现（DNS-SD）客户端。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_SERVICE_DISCOVERY_ENABLE
#define OPENTHREAD_CONFIG_DNS_CLIENT_SERVICE_DISCOVERY_ENABLE 1
#endif

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_SERVER_ADDRESS_AUTO_SET_ENABLE
 *
 * 设置为1，DNS客户端将在默认配置中自动设置和更新服务器IPv6地址（当用户未明确设置该地址时）。
 *
 * 此功能要求同时启用SRP客户端及其自动启动功能。然后，SRP客户端将监视线程网络数据中的DNS/SRP服务条目，以选择SRP服务器。所选SRP服务器地址也在默认配置中设置为DNS服务器地址。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_SERVER_ADDRESS_AUTO_SET_ENABLE
#define OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_SERVER_ADDRESS_AUTO_SET_ENABLE \
    (OPENTHREAD_CONFIG_SRP_CLIENT_ENABLE && OPENTHREAD_CONFIG_SRP_CLIENT_AUTO_START_API_ENABLE)
#endif

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_SERVER_IP6_ADDRESS
 *
 * 指定默认DNS服务器IPv6地址。
 *
 * 它必须是服务器IPv6地址的C字符串表示。
 *
 * 默认值设置为“2001:4860:4860:：8888”，这是Google公共DNS IPv6地址。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_SERVER_IP6_ADDRESS
#define OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_SERVER_IP6_ADDRESS "2001:4860:4860::8888"
#endif

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_SERVER_PORT
 *
 * 指定默认DNS服务器端口号。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_SERVER_PORT
#define OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_SERVER_PORT 53
#endif

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_RESPONSE_TIMEOUT
 *
 * 指定DNS客户端等待服务器响应的默认等待时间（以毫秒为单位）。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_RESPONSE_TIMEOUT
#define OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_RESPONSE_TIMEOUT 6000
#endif

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_MAX_TX_ATTEMPTS
 *
 * 指定报告失败前没有响应的DNS查询tx尝试的默认最大次数。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_MAX_TX_ATTEMPTS
#define OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_MAX_TX_ATTEMPTS 3
#endif

/**
 * @def OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_NO_RECURSION_FLAG
 *
 * 指定默认的“递归所需”标志（指示服务器是否可以递归解析查询）。
 *
 */
#ifndef OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_RECURSION_DESIRED_FLAG
#define OPENTHREAD_CONFIG_DNS_CLIENT_DEFAULT_RECURSION_DESIRED_FLAG 1
#endif

#endif // CONFIG_DNS_CLIENT_H_

