/*
 *  版权所有（c）2021，The OpenThread Authors。保留所有权利。
 *
 *  在满足以下条件的情况下，允许以源代码和二进制形式重新分发和使用，无论是否进行修改：1.重新分发源代码必须保留上述版权声明、本条件列表和以下免责声明。2.二进制形式的再发行必须在随发行提供的文档和/或其他材料中复制上述版权声明、本条件列表和以下免责声明。3.未经事先书面许可，不得使用版权持有人的姓名或其贡献者的姓名为本软件衍生的产品背书或推广。
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * @file 此文件包括历史跟踪器模块的编译时配置。
 *
 */

#ifndef CONFIG_HISTORY_TRACKER_H_
#define CONFIG_HISTORY_TRACKER_H_

/**
 * @def OPENTHREAD_CONFIG_HISTORY_TRACKER_ENABLE
 *
 * 定义为1以启用历史跟踪器模块。
 *
 */
#ifndef OPENTHREAD_CONFIG_HISTORY_TRACKER_ENABLE
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_ENABLE 0
#endif

/**
 * @def OPENTHREAD_CONFIG_HISTORY_TRACKER_NET_INFO_LIST_SIZE
 *
 * 指定网络信息（角色、模式、分区ID、RLOC16）历史列表中的最大条目数。
 *
 * 可以设置为零，以配置历史跟踪模块不收集任何条目。
 *
 */
#ifndef OPENTHREAD_CONFIG_HISTORY_TRACKER_NET_INFO_LIST_SIZE
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_NET_INFO_LIST_SIZE 32
#endif

/**
 * @def OPENTHREAD_CONFIG_HISTORY_TRACKER_UNICAST_ADDRESS_LIST_SIZE
 *
 * 指定单播IPv6地址历史列表中的最大条目数。
 *
 * 可以设置为零，以配置历史跟踪模块不收集任何条目。
 *
 */
#ifndef OPENTHREAD_CONFIG_HISTORY_TRACKER_UNICAST_ADDRESS_LIST_SIZE
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_UNICAST_ADDRESS_LIST_SIZE 20
#endif

/**
 * @def OPENTHREAD_CONFIG_HISTORY_TRACKER_MULTICAST_ADDRESS_LIST_SIZE
 *
 * 指定多播IPv6地址历史列表中的最大条目数。
 *
 * 可以设置为零，以配置历史跟踪模块不收集任何条目。
 *
 */
#ifndef OPENTHREAD_CONFIG_HISTORY_TRACKER_MULTICAST_ADDRESS_LIST_SIZE
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_MULTICAST_ADDRESS_LIST_SIZE 20
#endif

/**
 * @def OPENTHREAD_CONFIG_HISTORY_TRACKER_RX_LIST_SIZE
 *
 * 指定RX历史列表中的最大条目数。
 *
 * 可设置为零，以配置历史跟踪器模块不收集任何RX历史。
 *
 */
#ifndef OPENTHREAD_CONFIG_HISTORY_TRACKER_RX_LIST_SIZE
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_RX_LIST_SIZE 32
#endif

/**
 * @def OPENTHREAD_CONFIG_HISTORY_TRACKER_TX_LIST_SIZE
 *
 * 指定TX历史列表中的最大条目数。
 *
 * 可设置为零，以配置历史跟踪器模块不收集任何发送历史。
 *
 */
#ifndef OPENTHREAD_CONFIG_HISTORY_TRACKER_TX_LIST_SIZE
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_TX_LIST_SIZE 32
#endif

/**
 * @def OPENTHREAD_CONFIG_HISTORY_TRACKER_EXCLUDE_THREAD_CONTROL_MESSAGES
 *
 * 定义为1以从TX和RX历史中排除线程控制消息（例如，MLE、TMF）。
 *
 */
#ifndef OPENTHREAD_CONFIG_HISTORY_TRACKER_EXCLUDE_THREAD_CONTROL_MESSAGES
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_EXCLUDE_THREAD_CONTROL_MESSAGES 1
#endif

/**
 * @def OPENTHREAD_CONFIG_HISTORY_TRACKER_NEIGHBOR_LIST_SIZE
 *
 * 指定相邻表历史记录列表中的最大条目数。
 *
 * 可以设置为零，以配置历史跟踪模块不收集任何邻居表历史。
 *
 */
#ifndef OPENTHREAD_CONFIG_HISTORY_TRACKER_NEIGHBOR_LIST_SIZE
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_NEIGHBOR_LIST_SIZE 64
#endif

#endif // CONFIG_HISTORY_TRACKER_H_

