/*
 *  版权所有（c）2019，The OpenThread作者。保留所有权利。
 *
 *  在满足以下条件的情况下，允许以源代码和二进制形式重新分发和使用，无论是否进行修改：1.重新分发源代码必须保留上述版权声明、本条件列表和以下免责声明。2.二进制形式的再发行必须在随发行提供的文档和/或其他材料中复制上述版权声明、本条件列表和以下免责声明。3.未经事先书面许可，不得使用版权持有人的姓名或其贡献者的姓名为本软件衍生的产品背书或推广。
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * @file 此文件包括父搜索的编译时配置。
 *
 */

#ifndef CONFIG_PARENT_SEARCH_H_
#define CONFIG_PARENT_SEARCH_H_

/**
 * @def OPENTHREAD_CONFIG_PARENT_SEARCH_ENABLE
 *
 * 定义为1以启用定期父搜索功能。
 *
 * 启用此功能后，终端设备/子设备（同时保持连接）将定期搜索可能的更好的父设备，如果找到更好的，则切换父设备。
 *
 * 子级将定期检查当前父级的平均RSS值，只有当该值低于特定阈值时，才会执行父级搜索。“OPENTHREAD_COONFIG_PARENT_SEARC_CHECK_INTERVAL”指定检查间隔（以秒为单位），“OPENTHRAD_CONFIG_PAREND_SEARC_RSS_THRESHOLD”提供RSS阈值。
 *
 * 由于父级搜索过程可能会消耗电力（子级需要保持在RX模式以收集父级响应），并限制其对电池供电设备的影响，因此在触发父级搜索后，子级不会在“OPENTHREAD_COONFIG_parent_SEARC_backoff_interval”指定的退避间隔之前触发另一个。
 *
 */
#ifndef OPENTHREAD_CONFIG_PARENT_SEARCH_ENABLE
#define OPENTHREAD_CONFIG_PARENT_SEARCH_ENABLE 0
#endif

/**
 * @def OPENTHREAD_CONFIG_PARENT_SEARCH_CHECK_INTERVAL
 *
 * 指定子级检查触发器条件以执行父级搜索的时间间隔（秒）。
 *
 * 仅在启用定期父搜索功能时适用（请参阅`OPENTHREAD_CONFIG_parent_search_ENABLE`）。
 *
 */
#ifndef OPENTHREAD_CONFIG_PARENT_SEARCH_CHECK_INTERVAL
#define OPENTHREAD_CONFIG_PARENT_SEARCH_CHECK_INTERVAL (9 * 60)
#endif

/**
 * @def OPENTHREAD_CONFIG_PARENT_SEARCH_BACKOFF_INTERVAL
 *
 * 指定子级在触发父级搜索后不执行父级搜索的回退间隔（秒）。
 *
 * 仅在启用定期父搜索功能时适用（请参阅`OPENTHREAD_CONFIG_parent_search_ENABLE`）。
 *
 *
 */
#ifndef OPENTHREAD_CONFIG_PARENT_SEARCH_BACKOFF_INTERVAL
#define OPENTHREAD_CONFIG_PARENT_SEARCH_BACKOFF_INTERVAL (10 * 60 * 60)
#endif

/**
 * @def OPENTHREAD_CONFIG_PARENT_SEARCH_RSS_THRESHOLD
 *
 * 指定用于触发父搜索的RSS阈值。
 *
 * 仅在启用定期父搜索功能时适用（请参阅`OPENTHREAD_CONFIG_parent_search_ENABLE`）。
 *
 */
#ifndef OPENTHREAD_CONFIG_PARENT_SEARCH_RSS_THRESHOLD
#define OPENTHREAD_CONFIG_PARENT_SEARCH_RSS_THRESHOLD -65
#endif

#endif // CONFIG_PARENT_SEARCH_H_

