// 版权所有2020 Espressif Systems（上海）私人有限公司
//
// 根据Apache许可证2.0版（“许可证”）获得许可；
// 除非符合许可证，否则不得使用此文件。
// 您可以在以下地址获取许可证副本：
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// 除非适用法律要求或书面同意，软件
// 根据许可证分发的内容是按“原样”分发的，
// 无任何明示或暗示的保证或条件。
// 有关管理权限和
// 许可证下的限制。
#ifndef _SOC_EXTMEM_REG_H_
#define _SOC_EXTMEM_REG_H_


#ifdef __cplusplus
extern "C" {
#endif
#include "soc.h"
#define EXTMEM_ICACHE_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x000)
/* EXTMEM_ICACHE_ENABLE:R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于激活数据缓存。0：禁用1：启用*/
#define EXTMEM_ICACHE_ENABLE  (BIT(0))
#define EXTMEM_ICACHE_ENABLE_M  (BIT(0))
#define EXTMEM_ICACHE_ENABLE_V  0x1
#define EXTMEM_ICACHE_ENABLE_S  0

#define EXTMEM_ICACHE_CTRL1_REG          (DR_REG_EXTMEM_BASE + 0x004)
/* EXTMEM_ICACHE_SHUT_DBUS:R/W；位位置：[1]；默认值：1’b1；*/
/*description:该位用于禁用core1 ibus 0:启用1:禁用*/
#define EXTMEM_ICACHE_SHUT_DBUS  (BIT(1))
#define EXTMEM_ICACHE_SHUT_DBUS_M  (BIT(1))
#define EXTMEM_ICACHE_SHUT_DBUS_V  0x1
#define EXTMEM_ICACHE_SHUT_DBUS_S  1
/* EXTMEM_ICACHE_SHUT_IBUS:R/W；位位置：[0]；默认值：1’b1；*/
/*description:该位用于禁用core0 ibus 0：启用1：禁用*/
#define EXTMEM_ICACHE_SHUT_IBUS  (BIT(0))
#define EXTMEM_ICACHE_SHUT_IBUS_M  (BIT(0))
#define EXTMEM_ICACHE_SHUT_IBUS_V  0x1
#define EXTMEM_ICACHE_SHUT_IBUS_S  0

#define EXTMEM_ICACHE_TAG_POWER_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x008)
/* EXTMEM_ICACHE_TAG_MEM_FORCE_PU:R/W；位位置：[2]；默认值：1’b1；*/
/*description:该位用于为icache标记内存加电0:遵循rtc_lslp 1:加电*/
#define EXTMEM_ICACHE_TAG_MEM_FORCE_PU  (BIT(2))
#define EXTMEM_ICACHE_TAG_MEM_FORCE_PU_M  (BIT(2))
#define EXTMEM_ICACHE_TAG_MEM_FORCE_PU_V  0x1
#define EXTMEM_ICACHE_TAG_MEM_FORCE_PU_S  2
/* EXTMEM_ICACHE_TAG_MEM_FORCE_PD:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于关闭icache标记内存0：遵循rtc_lslp 1：关闭电源*/
#define EXTMEM_ICACHE_TAG_MEM_FORCE_PD  (BIT(1))
#define EXTMEM_ICACHE_TAG_MEM_FORCE_PD_M  (BIT(1))
#define EXTMEM_ICACHE_TAG_MEM_FORCE_PD_V  0x1
#define EXTMEM_ICACHE_TAG_MEM_FORCE_PD_S  1
/* EXTMEM_ICACHE_TAG_MEM_FORCE_ON:R/W；位位置：[0]；默认值：1’b1；*/
/*描述：该位用于关闭icache标签存储器的时钟门控。1： 关闭门控0：打开时钟门控。*/
#define EXTMEM_ICACHE_TAG_MEM_FORCE_ON  (BIT(0))
#define EXTMEM_ICACHE_TAG_MEM_FORCE_ON_M  (BIT(0))
#define EXTMEM_ICACHE_TAG_MEM_FORCE_ON_V  0x1
#define EXTMEM_ICACHE_TAG_MEM_FORCE_ON_S  0

#define EXTMEM_ICACHE_PRELOCK_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x00C)
/* EXTMEM_ICACHE_prelok_SCT1_EN:R/W；位位置：[1]；默认值：1'0；*/
/*description:该位用于启用预锁定功能的第二部分。*/
#define EXTMEM_ICACHE_PRELOCK_SCT1_EN  (BIT(1))
#define EXTMEM_ICACHE_PRELOCK_SCT1_EN_M  (BIT(1))
#define EXTMEM_ICACHE_PRELOCK_SCT1_EN_V  0x1
#define EXTMEM_ICACHE_PRELOCK_SCT1_EN_S  1
/* EXTMEM_ICACHE_prelok_SCT0_EN:R/W；位位置：[0]；默认值：1'0；*/
/*description:该位用于启用预锁定功能的第一部分。*/
#define EXTMEM_ICACHE_PRELOCK_SCT0_EN  (BIT(0))
#define EXTMEM_ICACHE_PRELOCK_SCT0_EN_M  (BIT(0))
#define EXTMEM_ICACHE_PRELOCK_SCT0_EN_V  0x1
#define EXTMEM_ICACHE_PRELOCK_SCT0_EN_S  0

#define EXTMEM_ICACHE_PRELOCK_SCT0_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x010)
/* EXTMEM_ICACHE_prelok_SCT0_ADDR:R/W；位位置：[31:0]；默认值：32'h0；*/
/*描述：这些位用于配置与ICACHE_prelock_SCT0_SIZE_REG组合的数据预锁的第一个起始虚拟地址*/
#define EXTMEM_ICACHE_PRELOCK_SCT0_ADDR  0xFFFFFFFF
#define EXTMEM_ICACHE_PRELOCK_SCT0_ADDR_M  ((EXTMEM_ICACHE_PRELOCK_SCT0_ADDR_V)<<(EXTMEM_ICACHE_PRELOCK_SCT0_ADDR_S))
#define EXTMEM_ICACHE_PRELOCK_SCT0_ADDR_V  0xFFFFFFFF
#define EXTMEM_ICACHE_PRELOCK_SCT0_ADDR_S  0

#define EXTMEM_ICACHE_PRELOCK_SCT1_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x014)
/* EXTMEM_ICACHE_prelok_SCT1_ADDR:R/W；位位置：[31:0]；默认值：32'h0；*/
/*描述：这些位用于配置与ICACHE_prelock_SCT1_SIZE_REG组合的数据预锁的第二个起始虚拟地址*/
#define EXTMEM_ICACHE_PRELOCK_SCT1_ADDR  0xFFFFFFFF
#define EXTMEM_ICACHE_PRELOCK_SCT1_ADDR_M  ((EXTMEM_ICACHE_PRELOCK_SCT1_ADDR_V)<<(EXTMEM_ICACHE_PRELOCK_SCT1_ADDR_S))
#define EXTMEM_ICACHE_PRELOCK_SCT1_ADDR_V  0xFFFFFFFF
#define EXTMEM_ICACHE_PRELOCK_SCT1_ADDR_S  0

#define EXTMEM_ICACHE_PRELOCK_SCT_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x018)
/* EXTMEM_ICACHE_prelok_scto_SIZE：R/W；比特位置：[31:16]；默认值：16'0；*/
/*描述：这些位用于配置与ICACHE_PRELOCK_SCT0_ADDR_REG组合的数据锁定的第一个长度*/
#define EXTMEM_ICACHE_PRELOCK_SCT0_SIZE  0x0000FFFF
#define EXTMEM_ICACHE_PRELOCK_SCT0_SIZE_M  ((EXTMEM_ICACHE_PRELOCK_SCT0_SIZE_V)<<(EXTMEM_ICACHE_PRELOCK_SCT0_SIZE_S))
#define EXTMEM_ICACHE_PRELOCK_SCT0_SIZE_V  0xFFFF
#define EXTMEM_ICACHE_PRELOCK_SCT0_SIZE_S  16
/* EXTMEM_ICACHE_prelok_SCT1_SIZE：R/W；比特位置：[15:0]；默认值：16'0；*/
/*描述：这些位用于配置与ICACHE_PRELOCK_SCT1_ADDR_REG组合的数据锁定的第二长度*/
#define EXTMEM_ICACHE_PRELOCK_SCT1_SIZE  0x0000FFFF
#define EXTMEM_ICACHE_PRELOCK_SCT1_SIZE_M  ((EXTMEM_ICACHE_PRELOCK_SCT1_SIZE_V)<<(EXTMEM_ICACHE_PRELOCK_SCT1_SIZE_S))
#define EXTMEM_ICACHE_PRELOCK_SCT1_SIZE_V  0xFFFF
#define EXTMEM_ICACHE_PRELOCK_SCT1_SIZE_S  0

#define EXTMEM_ICACHE_LOCK_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x01C)
/* EXTMEM_ICACHE_LOCK_DONE:RO；位位置：[2]；默认值：1’b1；*/
/*description:该位用于指示解锁/锁定操作完成。*/
#define EXTMEM_ICACHE_LOCK_DONE  (BIT(2))
#define EXTMEM_ICACHE_LOCK_DONE_M  (BIT(2))
#define EXTMEM_ICACHE_LOCK_DONE_V  0x1
#define EXTMEM_ICACHE_LOCK_DONE_S  2
/* EXTMEM_ICACHE_UNLOCK_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于启用解锁操作。解锁操作完成后，将由硬件清除。*/
#define EXTMEM_ICACHE_UNLOCK_ENA  (BIT(1))
#define EXTMEM_ICACHE_UNLOCK_ENA_M  (BIT(1))
#define EXTMEM_ICACHE_UNLOCK_ENA_V  0x1
#define EXTMEM_ICACHE_UNLOCK_ENA_S  1
/* EXTMEM_ICACHE_LOCK_ENA:R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于启用锁定操作。锁定操作完成后，将由硬件清除。*/
#define EXTMEM_ICACHE_LOCK_ENA  (BIT(0))
#define EXTMEM_ICACHE_LOCK_ENA_M  (BIT(0))
#define EXTMEM_ICACHE_LOCK_ENA_V  0x1
#define EXTMEM_ICACHE_LOCK_ENA_S  0

#define EXTMEM_ICACHE_LOCK_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x020)
/* EXTMEM_ICACHE_LOCK_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置锁操作的起始虚拟地址。它应与ICACHE_LOCK_SIZE_REG结合使用。*/
#define EXTMEM_ICACHE_LOCK_ADDR  0xFFFFFFFF
#define EXTMEM_ICACHE_LOCK_ADDR_M  ((EXTMEM_ICACHE_LOCK_ADDR_V)<<(EXTMEM_ICACHE_LOCK_ADDR_S))
#define EXTMEM_ICACHE_LOCK_ADDR_V  0xFFFFFFFF
#define EXTMEM_ICACHE_LOCK_ADDR_S  0

#define EXTMEM_ICACHE_LOCK_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x024)
/* EXTMEM_ICACHE_LOCK_SIZE:R/W；比特位置：[15:0]；默认值：16'0；*/
/*description:位用于配置锁定操作的长度。这些位是缓存块的计数。应与ICACHE_LOCK_ADDR_REG组合使用。*/
#define EXTMEM_ICACHE_LOCK_SIZE  0x0000FFFF
#define EXTMEM_ICACHE_LOCK_SIZE_M  ((EXTMEM_ICACHE_LOCK_SIZE_V)<<(EXTMEM_ICACHE_LOCK_SIZE_S))
#define EXTMEM_ICACHE_LOCK_SIZE_V  0xFFFF
#define EXTMEM_ICACHE_LOCK_SIZE_S  0

#define EXTMEM_ICACHE_SYNC_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x028)
/* EXTMEM_ICACHE_syncdone:RO；位位置：[1]；默认值：1’b0；*/
/*description:该位用于指示无效操作已完成。*/
#define EXTMEM_ICACHE_SYNC_DONE  (BIT(1))
#define EXTMEM_ICACHE_SYNC_DONE_M  (BIT(1))
#define EXTMEM_ICACHE_SYNC_DONE_V  0x1
#define EXTMEM_ICACHE_SYNC_DONE_S  1
/* EXTMEM_ICACHE_INVALIDATE_ENA:R/W；位位置：[0]；默认值：1’b1；*/
/*description:该位用于启用无效操作。无效操作完成后，将由硬件清除。*/
#define EXTMEM_ICACHE_INVALIDATE_ENA  (BIT(0))
#define EXTMEM_ICACHE_INVALIDATE_ENA_M  (BIT(0))
#define EXTMEM_ICACHE_INVALIDATE_ENA_V  0x1
#define EXTMEM_ICACHE_INVALIDATE_ENA_S  0

#define EXTMEM_ICACHE_SYNC_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x02C)
/* EXTMEM_ICACHE_SYNC_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置清理操作的起始虚拟地址。它应与ICACHE_SYNC_SIZE_REG结合使用。*/
#define EXTMEM_ICACHE_SYNC_ADDR  0xFFFFFFFF
#define EXTMEM_ICACHE_SYNC_ADDR_M  ((EXTMEM_ICACHE_SYNC_ADDR_V)<<(EXTMEM_ICACHE_SYNC_ADDR_S))
#define EXTMEM_ICACHE_SYNC_ADDR_V  0xFFFFFFFF
#define EXTMEM_ICACHE_SYNC_ADDR_S  0

#define EXTMEM_ICACHE_SYNC_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x030)
/* EXTMEM_ICACHE_SYNC_SIZE:R/W；比特位置：[22:0]；默认值：23'0；*/
/*description:这些位用于配置同步操作的长度。这些位是缓存块的计数。应与ICACHE_SYNC_ADDR_REG组合使用。*/
#define EXTMEM_ICACHE_SYNC_SIZE  0x007FFFFF
#define EXTMEM_ICACHE_SYNC_SIZE_M  ((EXTMEM_ICACHE_SYNC_SIZE_V)<<(EXTMEM_ICACHE_SYNC_SIZE_S))
#define EXTMEM_ICACHE_SYNC_SIZE_V  0x7FFFFF
#define EXTMEM_ICACHE_SYNC_SIZE_S  0

#define EXTMEM_ICACHE_PRELOAD_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x034)
/* EXTMEM_ICACHE_proad_ORDER:R/W；位位置：[2]；默认值：1’b0；*/
/*description:该位用于配置预加载操作的方向。1： 降序0：升序。*/
#define EXTMEM_ICACHE_PRELOAD_ORDER  (BIT(2))
#define EXTMEM_ICACHE_PRELOAD_ORDER_M  (BIT(2))
#define EXTMEM_ICACHE_PRELOAD_ORDER_V  0x1
#define EXTMEM_ICACHE_PRELOAD_ORDER_S  2
/* EXTMEM_ICACHE_proad_DONE:RO；位位置：[1]；默认值：1’b1；*/
/*description:该位用于指示预加载操作完成。*/
#define EXTMEM_ICACHE_PRELOAD_DONE  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_DONE_M  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_DONE_V  0x1
#define EXTMEM_ICACHE_PRELOAD_DONE_S  1
/* EXTMEM_ICACHE_proad_ENA:R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于启用预加载操作。预加载操作完成后，将由硬件清除。*/
#define EXTMEM_ICACHE_PRELOAD_ENA  (BIT(0))
#define EXTMEM_ICACHE_PRELOAD_ENA_M  (BIT(0))
#define EXTMEM_ICACHE_PRELOAD_ENA_V  0x1
#define EXTMEM_ICACHE_PRELOAD_ENA_S  0

#define EXTMEM_ICACHE_PRELOAD_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x038)
/* EXTMEM_ICACHE_proad_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置预加载操作的起始虚拟地址。它应与ICACHE_PRELOAD_SIZE_REG组合使用。*/
#define EXTMEM_ICACHE_PRELOAD_ADDR  0xFFFFFFFF
#define EXTMEM_ICACHE_PRELOAD_ADDR_M  ((EXTMEM_ICACHE_PRELOAD_ADDR_V)<<(EXTMEM_ICACHE_PRELOAD_ADDR_S))
#define EXTMEM_ICACHE_PRELOAD_ADDR_V  0xFFFFFFFF
#define EXTMEM_ICACHE_PRELOAD_ADDR_S  0

#define EXTMEM_ICACHE_PRELOAD_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x03C)
/* EXTMEM_ICACHE_proad_SIZE:R/W；比特位置：[15:0]；默认值：16'0；*/
/*description:位用于配置预加载操作的长度。这些位是缓存块的计数。它应与ICACHE_PRELOAD_ADDR_REG组合使用。。*/
#define EXTMEM_ICACHE_PRELOAD_SIZE  0x0000FFFF
#define EXTMEM_ICACHE_PRELOAD_SIZE_M  ((EXTMEM_ICACHE_PRELOAD_SIZE_V)<<(EXTMEM_ICACHE_PRELOAD_SIZE_S))
#define EXTMEM_ICACHE_PRELOAD_SIZE_V  0xFFFF
#define EXTMEM_ICACHE_PRELOAD_SIZE_S  0

#define EXTMEM_ICACHE_AUTOLOAD_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x040)
/* EXTMEM_ICACHE_AUTOLOAD_RQST:R/W；比特位置：[6:5]；默认值：2’b0；*/
/*描述：这些位用于配置自动加载的触发条件。0/3:缓存未命中1:缓存命中2:缓存未命中和命中。*/
#define EXTMEM_ICACHE_AUTOLOAD_RQST  0x00000003
#define EXTMEM_ICACHE_AUTOLOAD_RQST_M  ((EXTMEM_ICACHE_AUTOLOAD_RQST_V)<<(EXTMEM_ICACHE_AUTOLOAD_RQST_S))
#define EXTMEM_ICACHE_AUTOLOAD_RQST_V  0x3
#define EXTMEM_ICACHE_AUTOLOAD_RQST_S  5
/* EXTMEM_ICACHE_AUTOLOAD_ORDER:R/W；位位置：[4]；默认值：1’b0；*/
/*description:这些位用于配置自动加载的方向。1： 降序0：升序。*/
#define EXTMEM_ICACHE_AUTOLOAD_ORDER  (BIT(4))
#define EXTMEM_ICACHE_AUTOLOAD_ORDER_M  (BIT(4))
#define EXTMEM_ICACHE_AUTOLOAD_ORDER_V  0x1
#define EXTMEM_ICACHE_AUTOLOAD_ORDER_S  4
/* EXTMEM_ICACHE_AUTOLOAD_DONE:RO；位位置：[3]；默认值：1’b1；*/
/*description:该位用于指示自动加载操作已完成。*/
#define EXTMEM_ICACHE_AUTOLOAD_DONE  (BIT(3))
#define EXTMEM_ICACHE_AUTOLOAD_DONE_M  (BIT(3))
#define EXTMEM_ICACHE_AUTOLOAD_DONE_V  0x1
#define EXTMEM_ICACHE_AUTOLOAD_DONE_S  3
/* EXTMEM_ICACHE_AUTOLOAD_ENA:R/W；位位置：[2]；默认值：1’b0；*/
/*description:该位用于启用和禁用自动加载操作。它与icache_autoload_done结合使用。1： 启用0：禁用。*/
#define EXTMEM_ICACHE_AUTOLOAD_ENA  (BIT(2))
#define EXTMEM_ICACHE_AUTOLOAD_ENA_M  (BIT(2))
#define EXTMEM_ICACHE_AUTOLOAD_ENA_V  0x1
#define EXTMEM_ICACHE_AUTOLOAD_ENA_S  2
/* EXTMEM_ICACHE_AUTOLOAD_SCT1_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*描述：位用于启用自动加载操作的第二部分。*/
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_ENA  (BIT(1))
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_ENA_M  (BIT(1))
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_ENA_V  0x1
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_ENA_S  1
/* EXTMEM_ICACHE_AUTOLOAD_SCT0_ENA:R/W；位位置：[0]；默认值：1’b0；*/
/*描述：位用于启用自动加载操作的第一部分。*/
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_ENA  (BIT(0))
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_ENA_M  (BIT(0))
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_ENA_V  0x1
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_ENA_S  0

#define EXTMEM_ICACHE_AUTOLOAD_SCT0_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x044)
/* EXTMEM_ICACHE_AUTOLOAD_SCT0_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*description:这些位用于配置自动加载操作的第一部分的起始虚拟地址。它应该与icache_autoload_sct0_ena结合使用。*/
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_ADDR  0xFFFFFFFF
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_ADDR_M  ((EXTMEM_ICACHE_AUTOLOAD_SCT0_ADDR_V)<<(EXTMEM_ICACHE_AUTOLOAD_SCT0_ADDR_S))
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_ADDR_V  0xFFFFFFFF
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_ADDR_S  0

#define EXTMEM_ICACHE_AUTOLOAD_SCT0_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x048)
/* EXTMEM_ICACHE_AUTOLOAD_SCT0_SIZE:R/W；位位置：[26:0]；默认值：27'0；*/
/*description:这些位用于配置自动加载操作的第一部分的长度。它应该与icache_autoload_sct0_ena结合使用。*/
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_SIZE  0x07FFFFFF
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_SIZE_M  ((EXTMEM_ICACHE_AUTOLOAD_SCT0_SIZE_V)<<(EXTMEM_ICACHE_AUTOLOAD_SCT0_SIZE_S))
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_SIZE_V  0x7FFFFFF
#define EXTMEM_ICACHE_AUTOLOAD_SCT0_SIZE_S  0

#define EXTMEM_ICACHE_AUTOLOAD_SCT1_ADDR_REG          (DR_REG_EXTMEM_BASE + 0x04C)
/* EXTMEM_ICACHE_AUTOLOAD_SCT1_ADDR:R/W；位位置：[31:0]；默认值：32'b0；*/
/*描述：这些位用于配置自动加载操作的第二部分的起始虚拟地址。它应该与icache_autoload_sct1_ena结合使用。*/
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_ADDR  0xFFFFFFFF
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_ADDR_M  ((EXTMEM_ICACHE_AUTOLOAD_SCT1_ADDR_V)<<(EXTMEM_ICACHE_AUTOLOAD_SCT1_ADDR_S))
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_ADDR_V  0xFFFFFFFF
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_ADDR_S  0

#define EXTMEM_ICACHE_AUTOLOAD_SCT1_SIZE_REG          (DR_REG_EXTMEM_BASE + 0x050)
/* EXTMEM_ICACHE_AUTOLOAD_SCT1_SIZE:R/W；位位置：[26:0]；默认值：27'0；*/
/*description:这些位用于配置自动加载操作的第二部分的长度。它应该与icache_autoload_sct1_ena结合使用。*/
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_SIZE  0x07FFFFFF
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_SIZE_M  ((EXTMEM_ICACHE_AUTOLOAD_SCT1_SIZE_V)<<(EXTMEM_ICACHE_AUTOLOAD_SCT1_SIZE_S))
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_SIZE_V  0x7FFFFFF
#define EXTMEM_ICACHE_AUTOLOAD_SCT1_SIZE_S  0

#define EXTMEM_IBUS_TO_FLASH_START_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x054)
/* EXTMEM_IBUS_TO_FLASH_START_VADDR:R/W；位位置：[31:0]；默认值：32'H420000；*/
/*description:这些位用于配置访问闪存的ibus的起始虚拟地址。寄存器用于为ibus访问计数器提供约束。*/
#define EXTMEM_IBUS_TO_FLASH_START_VADDR  0xFFFFFFFF
#define EXTMEM_IBUS_TO_FLASH_START_VADDR_M  ((EXTMEM_IBUS_TO_FLASH_START_VADDR_V)<<(EXTMEM_IBUS_TO_FLASH_START_VADDR_S))
#define EXTMEM_IBUS_TO_FLASH_START_VADDR_V  0xFFFFFFFF
#define EXTMEM_IBUS_TO_FLASH_START_VADDR_S  0

#define EXTMEM_IBUS_TO_FLASH_END_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x058)
/* EXTMEM_IBUS_TO_FLASH_END_VADDR:R/W；位位置：[31:0]；默认值：32'h427FFFFF；*/
/*description:这些位用于配置访问闪存的ibus的最终虚拟地址。寄存器用于为ibus访问计数器提供约束。*/
#define EXTMEM_IBUS_TO_FLASH_END_VADDR  0xFFFFFFFF
#define EXTMEM_IBUS_TO_FLASH_END_VADDR_M  ((EXTMEM_IBUS_TO_FLASH_END_VADDR_V)<<(EXTMEM_IBUS_TO_FLASH_END_VADDR_S))
#define EXTMEM_IBUS_TO_FLASH_END_VADDR_V  0xFFFFFFFF
#define EXTMEM_IBUS_TO_FLASH_END_VADDR_S  0

#define EXTMEM_DBUS_TO_FLASH_START_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x05C)
/* EXTMEM_DBUS_TO_FLASH_START_VADDR:R/W；位位置：[31:0]；默认值：32'H3000000；*/
/*description:这些位用于配置dbus的开始虚拟地址以访问闪存。寄存器用于为dbus访问计数器提供约束。*/
#define EXTMEM_DBUS_TO_FLASH_START_VADDR  0xFFFFFFFF
#define EXTMEM_DBUS_TO_FLASH_START_VADDR_M  ((EXTMEM_DBUS_TO_FLASH_START_VADDR_V)<<(EXTMEM_DBUS_TO_FLASH_START_VADDR_S))
#define EXTMEM_DBUS_TO_FLASH_START_VADDR_V  0xFFFFFFFF
#define EXTMEM_DBUS_TO_FLASH_START_VADDR_S  0

#define EXTMEM_DBUS_TO_FLASH_END_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x060)
/* EXTMEM_DBUS_TO_FLASH_END_VADDR:R/W；位位置：[31:0]；默认值：32'h3C7FFFFF；*/
/*description:这些位用于配置dbus的最终虚拟地址以访问闪存。寄存器用于为dbus访问计数器提供约束。*/
#define EXTMEM_DBUS_TO_FLASH_END_VADDR  0xFFFFFFFF
#define EXTMEM_DBUS_TO_FLASH_END_VADDR_M  ((EXTMEM_DBUS_TO_FLASH_END_VADDR_V)<<(EXTMEM_DBUS_TO_FLASH_END_VADDR_S))
#define EXTMEM_DBUS_TO_FLASH_END_VADDR_V  0xFFFFFFFF
#define EXTMEM_DBUS_TO_FLASH_END_VADDR_S  0

#define EXTMEM_CACHE_ACS_CNT_CLR_REG          (DR_REG_EXTMEM_BASE + 0x064)
/* EXTMEM_DBUS_ACS_CNT_CLR:WOD；位位置：[1]；默认值：1’b0；*/
/*description:该位用于清除dbus计数器。*/
#define EXTMEM_DBUS_ACS_CNT_CLR  (BIT(1))
#define EXTMEM_DBUS_ACS_CNT_CLR_M  (BIT(1))
#define EXTMEM_DBUS_ACS_CNT_CLR_V  0x1
#define EXTMEM_DBUS_ACS_CNT_CLR_S  1
/* EXTMEM_IBUS_ACS_CNT_CLR:WOD；位位置：[0]；默认值：1’b0；*/
/*description:该位用于清除ibus计数器。*/
#define EXTMEM_IBUS_ACS_CNT_CLR  (BIT(0))
#define EXTMEM_IBUS_ACS_CNT_CLR_M  (BIT(0))
#define EXTMEM_IBUS_ACS_CNT_CLR_V  0x1
#define EXTMEM_IBUS_ACS_CNT_CLR_S  0

#define EXTMEM_IBUS_ACS_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x068)
/* EXTMEM_IBUS_ACS_MISS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*描述：这些位用于计算由ibus访问闪存导致的缓存未命中数。*/
#define EXTMEM_IBUS_ACS_MISS_CNT  0xFFFFFFFF
#define EXTMEM_IBUS_ACS_MISS_CNT_M  ((EXTMEM_IBUS_ACS_MISS_CNT_V)<<(EXTMEM_IBUS_ACS_MISS_CNT_S))
#define EXTMEM_IBUS_ACS_MISS_CNT_V  0xFFFFFFFF
#define EXTMEM_IBUS_ACS_MISS_CNT_S  0

#define EXTMEM_IBUS_ACS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x06C)
/* EXTMEM_IBUS_ACS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*描述：这些位用于计算通过icache访问闪存的ibus数量。*/
#define EXTMEM_IBUS_ACS_CNT  0xFFFFFFFF
#define EXTMEM_IBUS_ACS_CNT_M  ((EXTMEM_IBUS_ACS_CNT_V)<<(EXTMEM_IBUS_ACS_CNT_S))
#define EXTMEM_IBUS_ACS_CNT_V  0xFFFFFFFF
#define EXTMEM_IBUS_ACS_CNT_S  0

#define EXTMEM_DBUS_ACS_FLASH_MISS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x070)
/* EXTMEM_DBUS_ACS_FLASH_MISS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*描述：这些位用于计算dbus访问闪存导致的缓存未命中数。*/
#define EXTMEM_DBUS_ACS_FLASH_MISS_CNT  0xFFFFFFFF
#define EXTMEM_DBUS_ACS_FLASH_MISS_CNT_M  ((EXTMEM_DBUS_ACS_FLASH_MISS_CNT_V)<<(EXTMEM_DBUS_ACS_FLASH_MISS_CNT_S))
#define EXTMEM_DBUS_ACS_FLASH_MISS_CNT_V  0xFFFFFFFF
#define EXTMEM_DBUS_ACS_FLASH_MISS_CNT_S  0

#define EXTMEM_DBUS_ACS_CNT_REG          (DR_REG_EXTMEM_BASE + 0x074)
/* EXTMEM_DBUS_ACS_CNT:RO；位位置：[31:0]；默认值：32'h0；*/
/*描述：这些位用于计算通过icache访问dbus闪存的数量。*/
#define EXTMEM_DBUS_ACS_CNT  0xFFFFFFFF
#define EXTMEM_DBUS_ACS_CNT_M  ((EXTMEM_DBUS_ACS_CNT_V)<<(EXTMEM_DBUS_ACS_CNT_S))
#define EXTMEM_DBUS_ACS_CNT_V  0xFFFFFFFF
#define EXTMEM_DBUS_ACS_CNT_S  0

#define EXTMEM_CACHE_ILG_INT_ENA_REG          (DR_REG_EXTMEM_BASE + 0x078)
/* EXTMEM_DBUS_CNT_OVF_INT_ENA:R/W；位位置：[8]；默认值：1’b0；*/
/*description:该位用于通过dbus计数器溢出启用中断。*/
#define EXTMEM_DBUS_CNT_OVF_INT_ENA  (BIT(8))
#define EXTMEM_DBUS_CNT_OVF_INT_ENA_M  (BIT(8))
#define EXTMEM_DBUS_CNT_OVF_INT_ENA_V  0x1
#define EXTMEM_DBUS_CNT_OVF_INT_ENA_S  8
/* EXTMEM_IBUS_CNT_OVF_INT_ENA:R/W；位位置：[7]；默认值：1’b0；*/
/*description:该位用于通过ibus计数器溢出启用中断。*/
#define EXTMEM_IBUS_CNT_OVF_INT_ENA  (BIT(7))
#define EXTMEM_IBUS_CNT_OVF_INT_ENA_M  (BIT(7))
#define EXTMEM_IBUS_CNT_OVF_INT_ENA_V  0x1
#define EXTMEM_IBUS_CNT_OVF_INT_ENA_S  7
/* EXTMEM_MMU_ENTRY_FAULT_INT_ENA:R/W；位位置：[5]；默认值：1’b0；*/
/*description:该位用于通过mmu条目故障启用中断。*/
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA  (BIT(5))
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA_M  (BIT(5))
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA_V  0x1
#define EXTMEM_MMU_ENTRY_FAULT_INT_ENA_S  5
/* EXTMEM_ICACHE_proad_OP_FAULT_INT_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于通过预加载配置故障启用中断。*/
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_INT_ENA  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_INT_ENA_M  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_INT_ENA_V  0x1
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_INT_ENA_S  1
/* EXTMEM_ICACHE_SYNC_OP_fallt_INT_ENA:R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于启用同步配置故障中断。*/
#define EXTMEM_ICACHE_SYNC_OP_FAULT_INT_ENA  (BIT(0))
#define EXTMEM_ICACHE_SYNC_OP_FAULT_INT_ENA_M  (BIT(0))
#define EXTMEM_ICACHE_SYNC_OP_FAULT_INT_ENA_V  0x1
#define EXTMEM_ICACHE_SYNC_OP_FAULT_INT_ENA_S  0

#define EXTMEM_CACHE_ILG_INT_CLR_REG          (DR_REG_EXTMEM_BASE + 0x07C)
/* EXTMEM_DBUS_CNT_OVF_INT_CLR:WOD；位位置：[8]；默认值：1’b0；*/
/*description:该位用于清除dbus计数器溢出造成的中断。*/
#define EXTMEM_DBUS_CNT_OVF_INT_CLR  (BIT(8))
#define EXTMEM_DBUS_CNT_OVF_INT_CLR_M  (BIT(8))
#define EXTMEM_DBUS_CNT_OVF_INT_CLR_V  0x1
#define EXTMEM_DBUS_CNT_OVF_INT_CLR_S  8
/* EXTMEM_IBUS_CNT_OVF_INT_CLR:WOD；位位置：[7]；默认值：1’b0；*/
/*description:该位用于清除ibus计数器溢出造成的中断。*/
#define EXTMEM_IBUS_CNT_OVF_INT_CLR  (BIT(7))
#define EXTMEM_IBUS_CNT_OVF_INT_CLR_M  (BIT(7))
#define EXTMEM_IBUS_CNT_OVF_INT_CLR_V  0x1
#define EXTMEM_IBUS_CNT_OVF_INT_CLR_S  7
/* EXTMEM_MMU_ENTRY_FAULT_INT_CLR:WOD；位位置：[5]；默认值：1’b0；*/
/*description:该位用于清除mmu条目故障导致的中断。*/
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR  (BIT(5))
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR_M  (BIT(5))
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR_V  0x1
#define EXTMEM_MMU_ENTRY_FAULT_INT_CLR_S  5
/* EXTMEM_ICACHE_proad_OP_FAULT_INT_CLR:WOD；位位置：[1]；默认值：1’b0；*/
/*description:该位用于清除预加载配置故障导致的中断。*/
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_INT_CLR  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_INT_CLR_M  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_INT_CLR_V  0x1
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_INT_CLR_S  1
/* EXTMEM_ICACHE_SYNC_OP_fallt_INT_CLR:WOD；位位置：[0]；默认值：1’b0；*/
/*description:该位用于清除同步配置故障导致的中断。*/
#define EXTMEM_ICACHE_SYNC_OP_FAULT_INT_CLR  (BIT(0))
#define EXTMEM_ICACHE_SYNC_OP_FAULT_INT_CLR_M  (BIT(0))
#define EXTMEM_ICACHE_SYNC_OP_FAULT_INT_CLR_V  0x1
#define EXTMEM_ICACHE_SYNC_OP_FAULT_INT_CLR_S  0

#define EXTMEM_CACHE_ILG_INT_ST_REG          (DR_REG_EXTMEM_BASE + 0x080)
/* EXTMEM_DBUS_ACS_FLASH_MISS_CNT_OVF_ST:RO；位位置：[10]；默认值：1’b0；*/
/*description:该位用于指示dbus访问闪存未命中计数器溢出导致的中断。*/
#define EXTMEM_DBUS_ACS_FLASH_MISS_CNT_OVF_ST  (BIT(10))
#define EXTMEM_DBUS_ACS_FLASH_MISS_CNT_OVF_ST_M  (BIT(10))
#define EXTMEM_DBUS_ACS_FLASH_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS_ACS_FLASH_MISS_CNT_OVF_ST_S  10
/* EXTMEM_DBUS_ACS_CNT_OVF_ST:RO；位位置：[9]；默认值：1’b0；*/
/*description:该位用于指示dbus访问flash/spiram计数器溢出导致的中断。*/
#define EXTMEM_DBUS_ACS_CNT_OVF_ST  (BIT(9))
#define EXTMEM_DBUS_ACS_CNT_OVF_ST_M  (BIT(9))
#define EXTMEM_DBUS_ACS_CNT_OVF_ST_V  0x1
#define EXTMEM_DBUS_ACS_CNT_OVF_ST_S  9
/* EXTMEM_IBUS_ACS_MISS_CNT_OVF_ST:RO；位位置：[8]；默认值：1’b0；*/
/*description:该位用于指示ibus访问flash/spiram未命中计数器溢出导致的中断。*/
#define EXTMEM_IBUS_ACS_MISS_CNT_OVF_ST  (BIT(8))
#define EXTMEM_IBUS_ACS_MISS_CNT_OVF_ST_M  (BIT(8))
#define EXTMEM_IBUS_ACS_MISS_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS_ACS_MISS_CNT_OVF_ST_S  8
/* EXTMEM_IBUS_ACS_CNT_OVF_ST:RO；位位置：[7]；默认值：1’b0；*/
/*description:该位用于指示ibus访问flash/spiram计数器溢出导致的中断。*/
#define EXTMEM_IBUS_ACS_CNT_OVF_ST  (BIT(7))
#define EXTMEM_IBUS_ACS_CNT_OVF_ST_M  (BIT(7))
#define EXTMEM_IBUS_ACS_CNT_OVF_ST_V  0x1
#define EXTMEM_IBUS_ACS_CNT_OVF_ST_S  7
/* EXTMEM_MMU_ENTRY_FAULT_ST:RO；位位置：[5]；默认值：1’b0；*/
/*description:该位用于指示mmu条目故障导致的中断。*/
#define EXTMEM_MMU_ENTRY_FAULT_ST  (BIT(5))
#define EXTMEM_MMU_ENTRY_FAULT_ST_M  (BIT(5))
#define EXTMEM_MMU_ENTRY_FAULT_ST_V  0x1
#define EXTMEM_MMU_ENTRY_FAULT_ST_S  5
/* EXTMEM_ICACHE_proad_OP_FAULT_ST:RO；位位置：[1]；默认值：1’b0；*/
/*description:该位用于指示预加载配置故障导致的中断。*/
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_ST  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_ST_M  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_ST_V  0x1
#define EXTMEM_ICACHE_PRELOAD_OP_FAULT_ST_S  1
/* EXTMEM_ICACHE_SYNC_OP_fallt_ST:RO；位位置：[0]；默认值：1’b0；*/
/*description:该位用于指示同步配置故障导致的中断。*/
#define EXTMEM_ICACHE_SYNC_OP_FAULT_ST  (BIT(0))
#define EXTMEM_ICACHE_SYNC_OP_FAULT_ST_M  (BIT(0))
#define EXTMEM_ICACHE_SYNC_OP_FAULT_ST_V  0x1
#define EXTMEM_ICACHE_SYNC_OP_FAULT_ST_S  0

#define EXTMEM_CORE0_ACS_CACHE_INT_ENA_REG          (DR_REG_EXTMEM_BASE + 0x084)
/* EXTMEM_CORE0_DBUS_WR_IC_INT_ENA:R/W；位位置：[5]；默认值：1’b0；*/
/*description:该位用于启用dbus尝试写入icache的中断*/
#define EXTMEM_CORE0_DBUS_WR_IC_INT_ENA  (BIT(5))
#define EXTMEM_CORE0_DBUS_WR_IC_INT_ENA_M  (BIT(5))
#define EXTMEM_CORE0_DBUS_WR_IC_INT_ENA_V  0x1
#define EXTMEM_CORE0_DBUS_WR_IC_INT_ENA_S  5
/* EXTMEM_CORE0_DBUS_REJECT_INT_ENA:R/W；位位置：[4]；默认值：1’b0；*/
/*description:该位用于启用身份验证失败时的中断。*/
#define EXTMEM_CORE0_DBUS_REJECT_INT_ENA  (BIT(4))
#define EXTMEM_CORE0_DBUS_REJECT_INT_ENA_M  (BIT(4))
#define EXTMEM_CORE0_DBUS_REJECT_INT_ENA_V  0x1
#define EXTMEM_CORE0_DBUS_REJECT_INT_ENA_S  4
/* EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_ENA:R/W；位位置：[3]；默认值：1’b0；*/
/*描述：该位用于通过cpu访问icache启用中断，而相应的dbus被禁用，包括推测访问。*/
#define EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_ENA  (BIT(3))
#define EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_ENA_M  (BIT(3))
#define EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_ENA_V  0x1
#define EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_ENA_S  3
/* EXTMEM_CORE0.ibs_REJECT_INT_ENA:R/W；位位置：[2]；默认值：1’b0；*/
/*description:该位用于启用身份验证失败时的中断。*/
#define EXTMEM_CORE0_IBUS_REJECT_INT_ENA  (BIT(2))
#define EXTMEM_CORE0_IBUS_REJECT_INT_ENA_M  (BIT(2))
#define EXTMEM_CORE0_IBUS_REJECT_INT_ENA_V  0x1
#define EXTMEM_CORE0_IBUS_REJECT_INT_ENA_S  2
/* EXTMEM_CORE0.ibs_WR_IC_INT_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于启用ibus尝试写入icache时的中断*/
#define EXTMEM_CORE0_IBUS_WR_IC_INT_ENA  (BIT(1))
#define EXTMEM_CORE0_IBUS_WR_IC_INT_ENA_M  (BIT(1))
#define EXTMEM_CORE0_IBUS_WR_IC_INT_ENA_V  0x1
#define EXTMEM_CORE0_IBUS_WR_IC_INT_ENA_S  1
/* EXTMEM_CORE0.ibs_ACS_MSK_IC_INT_ENA:R/W；位位置：[0]；默认值：1’b0；*/
/*描述：该位用于启用中断通过cpu访问icache，而禁用相应的ibu（包括推测访问）。*/
#define EXTMEM_CORE0_IBUS_ACS_MSK_IC_INT_ENA  (BIT(0))
#define EXTMEM_CORE0_IBUS_ACS_MSK_IC_INT_ENA_M  (BIT(0))
#define EXTMEM_CORE0_IBUS_ACS_MSK_IC_INT_ENA_V  0x1
#define EXTMEM_CORE0_IBUS_ACS_MSK_IC_INT_ENA_S  0

#define EXTMEM_CORE0_ACS_CACHE_INT_CLR_REG          (DR_REG_EXTMEM_BASE + 0x088)
/* EXTMEM_CORE0_DBUS_WR_IC_INT_CLR:WOD；位位置：[5]；默认值：1’b0；*/
/*description:该位用于清除dbus试图写入icache的中断*/
#define EXTMEM_CORE0_DBUS_WR_IC_INT_CLR  (BIT(5))
#define EXTMEM_CORE0_DBUS_WR_IC_INT_CLR_M  (BIT(5))
#define EXTMEM_CORE0_DBUS_WR_IC_INT_CLR_V  0x1
#define EXTMEM_CORE0_DBUS_WR_IC_INT_CLR_S  5
/* EXTMEM_CORE0_DBUS_REJECT_INT_CLR:WOD；位位置：[4]；默认值：1’b0；*/
/*description:该位用于清除身份验证失败时的中断。*/
#define EXTMEM_CORE0_DBUS_REJECT_INT_CLR  (BIT(4))
#define EXTMEM_CORE0_DBUS_REJECT_INT_CLR_M  (BIT(4))
#define EXTMEM_CORE0_DBUS_REJECT_INT_CLR_V  0x1
#define EXTMEM_CORE0_DBUS_REJECT_INT_CLR_S  4
/* EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_CLR:WOD；位位置：[3]；默认值：1’b0；*/
/*描述：当禁用相应的dbus或禁用icache（包括推测访问）时，该位用于清除cpu访问icache的中断。*/
#define EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_CLR  (BIT(3))
#define EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_CLR_M  (BIT(3))
#define EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_CLR_V  0x1
#define EXTMEM_CORE0_DBUS_ACS_MSK_IC_INT_CLR_S  3
/* EXTMEM_CORE0.ibs_REJECT_INT_CLR:WOD；位位置：[2]；默认值：1’b0；*/
/*description:该位用于清除身份验证失败时的中断。*/
#define EXTMEM_CORE0_IBUS_REJECT_INT_CLR  (BIT(2))
#define EXTMEM_CORE0_IBUS_REJECT_INT_CLR_M  (BIT(2))
#define EXTMEM_CORE0_IBUS_REJECT_INT_CLR_V  0x1
#define EXTMEM_CORE0_IBUS_REJECT_INT_CLR_S  2
/* EXTMEM_CORE0.ibs_WR_IC_INT_CLR:WOD；位位置：[1]；默认值：1’b0；*/
/*description:该位用于清除ibus尝试编写icache时的中断*/
#define EXTMEM_CORE0_IBUS_WR_IC_INT_CLR  (BIT(1))
#define EXTMEM_CORE0_IBUS_WR_IC_INT_CLR_M  (BIT(1))
#define EXTMEM_CORE0_IBUS_WR_IC_INT_CLR_V  0x1
#define EXTMEM_CORE0_IBUS_WR_IC_INT_CLR_S  1
/* EXTMEM_CORE0.ibs_ACS_MSK_INT_CLR:WOD；位位置：[0]；默认值：1’b0；*/
/*描述：当禁用相应的ibu或禁用icache（包括推测访问）时，该位用于清除cpu访问icache的中断。*/
#define EXTMEM_CORE0_IBUS_ACS_MSK_IC_INT_CLR  (BIT(0))
#define EXTMEM_CORE0_IBUS_ACS_MSK_IC_INT_CLR_M  (BIT(0))
#define EXTMEM_CORE0_IBUS_ACS_MSK_IC_INT_CLR_V  0x1
#define EXTMEM_CORE0_IBUS_ACS_MSK_IC_INT_CLR_S  0

#define EXTMEM_CORE0_ACS_CACHE_INT_ST_REG          (DR_REG_EXTMEM_BASE + 0x08C)
/* EXTMEM_CORE0_DBUS_WR_ICACHE_ST:RO；位位置：[5]；默认值：1’b0；*/
/*description:该位用于指示dbus尝试写入icache时的中断*/
#define EXTMEM_CORE0_DBUS_WR_ICACHE_ST  (BIT(5))
#define EXTMEM_CORE0_DBUS_WR_ICACHE_ST_M  (BIT(5))
#define EXTMEM_CORE0_DBUS_WR_ICACHE_ST_V  0x1
#define EXTMEM_CORE0_DBUS_WR_ICACHE_ST_S  5
/* EXTMEM_CORE0_DBUS_REJECT_ST:RO；位位置：[4]；默认值：1’b0；*/
/*description:该位用于指示认证失败导致的中断。*/
#define EXTMEM_CORE0_DBUS_REJECT_ST  (BIT(4))
#define EXTMEM_CORE0_DBUS_REJECT_ST_M  (BIT(4))
#define EXTMEM_CORE0_DBUS_REJECT_ST_V  0x1
#define EXTMEM_CORE0_DBUS_REJECT_ST_S  4
/* EXTMEM_CORE0_DBUS_ACS_MSK_ICACHE_ST:RO；位位置：[3]；默认值：1’b0；*/
/*描述：当禁用core0_dbus或禁用icache（包括推测访问）时，该位用于指示cpu访问icache的中断。*/
#define EXTMEM_CORE0_DBUS_ACS_MSK_ICACHE_ST  (BIT(3))
#define EXTMEM_CORE0_DBUS_ACS_MSK_ICACHE_ST_M  (BIT(3))
#define EXTMEM_CORE0_DBUS_ACS_MSK_ICACHE_ST_V  0x1
#define EXTMEM_CORE0_DBUS_ACS_MSK_ICACHE_ST_S  3
/* EXTMEM_CORE0.ibs_REJECT_ST:RO；位位置：[2]；默认值：1’b0；*/
/*description:该位用于指示认证失败导致的中断。*/
#define EXTMEM_CORE0_IBUS_REJECT_ST  (BIT(2))
#define EXTMEM_CORE0_IBUS_REJECT_ST_M  (BIT(2))
#define EXTMEM_CORE0_IBUS_REJECT_ST_V  0x1
#define EXTMEM_CORE0_IBUS_REJECT_ST_S  2
/* EXTMEM_CORE0.ibs_WR_cache_ST:RO；位位置：[1]；默认值：1’b0；*/
/*description:该位用于指示ibus尝试写入icache时的中断*/
#define EXTMEM_CORE0_IBUS_WR_ICACHE_ST  (BIT(1))
#define EXTMEM_CORE0_IBUS_WR_ICACHE_ST_M  (BIT(1))
#define EXTMEM_CORE0_IBUS_WR_ICACHE_ST_V  0x1
#define EXTMEM_CORE0_IBUS_WR_ICACHE_ST_S  1
/* EXTMEM_CORE0.ibs_ACS_MSK_inache_ST:RO；位位置：[0]；默认值：1’b0；*/
/*描述：当禁用core0.ibus或禁用icache（包括推测访问）时，该位用于指示cpu访问icache的中断。*/
#define EXTMEM_CORE0_IBUS_ACS_MSK_ICACHE_ST  (BIT(0))
#define EXTMEM_CORE0_IBUS_ACS_MSK_ICACHE_ST_M  (BIT(0))
#define EXTMEM_CORE0_IBUS_ACS_MSK_ICACHE_ST_V  0x1
#define EXTMEM_CORE0_IBUS_ACS_MSK_ICACHE_ST_S  0

#define EXTMEM_CORE0_DBUS_REJECT_ST_REG          (DR_REG_EXTMEM_BASE + 0x090)
/* EXTMEM_CORE0_DBUS_WORLD:RO；位位置：[3]；默认值：1’b0；*/
/*description:该位用于指示身份验证失败时CPU访问dbus的世界。0:世界0 1:世界1*/
#define EXTMEM_CORE0_DBUS_WORLD  (BIT(3))
#define EXTMEM_CORE0_DBUS_WORLD_M  (BIT(3))
#define EXTMEM_CORE0_DBUS_WORLD_V  0x1
#define EXTMEM_CORE0_DBUS_WORLD_S  3
/* EXTMEM_CORE0_DBUS_ATTR:RO；位位置：[2:0]；默认值：3'b0；*/
/*description:这些位用于指示验证失败时CPU访问dbus的属性。0：无效1：可执行2：可读取4：可写入。*/
#define EXTMEM_CORE0_DBUS_ATTR  0x00000007
#define EXTMEM_CORE0_DBUS_ATTR_M  ((EXTMEM_CORE0_DBUS_ATTR_V)<<(EXTMEM_CORE0_DBUS_ATTR_S))
#define EXTMEM_CORE0_DBUS_ATTR_V  0x7
#define EXTMEM_CORE0_DBUS_ATTR_S  0

#define EXTMEM_CORE0_DBUS_REJECT_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x094)
/* EXTMEM_CORE0_DBUS_VADDR:RO；位位置：[31:0]；默认值：32'ffffffff；*/
/*description:这些位用于指示验证失败时CPU访问dbus的虚拟地址。*/
#define EXTMEM_CORE0_DBUS_VADDR  0xFFFFFFFF
#define EXTMEM_CORE0_DBUS_VADDR_M  ((EXTMEM_CORE0_DBUS_VADDR_V)<<(EXTMEM_CORE0_DBUS_VADDR_S))
#define EXTMEM_CORE0_DBUS_VADDR_V  0xFFFFFFFF
#define EXTMEM_CORE0_DBUS_VADDR_S  0

#define EXTMEM_CORE0_IBUS_REJECT_ST_REG          (DR_REG_EXTMEM_BASE + 0x098)
/* EXTMEM_CORE0.ibs_WORLD:RO；位位置：[3]；默认值：1’b0；*/
/*description:该位用于指示身份验证失败时CPU访问ibus的世界。0:世界0 1:世界1*/
#define EXTMEM_CORE0_IBUS_WORLD  (BIT(3))
#define EXTMEM_CORE0_IBUS_WORLD_M  (BIT(3))
#define EXTMEM_CORE0_IBUS_WORLD_V  0x1
#define EXTMEM_CORE0_IBUS_WORLD_S  3
/* EXTMEM_CORE0.ibs_ATTR:RO；位位置：[2:0]；默认值：3'b0；*/
/*description:这些位用于指示验证失败时CPU访问ibus的属性。0：无效1：可执行2：可读取*/
#define EXTMEM_CORE0_IBUS_ATTR  0x00000007
#define EXTMEM_CORE0_IBUS_ATTR_M  ((EXTMEM_CORE0_IBUS_ATTR_V)<<(EXTMEM_CORE0_IBUS_ATTR_S))
#define EXTMEM_CORE0_IBUS_ATTR_V  0x7
#define EXTMEM_CORE0_IBUS_ATTR_S  0

#define EXTMEM_CORE0_IBUS_REJECT_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x09C)
/* EXTMEM_CORE0.ibs_vadr:RO；位位置：[31:0]；默认值：32'ffffffff；*/
/*description:这些位用于指示验证失败时CPU访问ibus的虚拟地址。*/
#define EXTMEM_CORE0_IBUS_VADDR  0xFFFFFFFF
#define EXTMEM_CORE0_IBUS_VADDR_M  ((EXTMEM_CORE0_IBUS_VADDR_V)<<(EXTMEM_CORE0_IBUS_VADDR_S))
#define EXTMEM_CORE0_IBUS_VADDR_V  0xFFFFFFFF
#define EXTMEM_CORE0_IBUS_VADDR_S  0

#define EXTMEM_CACHE_MMU_FAULT_CONTENT_REG          (DR_REG_EXTMEM_BASE + 0x0A0)
/* EXTMEM_CACHE_MMU_FAULT_CODE:RO；比特位置：[13:10]；默认值：4'0；*/
/*描述：最右边的3位用于指示导致mmu故障发生的操作。0:默认值1:cpu未命中2:预加载未命中3:写回4:cpu未命中逐出恢复地址5:加载未命中逐出还原地址6:外部dma tx 7:外部dma rx。最高有效位用于指示该操作发生在哪个icache中。*/
#define EXTMEM_CACHE_MMU_FAULT_CODE  0x0000000F
#define EXTMEM_CACHE_MMU_FAULT_CODE_M  ((EXTMEM_CACHE_MMU_FAULT_CODE_V)<<(EXTMEM_CACHE_MMU_FAULT_CODE_S))
#define EXTMEM_CACHE_MMU_FAULT_CODE_V  0xF
#define EXTMEM_CACHE_MMU_FAULT_CODE_S  10
/* EXTMEM_CACHE_MMU_FAULT_CONTENT:RO；位位置：[9:0]；默认值：10'0；*/
/*description:位用于指示导致mmu故障的mmu条目的内容。。*/
#define EXTMEM_CACHE_MMU_FAULT_CONTENT  0x000003FF
#define EXTMEM_CACHE_MMU_FAULT_CONTENT_M  ((EXTMEM_CACHE_MMU_FAULT_CONTENT_V)<<(EXTMEM_CACHE_MMU_FAULT_CONTENT_S))
#define EXTMEM_CACHE_MMU_FAULT_CONTENT_V  0x3FF
#define EXTMEM_CACHE_MMU_FAULT_CONTENT_S  0

#define EXTMEM_CACHE_MMU_FAULT_VADDR_REG          (DR_REG_EXTMEM_BASE + 0x0A4)
/* EXTMEM_CACHE_MMU_FAULT_vadr:RO；位位置：[31:0]；默认值：32'h0；*/
/*description:位用于指示导致mmu故障的虚拟地址。。*/
#define EXTMEM_CACHE_MMU_FAULT_VADDR  0xFFFFFFFF
#define EXTMEM_CACHE_MMU_FAULT_VADDR_M  ((EXTMEM_CACHE_MMU_FAULT_VADDR_V)<<(EXTMEM_CACHE_MMU_FAULT_VADDR_S))
#define EXTMEM_CACHE_MMU_FAULT_VADDR_V  0xFFFFFFFF
#define EXTMEM_CACHE_MMU_FAULT_VADDR_S  0

#define EXTMEM_CACHE_WRAP_AROUND_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x0A8)
/* EXTMEM_CACHE_FLASH_WRAP_AROUND：R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于在从闪存读取数据时启用环绕模式。*/
#define EXTMEM_CACHE_FLASH_WRAP_AROUND  (BIT(0))
#define EXTMEM_CACHE_FLASH_WRAP_AROUND_M  (BIT(0))
#define EXTMEM_CACHE_FLASH_WRAP_AROUND_V  0x1
#define EXTMEM_CACHE_FLASH_WRAP_AROUND_S  0

#define EXTMEM_CACHE_MMU_POWER_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x0AC)
/* EXTMEM_CACHE_MMU_MEM_FORCE_PU:R/W；位位置：[2]；默认值：1’b1；*/
/*description:该位用于关闭mmu内存0:follow_rtc_lslp_pd 1:power-up*/
#define EXTMEM_CACHE_MMU_MEM_FORCE_PU  (BIT(2))
#define EXTMEM_CACHE_MMU_MEM_FORCE_PU_M  (BIT(2))
#define EXTMEM_CACHE_MMU_MEM_FORCE_PU_V  0x1
#define EXTMEM_CACHE_MMU_MEM_FORCE_PU_S  2
/* EXTMEM_CACHE_MMU_MEM_FORCE_PD:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于关闭mmu内存0:follow_rtc_lslp_pd 1:关闭电源*/
#define EXTMEM_CACHE_MMU_MEM_FORCE_PD  (BIT(1))
#define EXTMEM_CACHE_MMU_MEM_FORCE_PD_M  (BIT(1))
#define EXTMEM_CACHE_MMU_MEM_FORCE_PD_V  0x1
#define EXTMEM_CACHE_MMU_MEM_FORCE_PD_S  1
/* EXTMEM_CACHE_MMU_MEM_FORCE_ON:R/W；位位置：[0]；默认值：1’b1；*/
/*描述：当访问mmu内存0：启用1：禁用时，该位用于启用时钟门控以节省电源*/
#define EXTMEM_CACHE_MMU_MEM_FORCE_ON  (BIT(0))
#define EXTMEM_CACHE_MMU_MEM_FORCE_ON_M  (BIT(0))
#define EXTMEM_CACHE_MMU_MEM_FORCE_ON_V  0x1
#define EXTMEM_CACHE_MMU_MEM_FORCE_ON_S  0

#define EXTMEM_CACHE_STATE_REG          (DR_REG_EXTMEM_BASE + 0x0B0)
/* EXTMEM_ICACHE_STATE:RO；位位置：[11:0]；默认值：12'h1；*/
/*description:该位用于指示icache主fsm是否处于空闲状态。1： 处于空闲状态0：不处于空闲状态*/
#define EXTMEM_ICACHE_STATE  0x00000FFF
#define EXTMEM_ICACHE_STATE_M  ((EXTMEM_ICACHE_STATE_V)<<(EXTMEM_ICACHE_STATE_S))
#define EXTMEM_ICACHE_STATE_V  0xFFF
#define EXTMEM_ICACHE_STATE_S  0

#define EXTMEM_CACHE_ENCRYPT_DECRYPT_RECORD_DISABLE_REG          (DR_REG_EXTMEM_BASE + 0x0B4)
/* EXTMEM_RECORD_isable_G0CB_DECRYPT:R/W；位位置：[1]；默认值：1’b0；*/
/*description:保留。*/
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT  (BIT(1))
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT_M  (BIT(1))
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT_V  0x1
#define EXTMEM_RECORD_DISABLE_G0CB_DECRYPT_S  1
/* EXTMEM_RECORD_isable_DB_ENCRYPT:R/W；位位置：[0]；默认值：1’b0；*/
/*description:保留。*/
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT  (BIT(0))
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT_M  (BIT(0))
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT_V  0x1
#define EXTMEM_RECORD_DISABLE_DB_ENCRYPT_S  0

#define EXTMEM_CACHE_ENCRYPT_DECRYPT_CLK_FORCE_ON_REG          (DR_REG_EXTMEM_BASE + 0x0B8)
/* EXTMEM_CLK_FORCE_ON_CRYPT:R/W；位位置：[2]；默认值：1’b1；*/
/*描述：该位用于关闭外部存储器的时钟门控，加密和解密时钟。1： 关闭门控0：打开时钟门控。*/
#define EXTMEM_CLK_FORCE_ON_CRYPT  (BIT(2))
#define EXTMEM_CLK_FORCE_ON_CRYPT_M  (BIT(2))
#define EXTMEM_CLK_FORCE_ON_CRYPT_V  0x1
#define EXTMEM_CLK_FORCE_ON_CRYPT_S  2
/* EXTMEM_CLK_FORCE_ON_AUTO_CRYPT:R/W；位位置：[1]；默认值：1’b1；*/
/*描述：该位用于关闭自动密码时钟的时钟门控。1： 关闭门控0：打开时钟门控。*/
#define EXTMEM_CLK_FORCE_ON_AUTO_CRYPT  (BIT(1))
#define EXTMEM_CLK_FORCE_ON_AUTO_CRYPT_M  (BIT(1))
#define EXTMEM_CLK_FORCE_ON_AUTO_CRYPT_V  0x1
#define EXTMEM_CLK_FORCE_ON_AUTO_CRYPT_S  1
/* EXTMEM_CLK_FORCE_ON_MANUAL_CRYPT:R/W；位位置：[0]；默认值：1’b1；*/
/*描述：该位用于关闭手动密码时钟的时钟门控。1： 关闭门控0：打开时钟门控。*/
#define EXTMEM_CLK_FORCE_ON_MANUAL_CRYPT  (BIT(0))
#define EXTMEM_CLK_FORCE_ON_MANUAL_CRYPT_M  (BIT(0))
#define EXTMEM_CLK_FORCE_ON_MANUAL_CRYPT_V  0x1
#define EXTMEM_CLK_FORCE_ON_MANUAL_CRYPT_S  0

#define EXTMEM_CACHE_PRELOAD_INT_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x0BC)
/* EXTMEM_ICACHE_proad_INT_CLR:WOD；位位置：[2]；默认值：1’b0；*/
/*description:该位用于通过icache预加载完成来清除中断。*/
#define EXTMEM_ICACHE_PRELOAD_INT_CLR  (BIT(2))
#define EXTMEM_ICACHE_PRELOAD_INT_CLR_M  (BIT(2))
#define EXTMEM_ICACHE_PRELOAD_INT_CLR_V  0x1
#define EXTMEM_ICACHE_PRELOAD_INT_CLR_S  2
/* EXTMEM_ICACHE_proad_INT_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于通过icache预加载完成启用中断。*/
#define EXTMEM_ICACHE_PRELOAD_INT_ENA  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_INT_ENA_M  (BIT(1))
#define EXTMEM_ICACHE_PRELOAD_INT_ENA_V  0x1
#define EXTMEM_ICACHE_PRELOAD_INT_ENA_S  1
/* EXTMEM_ICACHE_proad_INT_ST:RO；位位置：[0]；默认值：1’b0；*/
/*description:该位用于指示icache预加载完成的中断。*/
#define EXTMEM_ICACHE_PRELOAD_INT_ST  (BIT(0))
#define EXTMEM_ICACHE_PRELOAD_INT_ST_M  (BIT(0))
#define EXTMEM_ICACHE_PRELOAD_INT_ST_V  0x1
#define EXTMEM_ICACHE_PRELOAD_INT_ST_S  0

#define EXTMEM_CACHE_SYNC_INT_CTRL_REG          (DR_REG_EXTMEM_BASE + 0x0C0)
/* EXTMEM_ICACHE_SYNC_INT_CLR:WOD；位位置：[2]；默认值：1’b0；*/
/*description:该位用于通过完成icache同步来清除中断。*/
#define EXTMEM_ICACHE_SYNC_INT_CLR  (BIT(2))
#define EXTMEM_ICACHE_SYNC_INT_CLR_M  (BIT(2))
#define EXTMEM_ICACHE_SYNC_INT_CLR_V  0x1
#define EXTMEM_ICACHE_SYNC_INT_CLR_S  2
/* EXTMEM_ICACHE_SYNC_INT_ENA:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于通过icache sync done启用中断。*/
#define EXTMEM_ICACHE_SYNC_INT_ENA  (BIT(1))
#define EXTMEM_ICACHE_SYNC_INT_ENA_M  (BIT(1))
#define EXTMEM_ICACHE_SYNC_INT_ENA_V  0x1
#define EXTMEM_ICACHE_SYNC_INT_ENA_S  1
/* EXTMEM_ICACHE_SYNC_INT_ST:RO；位位置：[0]；默认值：1’b0；*/
/*description:该位用于指示icache sync完成的中断。*/
#define EXTMEM_ICACHE_SYNC_INT_ST  (BIT(0))
#define EXTMEM_ICACHE_SYNC_INT_ST_M  (BIT(0))
#define EXTMEM_ICACHE_SYNC_INT_ST_V  0x1
#define EXTMEM_ICACHE_SYNC_INT_ST_S  0

#define EXTMEM_CACHE_MMU_OWNER_REG          (DR_REG_EXTMEM_BASE + 0x0C4)
/* EXTMEM_CACHE_MMU_OWNER:R/W；位位置：[3:0]；默认值：4'0；*/
/*description:这些位用于指定MMU的所有者。bit0/bit2:ibus bit1/bit3:dbus*/
#define EXTMEM_CACHE_MMU_OWNER  0x0000000F
#define EXTMEM_CACHE_MMU_OWNER_M  ((EXTMEM_CACHE_MMU_OWNER_V)<<(EXTMEM_CACHE_MMU_OWNER_S))
#define EXTMEM_CACHE_MMU_OWNER_V  0xF
#define EXTMEM_CACHE_MMU_OWNER_S  0

#define EXTMEM_CACHE_CONF_MISC_REG          (DR_REG_EXTMEM_BASE + 0x0C8)
/* EXTMEM_CACHE_TRACE_ENA:R/W；位位置：[2]；默认值：1’b1；*/
/*description:该位用于启用缓存跟踪功能。*/
#define EXTMEM_CACHE_TRACE_ENA  (BIT(2))
#define EXTMEM_CACHE_TRACE_ENA_M  (BIT(2))
#define EXTMEM_CACHE_TRACE_ENA_V  0x1
#define EXTMEM_CACHE_TRACE_ENA_S  2
/* EXTMEM_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT:R/W；位位置：[1]；默认值：1’b1；*/
/*description:该位用于通过同步操作禁用检查mmu条目错误。*/
#define EXTMEM_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT  (BIT(1))
#define EXTMEM_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT_M  (BIT(1))
#define EXTMEM_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT_V  0x1
#define EXTMEM_CACHE_IGNORE_SYNC_MMU_ENTRY_FAULT_S  1
/* EXTMEM_CACHE_IGNORE_proad_MMU_ENTRY_FAULT:R/W；位位置：[0]；默认值：1’b1；*/
/*描述：该位用于通过预加载操作禁用检查mmu条目故障。*/
#define EXTMEM_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT  (BIT(0))
#define EXTMEM_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT_M  (BIT(0))
#define EXTMEM_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT_V  0x1
#define EXTMEM_CACHE_IGNORE_PRELOAD_MMU_ENTRY_FAULT_S  0

#define EXTMEM_ICACHE_FREEZE_REG          (DR_REG_EXTMEM_BASE + 0x0CC)
/* EXTMEM_ICACHE_freezedone:RO；位位置：[2]；默认值：1’b0；*/
/*description:该位用于指示icache冻结成功*/
#define EXTMEM_ICACHE_FREEZE_DONE  (BIT(2))
#define EXTMEM_ICACHE_FREEZE_DONE_M  (BIT(2))
#define EXTMEM_ICACHE_FREEZE_DONE_V  0x1
#define EXTMEM_ICACHE_FREEZE_DONE_S  2
/* EXTMEM_ICACHE_FREEZE_MODE:R/W；位位置：[1]；默认值：1’b0；*/
/*description:该位用于配置冻结模式0：如果CPU未命中则断言忙1：如果CPU没有命中则断言命中*/
#define EXTMEM_ICACHE_FREEZE_MODE  (BIT(1))
#define EXTMEM_ICACHE_FREEZE_MODE_M  (BIT(1))
#define EXTMEM_ICACHE_FREEZE_MODE_V  0x1
#define EXTMEM_ICACHE_FREEZE_MODE_S  1
/* EXTMEM_ICACHE_FREEZE_ENA:R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于启用icache冻结模式*/
#define EXTMEM_ICACHE_FREEZE_ENA  (BIT(0))
#define EXTMEM_ICACHE_FREEZE_ENA_M  (BIT(0))
#define EXTMEM_ICACHE_FREEZE_ENA_V  0x1
#define EXTMEM_ICACHE_FREEZE_ENA_S  0

#define EXTMEM_ICACHE_ATOMIC_OPERATE_ENA_REG          (DR_REG_EXTMEM_BASE + 0x0D0)
/* EXTMEM_ICACHE_ATOMIC_OPERATE_ENA:R/W；位位置：[0]；默认值：1’b1；*/
/*描述：该位用于激活icache原子操作保护。在这种情况下，同步/锁定操作不会中断未完成的工作。在invalidateAll操作期间，此功能不起作用。*/
#define EXTMEM_ICACHE_ATOMIC_OPERATE_ENA  (BIT(0))
#define EXTMEM_ICACHE_ATOMIC_OPERATE_ENA_M  (BIT(0))
#define EXTMEM_ICACHE_ATOMIC_OPERATE_ENA_V  0x1
#define EXTMEM_ICACHE_ATOMIC_OPERATE_ENA_S  0

#define EXTMEM_CACHE_REQUEST_REG          (DR_REG_EXTMEM_BASE + 0x0D4)
/* EXTMEM_CACHE_REQUEST_BYPASS:R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于禁用可能导致性能问题的请求记录*/
#define EXTMEM_CACHE_REQUEST_BYPASS  (BIT(0))
#define EXTMEM_CACHE_REQUEST_BYPASS_M  (BIT(0))
#define EXTMEM_CACHE_REQUEST_BYPASS_V  0x1
#define EXTMEM_CACHE_REQUEST_BYPASS_S  0

#define EXTMEM_IBUS_PMS_TBL_LOCK_REG          (DR_REG_EXTMEM_BASE + 0x0D8)
/* EXTMEM_IBUS_PMS_LOCK：R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于配置ibus权限控制部分边界0*/
#define EXTMEM_IBUS_PMS_LOCK  (BIT(0))
#define EXTMEM_IBUS_PMS_LOCK_M  (BIT(0))
#define EXTMEM_IBUS_PMS_LOCK_V  0x1
#define EXTMEM_IBUS_PMS_LOCK_S  0

#define EXTMEM_IBUS_PMS_TBL_BOUNDARY0_REG          (DR_REG_EXTMEM_BASE + 0x0DC)
/* EXTMEM_IBUS_PMS_BOUNDARY0:R/W；位位置：[11:0]；默认值：12'0；*/
/*description:该位用于配置ibus权限控制部分边界0*/
#define EXTMEM_IBUS_PMS_BOUNDARY0  0x00000FFF
#define EXTMEM_IBUS_PMS_BOUNDARY0_M  ((EXTMEM_IBUS_PMS_BOUNDARY0_V)<<(EXTMEM_IBUS_PMS_BOUNDARY0_S))
#define EXTMEM_IBUS_PMS_BOUNDARY0_V  0xFFF
#define EXTMEM_IBUS_PMS_BOUNDARY0_S  0

#define EXTMEM_IBUS_PMS_TBL_BOUNDARY1_REG          (DR_REG_EXTMEM_BASE + 0x0E0)
/* EXTMEM_IBUS_PMS_BOUNDARY1:R/W；位位置：[11:0]；默认值：12'h800；*/
/*description:该位用于配置ibus权限控制部分边界1*/
#define EXTMEM_IBUS_PMS_BOUNDARY1  0x00000FFF
#define EXTMEM_IBUS_PMS_BOUNDARY1_M  ((EXTMEM_IBUS_PMS_BOUNDARY1_V)<<(EXTMEM_IBUS_PMS_BOUNDARY1_S))
#define EXTMEM_IBUS_PMS_BOUNDARY1_V  0xFFF
#define EXTMEM_IBUS_PMS_BOUNDARY1_S  0

#define EXTMEM_IBUS_PMS_TBL_BOUNDARY2_REG          (DR_REG_EXTMEM_BASE + 0x0E4)
/* EXTMEM_IBUS_PMS_BOUNDARY2:R/W；位位置：[11:0]；默认值：12'h800；*/
/*description:该位用于配置ibus权限控制部分边界2*/
#define EXTMEM_IBUS_PMS_BOUNDARY2  0x00000FFF
#define EXTMEM_IBUS_PMS_BOUNDARY2_M  ((EXTMEM_IBUS_PMS_BOUNDARY2_V)<<(EXTMEM_IBUS_PMS_BOUNDARY2_S))
#define EXTMEM_IBUS_PMS_BOUNDARY2_V  0xFFF
#define EXTMEM_IBUS_PMS_BOUNDARY2_S  0

#define EXTMEM_IBUS_PMS_TBL_ATTR_REG          (DR_REG_EXTMEM_BASE + 0x0E8)
/* EXTMEM_IBUS_PMS_SCT2_ATTR:R/W；位位置：[7:4]；默认值：4'hF；*/
/*description:该位用于配置ibus权限控制部分的属性2 bit0：获取世界0 bit1：加载世界0 bit2：获取世界1 bit3：加载世界1*/
#define EXTMEM_IBUS_PMS_SCT2_ATTR  0x0000000F
#define EXTMEM_IBUS_PMS_SCT2_ATTR_M  ((EXTMEM_IBUS_PMS_SCT2_ATTR_V)<<(EXTMEM_IBUS_PMS_SCT2_ATTR_S))
#define EXTMEM_IBUS_PMS_SCT2_ATTR_V  0xF
#define EXTMEM_IBUS_PMS_SCT2_ATTR_S  4
/* EXTMEM_IBUS_PMS_SCT1_ATTR:R/W；位位置：[3:0]；默认值：4'hF；*/
/*description:该位用于配置ibus权限控制部分的属性1 bit0：获取世界0 bit1：加载世界0 bit2：获取世界1 bit3：加载世界1*/
#define EXTMEM_IBUS_PMS_SCT1_ATTR  0x0000000F
#define EXTMEM_IBUS_PMS_SCT1_ATTR_M  ((EXTMEM_IBUS_PMS_SCT1_ATTR_V)<<(EXTMEM_IBUS_PMS_SCT1_ATTR_S))
#define EXTMEM_IBUS_PMS_SCT1_ATTR_V  0xF
#define EXTMEM_IBUS_PMS_SCT1_ATTR_S  0

#define EXTMEM_DBUS_PMS_TBL_LOCK_REG          (DR_REG_EXTMEM_BASE + 0x0EC)
/* EXTMEM_DBUS_PMS_LOCK：R/W；位位置：[0]；默认值：1’b0；*/
/*description:该位用于配置ibus权限控制部分边界0*/
#define EXTMEM_DBUS_PMS_LOCK  (BIT(0))
#define EXTMEM_DBUS_PMS_LOCK_M  (BIT(0))
#define EXTMEM_DBUS_PMS_LOCK_V  0x1
#define EXTMEM_DBUS_PMS_LOCK_S  0

#define EXTMEM_DBUS_PMS_TBL_BOUNDARY0_REG          (DR_REG_EXTMEM_BASE + 0x0F0)
/* EXTMEM_DBUS_PMS_BOUNDARY0:R/W；位位置：[11:0]；默认值：12'0；*/
/*description:该位用于配置dbus权限控制部分边界0*/
#define EXTMEM_DBUS_PMS_BOUNDARY0  0x00000FFF
#define EXTMEM_DBUS_PMS_BOUNDARY0_M  ((EXTMEM_DBUS_PMS_BOUNDARY0_V)<<(EXTMEM_DBUS_PMS_BOUNDARY0_S))
#define EXTMEM_DBUS_PMS_BOUNDARY0_V  0xFFF
#define EXTMEM_DBUS_PMS_BOUNDARY0_S  0

#define EXTMEM_DBUS_PMS_TBL_BOUNDARY1_REG          (DR_REG_EXTMEM_BASE + 0x0F4)
/* EXTMEM_DBUS_PMS_BOUNDARY1:R/W；位位置：[11:0]；默认值：12'h800；*/
/*description:该位用于配置dbus权限控制部分边界1*/
#define EXTMEM_DBUS_PMS_BOUNDARY1  0x00000FFF
#define EXTMEM_DBUS_PMS_BOUNDARY1_M  ((EXTMEM_DBUS_PMS_BOUNDARY1_V)<<(EXTMEM_DBUS_PMS_BOUNDARY1_S))
#define EXTMEM_DBUS_PMS_BOUNDARY1_V  0xFFF
#define EXTMEM_DBUS_PMS_BOUNDARY1_S  0

#define EXTMEM_DBUS_PMS_TBL_BOUNDARY2_REG          (DR_REG_EXTMEM_BASE + 0x0F8)
/* EXTMEM_DBUS_PMS_BOUNDARY2:R/W；位位置：[11:0]；默认值：12'h800；*/
/*description:该位用于配置dbus权限控制部分边界2*/
#define EXTMEM_DBUS_PMS_BOUNDARY2  0x00000FFF
#define EXTMEM_DBUS_PMS_BOUNDARY2_M  ((EXTMEM_DBUS_PMS_BOUNDARY2_V)<<(EXTMEM_DBUS_PMS_BOUNDARY2_S))
#define EXTMEM_DBUS_PMS_BOUNDARY2_V  0xFFF
#define EXTMEM_DBUS_PMS_BOUNDARY2_S  0

#define EXTMEM_DBUS_PMS_TBL_ATTR_REG          (DR_REG_EXTMEM_BASE + 0x0FC)
/* EXTMEM_DBUS_PMS_SCT2_ATTR:R/W；位位置：[3:2]；默认值：2'd3；*/
/*description:该位用于配置dbus权限控制部分的属性2 bit0：在世界中加载0 bit2：在世界1中加载*/
#define EXTMEM_DBUS_PMS_SCT2_ATTR  0x00000003
#define EXTMEM_DBUS_PMS_SCT2_ATTR_M  ((EXTMEM_DBUS_PMS_SCT2_ATTR_V)<<(EXTMEM_DBUS_PMS_SCT2_ATTR_S))
#define EXTMEM_DBUS_PMS_SCT2_ATTR_V  0x3
#define EXTMEM_DBUS_PMS_SCT2_ATTR_S  2
/* EXTMEM_DBUS_PMS_SCT1_ATTR:R/W；位位置：[1:0]；默认值：2'd3；*/
/*description:该位用于配置dbus权限控制部分的属性1 bit0：在世界中加载0 bit2：在世界1中加载*/
#define EXTMEM_DBUS_PMS_SCT1_ATTR  0x00000003
#define EXTMEM_DBUS_PMS_SCT1_ATTR_M  ((EXTMEM_DBUS_PMS_SCT1_ATTR_V)<<(EXTMEM_DBUS_PMS_SCT1_ATTR_S))
#define EXTMEM_DBUS_PMS_SCT1_ATTR_V  0x3
#define EXTMEM_DBUS_PMS_SCT1_ATTR_S  0

#define EXTMEM_CLOCK_GATE_REG          (DR_REG_EXTMEM_BASE + 0x100)
/* EXTMEM_CLK_EN:R/W；位位置：[0]；默认值：1’b1；*/
/*description:保留。*/
#define EXTMEM_CLK_EN  (BIT(0))
#define EXTMEM_CLK_EN_M  (BIT(0))
#define EXTMEM_CLK_EN_V  0x1
#define EXTMEM_CLK_EN_S  0

#define EXTMEM_DATE_REG          (DR_REG_EXTMEM_BASE + 0x3FC)
/* EXTMEM_DATE:R/W；位位置：[27:0]；默认值：28'h2007160；*/
/*description:保留。*/
#define EXTMEM_DATE  0x0FFFFFFF
#define EXTMEM_DATE_M  ((EXTMEM_DATE_V)<<(EXTMEM_DATE_S))
#define EXTMEM_DATE_V  0xFFFFFFF
#define EXTMEM_DATE_S  0

#ifdef __cplusplus
}
#endif



#endif /*_SOC_EXTMEM_REG_H_ */

