/*
 * nghttp2-HTTP/2 C库
 *
 * 版权所有（c）20122013 Tatsuhiro Tsujikawa
 *
 * 特此免费授予获得本软件和相关文档文件（“软件”）副本的任何人无限制地处理软件的权利，包括但不限于使用、复制、修改、合并、发布、分发、再许可和/或销售软件副本的权利，并允许向其提供软件的人这样做，符合以下条件：
 *
 * 上述版权声明和本许可声明应包含在软件的所有副本或主要部分中。
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef NGHTTP2VER_H
#define NGHTTP2VER_H

/**
 * @macro nghttp2库版本号
 */
#define NGHTTP2_VERSION "v1.22.0"

/**
 * @macro nghttp2库版本号的数字表示。这是一个24位的数字，8位用于主要数字，8个位用于次要数字，8位数用于补丁。版本1.2.3变为0x010203。
 */
#define NGHTTP2_VERSION_NUM 0x012200

#endif /* NGHTTP2VER_H */

