/*
 *  版权所有（c）2018，The OpenThread作者。保留所有权利。
 *
 *  在满足以下条件的情况下，允许以源代码和二进制形式重新分发和使用，无论是否进行修改：1.重新分发源代码必须保留上述版权声明、本条件列表和以下免责声明。2.二进制形式的再发行必须在随发行提供的文档和/或其他材料中复制上述版权声明、本条件列表和以下免责声明。3.未经事先书面许可，不得使用版权持有人的姓名或其贡献者的姓名为本软件衍生的产品背书或推广。
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifdef OPENTHREAD_CONFIG_ANDROID_VERSION_HEADER_ENABLE
#include <openthread-config-android-version.h>
#endif

/* 定义为1以启用边界代理功能。*/
#define OPENTHREAD_CONFIG_BORDER_AGENT_ENABLE 1

/* 如果要启用边界路由器，请定义为1*/
#define OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE 1

/* 如果要启用频道管理器功能，请定义为1*/
#define OPENTHREAD_CONFIG_CHANNEL_MANAGER_ENABLE 0

/* 如果要使用通道监视器功能，请定义为1*/
#define OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE 0

/* 如果要使用子监控功能，请定义为1*/
#define OPENTHREAD_CONFIG_CHILD_SUPERVISION_ENABLE 1

/* 定义为1以启用dtls支持。*/
#define OPENTHREAD_CONFIG_DTLS_ENABLE 1

/* 如果要使用卡纸检测功能，请定义为1*/
#define OPENTHREAD_CONFIG_JAM_DETECTION_ENABLE 1

/* 定义为1以启用加入者角色。*/
#define OPENTHREAD_CONFIG_JOINER_ENABLE 1

/* 如果要使用传统网络支持，请定义为1*/
#define OPENTHREAD_CONFIG_LEGACY_ENABLE 1

/* 定义为1以启用NCP HDLC接口。*/
#define OPENTHREAD_CONFIG_NCP_HDLC_ENABLE 1

/* 定义为1以启用posix平台。*/
#define OPENTHREAD_PLATFORM_POSIX 1

/* 如果要启用服务，请定义为1*/
#define OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE 1

/* OpenThread示例*/
#define OPENTHREAD_EXAMPLES none

